namespace PicView.Core.WindowsNT;

public static class WindowsKeybindings
{
    public const string DefaultKeybindings = """
                                             {
                                               "Esc": "Close",
                                               "F1": "AboutWindow",
                                               "F2": "Rename",
                                               "F3": "OpenInExplorer",
                                               "F4": "SettingsWindow",
                                               "F5": "Slideshow",
                                               "F6": "EffectsWindow",
                                               "F7": "BatchResizeWindow",
                                               "F10": "ToggleInterface",
                                               "F11": "Fullscreen",
                                               "W": "Up",
                                               "E": "GalleryClick",
                                               "Enter": "GalleryClick",
                                               "Ctrl+E": "OpenWith",
                                               "R": "ResetZoom",
                                               "Ctrl+R": "Reload",
                                               "T": "SetTopMost",
                                               "I": "ImageInfoWindow",
                                               "Ctrl+I": "ShowFileProperties",
                                               "Ctrl+Alt+I": "ResizeWindow",
                                               "O": "Open",
                                               "Ctrl+O": "Open",
                                               "Ctrl+P": "Print",
                                               "A": "Prev",
                                               "Ctrl+A": "First",
                                               "Shift+A": "PrevFolder",
                                               "S": "Down",
                                               "Ctrl+S": "Save",
                                               "Ctrl+Shift+S": "SaveAs",
                                               "D": "Next",
                                               "Ctrl+D": "Last",
                                               "Alt+D": "DuplicateFile",
                                               "Shift+D": "NextFolder",
                                               "F": "Flip",
                                               "G": "ToggleGallery",
                                               "J": "ResizeWindow",
                                               "K": "KeybindingsWindow",
                                               "L": "ToggleLooping",
                                               "Alt+Z": "ToggleInterface",
                                               "X": "ToggleScroll",
                                               "Scroll": "ToggleScroll",
                                               "C": "Crop",
                                               "Ctrl+C": "CopyImage",
                                               "Ctrl+Alt+C": "CopyFilePath",
                                               "Ctrl+Shift+C": "CopyFile",
                                               "Ctrl+X": "CutFile",
                                               "V": "Paste",
                                               "Ctrl+V": "Paste",
                                               "B": "ChangeBackground",
                                               "Ctrl+N": "NewWindow",
                                               "Space": "Center",
                                               "Home": "ScrollToTop",
                                               "End": "ScrollToBottom",
                                               "Left": "Prev",
                                               "Ctrl+Left": "First",
                                               "Right": "Next",
                                               "Ctrl+Right": "Last",
                                               "Shift+Right": "NextFolder",
                                               "Shift+Left": "PrevFolder",
                                               "Up": "Up",
                                               "PageUp": "ScrollUp",
                                               "Down": "Down",
                                               "PageDown": "ScrollDown",
                                               "Add": "ZoomIn",
                                               "OemPlus": "ZoomIn",
                                               "Subtract": "ZoomOut",
                                               "OemMinus": "ZoomOut",
                                               "Delete": "DeleteFile",
                                               "Shift+Delete": "DeleteFilePermanently",
                                               "Alt+Enter": "Fullscreen",
                                               "Ctrl+F": "Search",
                                             }
                                             """;
}
