using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class BrazilianPortugueseUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckBrazilianPortugueseLanguage()
    {
        var exists = await TranslationHelper.LoadLanguage("pt-br");
        Assert.True(exists);

        Assert.Equal(TranslationHelper.Translation.About, "Sobre");
        Assert.Equal(TranslationHelper.Translation.ActionProgram, "Action program");
        Assert.Equal(TranslationHelper.Translation.AddedToClipboard, "Adicionada à área de transferência");
        Assert.Equal(TranslationHelper.Translation.AdditionalFunctions, "Funções adicionais");
        Assert.Equal(TranslationHelper.Translation.AdjustNavSpeed,
            "Ajustar a velocidade quando uma tecla é mantida pressionada");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForSlideshow,
            "Ajustar o tempo da apresentação de slides");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForZoom, "Ajustar a velocidade do zoom");
        Assert.Equal(TranslationHelper.Translation.AdjustZoomLevel, "Ajustar o nível de zoom");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy100Images, "Avançar por 100 imagens");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy10Images, "Avançar por 10 imagens");
        Assert.Equal(TranslationHelper.Translation.AllowZoomOut,
            "Evitar diminuir o zoom da imagem quando ela já estiver no tamanho máximo");
        Assert.Equal(TranslationHelper.Translation.Alt, "Alt");
        Assert.Equal(TranslationHelper.Translation.Altitude, "Altura");
        Assert.Equal(TranslationHelper.Translation.AperturePriority, "Prioridade de abertura");
        Assert.Equal(TranslationHelper.Translation.Appearance, "Aparência");
        Assert.Equal(TranslationHelper.Translation.ApplicationShortcuts, "Atalhos do aplicativo");
        Assert.Equal(TranslationHelper.Translation.ApplicationStartup, "Inicialização do aplicativo");
        Assert.Equal(TranslationHelper.Translation.Apply, "Aplicar");
        Assert.Equal(TranslationHelper.Translation.Applying, "Aplicando");
        Assert.Equal(TranslationHelper.Translation.Ascending, "Crescente");
        Assert.Equal(TranslationHelper.Translation.AspectRatio, "Proporção de aspecto");
        Assert.Equal(TranslationHelper.Translation.Authors, "Autores");
        Assert.Equal(TranslationHelper.Translation.Auto, "Auto");
        Assert.Equal(TranslationHelper.Translation.AutoFitWindow, "Auto ajustar janela");
        Assert.Equal(TranslationHelper.Translation.BadArchive, "O arquivo não pôde ser processado");
        Assert.Equal(TranslationHelper.Translation.BandedSwirl, "Banded Swirl");
        Assert.Equal(TranslationHelper.Translation.Bands, "Bands");
        Assert.Equal(TranslationHelper.Translation.Base64Image, "Imagem em formato Base64");
        Assert.Equal(TranslationHelper.Translation.BatchResize, "Redimensionar em lote");
        Assert.Equal(TranslationHelper.Translation.BitDepth, "Profundidade de bits");
        Assert.Equal(TranslationHelper.Translation.BlackAndWhite, "Preto e branco");
        Assert.Equal(TranslationHelper.Translation.Bloom, "Bloom");
        Assert.Equal(TranslationHelper.Translation.Blur, "Desfoque");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryItemSize, "Tamanho das miniaturas na galeria inferior");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryThumbnailStretch,
            "Extensão de miniaturas na galeria inferior");
        Assert.Equal(TranslationHelper.Translation.Brightness, "Luminosidade");
        Assert.Equal(TranslationHelper.Translation.CameraMaker, "Compositor de câmera");
        Assert.Equal(TranslationHelper.Translation.CameraModel, "Modelo da câmera");
        Assert.Equal(TranslationHelper.Translation.Cancel, "Cancelar");
        Assert.Equal(TranslationHelper.Translation.Center, "Centro");
        Assert.Equal(TranslationHelper.Translation.CenterWindow, "Janela centralizada");
        Assert.Equal(TranslationHelper.Translation.Centimeters, "centímetros");
        Assert.Equal(TranslationHelper.Translation.ChangeBackground, "Alterar plano de fundo");
        Assert.Equal(TranslationHelper.Translation.ChangeBackgroundTooltip,
            "Alterar a cor de fundo de imagens com fundo transparente");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingText,
            "Clique na caixa de texto para alterar o vínculo de teclas. Pressionar Esc desvincular a tecla.");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingTooltip, "Clique para alterar a tecla de atalho");
        Assert.Equal(TranslationHelper.Translation.ChangingThemeRequiresRestart,
            "* Mudar o tema requer reinicialização");
        Assert.Equal(TranslationHelper.Translation.CheckForUpdates, "Verificar atualizações");
        Assert.Equal(TranslationHelper.Translation.ClipboardImage, "Imagem da área de transferência");
        Assert.Equal(TranslationHelper.Translation.Close, "Fechar");
        Assert.Equal(TranslationHelper.Translation.CloseApp, "Fechar o aplicativo");
        Assert.Equal(TranslationHelper.Translation.CloseGallery, "Fechar galeria");
        Assert.Equal(TranslationHelper.Translation.CloseWindowPrompt, "Pencereyi kapatmak istiyor musunuz?");
        Assert.Equal(TranslationHelper.Translation.CloudyWeather, "Nublado");
        Assert.Equal(TranslationHelper.Translation.ColorPickerTool, "Ferramenta de seleção de cores");
        Assert.Equal(TranslationHelper.Translation.ColorPickerToolTooltip, "Escolha a cor da imagem");
        Assert.Equal(TranslationHelper.Translation.ColorRepresentation, "Representação de cores");
        Assert.Equal(TranslationHelper.Translation.ColorTone, "Tonalidade da cor");
        Assert.Equal(TranslationHelper.Translation.CompressedBitsPixel, "Bits compactados por pixel");
        Assert.Equal(TranslationHelper.Translation.Compression, "Compressão");
        Assert.Equal(TranslationHelper.Translation.Contrast, "Contraste");
        Assert.Equal(TranslationHelper.Translation.ConvertTo, "Converter para");
        Assert.Equal(TranslationHelper.Translation.ConvertedToBase64, "Convertido para base64");
        Assert.Equal(TranslationHelper.Translation.CoolWhiteFluorescent, "Branco fluorescente frio");
        Assert.Equal(TranslationHelper.Translation.CopiedImage, "Imagem copiada para a área de transferência");
        Assert.Equal(TranslationHelper.Translation.Copy, "Copiar");
        Assert.Equal(TranslationHelper.Translation.CopyFile, "Copiar arquivo");
        Assert.Equal(TranslationHelper.Translation.CopyImage, "Copiar imagem");
        Assert.Equal(TranslationHelper.Translation.CopyImageTooltip, "Copiar como imagem da área de transferência");
        Assert.Equal(TranslationHelper.Translation.Copyright, "Direitos autorais");
        Assert.Equal(TranslationHelper.Translation.Created, "Criado");
        Assert.Equal(TranslationHelper.Translation.CreationTime, "Hora da criação");
        Assert.Equal(TranslationHelper.Translation.CreativeProgram, "Programa de criação");
        Assert.Equal(TranslationHelper.Translation.Credits, "Créditos");
        Assert.Equal(TranslationHelper.Translation.Crop, "Cortar");
        Assert.Equal(TranslationHelper.Translation.CropMessage, "Pressione Esc para fechar, Enter para salvar");
        Assert.Equal(TranslationHelper.Translation.CropPicture, "Cortar imagem");
        Assert.Equal(TranslationHelper.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationHelper.Translation.CtrlToZoom, "Ctrl para dar zoom, rolar para navegar");
        Assert.Equal(TranslationHelper.Translation.Cut, "Corte");
        Assert.Equal(TranslationHelper.Translation.DarkTheme, "Tema escuro");
        Assert.Equal(TranslationHelper.Translation.Date, "Data");
        Assert.Equal(TranslationHelper.Translation.DateTaken, "Data da captura");
        Assert.Equal(TranslationHelper.Translation.DayWhiteFluorescent, "Branco fluorescente");
        Assert.Equal(TranslationHelper.Translation.Daylight, "Luz do dia");
        Assert.Equal(TranslationHelper.Translation.DaylightFluorescent, "Branco fluorescente");
        Assert.Equal(TranslationHelper.Translation.Del, "Excluir");
        Assert.Equal(TranslationHelper.Translation.DeleteFile, "Excluir arquivo");
        Assert.Equal(TranslationHelper.Translation.DeleteFilePermanently,
            "Tem certeza de que deseja excluir permanentemente");
        Assert.Equal(TranslationHelper.Translation.DeletedFile, "Arquivo excluído");
        Assert.Equal(TranslationHelper.Translation.Descending, "Decrescente");
        Assert.Equal(TranslationHelper.Translation.DigitalZoom, "Zoom digital");
        Assert.Equal(TranslationHelper.Translation.DirectionalBlur, "Desfoque direcional");
        Assert.Equal(TranslationHelper.Translation.DisableFadeInButtonsOnHover,
            "Desativar botões de transição ao pousar ponteiro do mouse");
        Assert.Equal(TranslationHelper.Translation.DiskSize, "Tamanho do disco");
        Assert.Equal(TranslationHelper.Translation.DoubleClick, "Duplo clique");
        Assert.Equal(TranslationHelper.Translation.Down, "Para baixo");
        Assert.Equal(TranslationHelper.Translation.Dpi, "DPI");
        Assert.Equal(TranslationHelper.Translation.DragFileTo,
            "Arraste o arquivo para o Windows Explorer ou outro aplicativo/navegador");
        Assert.Equal(TranslationHelper.Translation.DragImage, "Arraste a imagem");
        Assert.Equal(TranslationHelper.Translation.DropToLoad, "Solte para carregar a imagem");
        Assert.Equal(TranslationHelper.Translation.DuplicateFile, "Arquivo duplicado");
        Assert.Equal(TranslationHelper.Translation.Effects, "Efeitos");
        Assert.Equal(TranslationHelper.Translation.EffectsTooltip, "Mostrar a janela de efeitos de imagem");
        Assert.Equal(TranslationHelper.Translation.Embossed, "Com relevo");
        Assert.Equal(TranslationHelper.Translation.Enter, "Enter");
        Assert.Equal(TranslationHelper.Translation.Esc, "Esc");
        Assert.Equal(TranslationHelper.Translation.EscCloseTooltip, "Fecha a janela/menu aberto no momento");
        Assert.Equal(TranslationHelper.Translation.ExifVersion, "Exibir versão");
        Assert.Equal(TranslationHelper.Translation.ExpandedGalleryItemSize, "Tamanho das miniaturas");
        Assert.Equal(TranslationHelper.Translation.ExposureBias, "Tendência de exposição");
        Assert.Equal(TranslationHelper.Translation.ExposureProgram, "Fator de exposição");
        Assert.Equal(TranslationHelper.Translation.ExposureTime, "Tempo de exposição");
        Assert.Equal(TranslationHelper.Translation.FNumber, "Número");
        Assert.Equal(TranslationHelper.Translation.File, "Arquivo");
        Assert.Equal(TranslationHelper.Translation.FileCopy, "Arquivo adicionado à área de transferência");
        Assert.Equal(TranslationHelper.Translation.FileCopyPath, "Copiar o caminho do arquivo");
        Assert.Equal(TranslationHelper.Translation.FileCopyPathMessage,
            "Caminho do arquivo adicionado à área de transferência");
        Assert.Equal(TranslationHelper.Translation.FileCutMessage,
            "Arquivo adicionado para mover na área de transferência");
        Assert.Equal(TranslationHelper.Translation.FileExtension, "Extensão do arquivo");
        Assert.Equal(TranslationHelper.Translation.FileManagement, "Gerenciamento de arquivos");
        Assert.Equal(TranslationHelper.Translation.FileName, "Nome do arquivo");
        Assert.Equal(TranslationHelper.Translation.FilePaste, "Colar");
        Assert.Equal(TranslationHelper.Translation.FileProperties, "Propriedades do arquivo");
        Assert.Equal(TranslationHelper.Translation.FileSize, "Tamanho do arquivo");
        Assert.Equal(TranslationHelper.Translation.Files, "arquivos");
        Assert.Equal(TranslationHelper.Translation.Fill, "Preencher");
        Assert.Equal(TranslationHelper.Translation.FillHeight, "⇔ Altura do preenchimento");
        Assert.Equal(TranslationHelper.Translation.FillSquare, "Preenchimento do quadrado");
        Assert.Equal(TranslationHelper.Translation.FineWeather, "Clima agradável");
        Assert.Equal(TranslationHelper.Translation.FirstImage, "Primeira imagem");
        Assert.Equal(TranslationHelper.Translation.Fit, "Ajustar");
        Assert.Equal(TranslationHelper.Translation.FitToWindow, "Ajustar à janela/imagem");
        Assert.Equal(TranslationHelper.Translation.Flash, "Flash");
        Assert.Equal(TranslationHelper.Translation.FlashDidNotFire, "O flash não disparou");
        Assert.Equal(TranslationHelper.Translation.FlashEnergy, "Energia do flash");
        Assert.Equal(TranslationHelper.Translation.FlashFired, "Disparo de flash");
        Assert.Equal(TranslationHelper.Translation.FlashMode, "Modo do flash");
        Assert.Equal(TranslationHelper.Translation.Flip, "Virar horizontalmente");
        Assert.Equal(TranslationHelper.Translation.Flipped, "Virado horizontalmente");
        Assert.Equal(TranslationHelper.Translation.Fluorescent, "Fluorescente");
        Assert.Equal(TranslationHelper.Translation.FocalLength, "Comprimento focal");
        Assert.Equal(TranslationHelper.Translation.FocalLength35mm, "Distância focal de 35 mm");
        Assert.Equal(TranslationHelper.Translation.Folder, "Pasta");
        Assert.Equal(TranslationHelper.Translation.Forward, "Para frente");
        Assert.Equal(TranslationHelper.Translation.FrostyOutline, "Contorno de gelo");
        Assert.Equal(TranslationHelper.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationHelper.Translation.FullPath, "Caminho completo");
        Assert.Equal(TranslationHelper.Translation.Fullscreen, "Tela cheia");
        Assert.Equal(TranslationHelper.Translation.GallerySettings, "Configurações da galeria");
        Assert.Equal(TranslationHelper.Translation.GalleryThumbnailStretch, "Ampliação da miniatura da galeria");
        Assert.Equal(TranslationHelper.Translation.GeneralSettings, "Configurações gerais");
        Assert.Equal(TranslationHelper.Translation.GenerateThumbnails, "Gerar miniaturas");
        Assert.Equal(TranslationHelper.Translation.GithubRepo, "Repositório no Github");
        Assert.Equal(TranslationHelper.Translation.GlassTheme, "Tema de vidro");
        Assert.Equal(TranslationHelper.Translation.GlassTile, "Estilo envidraçado");
        Assert.Equal(TranslationHelper.Translation.Gloom, "Sombrio");
        Assert.Equal(TranslationHelper.Translation.GoBackBy100Images, "Retroceder em 100 imagens");
        Assert.Equal(TranslationHelper.Translation.GoBackBy10Images, "Retroceder em 10 imagens");
        Assert.Equal(TranslationHelper.Translation.GoToImageAtSpecifiedIndex,
            "Ir para a imagem no índice especificado");
        Assert.Equal(TranslationHelper.Translation.Hard, "Forte");
        Assert.Equal(TranslationHelper.Translation.Height, "Altura");
        Assert.Equal(TranslationHelper.Translation.HideBottomGallery, "Ocultar galeria inferior");
        Assert.Equal(TranslationHelper.Translation.HideBottomToolbar, "Ocultar a barra de ferramentas inferior");
        Assert.Equal(TranslationHelper.Translation.HideUI, "Ocultar a interface");
        Assert.Equal(TranslationHelper.Translation.High, "Alto");
        Assert.Equal(TranslationHelper.Translation.HighQuality, "Alta qualidade");
        Assert.Equal(TranslationHelper.Translation.HighlightColor, "Cor de realce");
        Assert.Equal(TranslationHelper.Translation.ISOSpeed, "Velocidade ISO");
        Assert.Equal(TranslationHelper.Translation.IconsUsed, "Ícones usados:");
        Assert.Equal(TranslationHelper.Translation.Image, "Imagem");
        Assert.Equal(TranslationHelper.Translation.ImageAliasing, "Distorção da imagem");
        Assert.Equal(TranslationHelper.Translation.ImageControl, "Controle da imagem");
        Assert.Equal(TranslationHelper.Translation.ImageInfo, "Informação da imagem");
        Assert.Equal(TranslationHelper.Translation.Inches, "polegadas");
        Assert.Equal(TranslationHelper.Translation.InfoWindow, "Informação da janela");
        Assert.Equal(TranslationHelper.Translation.InfoWindowTitle, "Informação e atalhos");
        Assert.Equal(TranslationHelper.Translation.InterfaceConfiguration, "Configuração da interface");
        Assert.Equal(TranslationHelper.Translation.Landscape, "Paisagem");
        Assert.Equal(TranslationHelper.Translation.Language, "Idioma");
        Assert.Equal(TranslationHelper.Translation.LastAccessTime, "Hora do último acesso");
        Assert.Equal(TranslationHelper.Translation.LastImage, "Última imagem");
        Assert.Equal(TranslationHelper.Translation.LastWriteTime, "Última gravação");
        Assert.Equal(TranslationHelper.Translation.Latitude, "Latitude");
        Assert.Equal(TranslationHelper.Translation.Left, "Esquerda");
        Assert.Equal(TranslationHelper.Translation.LensMaker, "Criador de lentes");
        Assert.Equal(TranslationHelper.Translation.LensModel, "Modelo da lente");
        Assert.Equal(TranslationHelper.Translation.LightSource, "Fonte da luz");
        Assert.Equal(TranslationHelper.Translation.LightTheme, "Tema claro");
        Assert.Equal(TranslationHelper.Translation.Lighting, "Iluminação");
        Assert.Equal(TranslationHelper.Translation.Loading, "Carregando...");
        Assert.Equal(TranslationHelper.Translation.Longitude, "Longitude");
        Assert.Equal(TranslationHelper.Translation.Looping, "Repetição");
        Assert.Equal(TranslationHelper.Translation.LoopingDisabled, "Repetição desativada");
        Assert.Equal(TranslationHelper.Translation.LoopingEnabled, "Repetição ativada");
        Assert.Equal(TranslationHelper.Translation.Lossless, "Sem perdas");
        Assert.Equal(TranslationHelper.Translation.Lossy, "Com perdas");
        Assert.Equal(TranslationHelper.Translation.Low, "Baixo");
        Assert.Equal(TranslationHelper.Translation.Manual, "Manual");
        Assert.Equal(TranslationHelper.Translation.MaxAperture, "Abertura máxima");
        Assert.Equal(TranslationHelper.Translation.Maximize, "Maximizar");
        Assert.Equal(TranslationHelper.Translation.MegaPixels, "megapixels");
        Assert.Equal(TranslationHelper.Translation.Meter, "Metro");
        Assert.Equal(TranslationHelper.Translation.MeteringMode, "Modo de medição");
        Assert.Equal(TranslationHelper.Translation.Minimize, "Minimizar");
        Assert.Equal(TranslationHelper.Translation.MiscSettings, "Configurações diversas");
        Assert.Equal(TranslationHelper.Translation.Modified, "Modificado");
        Assert.Equal(TranslationHelper.Translation.Monochrome, "Monocromático");
        Assert.Equal(TranslationHelper.Translation.MouseDrag, "Arrastar com o mouse");
        Assert.Equal(TranslationHelper.Translation.MouseKeyBack, "Tecla do mouse para trás");
        Assert.Equal(TranslationHelper.Translation.MouseKeyForward, "Tecla do mouse para frente");
        Assert.Equal(TranslationHelper.Translation.MouseWheel, "Roda do mouse");
        Assert.Equal(TranslationHelper.Translation.MoveWindow, "Mover janela");
        Assert.Equal(TranslationHelper.Translation.Navigation, "Navegação");
        Assert.Equal(TranslationHelper.Translation.NearestNeighbor, "Nearest neighbor");
        Assert.Equal(TranslationHelper.Translation.NegativeColors, "Cores negativas");
        Assert.Equal(TranslationHelper.Translation.NewWindow, "Nova janela");
        Assert.Equal(TranslationHelper.Translation.NextFolder, "Navegar para a próxima pasta");
        Assert.Equal(TranslationHelper.Translation.NextImage, "Próxima imagem");
        Assert.Equal(TranslationHelper.Translation.NoChange, "Sem alterações");
        Assert.Equal(TranslationHelper.Translation.NoConversion, "Sem conversão");
        Assert.Equal(TranslationHelper.Translation.NoImage, "Nenhuma imagem foi carregada");
        Assert.Equal(TranslationHelper.Translation.NoImages, "Sem imagens");
        Assert.Equal(TranslationHelper.Translation.NoResize, "Sem redimensionamento");
        Assert.Equal(TranslationHelper.Translation.None, "Nenhum");
        Assert.Equal(TranslationHelper.Translation.Normal, "Normal");
        Assert.Equal(TranslationHelper.Translation.NormalWindow, "Janela normal");
        Assert.Equal(TranslationHelper.Translation.NotDefined, "Não definido");
        Assert.Equal(TranslationHelper.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationHelper.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationHelper.Translation.OldMovie, "Filme antigo");
        Assert.Equal(TranslationHelper.Translation.Open, "Abrir");
        Assert.Equal(TranslationHelper.Translation.OpenFileDialog, "Escolha um arquivo");
        Assert.Equal(TranslationHelper.Translation.OpenInSameWindow, "Abrir arquivos na mesma janela");
        Assert.Equal(TranslationHelper.Translation.OpenLastFile, "Abrir o último arquivo");
        Assert.Equal(TranslationHelper.Translation.OpenWith, "Abrir com...");
        Assert.Equal(TranslationHelper.Translation.OptimizeImage, "Otimizar imagem");
        Assert.Equal(TranslationHelper.Translation.Orientation, "Orientação");
        Assert.Equal(TranslationHelper.Translation.OutputFolder, "Pasta de saída");
        Assert.Equal(TranslationHelper.Translation.Pan, "Panorama");
        Assert.Equal(TranslationHelper.Translation.PaperFold, "Papel dobrado");
        Assert.Equal(TranslationHelper.Translation.PasswordArchive, "Não há suporte para arquivo protegido por senha");
        Assert.Equal(TranslationHelper.Translation.PasteImageFromClipholder, "Colar imagem");
        Assert.Equal(TranslationHelper.Translation.PencilSketch, "Esboço a lápis");
        Assert.Equal(TranslationHelper.Translation.PercentComplete, "% terminado...");
        Assert.Equal(TranslationHelper.Translation.Percentage, "Porcentagem");
        Assert.Equal(TranslationHelper.Translation.PermanentlyDelete, "Excluir permanentemente");
        Assert.Equal(TranslationHelper.Translation.PhotometricInterpretation, "Interpretação fotométrica");
        Assert.Equal(TranslationHelper.Translation.Pivot, "Pivô");
        Assert.Equal(TranslationHelper.Translation.Pixelate, "Pixelada");
        Assert.Equal(TranslationHelper.Translation.Pixels, "pixels");
        Assert.Equal(TranslationHelper.Translation.Portrait, "Retrato");
        Assert.Equal(TranslationHelper.Translation.PressKey, "Aperta uma tecla...");
        Assert.Equal(TranslationHelper.Translation.PrevFolder, "Navegar para a pasta anterior");
        Assert.Equal(TranslationHelper.Translation.PrevImage, "Imagem anterior");
        Assert.Equal(TranslationHelper.Translation.Print, "Imprimir");
        Assert.Equal(TranslationHelper.Translation.PrintSizeCm, "Tamanho da impressão (cm)");
        Assert.Equal(TranslationHelper.Translation.PrintSizeIn, "Tamanho da impressão (in)");
        Assert.Equal(TranslationHelper.Translation.Quality, "Qualidade");
        Assert.Equal(TranslationHelper.Translation.Random, "Aleatório");
        Assert.Equal(TranslationHelper.Translation.RecentFiles, "Arquivos recentes");
        Assert.Equal(TranslationHelper.Translation.RedEyeReduction, "Redução do olho vermelho");
        Assert.Equal(TranslationHelper.Translation.Reload, "Recarregar");
        Assert.Equal(TranslationHelper.Translation.RemoveStarRating, "Remover classificação");
        Assert.Equal(TranslationHelper.Translation.RenameFile, "Renomear arquivo");
        Assert.Equal(TranslationHelper.Translation.Reset, "Redefinir");
        Assert.Equal(TranslationHelper.Translation.ResetButtonText, "Redefinir para o padrão");
        Assert.Equal(TranslationHelper.Translation.ResetZoom, "Redefinir o zoom");
        Assert.Equal(TranslationHelper.Translation.Resize, "Redimensionar");
        Assert.Equal(TranslationHelper.Translation.ResizeImage, "Redimensionar imagem");
        Assert.Equal(TranslationHelper.Translation.Resolution, "Resolução");
        Assert.Equal(TranslationHelper.Translation.ResolutionUnit, "Unidade de resolução");
        Assert.Equal(TranslationHelper.Translation.RestartApp, "Reiniciar o aplicativo");
        Assert.Equal(TranslationHelper.Translation.RestoreDown, "Restaurar");
        Assert.Equal(TranslationHelper.Translation.Reverse, "Reverter");
        Assert.Equal(TranslationHelper.Translation.Right, "Direita");
        Assert.Equal(TranslationHelper.Translation.Ripple, "Ondulação");
        Assert.Equal(TranslationHelper.Translation.RippleAlt, "Alt. de ondulação");
        Assert.Equal(TranslationHelper.Translation.RotateLeft, "Girar à esquerda");
        Assert.Equal(TranslationHelper.Translation.RotateRight, "Girar à direita");
        Assert.Equal(TranslationHelper.Translation.Rotated, "Rotacionado");
        Assert.Equal(TranslationHelper.Translation.Saturation, "Saturação");
        Assert.Equal(TranslationHelper.Translation.Save, "Salvar");
        Assert.Equal(TranslationHelper.Translation.SaveAs, "Salvar como");
        Assert.Equal(TranslationHelper.Translation.SaveImage, "Salvar imagem");
        Assert.Equal(TranslationHelper.Translation.SavingFileFailed, "Falha ao salvar o arquivo");
        Assert.Equal(TranslationHelper.Translation.ScrollAndRotate, "Rolar e girar");
        Assert.Equal(TranslationHelper.Translation.ScrollDirection, "Direção da rolagem");
        Assert.Equal(TranslationHelper.Translation.ScrollDown, "Rolar para baixo");
        Assert.Equal(TranslationHelper.Translation.ScrollToBottom, "Role para o final");
        Assert.Equal(TranslationHelper.Translation.ScrollToTop, "Role para o topo");
        Assert.Equal(TranslationHelper.Translation.ScrollToZoom, "Zoom com a roda do mouse, navegação com Ctrl");
        Assert.Equal(TranslationHelper.Translation.ScrollUp, "Rolar para cima");
        Assert.Equal(TranslationHelper.Translation.Scrolling, "Rolagem");
        Assert.Equal(TranslationHelper.Translation.ScrollingDisabled, "Rolagem desativada");
        Assert.Equal(TranslationHelper.Translation.ScrollingEnabled, "Rolagem ativada");
        Assert.Equal(TranslationHelper.Translation.SearchSubdirectory, "Pesquisar subdiretórios");
        Assert.Equal(TranslationHelper.Translation.SecAbbreviation, "Sel.");
        Assert.Equal(TranslationHelper.Translation.SelectAll, "Selecionar tudo");
        Assert.Equal(TranslationHelper.Translation.SelectGalleryThumb, "Selecione a miniatura da galeria");
        Assert.Equal(TranslationHelper.Translation.SendCurrentImageToRecycleBin,
            "Enviar a imagem atual para a lixeira");
        Assert.Equal(TranslationHelper.Translation.SentFileToRecycleBin, "Enviar arquivo para a lixeira");
        Assert.Equal(TranslationHelper.Translation.SetAs, "Definir como...");
        Assert.Equal(TranslationHelper.Translation.SetAsLockScreenImage, "Definir como imagem da tela de bloqueio");
        Assert.Equal(TranslationHelper.Translation.SetAsWallpaper, "Definir como papel de parede");
        Assert.Equal(TranslationHelper.Translation.SetCurrentImageAsWallpaper,
            "Definir a imagem atual como papel de parede:");
        Assert.Equal(TranslationHelper.Translation.SetStarRating, "Definir classificação por estrelas");
        Assert.Equal(TranslationHelper.Translation.Settings, "Configurações");
        Assert.Equal(TranslationHelper.Translation.Shade, "Tom");
        Assert.Equal(TranslationHelper.Translation.Sharpness, "Nitidez");
        Assert.Equal(TranslationHelper.Translation.Shift, "Shift");
        Assert.Equal(TranslationHelper.Translation.ShowAllSettingsWindow, "Mostrar todas as janelas de configurações");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGallery, "Mostrar a galeria inferior");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Mostrar a galeria inferior quando a interface do usuário estiver oculta");
        Assert.Equal(TranslationHelper.Translation.ShowBottomToolbar, "Mostrar a barra de ferramentas inferior");
        Assert.Equal(TranslationHelper.Translation.ShowConfirmationOnEsc, "Mostrar aviso de fechar janela?");
        Assert.Equal(TranslationHelper.Translation.ShowFadeInButtonsOnHover,
            "Mostrar botões de transição ao passar o ponteiro");
        Assert.Equal(TranslationHelper.Translation.ShowFileSavingDialog, "Mostrar diálogo de salvamento de arquivos");
        Assert.Equal(TranslationHelper.Translation.ShowImageGallery, "Mostrar galeria de imagens");
        Assert.Equal(TranslationHelper.Translation.ShowImageInfo, "Mostrar informação de imagens");
        Assert.Equal(TranslationHelper.Translation.ShowInFolder, "Mostrar na pasta");
        Assert.Equal(TranslationHelper.Translation.ShowInfoWindow, "Mostrar janela de informação");
        Assert.Equal(TranslationHelper.Translation.ShowResizeWindow, "Mostrar a janela de redimensionamento");
        Assert.Equal(TranslationHelper.Translation.ShowUI, "Mostar a interface do usuário");
        Assert.Equal(TranslationHelper.Translation.ShutterPriority, "Prioridade");
        Assert.Equal(TranslationHelper.Translation.SideBySide, "Lado a lado");
        Assert.Equal(TranslationHelper.Translation.SideBySideTooltip, "Mostrar imagens lado a lado");
        Assert.Equal(TranslationHelper.Translation.Size, "Tamanho");
        Assert.Equal(TranslationHelper.Translation.SizeMp, "Tamanho (mp)");
        Assert.Equal(TranslationHelper.Translation.SizeTooltip, "Digite o tamanho desejado em pixels ou porcentagem.");
        Assert.Equal(TranslationHelper.Translation.Sketch, "Esboço");
        Assert.Equal(TranslationHelper.Translation.Slideshow, "Apresentação de slides");
        Assert.Equal(TranslationHelper.Translation.SmoothMagnify, "Ampliação suave");
        Assert.Equal(TranslationHelper.Translation.Soft, "Suave");
        Assert.Equal(TranslationHelper.Translation.Software, "Software");
        Assert.Equal(TranslationHelper.Translation.SortFilesBy, "Ordenar arquivos por");
        Assert.Equal(TranslationHelper.Translation.SourceFolder, "Pasta de origem");
        Assert.Equal(TranslationHelper.Translation.Space, "Espaço");
        Assert.Equal(TranslationHelper.Translation.Square, "Quadrado");
        Assert.Equal(TranslationHelper.Translation.Start, "Iniciar");
        Assert.Equal(TranslationHelper.Translation.StartSlideshow, "Iniciar apresentação");
        Assert.Equal(TranslationHelper.Translation.StayCentered, "Manter a janela centralizada");
        Assert.Equal(TranslationHelper.Translation.StayTopMost, "Manter a janela sobreposta");
        Assert.Equal(TranslationHelper.Translation.Stretch, "Esticar");
        Assert.Equal(TranslationHelper.Translation.StretchImage, "Esticar imagem");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightDetected,
            "Detecção de luz de retorno estroboscópica");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightNotDetected,
            "Luz de retorno estroboscópica detectada");
        Assert.Equal(TranslationHelper.Translation.Subject, "Assunto");
        Assert.Equal(TranslationHelper.Translation.Swirl, "Espiral");
        Assert.Equal(TranslationHelper.Translation.TelescopicBlur, "Desfoque telescópico");
        Assert.Equal(TranslationHelper.Translation.Theme, "Tena");
        Assert.Equal(TranslationHelper.Translation.Thumbnail, "Miniatura");
        Assert.Equal(TranslationHelper.Translation.Tile, "Quadrado");
        Assert.Equal(TranslationHelper.Translation.Title, "Título");
        Assert.Equal(TranslationHelper.Translation.ToggleBackgroundColor, "Alternar a cor de fundo");
        Assert.Equal(TranslationHelper.Translation.ToggleFullscreen, "Alternar a tela cheia");
        Assert.Equal(TranslationHelper.Translation.ToggleLooping, "Alternar a repetição de imagens");
        Assert.Equal(TranslationHelper.Translation.ToggleScroll, "Alternar a rolagem");
        Assert.Equal(TranslationHelper.Translation.ToggleTaskbarProgress, "Exibir o progresso na barra de tarefas");
        Assert.Equal(TranslationHelper.Translation.ToneMapping, "Mapeamento de tons");
        Assert.Equal(TranslationHelper.Translation.UnableToRender, "Não foi possível renderizar a imagem");
        Assert.Equal(TranslationHelper.Translation.Uncalibrated, "Não calibrado");
        Assert.Equal(TranslationHelper.Translation.Underwater, "Debaixo d'água");
        Assert.Equal(TranslationHelper.Translation.UnexpectedError, "Ocorreu um erro desconhecido");
        Assert.Equal(TranslationHelper.Translation.Unflip, "Desenrolar");
        Assert.Equal(TranslationHelper.Translation.Uniform, "Uniforme");
        Assert.Equal(TranslationHelper.Translation.UniformToFill, "Igualmente preenchida");
        Assert.Equal(TranslationHelper.Translation.Unknown, "Desconhecido");
        Assert.Equal(TranslationHelper.Translation.UnsupportedFile, "Arquivo não suportado");
        Assert.Equal(TranslationHelper.Translation.Up, "Para cima");
        Assert.Equal(TranslationHelper.Translation.UsingMouse, "Usando o mouse");
        Assert.Equal(TranslationHelper.Translation.UsingTouchpad, "Usando o touchpad");
        Assert.Equal(TranslationHelper.Translation.Version, "Versão:");
        Assert.Equal(TranslationHelper.Translation.ViewLicenseFile, "Exibir arquivo de licença");
        Assert.Equal(TranslationHelper.Translation.WaveWarper, "Onda deformadora");
        Assert.Equal(TranslationHelper.Translation.WhiteBalance, "Equilíbrio do branco");
        Assert.Equal(TranslationHelper.Translation.WhiteFluorescent, "Branco fluorescente");
        Assert.Equal(TranslationHelper.Translation.Width, "Largura");
        Assert.Equal(TranslationHelper.Translation.WidthAndHeight, "Largura e altura");
        Assert.Equal(TranslationHelper.Translation.WindowManagement, "Gerenciamento de janelas");
        Assert.Equal(TranslationHelper.Translation.WindowScaling, "Dimensionamento da janela");
        Assert.Equal(TranslationHelper.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationHelper.Translation.ZoomIn, "Aumentar o zoom");
        Assert.Equal(TranslationHelper.Translation.ZoomOut, "Diminuir o zoom");
        Assert.Equal(TranslationHelper.Translation._1Star, "1 classificação por estrela");
        Assert.Equal(TranslationHelper.Translation._2Star, "2 classificação por estrela");
        Assert.Equal(TranslationHelper.Translation._3Star, "3 classificação por estrela");
        Assert.Equal(TranslationHelper.Translation._4Star, "4 classificação por estrela");
        Assert.Equal(TranslationHelper.Translation._5Star, "5 classificação por estrela");
    }
}