using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class ChineseSimplifiedUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckChineseSimplifiedLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("zh-CN");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "关于");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "动作程序");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "已复制");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "额外功能");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed, "按住键时调整速度");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "调整幻灯片切换时间");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "调整缩放动画速度");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "调整缩放级别");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "前进 100 张图片");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "前进 10 张图片");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut, "在最大尺寸时避免缩小图像");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "海拔");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "光圈优先");
        Assert.Equal(TranslationManager.Translation.Appearance, "外观");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "应用程序快捷键");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "应用程序启动");
        Assert.Equal(TranslationManager.Translation.Apply, "应用");
        Assert.Equal(TranslationManager.Translation.Applying, "正在应用");
        Assert.Equal(TranslationManager.Translation.Ascending, "上升");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "纵横比");
        Assert.Equal(TranslationManager.Translation.Authors, "作者");
        Assert.Equal(TranslationManager.Translation.Auto, "自动");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "自动适应窗口");
        Assert.Equal(TranslationManager.Translation.BadArchive, "无法处理压缩文件");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Base64 图片");
        Assert.Equal(TranslationManager.Translation.BatchResize, "批量调整尺寸");
        Assert.Equal(TranslationManager.Translation.BitDepth, "位深");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "黑白");
        Assert.Equal(TranslationManager.Translation.Blur, "模糊");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "底部图库项目");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch, "缩略图拉伸在底部图库");
        Assert.Equal(TranslationManager.Translation.Brightness, "亮度");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "相机制造商");
        Assert.Equal(TranslationManager.Translation.CameraModel, "相机型号");
        Assert.Equal(TranslationManager.Translation.Cancel, "取消");
        Assert.Equal(TranslationManager.Translation.Center, "居中");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "居中窗口");
        Assert.Equal(TranslationManager.Translation.Centimeters, "cm");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "切换背景");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip, "在透明背景的图像中改变背景颜色");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText, "点击文本框以更改按键绑定。按 Esc 键取消绑定。");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip, "点击更改键绑定");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart, "* 切换主题需要重新启动应用程序");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "检查更新");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "剪贴板图片");
        Assert.Equal(TranslationManager.Translation.Close, "关闭");
        Assert.Equal(TranslationManager.Translation.CloseApp, "关闭本应用程序");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "关闭相册");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "您想关闭窗口吗？");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "多云");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "取色工具");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "从图片中选取颜色");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "颜色表示");
        Assert.Equal(TranslationManager.Translation.ColorTone, "色调");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "压缩位像素");
        Assert.Equal(TranslationManager.Translation.Compression, "压缩");
        Assert.Equal(TranslationManager.Translation.Contrast, "对比度");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "转换为");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "已复制为 base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "冷白荧光");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "已将图像复制至剪贴板");
        Assert.Equal(TranslationManager.Translation.Copy, "复制");
        Assert.Equal(TranslationManager.Translation.CopyFile, "复制文件");
        Assert.Equal(TranslationManager.Translation.CopyImage, "复制图像");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "将图片复制至剪贴板");
        Assert.Equal(TranslationManager.Translation.Copyright, "版权");
        Assert.Equal(TranslationManager.Translation.Created, "创建时间");
        Assert.Equal(TranslationManager.Translation.CreationTime, "创建时间");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "创意程序");
        Assert.Equal(TranslationManager.Translation.Credits, "鸣谢");
        Assert.Equal(TranslationManager.Translation.Crop, "裁剪");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Esc 键关闭，Enter 键保存");
        Assert.Equal(TranslationManager.Translation.CropPicture, "裁剪图片");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Ctrl + 鼠标滚轮缩放，鼠标滚轮导航");
        Assert.Equal(TranslationManager.Translation.Cut, "剪切");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "深色主题");
        Assert.Equal(TranslationManager.Translation.Date, "时间");
        Assert.Equal(TranslationManager.Translation.DateTaken, "拍摄日期");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "白天白光");
        Assert.Equal(TranslationManager.Translation.Daylight, "白天");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "白天荧光");
        Assert.Equal(TranslationManager.Translation.Del, "Del");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "删除文件");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently, "您確定要永久刪除嗎");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "已删除文件");
        Assert.Equal(TranslationManager.Translation.Descending, "下降");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "数码变焦");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover, "禁用鼠标悬停时的淡入按钮");
        Assert.Equal(TranslationManager.Translation.DiskSize, "磁盘大小");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "双击");
        Assert.Equal(TranslationManager.Translation.Down, "下");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo, "将文件拖拽至 Windows 资源管理器或者其他应用程序/浏览器");
        Assert.Equal(TranslationManager.Translation.DragImage, "拖拽图片");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "拖放以打开图像");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "创建副本");
        Assert.Equal(TranslationManager.Translation.Effects, "特效");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "显示图像特效窗口");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "关闭当前打开的窗口和菜单");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Exif 版本");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "展开的图库项目");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "曝光补偿");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "曝光程序");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "曝光时间");
        Assert.Equal(TranslationManager.Translation.FNumber, "F 数");
        Assert.Equal(TranslationManager.Translation.File, "文件");
        Assert.Equal(TranslationManager.Translation.FileCopy, "文件已复制");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "复制文件路径");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "文件路径已复制");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "文件已剪切");
        Assert.Equal(TranslationManager.Translation.FileExtension, "文件拓展名");
        Assert.Equal(TranslationManager.Translation.FileManagement, "文件管理");
        Assert.Equal(TranslationManager.Translation.FileName, "文件名");
        Assert.Equal(TranslationManager.Translation.FilePaste, "粘贴");
        Assert.Equal(TranslationManager.Translation.FileProperties, "文件属性");
        Assert.Equal(TranslationManager.Translation.FileSize, "文件大小");
        Assert.Equal(TranslationManager.Translation.Files, "文件");
        Assert.Equal(TranslationManager.Translation.Fill, "填充");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ 适应高度");
        Assert.Equal(TranslationManager.Translation.FillSquare, "填充正方形");
        Assert.Equal(TranslationManager.Translation.FineWeather, "晴天");
        Assert.Equal(TranslationManager.Translation.FirstImage, "第一张图片");
        Assert.Equal(TranslationManager.Translation.Fit, "适应");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "适应窗口/图片");
        Assert.Equal(TranslationManager.Translation.Flash, "闪光灯");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "闪光未触发");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "闪光能量");
        Assert.Equal(TranslationManager.Translation.FlashFired, "闪光已触发");
        Assert.Equal(TranslationManager.Translation.FlashMode, "闪光模式");
        Assert.Equal(TranslationManager.Translation.Flip, "水平翻转");
        Assert.Equal(TranslationManager.Translation.Flipped, "已水平翻转");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "荧光");
        Assert.Equal(TranslationManager.Translation.FocalLength, "焦距");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "35mm 焦距");
        Assert.Equal(TranslationManager.Translation.Folder, "文件夹");
        Assert.Equal(TranslationManager.Translation.Forward, "向前");
        Assert.Equal(TranslationManager.Translation.Fstop, "F 值");
        Assert.Equal(TranslationManager.Translation.FullPath, "完整路径");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "全屏");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "图库设置");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "图库缩略图拉伸");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "常规设置");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "生成缩略图");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Github 仓库");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "玻璃主题");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "后退 100 张图片");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "后退 10 张图片");
        Assert.Equal(TranslationManager.Translation.GoToImageAtSpecifiedIndex, "跳转至指定图片");
        Assert.Equal(TranslationManager.Translation.Hard, "硬");
        Assert.Equal(TranslationManager.Translation.Height, "高度");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "收起底部图");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "隐藏底部工具栏");
        Assert.Equal(TranslationManager.Translation.HideUI, "隐藏界面");
        Assert.Equal(TranslationManager.Translation.High, "高");
        Assert.Equal(TranslationManager.Translation.HighQuality, "高质量");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "主题高亮色");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "ISO 速度");
        Assert.Equal(TranslationManager.Translation.Image, "图片");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "图像混淆");
        Assert.Equal(TranslationManager.Translation.ImageControl, "图片调整");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "图像信息");
        Assert.Equal(TranslationManager.Translation.Inches, "in");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "信息窗口");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "信息与快捷键");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "界面配置");
        Assert.Equal(TranslationManager.Translation.Landscape, "横向");
        Assert.Equal(TranslationManager.Translation.Language, "语言");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "访问时间");
        Assert.Equal(TranslationManager.Translation.LastImage, "最后一张图片");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "修改时间");
        Assert.Equal(TranslationManager.Translation.Latitude, "纬度");
        Assert.Equal(TranslationManager.Translation.Left, "左");
        Assert.Equal(TranslationManager.Translation.LensMaker, "镜头制造商");
        Assert.Equal(TranslationManager.Translation.LensModel, "镜头型号");
        Assert.Equal(TranslationManager.Translation.LightSource, "光源");
        Assert.Equal(TranslationManager.Translation.LightTheme, "亮色主题");
        Assert.Equal(TranslationManager.Translation.Lighting, "照明");
        Assert.Equal(TranslationManager.Translation.Loading, "正在加载...");
        Assert.Equal(TranslationManager.Translation.Longitude, "经度");
        Assert.Equal(TranslationManager.Translation.Looping, "循环");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "已禁用循环");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "已启用循环");
        Assert.Equal(TranslationManager.Translation.Lossless, "无损");
        Assert.Equal(TranslationManager.Translation.Lossy, "有损");
        Assert.Equal(TranslationManager.Translation.Low, "低");
        Assert.Equal(TranslationManager.Translation.Manual, "手动");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "最大光圈");
        Assert.Equal(TranslationManager.Translation.Maximize, "最大化");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "mp");
        Assert.Equal(TranslationManager.Translation.Meter, "米");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "测光模式");
        Assert.Equal(TranslationManager.Translation.Minimize, "最小化");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "其他设置");
        Assert.Equal(TranslationManager.Translation.Modified, "修改时间");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "鼠标拖拽");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "鼠标拓展键 向后键");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "鼠标拓展键 向前键");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "鼠标滚轮");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "移动窗口");
        Assert.Equal(TranslationManager.Translation.Navigation, "导航");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "最近邻");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "反色");
        Assert.Equal(TranslationManager.Translation.NewWindow, "新窗口");
        Assert.Equal(TranslationManager.Translation.NextFolder, "导航到下一个文件夹");
        Assert.Equal(TranslationManager.Translation.NextImage, "下一张图片");
        Assert.Equal(TranslationManager.Translation.NoChange, "无变化");
        Assert.Equal(TranslationManager.Translation.NoConversion, "不转换");
        Assert.Equal(TranslationManager.Translation.NoImage, "请打开图片");
        Assert.Equal(TranslationManager.Translation.NoImages, "无图像");
        Assert.Equal(TranslationManager.Translation.NoResize, "禁止缩放");
        Assert.Equal(TranslationManager.Translation.None, "没有任何");
        Assert.Equal(TranslationManager.Translation.Normal, "正常");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "正常窗口");
        Assert.Equal(TranslationManager.Translation.NotDefined, "未定义");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "数字键盘 -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "数字键盘 +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "老电影");
        Assert.Equal(TranslationManager.Translation.Open, "打开");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "打开文件对话框");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "在同一窗口中打开文件");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "打开最后一个文件");
        Assert.Equal(TranslationManager.Translation.OpenWith, "打开使用");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "优化图像");
        Assert.Equal(TranslationManager.Translation.Orientation, "方向");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "输出文件夹");
        Assert.Equal(TranslationManager.Translation.Pan, "平移");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "暂不支持带密码的压缩文件");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "从剪贴板中粘贴图片");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "铅笔素描");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% 已完成…");
        Assert.Equal(TranslationManager.Translation.Percentage, "百分比");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "永久删除");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "光度学解释");
        Assert.Equal(TranslationManager.Translation.Pixels, "px");
        Assert.Equal(TranslationManager.Translation.Portrait, "纵向");
        Assert.Equal(TranslationManager.Translation.PressKey, "按键...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "导航到上一个文件夹");
        Assert.Equal(TranslationManager.Translation.PrevImage, "上一张图片");
        Assert.Equal(TranslationManager.Translation.Print, "打印");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "打印大小（厘米）");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "打印大小（英尺）");
        Assert.Equal(TranslationManager.Translation.Quality, "质量");
        Assert.Equal(TranslationManager.Translation.Random, "随机");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "最近文件");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "减少红眼");
        Assert.Equal(TranslationManager.Translation.Reload, "重新载入");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "移除评分");
        Assert.Equal(TranslationManager.Translation.RenameFile, "重命名文件");
        Assert.Equal(TranslationManager.Translation.Reset, "重置");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "重置为默认设置");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "重设缩放");
        Assert.Equal(TranslationManager.Translation.Resize, "调整尺寸");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "调整图像大小");
        Assert.Equal(TranslationManager.Translation.Resolution, "分辨率");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "分辨率单位");
        Assert.Equal(TranslationManager.Translation.RestartApp, "重新启动应用程序");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "退出全屏");
        Assert.Equal(TranslationManager.Translation.Reverse, "逆转");
        Assert.Equal(TranslationManager.Translation.Right, "右");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "向左旋转");
        Assert.Equal(TranslationManager.Translation.RotateRight, "向右旋转");
        Assert.Equal(TranslationManager.Translation.Rotated, "已旋转");
        Assert.Equal(TranslationManager.Translation.Saturation, "饱和度");
        Assert.Equal(TranslationManager.Translation.Save, "保存");
        Assert.Equal(TranslationManager.Translation.SaveAs, "另存为");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "文件保存失败");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "滚动和旋转");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "滚动方向");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "向下滑动");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "滑动到底部");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "滑动到顶部");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "鼠标滚轮缩放，Ctrl + 鼠标滚轮导航");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "向上滑动");
        Assert.Equal(TranslationManager.Translation.Scrolling, "滚动");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "已禁用滚动");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "已启用滚动");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "包含子目录中的图片");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "秒");
        Assert.Equal(TranslationManager.Translation.SelectAll, "全选");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "选择画廊缩略图");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin, "将当前图片移至回收站");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "将文件移至回收站");
        Assert.Equal(TranslationManager.Translation.SetAs, "设置为…");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "设置为锁屏图像");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "设置为背景");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper, "将当前图像设置为壁纸：");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "设置星级评分");
        Assert.Equal(TranslationManager.Translation.Settings, "设置");
        Assert.Equal(TranslationManager.Translation.Shade, "阴影");
        Assert.Equal(TranslationManager.Translation.Sharpness, "锐度");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "显示设置窗口");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "查看底部图");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden, "当用户界面隐藏时显示底部图库");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "查看底部工具栏");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc, "按下 'Esc' 时显示确认对话框");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover, "將鼠標懸停時顯示淡入按鈕");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "查看文件保存对话框");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "显示图片相册");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "显示图像信息");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "在文件夹中显示");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "显示应用程序信息窗口");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "显示调整尺寸窗口");
        Assert.Equal(TranslationManager.Translation.ShowUI, "顯示介面");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "快门优先");
        Assert.Equal(TranslationManager.Translation.SideBySide, "并排");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "并排显示图像");
        Assert.Equal(TranslationManager.Translation.Size, "大小");
        Assert.Equal(TranslationManager.Translation.SizeMp, "大小（兆像素）");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "以像素或百分比输入所需的尺寸。");
        Assert.Equal(TranslationManager.Translation.Slideshow, "幻灯片");
        Assert.Equal(TranslationManager.Translation.Soft, "柔和");
        Assert.Equal(TranslationManager.Translation.Software, "软件");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "排序方式");
        Assert.Equal(TranslationManager.Translation.SourceFolder, "源文件夹");
        Assert.Equal(TranslationManager.Translation.Space, "Space");
        Assert.Equal(TranslationManager.Translation.Square, "正方形");
        Assert.Equal(TranslationManager.Translation.Start, "启动");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "放映幻灯片");
        Assert.Equal(TranslationManager.Translation.StayCentered, "保持窗口居中");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "窗口置顶");
        Assert.Equal(TranslationManager.Translation.Stretch, "拉伸");
        Assert.Equal(TranslationManager.Translation.StretchImage, "拉伸图像");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "检测到闪光灯返回光");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected, "未检测到闪光灯返回光");
        Assert.Equal(TranslationManager.Translation.Subject, "主题");
        Assert.Equal(TranslationManager.Translation.Theme, "主题");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "缩略图");
        Assert.Equal(TranslationManager.Translation.Tile, "平铺");
        Assert.Equal(TranslationManager.Translation.Title, "标题");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "切换背景色");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "切换全屏");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "切换循环");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "切换滚动");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "显示任务栏进度");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "无法渲染图像");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "未校准");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "发生未知错误");
        Assert.Equal(TranslationManager.Translation.Unflip, "取消水平翻转");
        Assert.Equal(TranslationManager.Translation.Uniform, "均匀");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "均匀填充");
        Assert.Equal(TranslationManager.Translation.Unknown, "未知");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "不支持的文件格式");
        Assert.Equal(TranslationManager.Translation.Up, "上");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "使用鼠标");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "使用触控板");
        Assert.Equal(TranslationManager.Translation.Version, "版本：");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "查看开源协议");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "白平衡");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "白光荧光");
        Assert.Equal(TranslationManager.Translation.Width, "宽度");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "宽度和高度");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "窗口管理");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "窗口缩放");
        Assert.Equal(TranslationManager.Translation.Zoom, "缩放");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "放大");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "缩小");
        Assert.Equal(TranslationManager.Translation._1Star, "1星评分");
        Assert.Equal(TranslationManager.Translation._2Star, "2星评分");
        Assert.Equal(TranslationManager.Translation._3Star, "3星评分");
        Assert.Equal(TranslationManager.Translation._4Star, "4星评分");
        Assert.Equal(TranslationManager.Translation._5Star, "5星评分");
    }
}