using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class DanishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckDanishLanguage()
    {
        var exists = await TranslationHelper.LoadLanguage("da");
        Assert.True(exists);

        Assert.Equal(TranslationHelper.Translation.About, "Om");
        Assert.Equal(TranslationHelper.Translation.ActionProgram, "Action program");
        Assert.Equal(TranslationHelper.Translation.AddedToClipboard, "Tilføjet til udklipsholderen");
        Assert.Equal(TranslationHelper.Translation.AdditionalFunctions, "Diverse funktioner");
        Assert.Equal(TranslationHelper.Translation.AdjustNavSpeed, "Juster hastighed, når tasten holdes nede");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForSlideshow, "Juster timing for slideshowet");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForZoom, "Justér zooming hastighed");
        Assert.Equal(TranslationHelper.Translation.AdjustZoomLevel, "Juster zoom niveau");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy100Images, "Gå 100 billeder frem");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy10Images, "Gå 10 billeder frem");
        Assert.Equal(TranslationHelper.Translation.AllowZoomOut,
            "Undgå at zoome billedet ud, når det allerede er i maksimal størrelse");
        Assert.Equal(TranslationHelper.Translation.Alt, "Alt");
        Assert.Equal(TranslationHelper.Translation.Altitude, "Højde");
        Assert.Equal(TranslationHelper.Translation.AperturePriority, "Blænde prioritet");
        Assert.Equal(TranslationHelper.Translation.Appearance, "Udseende");
        Assert.Equal(TranslationHelper.Translation.ApplicationShortcuts, "Genveje til programmet");
        Assert.Equal(TranslationHelper.Translation.ApplicationStartup, "Opstart af programmet");
        Assert.Equal(TranslationHelper.Translation.Apply, "Anvend");
        Assert.Equal(TranslationHelper.Translation.Applying, "Udfører");
        Assert.Equal(TranslationHelper.Translation.Ascending, "Stigende");
        Assert.Equal(TranslationHelper.Translation.AspectRatio, "Aspektforhold");
        Assert.Equal(TranslationHelper.Translation.Authors, "Forfattere");
        Assert.Equal(TranslationHelper.Translation.Auto, "Auto");
        Assert.Equal(TranslationHelper.Translation.AutoFitWindow, "Auto tilpas vindue");
        Assert.Equal(TranslationHelper.Translation.BadArchive, "Arkivet kunne ikke behandles");
        Assert.Equal(TranslationHelper.Translation.BandedSwirl, "Båndet virvel");
        Assert.Equal(TranslationHelper.Translation.Bands, "Bånd");
        Assert.Equal(TranslationHelper.Translation.Base64Image, "Base64 billede");
        Assert.Equal(TranslationHelper.Translation.BatchResize, "Batch Billedstørrelse");
        Assert.Equal(TranslationHelper.Translation.BitDepth, "Bit dybde");
        Assert.Equal(TranslationHelper.Translation.BlackAndWhite, "Sort/hvid");
        Assert.Equal(TranslationHelper.Translation.Bloom, "Bloom");
        Assert.Equal(TranslationHelper.Translation.Blur, "Sløring");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryItemSize, "Billedstørrelse i bundgalleriet");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryThumbnailStretch,
            "Udstrækning af billeder i bundgalleriet");
        Assert.Equal(TranslationHelper.Translation.Brightness, "Lysstyrke");
        Assert.Equal(TranslationHelper.Translation.CameraMaker, "Kamera producent");
        Assert.Equal(TranslationHelper.Translation.CameraModel, "Kamera model");
        Assert.Equal(TranslationHelper.Translation.Cancel, "Annuler");
        Assert.Equal(TranslationHelper.Translation.Center, "Centrer");
        Assert.Equal(TranslationHelper.Translation.CenterWindow, "Centrer vinduet");
        Assert.Equal(TranslationHelper.Translation.Centimeters, "centimeter");
        Assert.Equal(TranslationHelper.Translation.ChangeBackground, "Skift baggrund");
        Assert.Equal(TranslationHelper.Translation.ChangeBackgroundTooltip,
            "Skift mellem baggrundsfarve til billeder med gennemsigtig baggrund");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingText,
            "Klik på en tekstboks for at ændre genvejen. Tryk på Esc for at frakoble den.");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingTooltip, "Klik for at ændre genvejstast");
        Assert.Equal(TranslationHelper.Translation.ChangingThemeRequiresRestart, "* Skiftning af tema kræver genstart");
        Assert.Equal(TranslationHelper.Translation.CheckForUpdates, "Søg efter opdateringer");
        Assert.Equal(TranslationHelper.Translation.ClipboardImage, "Billede fra udklipsholderen");
        Assert.Equal(TranslationHelper.Translation.Close, "Luk");
        Assert.Equal(TranslationHelper.Translation.CloseApp, "Lukker hele programmet");
        Assert.Equal(TranslationHelper.Translation.CloseGallery, "Luk galleri");
        Assert.Equal(TranslationHelper.Translation.CloseWindowPrompt, "Vil du gerne lukke vinduet?");
        Assert.Equal(TranslationHelper.Translation.CloudyWeather, "Overskyet vejr");
        Assert.Equal(TranslationHelper.Translation.ColorPickerTool, "Farvevælgningsværktøj");
        Assert.Equal(TranslationHelper.Translation.ColorPickerToolTooltip, "Vælg en farve fra billedet");
        Assert.Equal(TranslationHelper.Translation.ColorRepresentation, "Farve repræsentation");
        Assert.Equal(TranslationHelper.Translation.ColorTone, "Farve Tone");
        Assert.Equal(TranslationHelper.Translation.CompressedBitsPixel, "Komprimerede bits pr. pixel");
        Assert.Equal(TranslationHelper.Translation.Compression, "Kompression");
        Assert.Equal(TranslationHelper.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationHelper.Translation.ConvertTo, "Konverter til");
        Assert.Equal(TranslationHelper.Translation.ConvertedToBase64, "Konverteret til base64");
        Assert.Equal(TranslationHelper.Translation.CoolWhiteFluorescent, "Kold hvid fluorescerende");
        Assert.Equal(TranslationHelper.Translation.CopiedImage, "Kopier billede til udklipsholderen");
        Assert.Equal(TranslationHelper.Translation.Copy, "Kopier");
        Assert.Equal(TranslationHelper.Translation.CopyFile, "Kopier fil");
        Assert.Equal(TranslationHelper.Translation.CopyImage, "Kopier billede");
        Assert.Equal(TranslationHelper.Translation.CopyImageTooltip, "Kopier som Windows-klippebordsbillede");
        Assert.Equal(TranslationHelper.Translation.Copyright, "Ophavsret");
        Assert.Equal(TranslationHelper.Translation.Created, "Opretted");
        Assert.Equal(TranslationHelper.Translation.CreationTime, "Oprettelses tid");
        Assert.Equal(TranslationHelper.Translation.CreativeProgram, "Kreativt program");
        Assert.Equal(TranslationHelper.Translation.Credits, "Anerkendelser");
        Assert.Equal(TranslationHelper.Translation.Crop, "Beskær");
        Assert.Equal(TranslationHelper.Translation.CropMessage, "Tryk Esc for at lukke, Enter for at gemme");
        Assert.Equal(TranslationHelper.Translation.CropPicture, "Beskær billede");
        Assert.Equal(TranslationHelper.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationHelper.Translation.CtrlToZoom, "Zoom med Ctrl, naviger med musehjulet");
        Assert.Equal(TranslationHelper.Translation.Cut, "Klip");
        Assert.Equal(TranslationHelper.Translation.DarkTheme, "Mørkt tema");
        Assert.Equal(TranslationHelper.Translation.Date, "Dato");
        Assert.Equal(TranslationHelper.Translation.DateTaken, "Dato fotograferet");
        Assert.Equal(TranslationHelper.Translation.DayWhiteFluorescent, "Dag hvid fluorescerende");
        Assert.Equal(TranslationHelper.Translation.Daylight, "Dagslys");
        Assert.Equal(TranslationHelper.Translation.DaylightFluorescent, "Dagslys fluorescerende");
        Assert.Equal(TranslationHelper.Translation.Del, "Del");
        Assert.Equal(TranslationHelper.Translation.DeleteFile, "Slet fil");
        Assert.Equal(TranslationHelper.Translation.DeleteFilePermanently,
            "Er du sikker på, at du vil slette filen permanent");
        Assert.Equal(TranslationHelper.Translation.DeletedFile, "Slettede filen");
        Assert.Equal(TranslationHelper.Translation.Descending, "Faldende");
        Assert.Equal(TranslationHelper.Translation.DigitalZoom, "Digital zoom");
        Assert.Equal(TranslationHelper.Translation.DirectionalBlur, "Retningsvis Sløring");
        Assert.Equal(TranslationHelper.Translation.DisableFadeInButtonsOnHover,
            "Skjul skjulte knapper, når musen er i kanterne i programmet");
        Assert.Equal(TranslationHelper.Translation.DiskSize, "Disk størrelse");
        Assert.Equal(TranslationHelper.Translation.DoubleClick, "Dobbeltklik");
        Assert.Equal(TranslationHelper.Translation.Down, "Ned");
        Assert.Equal(TranslationHelper.Translation.Dpi, "DPI");
        Assert.Equal(TranslationHelper.Translation.DragFileTo,
            "Slip filen til stifinderen eller et andet program/browser");
        Assert.Equal(TranslationHelper.Translation.DragImage, "Træk billede");
        Assert.Equal(TranslationHelper.Translation.DropToLoad, "Slip for at indlæse");
        Assert.Equal(TranslationHelper.Translation.DuplicateFile, "Dupliker fil");
        Assert.Equal(TranslationHelper.Translation.Effects, "Billedeffekter");
        Assert.Equal(TranslationHelper.Translation.EffectsTooltip, "Vis billedeffektsvinduet");
        Assert.Equal(TranslationHelper.Translation.Embossed, "Emboss");
        Assert.Equal(TranslationHelper.Translation.Enter, "Enter");
        Assert.Equal(TranslationHelper.Translation.Esc, "Esc");
        Assert.Equal(TranslationHelper.Translation.EscCloseTooltip, "Lukker nuværende åbne vindue el. menu");
        Assert.Equal(TranslationHelper.Translation.ExifVersion, "Exif version");
        Assert.Equal(TranslationHelper.Translation.ExpandedGalleryItemSize, "Billedstørrelse i galleriet");
        Assert.Equal(TranslationHelper.Translation.ExposureBias, "Eksponeringsbias");
        Assert.Equal(TranslationHelper.Translation.ExposureProgram, "Eksponeringsprogram");
        Assert.Equal(TranslationHelper.Translation.ExposureTime, "Eksponeringstid");
        Assert.Equal(TranslationHelper.Translation.FNumber, "F nummer");
        Assert.Equal(TranslationHelper.Translation.File, "fil");
        Assert.Equal(TranslationHelper.Translation.FileCopy, "Fil tilføjet til udklipsholderen");
        Assert.Equal(TranslationHelper.Translation.FileCopyPath, "Kopier fil sti");
        Assert.Equal(TranslationHelper.Translation.FileCopyPathMessage, "Fil stien tilføjet til udklipsholderen");
        Assert.Equal(TranslationHelper.Translation.FileCutMessage, "Fil tilføjet til flytte udklipsholderen");
        Assert.Equal(TranslationHelper.Translation.FileExtension, "Filtypenavn");
        Assert.Equal(TranslationHelper.Translation.FileManagement, "Behandling af filer");
        Assert.Equal(TranslationHelper.Translation.FileName, "Fil navn");
        Assert.Equal(TranslationHelper.Translation.FilePaste, "Indsæt");
        Assert.Equal(TranslationHelper.Translation.FileProperties, "Filegenskaber");
        Assert.Equal(TranslationHelper.Translation.FileSize, "Filstørrelse");
        Assert.Equal(TranslationHelper.Translation.Files, "filer");
        Assert.Equal(TranslationHelper.Translation.Fill, "Fyld");
        Assert.Equal(TranslationHelper.Translation.FillHeight, "⇔ Fyld højde");
        Assert.Equal(TranslationHelper.Translation.FillSquare, "Fyldt firkant");
        Assert.Equal(TranslationHelper.Translation.FineWeather, "Godt vejr");
        Assert.Equal(TranslationHelper.Translation.FirstImage, "Første billede");
        Assert.Equal(TranslationHelper.Translation.Fit, "Tilpas");
        Assert.Equal(TranslationHelper.Translation.FitToWindow, "Tilpas til vinduet");
        Assert.Equal(TranslationHelper.Translation.Flash, "Flash");
        Assert.Equal(TranslationHelper.Translation.FlashDidNotFire, "Flash ikke tændt");
        Assert.Equal(TranslationHelper.Translation.FlashEnergy, "Flash energi");
        Assert.Equal(TranslationHelper.Translation.FlashFired, "Flash tændt");
        Assert.Equal(TranslationHelper.Translation.FlashMode, "Flash tilstand");
        Assert.Equal(TranslationHelper.Translation.Flip, "Spejlvend");
        Assert.Equal(TranslationHelper.Translation.Flipped, "Spejlvendt");
        Assert.Equal(TranslationHelper.Translation.Fluorescent, "Fluorescerende");
        Assert.Equal(TranslationHelper.Translation.FocalLength, "Brændvidde");
        Assert.Equal(TranslationHelper.Translation.FocalLength35mm, "Brændvidde 35mm");
        Assert.Equal(TranslationHelper.Translation.Folder, "Mappe");
        Assert.Equal(TranslationHelper.Translation.Forward, "Fremad");
        Assert.Equal(TranslationHelper.Translation.FrostyOutline, "Frosty Outline");
        Assert.Equal(TranslationHelper.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationHelper.Translation.FullPath, "Filsti");
        Assert.Equal(TranslationHelper.Translation.Fullscreen, "Fuldskærm");
        Assert.Equal(TranslationHelper.Translation.GallerySettings, "Galleriindstillinger");
        Assert.Equal(TranslationHelper.Translation.GalleryThumbnailStretch, "Udstrækning af galleribilleder");
        Assert.Equal(TranslationHelper.Translation.GeneralSettings, "Generale Indstillinger");
        Assert.Equal(TranslationHelper.Translation.GenerateThumbnails, "Generer thumbnails");
        Assert.Equal(TranslationHelper.Translation.GithubRepo, "Github side");
        Assert.Equal(TranslationHelper.Translation.GlassTheme, "Glas tema");
        Assert.Equal(TranslationHelper.Translation.GlassTile, "Glasflise");
        Assert.Equal(TranslationHelper.Translation.Gloom, "Gloom");
        Assert.Equal(TranslationHelper.Translation.GoBackBy100Images, "Gå 100 billeder tilbage");
        Assert.Equal(TranslationHelper.Translation.GoBackBy10Images, "Gå 10 billeder tilbage");
        Assert.Equal(TranslationHelper.Translation.GoToImageAtSpecifiedIndex,
            "Indlæs billede ved at indtaste numerisk placering");
        Assert.Equal(TranslationHelper.Translation.Hard, "Hård");
        Assert.Equal(TranslationHelper.Translation.Height, "Højde");
        Assert.Equal(TranslationHelper.Translation.HideBottomGallery, "Skjul nederste galleri");
        Assert.Equal(TranslationHelper.Translation.HideBottomToolbar, "Skjul bundværktøjslinje");
        Assert.Equal(TranslationHelper.Translation.HideUI, "Skjul brugergrænsefladen");
        Assert.Equal(TranslationHelper.Translation.High, "Høj");
        Assert.Equal(TranslationHelper.Translation.HighQuality, "Høj kvalitet");
        Assert.Equal(TranslationHelper.Translation.HighlightColor, "Accentfarve");
        Assert.Equal(TranslationHelper.Translation.ISOSpeed, "ISO hastighed");
        Assert.Equal(TranslationHelper.Translation.IconsUsed, "Brugte ikoner:");
        Assert.Equal(TranslationHelper.Translation.Image, "Billede");
        Assert.Equal(TranslationHelper.Translation.ImageAliasing, "Billedantialiasering");
        Assert.Equal(TranslationHelper.Translation.ImageControl, "Billedstyring");
        Assert.Equal(TranslationHelper.Translation.ImageInfo, "Billede Info");
        Assert.Equal(TranslationHelper.Translation.Inches, "tommer");
        Assert.Equal(TranslationHelper.Translation.InfoWindow, "Info vindue");
        Assert.Equal(TranslationHelper.Translation.InfoWindowTitle, "Information og genveje");
        Assert.Equal(TranslationHelper.Translation.InterfaceConfiguration, "Interfacekonfiguration");
        Assert.Equal(TranslationHelper.Translation.Landscape, "Landskab");
        Assert.Equal(TranslationHelper.Translation.Language, "Sprog");
        Assert.Equal(TranslationHelper.Translation.LastAccessTime, "Sidst tilgået");
        Assert.Equal(TranslationHelper.Translation.LastImage, "Sidste billede");
        Assert.Equal(TranslationHelper.Translation.LastWriteTime, "Sidst skrevet til");
        Assert.Equal(TranslationHelper.Translation.Latitude, "Breddegrad");
        Assert.Equal(TranslationHelper.Translation.Left, "Venstre");
        Assert.Equal(TranslationHelper.Translation.LensMaker, "Linse producent");
        Assert.Equal(TranslationHelper.Translation.LensModel, "Linse model");
        Assert.Equal(TranslationHelper.Translation.LightSource, "Lyskilde");
        Assert.Equal(TranslationHelper.Translation.LightTheme, "Lyst tema");
        Assert.Equal(TranslationHelper.Translation.Lighting, "Belysning");
        Assert.Equal(TranslationHelper.Translation.Loading, "Indlæser...");
        Assert.Equal(TranslationHelper.Translation.Longitude, "Længdegrad");
        Assert.Equal(TranslationHelper.Translation.Looping, "Loopning");
        Assert.Equal(TranslationHelper.Translation.LoopingDisabled, "Looping slået fra");
        Assert.Equal(TranslationHelper.Translation.LoopingEnabled, "Looping slået til");
        Assert.Equal(TranslationHelper.Translation.Lossless, "Ingen tab af kvalited");
        Assert.Equal(TranslationHelper.Translation.Lossy, "Delvis tab af kvalitet");
        Assert.Equal(TranslationHelper.Translation.Low, "Lav");
        Assert.Equal(TranslationHelper.Translation.Manual, "Manuel");
        Assert.Equal(TranslationHelper.Translation.MaxAperture, "Maks blænde");
        Assert.Equal(TranslationHelper.Translation.Maximize, "Maksimer");
        Assert.Equal(TranslationHelper.Translation.MegaPixels, "megapixels");
        Assert.Equal(TranslationHelper.Translation.Meter, "Meter");
        Assert.Equal(TranslationHelper.Translation.MeteringMode, "Målemetode");
        Assert.Equal(TranslationHelper.Translation.Minimize, "Minimer");
        Assert.Equal(TranslationHelper.Translation.MiscSettings, "Diverse indstillinger");
        Assert.Equal(TranslationHelper.Translation.Modified, "Modificeret");
        Assert.Equal(TranslationHelper.Translation.Monochrome, "Monokrom");
        Assert.Equal(TranslationHelper.Translation.MouseDrag, "Træk musen");
        Assert.Equal(TranslationHelper.Translation.MouseKeyBack, "Mouse knap tilbage");
        Assert.Equal(TranslationHelper.Translation.MouseKeyForward, "Museknap fremad");
        Assert.Equal(TranslationHelper.Translation.MouseWheel, "Musehjul");
        Assert.Equal(TranslationHelper.Translation.MoveWindow, "Flyt vinduet");
        Assert.Equal(TranslationHelper.Translation.Navigation, "Navigering");
        Assert.Equal(TranslationHelper.Translation.NearestNeighbor, "Nærmeste nabo");
        Assert.Equal(TranslationHelper.Translation.NegativeColors, "Negative Farver");
        Assert.Equal(TranslationHelper.Translation.NewWindow, "Nyt vindue");
        Assert.Equal(TranslationHelper.Translation.NextFolder, "Gå til næste mappe");
        Assert.Equal(TranslationHelper.Translation.NextImage, "Næste billede");
        Assert.Equal(TranslationHelper.Translation.NoChange, "Ingen ændring");
        Assert.Equal(TranslationHelper.Translation.NoConversion, "Ingen konvertering");
        Assert.Equal(TranslationHelper.Translation.NoImage, "Intet billede er indlæst");
        Assert.Equal(TranslationHelper.Translation.NoImages, "Ingen billeder");
        Assert.Equal(TranslationHelper.Translation.NoResize, "Ingen ændring");
        Assert.Equal(TranslationHelper.Translation.None, "Ingen");
        Assert.Equal(TranslationHelper.Translation.Normal, "Normal");
        Assert.Equal(TranslationHelper.Translation.NormalWindow, "Normalt vindue");
        Assert.Equal(TranslationHelper.Translation.NotDefined, "Ikke defineret");
        Assert.Equal(TranslationHelper.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationHelper.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationHelper.Translation.OldMovie, "Gammel film");
        Assert.Equal(TranslationHelper.Translation.Open, "Åben");
        Assert.Equal(TranslationHelper.Translation.OpenFileDialog, "Åben fil dialog");
        Assert.Equal(TranslationHelper.Translation.OpenInSameWindow, "Åbn filer i det samme vindue");
        Assert.Equal(TranslationHelper.Translation.OpenLastFile, "Åben seneste fil");
        Assert.Equal(TranslationHelper.Translation.OpenWith, "Åben med...");
        Assert.Equal(TranslationHelper.Translation.OptimizeImage, "Optimer billede");
        Assert.Equal(TranslationHelper.Translation.Orientation, "Orientering");
        Assert.Equal(TranslationHelper.Translation.OutputFolder, "Destination");
        Assert.Equal(TranslationHelper.Translation.Pan, "Panorering");
        Assert.Equal(TranslationHelper.Translation.PaperFold, "Papirfoldning");
        Assert.Equal(TranslationHelper.Translation.PasswordArchive, "Adgangskodebeskyttet arkiv understøttes ikke");
        Assert.Equal(TranslationHelper.Translation.PasteImageFromClipholder, "Indsæt billede fra udklipsholderen");
        Assert.Equal(TranslationHelper.Translation.PencilSketch, "Blyantskitse");
        Assert.Equal(TranslationHelper.Translation.PercentComplete, "% gennemført...");
        Assert.Equal(TranslationHelper.Translation.Percentage, "Procent");
        Assert.Equal(TranslationHelper.Translation.PermanentlyDelete, "Slet permanent");
        Assert.Equal(TranslationHelper.Translation.PhotometricInterpretation, "Fotometrisk fortolkning");
        Assert.Equal(TranslationHelper.Translation.Pivot, "Omdrejning");
        Assert.Equal(TranslationHelper.Translation.Pixelate, "Pixeler");
        Assert.Equal(TranslationHelper.Translation.Pixels, "pixels");
        Assert.Equal(TranslationHelper.Translation.Portrait, "Portræt");
        Assert.Equal(TranslationHelper.Translation.PressKey, "Tryk på tasten...");
        Assert.Equal(TranslationHelper.Translation.PrevFolder, "Gå til forrige mappe");
        Assert.Equal(TranslationHelper.Translation.PrevImage, "Forrige billede");
        Assert.Equal(TranslationHelper.Translation.Print, "Print");
        Assert.Equal(TranslationHelper.Translation.PrintSizeCm, "Print str. (cm)");
        Assert.Equal(TranslationHelper.Translation.PrintSizeIn, "Print str. (inch)");
        Assert.Equal(TranslationHelper.Translation.Quality, "Kvalitet");
        Assert.Equal(TranslationHelper.Translation.Random, "Vilkårlig");
        Assert.Equal(TranslationHelper.Translation.RecentFiles, "Seneste filer");
        Assert.Equal(TranslationHelper.Translation.RedEyeReduction, "Røde øjne reduktion");
        Assert.Equal(TranslationHelper.Translation.Reload, "Genindlæs");
        Assert.Equal(TranslationHelper.Translation.RemoveStarRating, "Fjern vurdering");
        Assert.Equal(TranslationHelper.Translation.RenameFile, "Omdøb fil");
        Assert.Equal(TranslationHelper.Translation.Reset, "Nulstil");
        Assert.Equal(TranslationHelper.Translation.ResetButtonText, "Nulstil til standard");
        Assert.Equal(TranslationHelper.Translation.ResetZoom, "Nulstil zoom");
        Assert.Equal(TranslationHelper.Translation.Resize, "Ændre størrelse");
        Assert.Equal(TranslationHelper.Translation.ResizeImage, "Ændre billedets størrelse");
        Assert.Equal(TranslationHelper.Translation.Resolution, "Opløsning");
        Assert.Equal(TranslationHelper.Translation.ResolutionUnit, "Opløsningsenhed");
        Assert.Equal(TranslationHelper.Translation.RestartApp, "Genstart programmet");
        Assert.Equal(TranslationHelper.Translation.RestoreDown, "Gendan");
        Assert.Equal(TranslationHelper.Translation.Reverse, "Baglæns");
        Assert.Equal(TranslationHelper.Translation.Right, "Højre");
        Assert.Equal(TranslationHelper.Translation.Ripple, "Bølge effekt");
        Assert.Equal(TranslationHelper.Translation.RippleAlt, "Bølge effekt Alt");
        Assert.Equal(TranslationHelper.Translation.RotateLeft, "Roter til venstre");
        Assert.Equal(TranslationHelper.Translation.RotateRight, "Roter til højre");
        Assert.Equal(TranslationHelper.Translation.Rotated, "Roteret");
        Assert.Equal(TranslationHelper.Translation.Saturation, "Farvemætning");
        Assert.Equal(TranslationHelper.Translation.Save, "Gem");
        Assert.Equal(TranslationHelper.Translation.SaveAs, "Gem som");
        Assert.Equal(TranslationHelper.Translation.SavingFileFailed, "Gemning af fil mislykkedes");
        Assert.Equal(TranslationHelper.Translation.ScrollAndRotate, "Scroll og roter");
        Assert.Equal(TranslationHelper.Translation.ScrollDirection, "Scroll retning");
        Assert.Equal(TranslationHelper.Translation.ScrollDown, "Scroll ned");
        Assert.Equal(TranslationHelper.Translation.ScrollToBottom, "Scroll til bunden");
        Assert.Equal(TranslationHelper.Translation.ScrollToTop, "Scroll til toppen");
        Assert.Equal(TranslationHelper.Translation.ScrollToZoom, "Zoom med musehjulet, naviger med Ctrl");
        Assert.Equal(TranslationHelper.Translation.ScrollUp, "Scroll op");
        Assert.Equal(TranslationHelper.Translation.Scrolling, "Scrolling");
        Assert.Equal(TranslationHelper.Translation.ScrollingDisabled, "Scrolling slået fra");
        Assert.Equal(TranslationHelper.Translation.ScrollingEnabled, "Scrolling slået til");
        Assert.Equal(TranslationHelper.Translation.SearchSubdirectory, "Tilføj undermapper til filsøgningen");
        Assert.Equal(TranslationHelper.Translation.SecAbbreviation, "Sek.");
        Assert.Equal(TranslationHelper.Translation.SelectAll, "Vælg alle");
        Assert.Equal(TranslationHelper.Translation.SelectGalleryThumb, "Vælg galleri billede");
        Assert.Equal(TranslationHelper.Translation.SendCurrentImageToRecycleBin, "Send billede til papirkurven");
        Assert.Equal(TranslationHelper.Translation.SentFileToRecycleBin, "Sendt fil til papirkurven");
        Assert.Equal(TranslationHelper.Translation.SetAs, "Sæt som...");
        Assert.Equal(TranslationHelper.Translation.SetAsLockScreenImage, "Sæt som låseskærmsbillede");
        Assert.Equal(TranslationHelper.Translation.SetAsWallpaper, "Sæt som baggrund");
        Assert.Equal(TranslationHelper.Translation.SetCurrentImageAsWallpaper,
            "Sæt nuværende billede som skrivebordsbaggrund:");
        Assert.Equal(TranslationHelper.Translation.SetStarRating, "Angiv stjernevurdering");
        Assert.Equal(TranslationHelper.Translation.Settings, "Indstillinger");
        Assert.Equal(TranslationHelper.Translation.Shade, "Skygge");
        Assert.Equal(TranslationHelper.Translation.Sharpness, "Skarphed");
        Assert.Equal(TranslationHelper.Translation.Shift, "Skift");
        Assert.Equal(TranslationHelper.Translation.ShowAllSettingsWindow, "Vis indstillingsvinduet");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGallery, "Vis nederste galleri");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Vis nederste galleri, når brugergrænsefladen er skjult");
        Assert.Equal(TranslationHelper.Translation.ShowBottomToolbar, "Vis værktøjslinjen i bunden");
        Assert.Equal(TranslationHelper.Translation.ShowConfirmationOnEsc, "Vis bekræftelsesdialog, når 'Esc' trykkes");
        Assert.Equal(TranslationHelper.Translation.ShowFadeInButtonsOnHover,
            "Vis skjulte knapper, når musen er i kanterne i programmet");
        Assert.Equal(TranslationHelper.Translation.ShowFileSavingDialog, "Vis gem fil dialogen");
        Assert.Equal(TranslationHelper.Translation.ShowImageGallery, "Vis billedgalleri");
        Assert.Equal(TranslationHelper.Translation.ShowImageInfo, "Vis billede Info");
        Assert.Equal(TranslationHelper.Translation.ShowInFolder, "Vis i mappe");
        Assert.Equal(TranslationHelper.Translation.ShowInfoWindow, "Åbn vindue for info og genveje");
        Assert.Equal(TranslationHelper.Translation.ShowResizeWindow, "Vis størrelsesændringsvinduet");
        Assert.Equal(TranslationHelper.Translation.ShowUI, "Vis brugergrænsefladen");
        Assert.Equal(TranslationHelper.Translation.ShutterPriority, "Lukker prioritet");
        Assert.Equal(TranslationHelper.Translation.SideBySide, "Side om side");
        Assert.Equal(TranslationHelper.Translation.SideBySideTooltip, "Vis billeder side om side");
        Assert.Equal(TranslationHelper.Translation.Size, "Størrelse");
        Assert.Equal(TranslationHelper.Translation.SizeMp, "Størrelse (mp)");
        Assert.Equal(TranslationHelper.Translation.SizeTooltip, "Indtast størrelse i pixels eller procent.");
        Assert.Equal(TranslationHelper.Translation.Sketch, "Skitse");
        Assert.Equal(TranslationHelper.Translation.Slideshow, "Slideshow");
        Assert.Equal(TranslationHelper.Translation.SmoothMagnify, "Glat forstørrelse");
        Assert.Equal(TranslationHelper.Translation.Soft, "Blød");
        Assert.Equal(TranslationHelper.Translation.Software, "Program");
        Assert.Equal(TranslationHelper.Translation.SortFilesBy, "Sorter efter");
        Assert.Equal(TranslationHelper.Translation.SourceFolder, "Kilde");
        Assert.Equal(TranslationHelper.Translation.Space, "Mellemrum");
        Assert.Equal(TranslationHelper.Translation.Square, "Firkant");
        Assert.Equal(TranslationHelper.Translation.Start, "Start");
        Assert.Equal(TranslationHelper.Translation.StartSlideshow, "Start slideshow");
        Assert.Equal(TranslationHelper.Translation.StayCentered, "Hold vinduet centreret");
        Assert.Equal(TranslationHelper.Translation.StayTopMost, "Hold vinduet øverst");
        Assert.Equal(TranslationHelper.Translation.Stretch, "Stræk");
        Assert.Equal(TranslationHelper.Translation.StretchImage, "Stræk billedet");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightDetected, "Strob returneringslys genkendt");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightNotDetected, "returneringslys ikke genkendt");
        Assert.Equal(TranslationHelper.Translation.Subject, "Emne");
        Assert.Equal(TranslationHelper.Translation.Swirl, "Virvel");
        Assert.Equal(TranslationHelper.Translation.TelescopicBlur, "Teleskopisk Sløring");
        Assert.Equal(TranslationHelper.Translation.Theme, "Tema");
        Assert.Equal(TranslationHelper.Translation.Thumbnail, "Thumb");
        Assert.Equal(TranslationHelper.Translation.Tile, "Flise");
        Assert.Equal(TranslationHelper.Translation.Title, "Titel");
        Assert.Equal(TranslationHelper.Translation.ToggleBackgroundColor, "Skift baggrundsfarve");
        Assert.Equal(TranslationHelper.Translation.ToggleFullscreen, "Skift fuldskærmstilstand");
        Assert.Equal(TranslationHelper.Translation.ToggleLooping, "Slå looping til/fra");
        Assert.Equal(TranslationHelper.Translation.ToggleScroll, "Slå scroll til/fra");
        Assert.Equal(TranslationHelper.Translation.ToggleTaskbarProgress, "Vis fremskridt i proceslinjen");
        Assert.Equal(TranslationHelper.Translation.ToneMapping, "ToneMapping");
        Assert.Equal(TranslationHelper.Translation.UnableToRender, "Kan ikke gengive billedet");
        Assert.Equal(TranslationHelper.Translation.Uncalibrated, "Ikke kalibreret");
        Assert.Equal(TranslationHelper.Translation.Underwater, "Undersøisk");
        Assert.Equal(TranslationHelper.Translation.UnexpectedError, "Der skete en ukendt fejl");
        Assert.Equal(TranslationHelper.Translation.Unflip, "Spejlvend tilbage");
        Assert.Equal(TranslationHelper.Translation.Uniform, "Ensartet");
        Assert.Equal(TranslationHelper.Translation.UniformToFill, "Ensartet til fyldt");
        Assert.Equal(TranslationHelper.Translation.Unknown, "Ukendt");
        Assert.Equal(TranslationHelper.Translation.UnsupportedFile, "Ikke understøttet filformat");
        Assert.Equal(TranslationHelper.Translation.Up, "Op");
        Assert.Equal(TranslationHelper.Translation.UsingMouse, "Bruger mus");
        Assert.Equal(TranslationHelper.Translation.UsingTouchpad, "Bruger pegefelt");
        Assert.Equal(TranslationHelper.Translation.Version, "Version:");
        Assert.Equal(TranslationHelper.Translation.ViewLicenseFile, "Se licensfilen");
        Assert.Equal(TranslationHelper.Translation.WaveWarper, "Bølger");
        Assert.Equal(TranslationHelper.Translation.WhiteBalance, "Hvidbalance");
        Assert.Equal(TranslationHelper.Translation.WhiteFluorescent, "Hvid fluorescerende");
        Assert.Equal(TranslationHelper.Translation.Width, "Bredde");
        Assert.Equal(TranslationHelper.Translation.WidthAndHeight, "Bredde og højde");
        Assert.Equal(TranslationHelper.Translation.WindowManagement, "vinduesstyring");
        Assert.Equal(TranslationHelper.Translation.WindowScaling, "Skalering af vindue");
        Assert.Equal(TranslationHelper.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationHelper.Translation.ZoomIn, "Zoom Ind");
        Assert.Equal(TranslationHelper.Translation.ZoomOut, "Zoom Ud");
        Assert.Equal(TranslationHelper.Translation._1Star, "1 stjerne");
        Assert.Equal(TranslationHelper.Translation._2Star, "2 stjerner");
        Assert.Equal(TranslationHelper.Translation._3Star, "3 stjerner");
        Assert.Equal(TranslationHelper.Translation._4Star, "4 stjerner");
        Assert.Equal(TranslationHelper.Translation._5Star, "5 stjerner");
    }
}