using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class DanishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckDanishLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("da");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "Om");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Action program");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Tilføjet til udklipsholderen");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Diverse funktioner");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed, "Juster hastigheden når tasten holdes nede");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Juster timing for slideshowet");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Justér zooming hastighed");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Juster zoom niveau");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Gå 100 billeder frem");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Gå 10 billeder frem");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Undgå at zoome billedet ud, når billedet allerede er i maksimal størrelse");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Højde");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Blænde prioritet");
        Assert.Equal(TranslationManager.Translation.Appearance, "Udseende");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Genveje til programmet");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Opstart af programmet");
        Assert.Equal(TranslationManager.Translation.Apply, "Anvend");
        Assert.Equal(TranslationManager.Translation.Applying, "Udfører");
        Assert.Equal(TranslationManager.Translation.Ascending, "Stigende");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Aspektforhold");
        Assert.Equal(TranslationManager.Translation.Authors, "Forfattere");
        Assert.Equal(TranslationManager.Translation.Auto, "Auto");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Auto tilpas vindue");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Arkivet kunne ikke behandles");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Base64 billede");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Batch størrelse");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Bit dybde");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Sort/hvid");
        Assert.Equal(TranslationManager.Translation.Blur, "Sløring");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Billedstørrelse i bundgalleriet");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Udstrækning af billeder i bundgalleriet");
        Assert.Equal(TranslationManager.Translation.Brightness, "Lysstyrke");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Kamera producent");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Kamera model");
        Assert.Equal(TranslationManager.Translation.Cancel, "Annuler");
        Assert.Equal(TranslationManager.Translation.Center, "Centrer");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Centrer vinduet");
        Assert.Equal(TranslationManager.Translation.Centimeters, "centimeter");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Skift baggrund");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Skift mellem baggrundsfarve til billeder med gennemsigtig baggrund");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Klik på en tekstboks for at ændre genvejen. Tryk på Esc for at frakoble den.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip, "Klik for at ændre genvejstast");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart, "* Skiftning af tema kræver genstart");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Søg efter opdateringer");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Billede fra udklipsholderen");
        Assert.Equal(TranslationManager.Translation.Close, "Luk");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Lukker hele programmet");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Luk galleri");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Vil du gerne lukke vinduet?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Overskyet vejr");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Farvevælgningsværktøj");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Vælg en farve fra billedet");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Farve repræsentation");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Farve Tone");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Komprimerede bits pr. pixel");
        Assert.Equal(TranslationManager.Translation.Compression, "Kompression");
        Assert.Equal(TranslationManager.Translation.ConstrainBackgroundToImage, "Begræns baggrundsfarve til billedet");
        Assert.Equal(TranslationManager.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Konverter til");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Konverteret til base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Kold hvid fluorescerende");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Kopier billede til udklipsholderen");
        Assert.Equal(TranslationManager.Translation.Copy, "Kopier");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Kopier fil");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Kopier billede");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Kopier som Windows-klippebordsbillede");
        Assert.Equal(TranslationManager.Translation.Copyright, "Ophavsret");
        Assert.Equal(TranslationManager.Translation.Created, "Opretted");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Oprettelses tid");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Kreativt program");
        Assert.Equal(TranslationManager.Translation.Credits, "Anerkendelser");
        Assert.Equal(TranslationManager.Translation.Crop, "Beskær");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Tryk Esc for at lukke, Enter for at gemme");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Beskær billede");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Zoom med Ctrl, naviger med musehjulet");
        Assert.Equal(TranslationManager.Translation.Cut, "Klip");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Mørkt tema");
        Assert.Equal(TranslationManager.Translation.Date, "Dato");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Dato fotograferet");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Dag hvid fluorescerende");
        Assert.Equal(TranslationManager.Translation.Daylight, "Dagslys");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Dagslys fluorescerende");
        Assert.Equal(TranslationManager.Translation.Del, "Del");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Slet fil");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "Er du sikker på, at du vil slette filen permanent");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Slettede filen");
        Assert.Equal(TranslationManager.Translation.Descending, "Faldende");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Digital zoom");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Skjul skjulte knapper, når musen er i kanterne i programmet");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Disk størrelse");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Dobbeltklik");
        Assert.Equal(TranslationManager.Translation.Down, "Ned");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Slip filen til stifinderen eller et andet program/browser");
        Assert.Equal(TranslationManager.Translation.DragImage, "Træk billede");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Slip for at indlæse");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Dupliker fil");
        Assert.Equal(TranslationManager.Translation.Effects, "Billedeffekter");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Vis billedeffektsvinduet");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Lukker nuværende åbne vindue el. menu");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Exif version");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Billedstørrelse i galleriet");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Eksponeringsbias");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Eksponeringsprogram");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Eksponeringstid");
        Assert.Equal(TranslationManager.Translation.FNumber, "F nummer");
        Assert.Equal(TranslationManager.Translation.File, "fil");
        Assert.Equal(TranslationManager.Translation.FileCopy, "Fil tilføjet til udklipsholderen");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Kopier fil sti");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Fil stien tilføjet til udklipsholderen");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "Fil tilføjet til flytte udklipsholderen");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Filtypenavn");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Behandling af filer");
        Assert.Equal(TranslationManager.Translation.FileName, "Fil navn");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Indsæt");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Filegenskaber");
        Assert.Equal(TranslationManager.Translation.FileSize, "Filstørrelse");
        Assert.Equal(TranslationManager.Translation.Files, "filer");
        Assert.Equal(TranslationManager.Translation.Fill, "Fyld");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Fyld højde");
        Assert.Equal(TranslationManager.Translation.FillSquare, "Fyldt firkant");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Godt vejr");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Første billede");
        Assert.Equal(TranslationManager.Translation.Fit, "Tilpas");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Tilpas til vinduet");
        Assert.Equal(TranslationManager.Translation.Flash, "Flash");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Flash ikke tændt");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Flash energi");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Flash tændt");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Flash tilstand");
        Assert.Equal(TranslationManager.Translation.Flip, "Spejlvend");
        Assert.Equal(TranslationManager.Translation.Flipped, "Spejlvendt");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Fluorescerende");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Brændvidde");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Brændvidde 35mm");
        Assert.Equal(TranslationManager.Translation.Folder, "Mappe");
        Assert.Equal(TranslationManager.Translation.Forward, "Fremad");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationManager.Translation.FullPath, "Filsti");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Fuldskærm");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Galleriindstillinger");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "Udstrækning af galleribilleder");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Generale Indstillinger");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Generer thumbnails");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Github side");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Glas tema");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Gå 100 billeder tilbage");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Gå 10 billeder tilbage");
        Assert.Equal(TranslationManager.Translation.Hard, "Hård");
        Assert.Equal(TranslationManager.Translation.Height, "Højde");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Skjul nederste galleri");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Skjul bundværktøjslinje");
        Assert.Equal(TranslationManager.Translation.HideUI, "Skjul brugergrænsefladen");
        Assert.Equal(TranslationManager.Translation.High, "Høj");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Høj kvalitet");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Accentfarve");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "ISO hastighed");
        Assert.Equal(TranslationManager.Translation.Image, "Billede");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Billedantialiasering");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Billedstyring");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Billede Info");
        Assert.Equal(TranslationManager.Translation.Inches, "tommer");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Info vindue");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Information og genveje");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Interfacekonfiguration");
        Assert.Equal(TranslationManager.Translation.Landscape, "Landskab");
        Assert.Equal(TranslationManager.Translation.Language, "Sprog");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Sidst tilgået");
        Assert.Equal(TranslationManager.Translation.LastImage, "Sidste billede");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Sidst skrevet til");
        Assert.Equal(TranslationManager.Translation.Latitude, "Breddegrad");
        Assert.Equal(TranslationManager.Translation.Left, "Venstre");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Linse producent");
        Assert.Equal(TranslationManager.Translation.LensModel, "Linse model");
        Assert.Equal(TranslationManager.Translation.LightSource, "Lyskilde");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Lyst tema");
        Assert.Equal(TranslationManager.Translation.Lighting, "Belysning");
        Assert.Equal(TranslationManager.Translation.Loading, "Indlæser...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Længdegrad");
        Assert.Equal(TranslationManager.Translation.Looping, "Loopning");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Looping slået fra");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Looping slået til");
        Assert.Equal(TranslationManager.Translation.Lossless, "Ingen tab af kvalited");
        Assert.Equal(TranslationManager.Translation.Lossy, "Delvis tab af kvalitet");
        Assert.Equal(TranslationManager.Translation.Low, "Lav");
        Assert.Equal(TranslationManager.Translation.Manual, "Manuel");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Maks blænde");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maksimer");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "megapixels");
        Assert.Equal(TranslationManager.Translation.Meter, "Meter");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Målemetode");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimer");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Diverse indstillinger");
        Assert.Equal(TranslationManager.Translation.Modified, "Modificeret");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Træk musen");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Mouse knap tilbage");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Museknap fremad");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Musehjul");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Flyt vinduet");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navigering");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Nærmeste nabo");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Negative Farver");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Nyt vindue");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Gå til næste mappe");
        Assert.Equal(TranslationManager.Translation.NextImage, "Næste billede");
        Assert.Equal(TranslationManager.Translation.NoChange, "Ingen ændring");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Ingen konvertering");
        Assert.Equal(TranslationManager.Translation.NoImage, "Intet billede er indlæst");
        Assert.Equal(TranslationManager.Translation.NoImages, "Ingen billeder");
        Assert.Equal(TranslationManager.Translation.NoResize, "Ingen ændring");
        Assert.Equal(TranslationManager.Translation.None, "Ingen");
        Assert.Equal(TranslationManager.Translation.Normal, "Normal");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Normalt vindue");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Ikke defineret");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Gammel film");
        Assert.Equal(TranslationManager.Translation.Open, "Åben");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Åben fil dialog");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Åbn filer i det samme vindue");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Åben seneste fil");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Åben med...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Optimer billede");
        Assert.Equal(TranslationManager.Translation.Orientation, "Orientering");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Destination");
        Assert.Equal(TranslationManager.Translation.Pan, "Panorering");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Adgangskodebeskyttet arkiv understøttes ikke");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Indsæt billede fra udklipsholderen");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Blyantskitse");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% gennemført...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Procent");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Slet permanent");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Fotometrisk fortolkning");
        Assert.Equal(TranslationManager.Translation.Pixels, "pixels");
        Assert.Equal(TranslationManager.Translation.Portrait, "Portræt");
        Assert.Equal(TranslationManager.Translation.PressKey, "Tryk på tasten...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Gå til forrige mappe");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Forrige billede");
        Assert.Equal(TranslationManager.Translation.Print, "Print");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Print str. (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Print str. (inch)");
        Assert.Equal(TranslationManager.Translation.Quality, "Kvalitet");
        Assert.Equal(TranslationManager.Translation.Random, "Vilkårlig");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Seneste filer");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Røde øjne reduktion");
        Assert.Equal(TranslationManager.Translation.Reload, "Genindlæs");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Fjern vurdering");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Omdøb fil");
        Assert.Equal(TranslationManager.Translation.Reset, "Nulstil");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Nulstil til standard");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Nulstil zoom");
        Assert.Equal(TranslationManager.Translation.Resize, "Ændre størrelse");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Ændre billedets størrelse");
        Assert.Equal(TranslationManager.Translation.Resolution, "Opløsning");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Opløsningsenhed");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Genstart programmet");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Gendan");
        Assert.Equal(TranslationManager.Translation.Reverse, "Baglæns");
        Assert.Equal(TranslationManager.Translation.Right, "Højre");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Roter til venstre");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Roter til højre");
        Assert.Equal(TranslationManager.Translation.Rotated, "Roteret");
        Assert.Equal(TranslationManager.Translation.Saturation, "Farvemætning");
        Assert.Equal(TranslationManager.Translation.Save, "Gem");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Gem som");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Gemning af fil mislykkedes");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Scroll og roter");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Scroll retning");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Scroll ned");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Scroll til bunden");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Scroll til toppen");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Zoom med musehjulet, naviger med Ctrl");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Scroll op");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Scrolling");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Scrolling slået fra");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Scrolling slået til");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Tilføj undermapper til filsøgningen");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sek.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Vælg alle");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Vælg galleri billede");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin, "Send billede til papirkurven");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Sendt fil til papirkurven");
        Assert.Equal(TranslationManager.Translation.SetAs, "Sæt som...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Sæt som låseskærmsbillede");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Sæt som baggrund");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Sæt nuværende billede som skrivebordsbaggrund:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Angiv stjernevurdering");
        Assert.Equal(TranslationManager.Translation.Settings, "Indstillinger");
        Assert.Equal(TranslationManager.Translation.Shade, "Skygge");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Skarphed");
        Assert.Equal(TranslationManager.Translation.Shift, "Skift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Vis indstillingsvinduet");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Vis nederste galleri");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Vis nederste galleri, når brugergrænsefladen er skjult");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Vis værktøjslinjen i bunden");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc, "Vis bekræftelsesdialog, når 'Esc' trykkes");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover,
            "Vis skjulte knapper, når musen er i kanterne i programmet");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Vis gem fil dialogen");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Vis billedgalleri");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Vis billede Info");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Vis i mappe");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Åbn vindue for info og genveje");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Vis størrelsesændringsvinduet");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Vis brugergrænsefladen");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Lukker prioritet");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Side om side");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Vis billeder side om side");
        Assert.Equal(TranslationManager.Translation.Size, "Størrelse");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Størrelse (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "Indtast størrelse i pixels eller procent.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Slideshow");
        Assert.Equal(TranslationManager.Translation.Soft, "Blød");
        Assert.Equal(TranslationManager.Translation.Software, "Program");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Sorter efter");
        Assert.Equal(TranslationManager.Translation.Space, "Mellemrum");
        Assert.Equal(TranslationManager.Translation.Square, "Firkant");
        Assert.Equal(TranslationManager.Translation.Start, "Start");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Start slideshow");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Hold vinduet centreret");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Hold vinduet øverst");
        Assert.Equal(TranslationManager.Translation.Stretch, "Stræk");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Stræk billedet");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Strob returneringslys genkendt");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected, "returneringslys ikke genkendt");
        Assert.Equal(TranslationManager.Translation.Subject, "Emne");
        Assert.Equal(TranslationManager.Translation.Theme, "Tema");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Thumb");
        Assert.Equal(TranslationManager.Translation.Tile, "Flise");
        Assert.Equal(TranslationManager.Translation.Title, "Titel");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Skift baggrundsfarve");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Skift fuldskærmstilstand");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Slå looping til/fra");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Slå scroll til/fra");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Vis fremskridt i proceslinjen");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Kan ikke gengive billedet");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Ikke kalibreret");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Der skete en ukendt fejl");
        Assert.Equal(TranslationManager.Translation.Unflip, "Spejlvend tilbage");
        Assert.Equal(TranslationManager.Translation.Uniform, "Ensartet");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "Ensartet til fyldt");
        Assert.Equal(TranslationManager.Translation.Unknown, "Ukendt");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Ikke understøttet filformat");
        Assert.Equal(TranslationManager.Translation.Up, "Op");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Bruger mus");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Bruger pegefelt");
        Assert.Equal(TranslationManager.Translation.Version, "Version:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Se licensfilen");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Hvidbalance");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Hvid fluorescerende");
        Assert.Equal(TranslationManager.Translation.Width, "Bredde");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Bredde og højde");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "vinduesstyring");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Skalering af vindue");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Zoom Ind");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Zoom Ud");
        Assert.Equal(TranslationManager.Translation._1Star, "1 stjerne");
        Assert.Equal(TranslationManager.Translation._2Star, "2 stjerner");
        Assert.Equal(TranslationManager.Translation._3Star, "3 stjerner");
        Assert.Equal(TranslationManager.Translation._4Star, "4 stjerner");
        Assert.Equal(TranslationManager.Translation._5Star, "5 stjerner");
    }
}