using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class DutchUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckDutchLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("nl");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "Over");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Actieprogramma");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Toegevoegd aan klembord");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Aanvullende functies");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed, "Snelheid aanpassen bij ingedrukte toets");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Tijd aanpassen voor diavoorstelling");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Zoomsnelheid aanpassen");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Zoomniveau aanpassen");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Vooruitgaan met 100 afbeeldingen");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Vooruitgaan met 10 afbeeldingen");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut, "Niet uitzoomen als het al op maximale grootte is");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Hoogte");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Diafragmaprioriteit");
        Assert.Equal(TranslationManager.Translation.Appearance, "Uiterlijk");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Toepassings sneltoetsen");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Toepassing opstarten");
        Assert.Equal(TranslationManager.Translation.Apply, "Pas toe");
        Assert.Equal(TranslationManager.Translation.Applying, "Toepassen");
        Assert.Equal(TranslationManager.Translation.Ascending, "Oplopend");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Beeldverhouding");
        Assert.Equal(TranslationManager.Translation.Authors, "Auteurs");
        Assert.Equal(TranslationManager.Translation.Auto, "Automatisch");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Automatisch venster aanpassen");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Archief kon niet worden verwerkt");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Base64 afbeelding");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Batch aanpassen");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Bitdiepte");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Zwart & Wit");
        Assert.Equal(TranslationManager.Translation.Blur, "Vervagen");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize,
            "Grootte van thumbnail in de onderste galerij");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Miniatuurrekken in de onderste galerij");
        Assert.Equal(TranslationManager.Translation.Brightness, "Helderheid");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Camerafabrikant");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Cameramodel");
        Assert.Equal(TranslationManager.Translation.Cancel, "Annuleren");
        Assert.Equal(TranslationManager.Translation.Center, "Midden");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Venster centreren");
        Assert.Equal(TranslationManager.Translation.Centimeters, "centimeters");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Achtergrond wijzigen");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Wissel tussen achtergrondkleur voor afbeeldingen met transparante achtergrond");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Klik op een tekstvak om de toetsbinding te wijzigen. Druk op Esc om de toetsbinding op te heffen.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip, "Klik om de toetsbinding te wijzigen");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart, "* Thema wijzigen vereist herstart");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Controleren op updates");
        Assert.Equal(TranslationManager.Translation.ClearEffects, "Effecten wissen");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Klembord afbeelding");
        Assert.Equal(TranslationManager.Translation.Close, "Sluiten");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Sluit de hele toepassing");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Galerij sluiten");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Wilt u het venster sluiten?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Bewolkt weer");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Kleurkiezer");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Kleur kiezen uit afbeelding");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Kleurenrepresentatie");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Kleurtoon");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Gecomprimeerde bits per pixel");
        Assert.Equal(TranslationManager.Translation.Compression, "Compressie");
        Assert.Equal(TranslationManager.Translation.ConstrainBackgroundToImage, "Beperk achtergrondkleur tot afbeelding");
        Assert.Equal(TranslationManager.Translation.Contrast, "Contrast");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Converteren naar");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Geconverteerd naar base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Koel wit fluoriserend");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Afbeelding gekopieerd naar klembord");
        Assert.Equal(TranslationManager.Translation.Copy, "Kopiëren");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Bestand kopiëren");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Afbeelding kopiëren");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Kopiëren als Windows klembord afbeelding");
        Assert.Equal(TranslationManager.Translation.Copyright, "Copyright");
        Assert.Equal(TranslationManager.Translation.Created, "Gemaakt");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Aanmaak tijd");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Creatief programma");
        Assert.Equal(TranslationManager.Translation.Credits, "Credits");
        Assert.Equal(TranslationManager.Translation.Crop, "Bijsnijden");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Druk op Esc om te sluiten, Enter om op te slaan");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Afbeelding bijsnijden");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Ctrl om in te zoomen, scrollen om te navigeren");
        Assert.Equal(TranslationManager.Translation.Cut, "Knippen");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Donker thema");
        Assert.Equal(TranslationManager.Translation.Date, "Datum");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Datum gemaakt");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Dag wit fluorescent");
        Assert.Equal(TranslationManager.Translation.Daylight, "Daglicht");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Daglicht fluorescent");
        Assert.Equal(TranslationManager.Translation.Del, "Del");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Bestand verwijderen");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "Weet u zeker dat u permanent wilt verwijderen");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Bestand verwijderd");
        Assert.Equal(TranslationManager.Translation.Descending, "Aflopend");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Digitale zoom");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Fade-in knoppen uitschakelen bij muis hover");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Schijfgrootte");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Dubbelklik");
        Assert.Equal(TranslationManager.Translation.Down, "Omlaag");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo, "Bestand verslepen naar andere applicatie/browser");
        Assert.Equal(TranslationManager.Translation.DragImage, "Afbeelding slepen");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Laten vallen om afbeelding te laden");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Bestand dupliceren");
        Assert.Equal(TranslationManager.Translation.Effects, "Effecten");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Effectenvenster weergeven");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Sluit momenteel geopend venster/menu");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Exif versie");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Grootte van thumbnail");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Belichtingscompensatie");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Belichtingsprogramma");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Belichtingstijd");
        Assert.Equal(TranslationManager.Translation.FNumber, "F-getal");
        Assert.Equal(TranslationManager.Translation.File, "bestand");
        Assert.Equal(TranslationManager.Translation.FileCopy, "Bestand toegevoegd aan klembord");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Bestandspad kopiëren");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Bestandspad toegevoegd aan klembord");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "Bestand toegevoegd aan verplaats klembord");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Bestandsextensie");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Bestandsbeheer");
        Assert.Equal(TranslationManager.Translation.FileName, "Bestandsnaam");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Plakken");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Bestandseigenschappen");
        Assert.Equal(TranslationManager.Translation.FileSize, "Bestandsgrootte");
        Assert.Equal(TranslationManager.Translation.Files, "bestanden");
        Assert.Equal(TranslationManager.Translation.Fill, "Vullen");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Hoogte vullen");
        Assert.Equal(TranslationManager.Translation.FillSquare, "Vierkant vullen");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Mooi weer");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Eerste afbeelding");
        Assert.Equal(TranslationManager.Translation.Fit, "Passend");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Passend maken aan venster/afbeelding");
        Assert.Equal(TranslationManager.Translation.Flash, "Flitser");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Flitser ging niet af");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Flitser energie");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Flitser ging af");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Flitsmodus");
        Assert.Equal(TranslationManager.Translation.Flip, "Horizontaal draaien");
        Assert.Equal(TranslationManager.Translation.Flipped, "Horizontaal gedraaid");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Fluoriserend");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Brandpuntsafstand");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Brandpuntsafstand 35mm");
        Assert.Equal(TranslationManager.Translation.Folder, "Map");
        Assert.Equal(TranslationManager.Translation.Forward, "Vooruit");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-getal");
        Assert.Equal(TranslationManager.Translation.FullPath, "Volledig pad");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Volledig scherm");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Galerij instellingen");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "Miniatuurrekken in galerij");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Algemene instellingen");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Thumbnail genereren");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Github repository");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Glas thema");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Ga terug met 100 afbeeldingen");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Ga terug met 10 afbeeldingen");
        Assert.Equal(TranslationManager.Translation.Hard, "Hard");
        Assert.Equal(TranslationManager.Translation.Height, "Hoogte");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Verberg onderste galerij");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Verberg onderste werkbalk");
        Assert.Equal(TranslationManager.Translation.HideUI, "Verberg interface");
        Assert.Equal(TranslationManager.Translation.High, "Hoog");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Hoge kwaliteit");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Markeerkleur");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "ISO snelheid");
        Assert.Equal(TranslationManager.Translation.Image, "Afbeelding");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Beeldaliasing");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Afbeeldingscontrole");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Afbeeldingsinformatie");
        Assert.Equal(TranslationManager.Translation.Inches, "inches");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Informatievenster");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Informatie en sneltoetsen");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Interface configuratie");
        Assert.Equal(TranslationManager.Translation.Landscape, "Landschap");
        Assert.Equal(TranslationManager.Translation.Language, "Taal");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Laatste toegangstijd");
        Assert.Equal(TranslationManager.Translation.LastImage, "Laatste afbeelding");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Laatste schrijftijd");
        Assert.Equal(TranslationManager.Translation.Latitude, "Breedtegraad");
        Assert.Equal(TranslationManager.Translation.Left, "Links");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Lensfabrikant");
        Assert.Equal(TranslationManager.Translation.LensModel, "Lensmodel");
        Assert.Equal(TranslationManager.Translation.LightSource, "Lichtbron");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Licht thema");
        Assert.Equal(TranslationManager.Translation.Lighting, "Verlichting");
        Assert.Equal(TranslationManager.Translation.Loading, "Laden...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Lengtegraad");
        Assert.Equal(TranslationManager.Translation.Looping, "Looping");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Looping uitgeschakeld");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Looping ingeschakeld");
        Assert.Equal(TranslationManager.Translation.Lossless, "Verliesvrij");
        Assert.Equal(TranslationManager.Translation.Lossy, "Verliesrijk");
        Assert.Equal(TranslationManager.Translation.Low, "Laag");
        Assert.Equal(TranslationManager.Translation.Manual, "Handmatig");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Maximale diafragma");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maximaliseren");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "megapixels");
        Assert.Equal(TranslationManager.Translation.Meter, "Meter");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Meetmodus");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimaliseren");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Diverse instellingen");
        Assert.Equal(TranslationManager.Translation.Modified, "Aangepast");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Muis slepen");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Muistoets terug");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Muistoets vooruit");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Muiswiel");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Venster verplaatsen");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navigatie");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Dichtstbijzijnde buur");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Negatieve kleuren");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Nieuw venster");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Navigeer naar volgende map");
        Assert.Equal(TranslationManager.Translation.NextImage, "Volgende afbeelding");
        Assert.Equal(TranslationManager.Translation.NoChange, "Geen wijzigingen");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Geen conversie");
        Assert.Equal(TranslationManager.Translation.NoImage, "Geen afbeelding");
        Assert.Equal(TranslationManager.Translation.NoImages, "Geen afbeeldingen");
        Assert.Equal(TranslationManager.Translation.NoResize, "Niet aanpassen");
        Assert.Equal(TranslationManager.Translation.None, "Geen");
        Assert.Equal(TranslationManager.Translation.Normal, "Normaal");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Normaal venster");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Niet gedefinieerd");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Oude film");
        Assert.Equal(TranslationManager.Translation.Open, "Openen");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Selecteer een bestand");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Bestanden openen in hetzelfde venster");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Laatste bestand openen");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Openen met...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Afbeelding optimaliseren");
        Assert.Equal(TranslationManager.Translation.Orientation, "Oriëntatie");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Uitvoermap");
        Assert.Equal(TranslationManager.Translation.Pan, "Pannen");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Wachtwoord beveiligd archief niet ondersteund");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Afbeelding plakken vanuit klembord");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Potloodschets");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% voltooid...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Percentage");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Permanent verwijderen");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Fotometrische interpretatie");
        Assert.Equal(TranslationManager.Translation.Pixels, "pixels");
        Assert.Equal(TranslationManager.Translation.Portrait, "Portret");
        Assert.Equal(TranslationManager.Translation.Posterize, "Posteriseren");
        Assert.Equal(TranslationManager.Translation.PressKey, "Druk op toets...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Navigeer naar vorige map");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Vorige afbeelding");
        Assert.Equal(TranslationManager.Translation.Print, "Afdrukken");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Printgrootte (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Printgrootte (in)");
        Assert.Equal(TranslationManager.Translation.Quality, "Kwaliteit");
        Assert.Equal(TranslationManager.Translation.Random, "Willekeurig");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Recente bestanden");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Rode ogen reductie");
        Assert.Equal(TranslationManager.Translation.Reload, "Herladen");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Beoordeling verwijderen");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Bestand hernoemen");
        Assert.Equal(TranslationManager.Translation.Reset, "Resetten");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Reset naar standaard");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Zoom resetten");
        Assert.Equal(TranslationManager.Translation.Resize, "Aanpassen");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Afbeelding aanpassen");
        Assert.Equal(TranslationManager.Translation.Resolution, "Resolutie");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Resolutie-eenheid");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Herstart de toepassing");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Herstellen");
        Assert.Equal(TranslationManager.Translation.Reverse, "Omkeren");
        Assert.Equal(TranslationManager.Translation.Right, "Rechts");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Links draaien");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Rechts draaien");
        Assert.Equal(TranslationManager.Translation.Rotated, "Gedraaid");
        Assert.Equal(TranslationManager.Translation.Saturation, "Verzadiging");
        Assert.Equal(TranslationManager.Translation.Save, "Opslaan");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Opslaan als");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Bestand opslaan mislukt");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Scrollen en draaien");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Scrollrichting");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Scroll omlaag");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Scroll naar onderkant");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Scroll naar bovenkant");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Zoom met muiswiel, navigeer met Ctrl");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Scroll omhoog");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Scrollen");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Scrollen uitgeschakeld");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Scrollen ingeschakeld");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Zoek in subdirectories");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sec.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Alles selecteren");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Selecteer galerij miniatuur");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin,
            "Stuur huidige afbeelding naar prullenbak");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Bestand naar prullenbak gestuurd");
        Assert.Equal(TranslationManager.Translation.SetAs, "Instellen als...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage,
            "Instellen als vergrendelingsscherm afbeelding");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Instellen als achtergrond");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Huidige afbeelding instellen als achtergrond:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Sterbeoordeling instellen");
        Assert.Equal(TranslationManager.Translation.Settings, "Instellingen");
        Assert.Equal(TranslationManager.Translation.Shade, "Schaduw");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Scherpte");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Toon alle instellingen venster");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Toon onderste galerij");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Toon onderste galerij als UI verborgen is");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Toon onderste werkbalk");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "Toon bevestigingsdialoog bij het indrukken van 'Esc'");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover, "Toon fade-in knoppen bij muis hover");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Toon dialoogvenster voor bestand opslaan");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Toon afbeeldingsgalerij");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Toon afbeeldingsinformatie");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Weergeven in map");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Toon informatievenster");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Toon aanpasvenster");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Toon UI");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Sluiter prioriteit");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Zij aan zij");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Toon afbeeldingen zij aan zij");
        Assert.Equal(TranslationManager.Translation.Size, "Grootte");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Grootte (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "Voer gewenste grootte in pixels of percentage in.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Diavoorstelling");
        Assert.Equal(TranslationManager.Translation.Soft, "Zacht");
        Assert.Equal(TranslationManager.Translation.Software, "Software");
        Assert.Equal(TranslationManager.Translation.Solarize, "Solariseren");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Bestanden sorteren op");
        Assert.Equal(TranslationManager.Translation.Space, "Spatie");
        Assert.Equal(TranslationManager.Translation.Square, "Vierkant");
        Assert.Equal(TranslationManager.Translation.Start, "Start");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Start diavoorstelling");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Blijf gecentreerd");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Blijf boven andere vensters");
        Assert.Equal(TranslationManager.Translation.Stretch, "Rekken");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Afbeelding rekken");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Strobe teruggekeerd licht gedetecteerd");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected,
            "Strobe teruggekeerd licht niet gedetecteerd");
        Assert.Equal(TranslationManager.Translation.Subject, "Onderwerp");
        Assert.Equal(TranslationManager.Translation.Theme, "Thema");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Miniatuur");
        Assert.Equal(TranslationManager.Translation.Tile, "Tegel");
        Assert.Equal(TranslationManager.Translation.Title, "Titel");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Achtergrondkleur wisselen");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Volledig scherm wisselen");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Lussen wisselen");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Scroll wisselen");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Toon taakbalk voortgang");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Kan afbeelding niet weergeven");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Niet gekalibreerd");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Een onbekende fout is opgetreden");
        Assert.Equal(TranslationManager.Translation.Unflip, "Terugdraaien");
        Assert.Equal(TranslationManager.Translation.Uniform, "Uniform");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "Uniform vullen");
        Assert.Equal(TranslationManager.Translation.Unknown, "Onbekend");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Niet ondersteund bestand");
        Assert.Equal(TranslationManager.Translation.Up, "Omhoog");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Muis gebruiken");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Touchpad gebruiken");
        Assert.Equal(TranslationManager.Translation.Version, "Versie:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Toon licentiebestand");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Witbalans");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Wit fluoriserend");
        Assert.Equal(TranslationManager.Translation.Width, "Breedte");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Breedte en hoogte");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Vensterbeheer");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Venster scalen");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Inzoomen");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Uitzoomen");
        Assert.Equal(TranslationManager.Translation._1Star, "1 ster");
        Assert.Equal(TranslationManager.Translation._2Star, "2 sterren");
        Assert.Equal(TranslationManager.Translation._3Star, "3 sterren");
        Assert.Equal(TranslationManager.Translation._4Star, "4 sterren");
        Assert.Equal(TranslationManager.Translation._5Star, "5 sterren");
    }
}