using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;
public static class EnglishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckEnglishLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("en");
        Assert.True(exists);
        Assert.Equal(TranslationManager.Translation.About, "About");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Action program");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Added to clipboard");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Additional functions");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed, "Adjust speed when key is held down");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Adjust timing for slideshow");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Adjust zooming speed");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Adjust zoom level");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Advance by 100 Images");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Advance by 10 Images");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Avoid zooming out when it is already at maximum size");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Altitude");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Aperture priority");
        Assert.Equal(TranslationManager.Translation.Appearance, "Appearance");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Application Shortcuts");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Application startup");
        Assert.Equal(TranslationManager.Translation.Apply, "Apply");
        Assert.Equal(TranslationManager.Translation.Applying, "Applying");
        Assert.Equal(TranslationManager.Translation.Ascending, "Ascending");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Aspect ratio");
        Assert.Equal(TranslationManager.Translation.Authors, "Authors");
        Assert.Equal(TranslationManager.Translation.Auto, "Auto");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Auto fit window");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Archive could not be processed");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Base64 image");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Batch Resize");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Bit depth");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Black & White");
        Assert.Equal(TranslationManager.Translation.Blur, "Blur");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Size of thumbnails in the bottom gallery");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Thumbnail stretch in the bottom gallery");
        Assert.Equal(TranslationManager.Translation.Brightness, "Brightness");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Camera maker");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Camera model");
        Assert.Equal(TranslationManager.Translation.Cancel, "Cancel");
        Assert.Equal(TranslationManager.Translation.Center, "Center");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Center window");
        Assert.Equal(TranslationManager.Translation.Centimeters, "centimeters");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Change background");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Change between background color for images with transparent background");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Click on a textbox to change keybinding. Pressing Esc unbinds key.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip, "Click to change keybinding");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart, "* Changing theme requires restart");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Check for updates");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Clipboard image");
        Assert.Equal(TranslationManager.Translation.Close, "Close");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Close the whole application");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Close gallery");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Do you wish to close the window?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Cloudy weather");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Color Picker Tool");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Pick color from image");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Color representation");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Color Tone");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Compressed bits per pixel");
        Assert.Equal(TranslationManager.Translation.Compression, "Compression");
        Assert.Equal(TranslationManager.Translation.Contrast, "Contrast");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Convert to");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Converted to base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Cool white fluorescent");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Copied image to clipboard");
        Assert.Equal(TranslationManager.Translation.Copy, "Copy");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Copy file");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Copy image");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Copy as Windows clipboard image");
        Assert.Equal(TranslationManager.Translation.Copyright, "Copyright");
        Assert.Equal(TranslationManager.Translation.Created, "Created");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Creation time");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Creative program");
        Assert.Equal(TranslationManager.Translation.Credits, "Credits");
        Assert.Equal(TranslationManager.Translation.Crop, "Crop");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Press Esc to close, Enter to save");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Crop Picture");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Ctrl to zoom, scroll to navigate");
        Assert.Equal(TranslationManager.Translation.Cut, "Cut");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Dark theme");
        Assert.Equal(TranslationManager.Translation.Date, "Date");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Date taken");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Day white fluorescent");
        Assert.Equal(TranslationManager.Translation.Daylight, "Daylight");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Daylight fluorescent");
        Assert.Equal(TranslationManager.Translation.Del, "Del");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Delete file");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "Are you sure you want to permanently delete");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Deleted file");
        Assert.Equal(TranslationManager.Translation.Descending, "Descending");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Digital zoom");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Disable fade-in buttons on mouse hover");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Disk size");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Double Click");
        Assert.Equal(TranslationManager.Translation.Down, "Down");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Drag file to Windows Explorer or another application/browser");
        Assert.Equal(TranslationManager.Translation.DragImage, "Drag image");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Drop to load image");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Duplicate file");
        Assert.Equal(TranslationManager.Translation.Effects, "Effects");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Show image effects window");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Closes currently opened window/menu");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Exif version");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Size of thumbnails");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Exposure bias");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Exposure program");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Exposure time");
        Assert.Equal(TranslationManager.Translation.FNumber, "F number");
        Assert.Equal(TranslationManager.Translation.File, "file");
        Assert.Equal(TranslationManager.Translation.FileCopy, "File added to clipboard");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Copy file path");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "File path added to clipboard");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "File added to move clipboard");
        Assert.Equal(TranslationManager.Translation.FileExtension, "File extension");
        Assert.Equal(TranslationManager.Translation.FileManagement, "File management");
        Assert.Equal(TranslationManager.Translation.FileName, "File name");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Paste");
        Assert.Equal(TranslationManager.Translation.FileProperties, "File properties");
        Assert.Equal(TranslationManager.Translation.FileSize, "File size");
        Assert.Equal(TranslationManager.Translation.Files, "files");
        Assert.Equal(TranslationManager.Translation.Fill, "Fill");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Fill height");
        Assert.Equal(TranslationManager.Translation.FillSquare, "Fill square");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Fine weather");
        Assert.Equal(TranslationManager.Translation.FirstImage, "First image");
        Assert.Equal(TranslationManager.Translation.Fit, "Fit");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Fit to window/image");
        Assert.Equal(TranslationManager.Translation.Flash, "Flash");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Flash did not fire");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Flash energy");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Flash fired");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Flash mode");
        Assert.Equal(TranslationManager.Translation.Flip, "Flip horizontally");
        Assert.Equal(TranslationManager.Translation.Flipped, "Flipped horizontally");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Fluorescent");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Focal length");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Focal length 35mm");
        Assert.Equal(TranslationManager.Translation.Folder, "Folder");
        Assert.Equal(TranslationManager.Translation.Forward, "Forward");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationManager.Translation.FullPath, "Full path");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Fullscreen");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Gallery settings");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "Gallery thumbnail stretch");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "General Settings");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Generate thumbnails");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Github repository");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Glass Theme");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Go Back by 100 Images");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Go Back by 10 Images");
        Assert.Equal(TranslationManager.Translation.Hard, "Hard");
        Assert.Equal(TranslationManager.Translation.Height, "Height");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Hide bottom gallery");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Hide Bottom Toolbar");
        Assert.Equal(TranslationManager.Translation.HideUI, "Hide interface");
        Assert.Equal(TranslationManager.Translation.High, "High");
        Assert.Equal(TranslationManager.Translation.HighQuality, "High quality");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Highlight color");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "ISO speed");
        Assert.Equal(TranslationManager.Translation.Image, "Image");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Image aliasing");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Image control");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Image Info");
        Assert.Equal(TranslationManager.Translation.Inches, "inches");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Info window");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Info and shortcuts");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Interface configuration");
        Assert.Equal(TranslationManager.Translation.Landscape, "Landscape");
        Assert.Equal(TranslationManager.Translation.Language, "Language");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Last access time");
        Assert.Equal(TranslationManager.Translation.LastImage, "Last image");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Last write time");
        Assert.Equal(TranslationManager.Translation.Latitude, "Latitude");
        Assert.Equal(TranslationManager.Translation.Left, "Left");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Lens maker");
        Assert.Equal(TranslationManager.Translation.LensModel, "Lens model");
        Assert.Equal(TranslationManager.Translation.LightSource, "Light source");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Light theme");
        Assert.Equal(TranslationManager.Translation.Lighting, "Lighting");
        Assert.Equal(TranslationManager.Translation.Loading, "Loading...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Longitude");
        Assert.Equal(TranslationManager.Translation.Looping, "Looping");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Looping disabled");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Looping enabled");
        Assert.Equal(TranslationManager.Translation.Lossless, "Lossless");
        Assert.Equal(TranslationManager.Translation.Lossy, "Lossy");
        Assert.Equal(TranslationManager.Translation.Low, "Low");
        Assert.Equal(TranslationManager.Translation.Manual, "Manual");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Max aperture");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maximize");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "megapixels");
        Assert.Equal(TranslationManager.Translation.Meter, "Meter");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Metering mode");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimize");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Misc settings");
        Assert.Equal(TranslationManager.Translation.Modified, "Modified");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Mouse drag");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Mouse key back");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Mouse key forward");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Mouse wheel");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Move window");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navigation");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Nearest neighbor");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Negative Colors");
        Assert.Equal(TranslationManager.Translation.NewWindow, "New window");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Navigate to next folder");
        Assert.Equal(TranslationManager.Translation.NextImage, "Next image");
        Assert.Equal(TranslationManager.Translation.NoChange, "No changes");
        Assert.Equal(TranslationManager.Translation.NoConversion, "No conversion");
        Assert.Equal(TranslationManager.Translation.NoImage, "No image loaded");
        Assert.Equal(TranslationManager.Translation.NoImages, "No Images");
        Assert.Equal(TranslationManager.Translation.NoResize, "No resize");
        Assert.Equal(TranslationManager.Translation.None, "None");
        Assert.Equal(TranslationManager.Translation.Normal, "Normal");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Normal window");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Not defined");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Old Movie");
        Assert.Equal(TranslationManager.Translation.Open, "Open");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Select a file");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Open files in the same window");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Open last file");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Open with...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Optimize Image");
        Assert.Equal(TranslationManager.Translation.Orientation, "Orientation");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Output folder");
        Assert.Equal(TranslationManager.Translation.Pan, "Pan");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Password protected archive not supported");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Paste image from clip-holder");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Pencil Sketch");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% complete...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Percentage");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Permanently delete");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Photometric interpretation");
        Assert.Equal(TranslationManager.Translation.Pixels, "pixels");
        Assert.Equal(TranslationManager.Translation.Portrait, "Portrait");
        Assert.Equal(TranslationManager.Translation.PressKey, "Press key...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Navigate to previous folder");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Previous image");
        Assert.Equal(TranslationManager.Translation.Print, "Print");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Print size (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Print size (in)");
        Assert.Equal(TranslationManager.Translation.Quality, "Quality");
        Assert.Equal(TranslationManager.Translation.Random, "Random");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Recent files");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Red eye reduction");
        Assert.Equal(TranslationManager.Translation.Reload, "Reload");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Remove rating");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Rename file");
        Assert.Equal(TranslationManager.Translation.Reset, "Reset");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Reset to default");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Reset zoom");
        Assert.Equal(TranslationManager.Translation.Resize, "Resize");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Resize Image");
        Assert.Equal(TranslationManager.Translation.Resolution, "Resolution");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Resolution unit");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Restart the application");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Restore Down");
        Assert.Equal(TranslationManager.Translation.Reverse, "Reverse");
        Assert.Equal(TranslationManager.Translation.Right, "Right");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Rotate left");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Rotate right");
        Assert.Equal(TranslationManager.Translation.Rotated, "Rotated");
        Assert.Equal(TranslationManager.Translation.Saturation, "Saturation");
        Assert.Equal(TranslationManager.Translation.Save, "Save");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Save as");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Saving file failed");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Scroll and rotate");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Scroll direction");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Scroll down");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Scroll to bottom");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Scroll to top");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Zoom with mousewheel, navigate with Ctrl");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Scroll up");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Scrolling");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Scrolling disabled");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Scrolling enabled");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Search subdirectories");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sec.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Select All");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Select gallery thumbnail");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin,
            "Send current image to the recycle bin");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Sent file to the recycle bin");
        Assert.Equal(TranslationManager.Translation.SetAs, "Set as...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Set as lock screen image");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Set as wallpaper");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper, "Set current image as wallpaper:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Set star rating");
        Assert.Equal(TranslationManager.Translation.Settings, "Settings");
        Assert.Equal(TranslationManager.Translation.Shade, "Shade");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Sharpness");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Show all settings window");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Show bottom gallery");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Show bottom gallery when UI is hidden");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Show bottom toolbar");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "Show confirmation dialog when pressing 'Esc'");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover, "Show fade-in buttons on mouse hover");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Show file saving dialog");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Show image gallery");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Show Image Info");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Show in folder");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Show info window");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Show the Resize Window");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Show UI");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Shutter priority");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Side by side");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Show images side by side");
        Assert.Equal(TranslationManager.Translation.Size, "Size");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Size (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "Enter desired size in pixels or percentage.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Slideshow");
        Assert.Equal(TranslationManager.Translation.Soft, "Soft");
        Assert.Equal(TranslationManager.Translation.Software, "Software");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Sort files by");
        Assert.Equal(TranslationManager.Translation.Space, "Space");
        Assert.Equal(TranslationManager.Translation.Square, "Square");
        Assert.Equal(TranslationManager.Translation.Start, "Start");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Start slideshow");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Keep window centered");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Stay on top of other windows");
        Assert.Equal(TranslationManager.Translation.Stretch, "Stretch");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Stretch image");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Strobe return light detected");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected, "Strobe return light not detected");
        Assert.Equal(TranslationManager.Translation.Subject, "Subject");
        Assert.Equal(TranslationManager.Translation.Theme, "Theme");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Thumb");
        Assert.Equal(TranslationManager.Translation.Tile, "Tile");
        Assert.Equal(TranslationManager.Translation.Title, "Title");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Toggle background color");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Toggle fullscreen");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Toggle looping");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Toggle scroll");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Display taskbar progress");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Unable to render image");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Uncalibrated");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "An unknown error occured");
        Assert.Equal(TranslationManager.Translation.Unflip, "Unflip");
        Assert.Equal(TranslationManager.Translation.Uniform, "Uniform");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "Uniform to fill");
        Assert.Equal(TranslationManager.Translation.Unknown, "Unknown");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Unsupported file");
        Assert.Equal(TranslationManager.Translation.Up, "Up");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Using mouse");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Using touchpad");
        Assert.Equal(TranslationManager.Translation.Version, "Version:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "View license file");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "White balance");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "White fluorescent");
        Assert.Equal(TranslationManager.Translation.Width, "Width");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Width and height");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Window management");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Window scaling");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Zoom in");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Zoom out");
        Assert.Equal(TranslationManager.Translation._1Star, "1 star rating");
        Assert.Equal(TranslationManager.Translation._2Star, "2 star rating");
        Assert.Equal(TranslationManager.Translation._3Star, "3 star rating");
        Assert.Equal(TranslationManager.Translation._4Star, "4 star rating");
        Assert.Equal(TranslationManager.Translation._5Star, "5 star rating");
    }
#pragma warning restore xUnit2000
}
