using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class FrenchUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckFrenchLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("fr");
        Assert.True(exists);
        Assert.Equal(TranslationManager.Translation.About, "À propos");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Programme d'action");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Ajouter au presse-papier");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Fonctions supplémentaires");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed,
            "Ajuster la vitesse lorsque la touche est maintenue enfoncée");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Ajuster le durée pour le diaporama");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Ajuster la vitesse du zoom");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Ajuster le niveau de zoom");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Avancer de 100 images");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Avancer de 10 images");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Évitez de zoomer sur l'image lorsqu'elle est déjà à sa taille maximale");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Altitude");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Priorité à l'ouverture");
        Assert.Equal(TranslationManager.Translation.Appearance, "Apparence");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Raccourcis d'application");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Démarrage de l'application");
        Assert.Equal(TranslationManager.Translation.Apply, "Appliquer");
        Assert.Equal(TranslationManager.Translation.Applying, "Application en cours");
        Assert.Equal(TranslationManager.Translation.Ascending, "Ascendant");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Ratio de l'image");
        Assert.Equal(TranslationManager.Translation.Authors, "Auteurs");
        Assert.Equal(TranslationManager.Translation.Auto, "Auto");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Ajustement automatique de la fenêtre");
        Assert.Equal(TranslationManager.Translation.BadArchive, "L'archive n'a pas pu être traitée");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Image Base64");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Redimensionner par lot");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Profondeur");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Noir & blanc");
        Assert.Equal(TranslationManager.Translation.Blur, "Flouter");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Éléments de la galerie inférieure");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Estirer les miniatures de la galerie inférieure");
        Assert.Equal(TranslationManager.Translation.Brightness, "Luminosité");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Fabricant de l'appareil photo");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Modèle de l'appareil photo");
        Assert.Equal(TranslationManager.Translation.Cancel, "Annuler");
        Assert.Equal(TranslationManager.Translation.Center, "Centrer");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Centrer la fenêtre");
        Assert.Equal(TranslationManager.Translation.Centimeters, "centimètres");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Modifier l'arrière plan");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Changer la couleur d'arrière-plan pour les images avec un fond transparent");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Cliquez sur une zone de texte pour changer le raccourci clavier. Appuyez sur Échap pour désactiver le raccourci clavier.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip,
            "Cliquez pour changer la liaison de touche");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart,
            "* La modification du thème nécessite un redémarrage");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Vérifier les mises à jour");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Image du presse-papiers");
        Assert.Equal(TranslationManager.Translation.Close, "Fermer");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Quitter l'application");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Fermer la galerie");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Souhaitez-vous fermer la fenêtre ?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Temps nuageux");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Outil de sélection de couleur");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Choisir la couleur de l'image");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Représentation des couleurs");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Tonalité des couleurs");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Bits de pixel compressés");
        Assert.Equal(TranslationManager.Translation.Compression, "Compression");
        Assert.Equal(TranslationManager.Translation.Contrast, "Contraste");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Convertir en");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Converti en base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Fluorescent blanc froid");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Copier l'image dans le presse-papiers");
        Assert.Equal(TranslationManager.Translation.Copy, "Copier");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Copier le fichier");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Copier l'image");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip,
            "Copier en tant qu'image du presse-papiers Windows");
        Assert.Equal(TranslationManager.Translation.Copyright, "Droits d'auteur");
        Assert.Equal(TranslationManager.Translation.Created, "Créé le");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Date de création");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Programme créatif");
        Assert.Equal(TranslationManager.Translation.Credits, "Crédits");
        Assert.Equal(TranslationManager.Translation.Crop, "Recadrer");
        Assert.Equal(TranslationManager.Translation.CropMessage,
            "Appuyez sur Echap pour fermer, Entrée pour enregistrer");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Recadrer l'image");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Ctrl pour zoomer, défiler pour naviguer");
        Assert.Equal(TranslationManager.Translation.Cut, "Couper");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Thème sombre");
        Assert.Equal(TranslationManager.Translation.Date, "Date");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Date de prise de vue");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Fluorescent blanc de jour");
        Assert.Equal(TranslationManager.Translation.Daylight, "Lumière du jour");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Fluorescent de jour");
        Assert.Equal(TranslationManager.Translation.Del, "Suppr");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Supprimer le fichier");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "Êtes-vous sûr de vouloir supprimer définitivement");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Fichiers supprimés");
        Assert.Equal(TranslationManager.Translation.Descending, "Descendant");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Zoom numérique");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Désactiver les boutons en fondu au survol de la souris");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Taille sur le disque");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Double-clic");
        Assert.Equal(TranslationManager.Translation.Down, "Bas");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Faites glisser le fichier vers l'explorateur Windows ou une autre application/navigateur");
        Assert.Equal(TranslationManager.Translation.DragImage, "Faire glisser l'image");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Glisser pour charger l'image");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Dupliquer le fichier");
        Assert.Equal(TranslationManager.Translation.Effects, "Effets");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Afficher la fenêtre des effets d'image");
        Assert.Equal(TranslationManager.Translation.Enter, "Entrer");
        Assert.Equal(TranslationManager.Translation.Esc, "Echap");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Ferme la fenêtre actuellement ouverte /menu");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Version Exif");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Éléments de la galerie étendue");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Compensation d'exposition");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Programme d'exposition");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Temps d'exposition");
        Assert.Equal(TranslationManager.Translation.FNumber, "Nombre F");
        Assert.Equal(TranslationManager.Translation.File, "fichier");
        Assert.Equal(TranslationManager.Translation.FileCopy, "Fichier copié dans le presse-papiers");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Copier le chemin du fichier");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Chemin du fichier ajouté au presse-papiers");
        Assert.Equal(TranslationManager.Translation.FileCutMessage,
            "Fichier ajouté pour remplacer dans le presse-papiers");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Extension du fichier");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Gestion des fichiers");
        Assert.Equal(TranslationManager.Translation.FileName, "Nom du fichier");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Coller");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Propriétés du fichier");
        Assert.Equal(TranslationManager.Translation.FileSize, "Taille du fichier");
        Assert.Equal(TranslationManager.Translation.Files, "fichiers");
        Assert.Equal(TranslationManager.Translation.Fill, "Remplir");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Hauteur de remplissage");
        Assert.Equal(TranslationManager.Translation.FillSquare, "RemplirCarré");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Beau temps");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Première image");
        Assert.Equal(TranslationManager.Translation.Fit, "Ajuster");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Ajuster à la fenêtre / à l'image\"");
        Assert.Equal(TranslationManager.Translation.Flash, "Flash");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Flash non déclenché");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Énergie du flash");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Flash déclenché");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Mode Flash");
        Assert.Equal(TranslationManager.Translation.Flip, "Retourner horizontalement");
        Assert.Equal(TranslationManager.Translation.Flipped, "Retourné");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Fluorescent");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Longueur focale");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Longueur focale 35mm");
        Assert.Equal(TranslationManager.Translation.Folder, "Dossier");
        Assert.Equal(TranslationManager.Translation.Forward, "Suivant");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationManager.Translation.FullPath, "Chemin complet");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Plein Ecran");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Paramètres de la galerie");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch,
            "Élargissement des miniatures de la galerie");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Paramètres généraux");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Générer des miniatures");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Référentiel GitHub");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Thème en verre");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Reculer de 100 images");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Reculer de 10 images");
        Assert.Equal(TranslationManager.Translation.Hard, "Dur");
        Assert.Equal(TranslationManager.Translation.Height, "Hauteur");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Masquer la galerie inférieure");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Ocultar barra de herramientas inferior");
        Assert.Equal(TranslationManager.Translation.HideUI, "Masquer l'interface");
        Assert.Equal(TranslationManager.Translation.High, "Élevé");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Haute qualité");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Couleur de surbrillance");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "Vitesse ISO");
        Assert.Equal(TranslationManager.Translation.Image, "Image");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Anticrénelage d'image");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Contrôle des images");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Informations sur l'image");
        Assert.Equal(TranslationManager.Translation.Inches, "pouces");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Fenêtre Info");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Infos et raccourcis");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Configuration de l'interface");
        Assert.Equal(TranslationManager.Translation.Landscape, "Paysage");
        Assert.Equal(TranslationManager.Translation.Longitude, "Longitude");
        Assert.Equal(TranslationManager.Translation.Language, "Langue");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Dernier accès le");
        Assert.Equal(TranslationManager.Translation.LastImage, "Dernière image");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Date de la dernière écriture");
        Assert.Equal(TranslationManager.Translation.Left, "Gauche");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Fabricant de l'objectif");
        Assert.Equal(TranslationManager.Translation.LensModel, "Modèle de l'objectif");
        Assert.Equal(TranslationManager.Translation.LightSource, "Source de lumière");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Thème clair");
        Assert.Equal(TranslationManager.Translation.Lighting, "Éclairage");
        Assert.Equal(TranslationManager.Translation.Loading, "Chargement ...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Longitude");
        Assert.Equal(TranslationManager.Translation.Looping, "Boucle");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Boucle désactivée");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Boucle activée");
        Assert.Equal(TranslationManager.Translation.Lossless, "Sans pertes");
        Assert.Equal(TranslationManager.Translation.Lossy, "Avec perte");
        Assert.Equal(TranslationManager.Translation.Low, "Faible");
        Assert.Equal(TranslationManager.Translation.Manual, "Manuel");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Ouverture maximale");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maximiser");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "mégapixels");
        Assert.Equal(TranslationManager.Translation.Meter, "Mètre");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Mode de mesure");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimiser");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Autres paramètres");
        Assert.Equal(TranslationManager.Translation.Modified, "Modifié");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Glisser vers la souris");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Touche souris en arrière");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Touche souris en avant");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Roulette de la souris");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Déplacer la fenêtre");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navigation");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Voisin le plus proche");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Couleurs négatives");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Nouvelle fenêtre");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Accéder au dossier suivant");
        Assert.Equal(TranslationManager.Translation.NextImage, "Image suivante");
        Assert.Equal(TranslationManager.Translation.NoChange, "Aucun changement");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Pas de Conversion");
        Assert.Equal(TranslationManager.Translation.NoImage, "Aucune image chargée");
        Assert.Equal(TranslationManager.Translation.NoImages, "Aucune image");
        Assert.Equal(TranslationManager.Translation.NoResize, "Pas de redimensionnement");
        Assert.Equal(TranslationManager.Translation.None, "Rien");
        Assert.Equal(TranslationManager.Translation.Normal, "Normal");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Fenêtre normale");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Non défini");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "PavéNum  -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "PavéNum  +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Vieille vidéo");
        Assert.Equal(TranslationManager.Translation.Open, "Ouvrir");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Ouvrir la boîte de dialogue du fichier");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Ouvrir les fichiers dans la même fenêtre");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Ouvrir le dernier fichier");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Ouvrir avec...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Optimiser l'image");
        Assert.Equal(TranslationManager.Translation.Orientation, "Orientation");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Dossier de sortie");
        Assert.Equal(TranslationManager.Translation.Pan, "Panoramique");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Archive protégée par mot de passe non supportée");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder,
            "Coller l'image à partir du support de clip");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Croquis au crayon");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% achevée...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Pourcentage");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Supprimer définitivement");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Interprétation photométrique");
        Assert.Equal(TranslationManager.Translation.Pixels, "pixels");
        Assert.Equal(TranslationManager.Translation.Portrait, "Portrait");
        Assert.Equal(TranslationManager.Translation.PressKey, "Appuyez sur la touche...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Accéder au dossier précédent");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Image précédente");
        Assert.Equal(TranslationManager.Translation.Print, "Imprimer");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Taille d'impression (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Taille d'impression (in)");
        Assert.Equal(TranslationManager.Translation.Quality, "Qualité");
        Assert.Equal(TranslationManager.Translation.Random, "Aléatoire");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Fichiers récents");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Réduction des yeux rouges");
        Assert.Equal(TranslationManager.Translation.Reload, "Recharger");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Supprimer la note");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Renommer le fichier");
        Assert.Equal(TranslationManager.Translation.Reset, "Réinitialiser");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Réinitialiser par défaut");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Réinitialiser le zoom");
        Assert.Equal(TranslationManager.Translation.Resize, "Redimensionner");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Redimensionner l'image");
        Assert.Equal(TranslationManager.Translation.Resolution, "Résolution");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Unité de résolution");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Redémarrer l'application");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Restaurer en bas");
        Assert.Equal(TranslationManager.Translation.Reverse, "Inverser");
        Assert.Equal(TranslationManager.Translation.Right, "Droite");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Rotation vers la gauche");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Pivoter à droite");
        Assert.Equal(TranslationManager.Translation.Rotated, "Tourné");
        Assert.Equal(TranslationManager.Translation.Saturation, "Saturation");
        Assert.Equal(TranslationManager.Translation.Save, "Enregistrer");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Enregistrer sous");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "La sauvegarde du fichier a échoué");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Faire défiler et tourner");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Direction du défilement");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Faire défiler vers le bas");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Faire défiler vers le bas");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Faire défiler vers le haut");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Faites défiler pour zoomer, Ctrl pour naviguer");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Faire défiler vers le haut");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Défilement");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Défilement désactivé");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Défilement activé");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Chercher les sous-répertoires");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sec.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Tout sélectionner");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Sélectionner la vignette de la galerie");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin,
            "Envoyer l'image actuelle dans la corbeille");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Fichier envoyé dans la corbeille");
        Assert.Equal(TranslationManager.Translation.SetAs, "Définir comme..");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Définir comme image d'écran de verrouillage");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Définir comme papier peint");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Définir l'image actuelle comme fond d'écran :");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Définir une note avec des étoiles");
        Assert.Equal(TranslationManager.Translation.Settings, "Paramètres");
        Assert.Equal(TranslationManager.Translation.Shade, "Ombre");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Netteté");
        Assert.Equal(TranslationManager.Translation.Shift, "Maj");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Afficher la fenêtre de tous les paramètres");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Afficher la galerie inférieure");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Afficher la galerie inférieure lorsque l'interface utilisateur est masquée");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Afficher la barre d'outils inférieure");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "Afficher la boîte de confirmation lors de l'appui sur 'Esc'");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover,
            "Afficher les boutons en fondu au survol de la souris");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog,
            "Afficher la boîte de dialogue d'enregistrement de fichier");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Afficher la galerie d'images");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Afficher les infos de l'image");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Afficher dans le dossier");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Afficher la fenêtre d'infos");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Afficher la fenêtre de redimensionnement");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Afficher l'interface");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Priorité à l'obturateur");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Côte à côte");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Afficher les images côte à côte");
        Assert.Equal(TranslationManager.Translation.Size, "Taille");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Taille (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip,
            "Entrez la taille souhaitée en pixels ou en pourcentage.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Diaporama");
        Assert.Equal(TranslationManager.Translation.Soft, "Doux");
        Assert.Equal(TranslationManager.Translation.Software, "Logiciel");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Trier les fichiers par");
        Assert.Equal(TranslationManager.Translation.Space, "Espace");
        Assert.Equal(TranslationManager.Translation.Square, "Carré");
        Assert.Equal(TranslationManager.Translation.Start, "Démarrer");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Démarrer le diaporama");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Garder la fenêtre centrée");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Rester au-dessus des autres fenêtres");
        Assert.Equal(TranslationManager.Translation.Stretch, "Étirez");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Étirer l'image");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected,
            "Lumière de retour du stroboscope détectée");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected,
            "Lumière de retour du stroboscope non détectée");
        Assert.Equal(TranslationManager.Translation.Subject, "Sujet");
        Assert.Equal(TranslationManager.Translation.Theme, "Thème");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Miniature");
        Assert.Equal(TranslationManager.Translation.Tile, "Mosaïque");
        Assert.Equal(TranslationManager.Translation.Title, "Titre");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Basculer la couleur d'arrière-plan");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Basculer en plein écran");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Basculer en boucle");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Activer le défilement");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress,
            "Afficher la progression dans la barre des tâches");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Impossible de rendre l'image");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Non calibré");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Une erreur inconnue est survenue");
        Assert.Equal(TranslationManager.Translation.Unflip, "Annuler le retournement");
        Assert.Equal(TranslationManager.Translation.Uniform, "Uniforme");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "UniformePourRemplir");
        Assert.Equal(TranslationManager.Translation.Unknown, "Inconnu");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Fichier non pris en charge");
        Assert.Equal(TranslationManager.Translation.Up, "Haut");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Utiliser la souris");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Utiliser le pavé tactile");
        Assert.Equal(TranslationManager.Translation.Version, "Version :");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Voir le fichier de licence");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Balance des blancs");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Fluorescent blanc");
        Assert.Equal(TranslationManager.Translation.Width, "Largeur");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Largeur et hauteur");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Gestion des fenêtres");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Mise à l'échelle de la fenêtre");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zoomer");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Zoom avant");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Zoom Arrière");
        Assert.Equal(TranslationManager.Translation._1Star, "Note de 1 étoile");
        Assert.Equal(TranslationManager.Translation._2Star, "Note de 2 étoiles");
        Assert.Equal(TranslationManager.Translation._3Star, "Note de 3 étoiles");
        Assert.Equal(TranslationManager.Translation._4Star, "Note de 4 étoiles");
        Assert.Equal(TranslationManager.Translation._5Star, "Note de 5 étoiles");
    }
}
