using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;
public static class GermanUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckGermanLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("de");
        Assert.True(exists);
        Assert.Equal(TranslationManager.Translation.About, "Über");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Aktionsprogramm");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Zur Zwischenablage hinzugefügt");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Zusätzliche Funktionen");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed,
            "Geschwindigkeit anpassen, wenn Taste gedrückt gehalten wird");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Timing für Diashow anpassen");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Zoomgeschwindigkeit anpassen");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Zoomstufe anpassen");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "100 Bilder vorwärts gehen");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "10 Bilder vorwärts gehen");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Herauszoomen des Bildes vermeiden, wenn es bereits maximale Größe hat");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Höhe");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Blendenpriorität");
        Assert.Equal(TranslationManager.Translation.Appearance, "Aussehen");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Tastenkürzel");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Anwendungsstart");
        Assert.Equal(TranslationManager.Translation.Apply, "Anwenden");
        Assert.Equal(TranslationManager.Translation.Applying, "Wird angewandt");
        Assert.Equal(TranslationManager.Translation.Ascending, "Aufsteigend");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Seitenverhältnis");
        Assert.Equal(TranslationManager.Translation.Authors, "Autoren");
        Assert.Equal(TranslationManager.Translation.Auto, "Auto");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Fenster automatisch anpassen");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Archiv konnte nicht verarbeitet werden");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Base64-Bild");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Stapel-Größenänderung");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Farbtiefe");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Schwarz & Weiß");
        Assert.Equal(TranslationManager.Translation.Blur, "Verwischen");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize,
            "Größe der Miniaturansichten in der unteren Galerie");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Miniaturbild-Erweiterung in der unteren Galerie");
        Assert.Equal(TranslationManager.Translation.Brightness, "Helligkeit");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Kamerahersteller");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Kameramodell");
        Assert.Equal(TranslationManager.Translation.Cancel, "Abbrechen");
        Assert.Equal(TranslationManager.Translation.Center, "Zentrieren");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Fenster zentrieren");
        Assert.Equal(TranslationManager.Translation.Centimeters, "Zentimeter");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Hintergrund ändern");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Zwischen der Hintergrundfarbe für Bilder mit transparentem Hintergrund wechseln");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Auf ein Textfeld klicken, um die Tastenkombination zu ändern. Drücken Sie Esc, um die Tastenkombination zu lösen.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip, "Klicken, um die Tastenbelegung zu ändern");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart,
            "* Ändern des Themas erfordert einen Neustart");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Auf Updates prüfen");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Bild in der Zwischenablage");
        Assert.Equal(TranslationManager.Translation.Close, "Schließen");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Gesamte Anwendung schließen");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Galerie schließen");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Möchten Sie das Fenster schließen?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Bewölktes Wetter");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Farbauswahl-Werkzeug");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Farbe aus Bild auswählen");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Farbdarstellung");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Farbton");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Komprimierte Bits pro Pixel");
        Assert.Equal(TranslationManager.Translation.Compression, "Komprimierung");
        Assert.Equal(TranslationManager.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Konvertieren zu");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "In Base64 umgewandelt");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Kaltweiß fluoreszierend");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Bild in Zwischenablage kopiert");
        Assert.Equal(TranslationManager.Translation.Copy, "Kopieren");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Datei kopieren");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Bild kopieren");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Als Windows-Zwischenablagebild kopieren");
        Assert.Equal(TranslationManager.Translation.Copyright, "Copyright");
        Assert.Equal(TranslationManager.Translation.Created, "Erstellt");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Erstellungsdatum");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Kreativprogramm");
        Assert.Equal(TranslationManager.Translation.Credits, "Impressum");
        Assert.Equal(TranslationManager.Translation.Crop, "Zuschneiden");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Esc zum Schließen, Enter zum Speichern drücken");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Bild zuschneiden");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Strg");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Strg zum zoomen, Scrollen zum navigieren");
        Assert.Equal(TranslationManager.Translation.Cut, "Ausschneiden");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Dunkel");
        Assert.Equal(TranslationManager.Translation.Date, "Datum");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Aufnahmedatum");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Tagesweiß fluoreszierend");
        Assert.Equal(TranslationManager.Translation.Daylight, "Tageslicht");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Tageslicht fluoreszierend");
        Assert.Equal(TranslationManager.Translation.Del, "Entf");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Datei löschen");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "Sind Sie sicher, dass Sie dauerhaft löschen möchten");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Datei gelöscht");
        Assert.Equal(TranslationManager.Translation.Descending, "Absteigend");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Digitaler Zoom");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Fade-in-Schaltflächen bei Mauszeiger deaktivieren");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Festplattengröße");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Doppelklick");
        Assert.Equal(TranslationManager.Translation.Down, "Runter");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Ziehen Sie die Datei in den Windows Explorer oder eine andere Anwendung/einen anderen Browser");
        Assert.Equal(TranslationManager.Translation.DragImage, "Bild ziehen");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Loslassen um Bild zu laden");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Datei duplizieren");
        Assert.Equal(TranslationManager.Translation.Effects, "Effekte");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Fenster für Bildeffekte anzeigen");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Schließt das aktuell geöffnete Fenster/Menü");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "EXIF-Version");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Größe der Miniaturansichten");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Belichtungskorrektur");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Belichtungsprogramm");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Belichtungszeit");
        Assert.Equal(TranslationManager.Translation.FNumber, "F-Nummer");
        Assert.Equal(TranslationManager.Translation.File, "Datei");
        Assert.Equal(TranslationManager.Translation.FileCopy, "In der Zwischenablage gespeichert");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Dateipfad kopieren");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Dateipfad zur Zwischenablage hinzugefügt");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "Datei in der Zwischenablage gespeichert");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Dateierweiterung");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Dateiverwaltung");
        Assert.Equal(TranslationManager.Translation.FileName, "Dateiname");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Datei einfügen");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Dateieigenschaften");
        Assert.Equal(TranslationManager.Translation.FileSize, "Dateigröße");
        Assert.Equal(TranslationManager.Translation.Files, "Dateien");
        Assert.Equal(TranslationManager.Translation.Fill, "Füllen");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Füllhöhe");
        Assert.Equal(TranslationManager.Translation.FillSquare, "Quadrat Füllen");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Gutes Wetter");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Erstes Bild");
        Assert.Equal(TranslationManager.Translation.Fit, "Anpassen");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "An Fenster/Bild anpassen");
        Assert.Equal(TranslationManager.Translation.Flash, "Blitz");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Blitz nicht ausgelöst");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Blitzenergie");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Blitz ausgelöst");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Blitzmodus");
        Assert.Equal(TranslationManager.Translation.Flip, "Horizontal spiegeln");
        Assert.Equal(TranslationManager.Translation.Flipped, "Horizontal gespiegelt");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Fluoreszierend");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Brennweite");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Brennweite (35mm)");
        Assert.Equal(TranslationManager.Translation.Folder, "Ordner");
        Assert.Equal(TranslationManager.Translation.Forward, "Vorwärts");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-Stop");
        Assert.Equal(TranslationManager.Translation.FullPath, "Vollständiger Pfad");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Vollbild");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Galerie Einstellungen");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "Miniaturansicht-Verhältnis");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Allgemeine Einstellungen");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Miniaturansichten generieren");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Github-Repository");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Glas");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "100 Bilder zurück gehen");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "10 Bilder zurück gehen");
        Assert.Equal(TranslationManager.Translation.Hard, "Hart");
        Assert.Equal(TranslationManager.Translation.Height, "Höhe");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Untere Galerie ausblenden");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Untere Symbolleiste ausblenden");
        Assert.Equal(TranslationManager.Translation.HideUI, "Benutzeroberfläche ausblenden");
        Assert.Equal(TranslationManager.Translation.High, "Hoch");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Hohe Qualität");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Hervorhebungsfarbe");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "ISO-Geschwindigkeit");
        Assert.Equal(TranslationManager.Translation.Image, "Bild");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Bild-Aliasing");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Bildsteuerung");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Bildinformationen");
        Assert.Equal(TranslationManager.Translation.Inches, "Zoll");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Infofenster");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Informationen und Tastenkürzel");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Oberflächenkonfiguration");
        Assert.Equal(TranslationManager.Translation.Landscape, "Landschaft");
        Assert.Equal(TranslationManager.Translation.Language, "Sprache");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Datei zuletzt geöffnet");
        Assert.Equal(TranslationManager.Translation.LastImage, "Letztes Bild");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Letzte Änderung");
        Assert.Equal(TranslationManager.Translation.Latitude, "Breitengrad");
        Assert.Equal(TranslationManager.Translation.Left, "Links");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Objektivhersteller");
        Assert.Equal(TranslationManager.Translation.LensModel, "Objektivmodell");
        Assert.Equal(TranslationManager.Translation.LightSource, "Lichtquelle");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Hell");
        Assert.Equal(TranslationManager.Translation.Lighting, "Beleuchtung");
        Assert.Equal(TranslationManager.Translation.Loading, "Lädt...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Längengrad");
        Assert.Equal(TranslationManager.Translation.Looping, "Schleife");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Schleife deaktiviert");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Schleife aktiviert");
        Assert.Equal(TranslationManager.Translation.Lossless, "Verlustfrei");
        Assert.Equal(TranslationManager.Translation.Lossy, "Verlustbehaftet");
        Assert.Equal(TranslationManager.Translation.Low, "Niedrig");
        Assert.Equal(TranslationManager.Translation.Manual, "Manuell");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Maximale Blende");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maximieren");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "Megapixel");
        Assert.Equal(TranslationManager.Translation.Meter, "Messen");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Messmodus");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimieren");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Sonstige Einstellungen");
        Assert.Equal(TranslationManager.Translation.Modified, "Geändert");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Maus ziehen");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Maustaste zurück");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Maustaste vorwärts");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Mausrad");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Fenster verschieben");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navigation");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Nächster Nachbar");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Negative Farben");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Neues Fenster");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Zum nächsten Ordner wechseln");
        Assert.Equal(TranslationManager.Translation.NextImage, "Nächstes Bild");
        Assert.Equal(TranslationManager.Translation.NoChange, "Keine Änderungen");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Keine Konvertierung");
        Assert.Equal(TranslationManager.Translation.NoImage, "Kein Bild geladen");
        Assert.Equal(TranslationManager.Translation.NoImages, "Keine Bilder");
        Assert.Equal(TranslationManager.Translation.NoResize, "Keine Größenänderung");
        Assert.Equal(TranslationManager.Translation.None, "Keine");
        Assert.Equal(TranslationManager.Translation.Normal, "Normal");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Normales Fenster");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Nicht definiert");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Alter Film");
        Assert.Equal(TranslationManager.Translation.Open, "Öffnen");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Datei auswählen");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Dateien im selben Fenster öffnen");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Letzte Datei öffnen");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Öffnen mit...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Bild optimieren");
        Assert.Equal(TranslationManager.Translation.Orientation, "Orientierung");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Zielordner");
        Assert.Equal(TranslationManager.Translation.Pan, "Schwenken");
        Assert.Equal(TranslationManager.Translation.PasswordArchive,
            "Passwort geschützte Archive werden nicht unterstützt");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Bild von Zwischenablage einfügen");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Bleistiftskizze");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% vollständig...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Prozentsatz");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Endgültig löschen");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Photometrische Interpretation");
        Assert.Equal(TranslationManager.Translation.Pixels, "Pixel");
        Assert.Equal(TranslationManager.Translation.Portrait, "Porträt");
        Assert.Equal(TranslationManager.Translation.PressKey, "Taste drücken...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Zum vorherigen Ordner wechseln");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Vorheriges Bild");
        Assert.Equal(TranslationManager.Translation.Print, "Drucken");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Druckgröße (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Druckgröße (in)");
        Assert.Equal(TranslationManager.Translation.Quality, "Qualität");
        Assert.Equal(TranslationManager.Translation.Random, "Zufall");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Zuletzt geöffnete Dateien");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Rote-Augen-Reduktion");
        Assert.Equal(TranslationManager.Translation.Reload, "Neu laden");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Bewertung entfernen");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Datei umbenennen");
        Assert.Equal(TranslationManager.Translation.Reset, "Zurücksetzen");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Auf Standard zurücksetzen");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Zoom zurücksetzen");
        Assert.Equal(TranslationManager.Translation.Resize, "Größe ändern");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Bildgröße ändern");
        Assert.Equal(TranslationManager.Translation.Resolution, "Auflösung");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Auflösungseinheit");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Anwendung neu starten");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Mini-/Maximieren");
        Assert.Equal(TranslationManager.Translation.Reverse, "Umkehren");
        Assert.Equal(TranslationManager.Translation.Right, "Rechts");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Nach links drehen");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Nach rechts drehen");
        Assert.Equal(TranslationManager.Translation.Rotated, "Gedreht");
        Assert.Equal(TranslationManager.Translation.Saturation, "Sättigung");
        Assert.Equal(TranslationManager.Translation.Save, "Speichern");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Speichern unter");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Speichern der Datei fehlgeschlagen");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Scrollen und drehen");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Scrollrichtung");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Nach unten scrollen");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Zum Ende scrollen");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Zum Anfang scrollen");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Mit Mausrad zoomen, mit Strg navigieren");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Nach oben scrollen");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Scrollen");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Scrollen deaktiviert");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Scrollen aktiviert");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Unterverzeichnisse durchsuchen");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sek.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Alle auswählen");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Miniaturansicht der Galerie auswählen");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin,
            "Aktives Bild in den Papierkorb verschieben");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Datei in den Papierkorb verschieben");
        Assert.Equal(TranslationManager.Translation.SetAs, "Festlegen als...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Als Sperrbildschirmbild festlegen");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Als Hintergrundbild festlegen");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Aktuelles Bild als Hintergrundbild festlegen:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Bewertung festlegen");
        Assert.Equal(TranslationManager.Translation.Settings, "Einstellungen");
        Assert.Equal(TranslationManager.Translation.Shade, "Schatten");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Schärfe");
        Assert.Equal(TranslationManager.Translation.Shift, "Schicht");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Alle Einstellungsfenster anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Untere Galerie anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Untere Galerie anzeigen, wenn die Benutzeroberfläche ausgeblendet ist");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Untere Symbolleiste anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "Bestätigungsdialog anzeigen, wenn 'Esc' gedrückt wird");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover,
            "Fade-in-Schaltflächen bei Mauszeiger anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Dateispeicherdialog anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Bildergalerie anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Bildinformationen anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Im Ordner anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Infofenster anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Größenänderungsfenster anzeigen");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Benutzeroberfläche anzeigen");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Verschlusspriorität");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Nebeneinander");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Bilder nebeneinander anzeigen");
        Assert.Equal(TranslationManager.Translation.Size, "Größe");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Größe (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "Gewünschte Größe in Pixel oder Prozent eingeben.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Diashow");
        Assert.Equal(TranslationManager.Translation.Soft, "Weich");
        Assert.Equal(TranslationManager.Translation.Software, "Software");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Dateien sortieren nach");
        Assert.Equal(TranslationManager.Translation.Space, "Platz");
        Assert.Equal(TranslationManager.Translation.Square, "Quadrat");
        Assert.Equal(TranslationManager.Translation.Start, "Start");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Diashow starten");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Fenster zentriert halten");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Immer im Vordergrund");
        Assert.Equal(TranslationManager.Translation.Stretch, "Strecken");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Bild strecken");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Blitzlicht erkannt");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected, "Blitzlicht nicht erkannt");
        Assert.Equal(TranslationManager.Translation.Subject, "Thema");
        Assert.Equal(TranslationManager.Translation.Theme, "Thema");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Miniatur");
        Assert.Equal(TranslationManager.Translation.Tile, "Kachel");
        Assert.Equal(TranslationManager.Translation.Title, "Titel");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Hintergrundfarbe umschalten");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Vollbildmodus ein-/ausschalten");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Wiederholung ein-/ausschalten");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Scrollen umschalten");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Fortschritt in der Taskleiste anzeigen");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Bild kann nicht gerendert werden");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Nicht kalibriert");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Es ist ein unbekannter Fehler aufgetreten");
        Assert.Equal(TranslationManager.Translation.Unflip, "Umdrehen");
        Assert.Equal(TranslationManager.Translation.Uniform, "Gleichmäßig");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "Gleichmäßig zum Füllen");
        Assert.Equal(TranslationManager.Translation.Unknown, "Unbekannt");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Nicht unterstützte Datei");
        Assert.Equal(TranslationManager.Translation.Up, "Hoch");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Verwende Maus");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Verwende Touchpad");
        Assert.Equal(TranslationManager.Translation.Version, "Version:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Lizenzdatei ansehen");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Weißabgleich");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Weiß fluoreszierend");
        Assert.Equal(TranslationManager.Translation.Width, "Breite");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Breite und Höhe");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Fensterverwaltung");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Fensterskalierung");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Vergrößern");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Verkleinern");
        Assert.Equal(TranslationManager.Translation._1Star, "1 Stern");
        Assert.Equal(TranslationManager.Translation._2Star, "2 Sterne");
        Assert.Equal(TranslationManager.Translation._3Star, "3 Sterne");
        Assert.Equal(TranslationManager.Translation._4Star, "4 Sterne");
        Assert.Equal(TranslationManager.Translation._5Star, "5 Sterne");
    }
}
