using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;
public static class GermanUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckGermanLanguage()
    {
        var exists = await TranslationHelper.LoadLanguage("de");
        Assert.True(exists);
        Assert.Equal(TranslationHelper.Translation.About, "Über");
        Assert.Equal(TranslationHelper.Translation.ActionProgram, "Aktionsprogramm");
        Assert.Equal(TranslationHelper.Translation.AddedToClipboard, "Zur Zwischenablage hinzugefügt");
        Assert.Equal(TranslationHelper.Translation.AdditionalFunctions, "Zusätzliche Funktionen");
        Assert.Equal(TranslationHelper.Translation.AdjustNavSpeed,
            "Geschwindigkeit anpassen, wenn Taste gedrückt gehalten wird");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForSlideshow, "Timing für Diashow anpassen");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForZoom, "Zoomgeschwindigkeit anpassen");
        Assert.Equal(TranslationHelper.Translation.AdjustZoomLevel, "Zoomstufe anpassen");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy100Images, "100 Bilder vorwärts gehen");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy10Images, "10 Bilder vorwärts gehen");
        Assert.Equal(TranslationHelper.Translation.AllowZoomOut,
            "Herauszoomen des Bildes vermeiden, wenn es bereits maximale Größe hat");
        Assert.Equal(TranslationHelper.Translation.Alt, "Alt");
        Assert.Equal(TranslationHelper.Translation.Altitude, "Höhe");
        Assert.Equal(TranslationHelper.Translation.AperturePriority, "Blendenpriorität");
        Assert.Equal(TranslationHelper.Translation.Appearance, "Aussehen");
        Assert.Equal(TranslationHelper.Translation.ApplicationShortcuts, "Tastenkürzel");
        Assert.Equal(TranslationHelper.Translation.ApplicationStartup, "Anwendungsstart");
        Assert.Equal(TranslationHelper.Translation.Apply, "Anwenden");
        Assert.Equal(TranslationHelper.Translation.Applying, "Wird angewandt");
        Assert.Equal(TranslationHelper.Translation.Ascending, "Aufsteigend");
        Assert.Equal(TranslationHelper.Translation.AspectRatio, "Seitenverhältnis");
        Assert.Equal(TranslationHelper.Translation.Authors, "Autoren");
        Assert.Equal(TranslationHelper.Translation.Auto, "Auto");
        Assert.Equal(TranslationHelper.Translation.AutoFitWindow, "Fenster automatisch anpassen");
        Assert.Equal(TranslationHelper.Translation.BadArchive, "Archiv konnte nicht verarbeitet werden");
        Assert.Equal(TranslationHelper.Translation.BandedSwirl, "Gebänderter Wirbel");
        Assert.Equal(TranslationHelper.Translation.Bands, "Streifen");
        Assert.Equal(TranslationHelper.Translation.Base64Image, "Base64-Bild");
        Assert.Equal(TranslationHelper.Translation.BatchResize, "Stapel-Größenänderung");
        Assert.Equal(TranslationHelper.Translation.BitDepth, "Farbtiefe");
        Assert.Equal(TranslationHelper.Translation.BlackAndWhite, "Schwarz & Weiß");
        Assert.Equal(TranslationHelper.Translation.Bloom, "Blühen");
        Assert.Equal(TranslationHelper.Translation.Blur, "Verwischen");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryItemSize,
            "Größe der Miniaturansichten in der unteren Galerie");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryThumbnailStretch,
            "Miniaturbild-Erweiterung in der unteren Galerie");
        Assert.Equal(TranslationHelper.Translation.Brightness, "Helligkeit");
        Assert.Equal(TranslationHelper.Translation.CameraMaker, "Kamerahersteller");
        Assert.Equal(TranslationHelper.Translation.CameraModel, "Kameramodell");
        Assert.Equal(TranslationHelper.Translation.Cancel, "Abbrechen");
        Assert.Equal(TranslationHelper.Translation.Center, "Zentrieren");
        Assert.Equal(TranslationHelper.Translation.CenterWindow, "Fenster zentrieren");
        Assert.Equal(TranslationHelper.Translation.Centimeters, "Zentimeter");
        Assert.Equal(TranslationHelper.Translation.ChangeBackground, "Hintergrund ändern");
        Assert.Equal(TranslationHelper.Translation.ChangeBackgroundTooltip,
            "Zwischen der Hintergrundfarbe für Bilder mit transparentem Hintergrund wechseln");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingText,
            "Auf ein Textfeld klicken, um die Tastenkombination zu ändern. Drücken Sie Esc, um die Tastenkombination zu lösen.");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingTooltip, "Klicken, um die Tastenbelegung zu ändern");
        Assert.Equal(TranslationHelper.Translation.ChangingThemeRequiresRestart,
            "* Ändern des Themas erfordert einen Neustart");
        Assert.Equal(TranslationHelper.Translation.CheckForUpdates, "Auf Updates prüfen");
        Assert.Equal(TranslationHelper.Translation.ClipboardImage, "Bild in der Zwischenablage");
        Assert.Equal(TranslationHelper.Translation.Close, "Schließen");
        Assert.Equal(TranslationHelper.Translation.CloseApp, "Gesamte Anwendung schließen");
        Assert.Equal(TranslationHelper.Translation.CloseGallery, "Galerie schließen");
        Assert.Equal(TranslationHelper.Translation.CloseWindowPrompt, "Möchten Sie das Fenster schließen?");
        Assert.Equal(TranslationHelper.Translation.CloudyWeather, "Bewölktes Wetter");
        Assert.Equal(TranslationHelper.Translation.ColorPickerTool, "Farbauswahl-Werkzeug");
        Assert.Equal(TranslationHelper.Translation.ColorPickerToolTooltip, "Farbe aus Bild auswählen");
        Assert.Equal(TranslationHelper.Translation.ColorRepresentation, "Farbdarstellung");
        Assert.Equal(TranslationHelper.Translation.ColorTone, "Farbton");
        Assert.Equal(TranslationHelper.Translation.CompressedBitsPixel, "Komprimierte Bits pro Pixel");
        Assert.Equal(TranslationHelper.Translation.Compression, "Komprimierung");
        Assert.Equal(TranslationHelper.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationHelper.Translation.ConvertTo, "Konvertieren zu");
        Assert.Equal(TranslationHelper.Translation.ConvertedToBase64, "In Base64 umgewandelt");
        Assert.Equal(TranslationHelper.Translation.CoolWhiteFluorescent, "Kaltweiß fluoreszierend");
        Assert.Equal(TranslationHelper.Translation.CopiedImage, "Bild in Zwischenablage kopiert");
        Assert.Equal(TranslationHelper.Translation.Copy, "Kopieren");
        Assert.Equal(TranslationHelper.Translation.CopyFile, "Datei kopieren");
        Assert.Equal(TranslationHelper.Translation.CopyImage, "Bild kopieren");
        Assert.Equal(TranslationHelper.Translation.CopyImageTooltip, "Als Windows-Zwischenablagebild kopieren");
        Assert.Equal(TranslationHelper.Translation.Copyright, "Copyright");
        Assert.Equal(TranslationHelper.Translation.Created, "Erstellt");
        Assert.Equal(TranslationHelper.Translation.CreationTime, "Erstellungsdatum");
        Assert.Equal(TranslationHelper.Translation.CreativeProgram, "Kreativprogramm");
        Assert.Equal(TranslationHelper.Translation.Credits, "Impressum");
        Assert.Equal(TranslationHelper.Translation.Crop, "Zuschneiden");
        Assert.Equal(TranslationHelper.Translation.CropMessage, "Esc zum Schließen, Enter zum Speichern drücken");
        Assert.Equal(TranslationHelper.Translation.CropPicture, "Bild zuschneiden");
        Assert.Equal(TranslationHelper.Translation.Ctrl, "Strg");
        Assert.Equal(TranslationHelper.Translation.CtrlToZoom, "Strg zum zoomen, Scrollen zum navigieren");
        Assert.Equal(TranslationHelper.Translation.Cut, "Ausschneiden");
        Assert.Equal(TranslationHelper.Translation.DarkTheme, "Dunkel");
        Assert.Equal(TranslationHelper.Translation.Date, "Datum");
        Assert.Equal(TranslationHelper.Translation.DateTaken, "Aufnahmedatum");
        Assert.Equal(TranslationHelper.Translation.DayWhiteFluorescent, "Tagesweiß fluoreszierend");
        Assert.Equal(TranslationHelper.Translation.Daylight, "Tageslicht");
        Assert.Equal(TranslationHelper.Translation.DaylightFluorescent, "Tageslicht fluoreszierend");
        Assert.Equal(TranslationHelper.Translation.Del, "Entf");
        Assert.Equal(TranslationHelper.Translation.DeleteFile, "Datei löschen");
        Assert.Equal(TranslationHelper.Translation.DeleteFilePermanently,
            "Sind Sie sicher, dass Sie dauerhaft löschen möchten");
        Assert.Equal(TranslationHelper.Translation.DeletedFile, "Datei gelöscht");
        Assert.Equal(TranslationHelper.Translation.Descending, "Absteigend");
        Assert.Equal(TranslationHelper.Translation.DigitalZoom, "Digitaler Zoom");
        Assert.Equal(TranslationHelper.Translation.DirectionalBlur, "Richtungsunschärfe");
        Assert.Equal(TranslationHelper.Translation.DisableFadeInButtonsOnHover,
            "Fade-in-Schaltflächen bei Mauszeiger deaktivieren");
        Assert.Equal(TranslationHelper.Translation.DiskSize, "Festplattengröße");
        Assert.Equal(TranslationHelper.Translation.DoubleClick, "Doppelklick");
        Assert.Equal(TranslationHelper.Translation.Down, "Runter");
        Assert.Equal(TranslationHelper.Translation.Dpi, "DPI");
        Assert.Equal(TranslationHelper.Translation.DragFileTo,
            "Ziehen Sie die Datei in den Windows Explorer oder eine andere Anwendung/einen anderen Browser");
        Assert.Equal(TranslationHelper.Translation.DragImage, "Bild ziehen");
        Assert.Equal(TranslationHelper.Translation.DropToLoad, "Loslassen um Bild zu laden");
        Assert.Equal(TranslationHelper.Translation.DuplicateFile, "Datei duplizieren");
        Assert.Equal(TranslationHelper.Translation.Effects, "Effekte");
        Assert.Equal(TranslationHelper.Translation.EffectsTooltip, "Fenster für Bildeffekte anzeigen");
        Assert.Equal(TranslationHelper.Translation.Embossed, "Erhaben");
        Assert.Equal(TranslationHelper.Translation.Enter, "Enter");
        Assert.Equal(TranslationHelper.Translation.Esc, "Esc");
        Assert.Equal(TranslationHelper.Translation.EscCloseTooltip, "Schließt das aktuell geöffnete Fenster/Menü");
        Assert.Equal(TranslationHelper.Translation.ExifVersion, "EXIF-Version");
        Assert.Equal(TranslationHelper.Translation.ExpandedGalleryItemSize, "Größe der Miniaturansichten");
        Assert.Equal(TranslationHelper.Translation.ExposureBias, "Belichtungskorrektur");
        Assert.Equal(TranslationHelper.Translation.ExposureProgram, "Belichtungsprogramm");
        Assert.Equal(TranslationHelper.Translation.ExposureTime, "Belichtungszeit");
        Assert.Equal(TranslationHelper.Translation.FNumber, "F-Nummer");
        Assert.Equal(TranslationHelper.Translation.File, "Datei");
        Assert.Equal(TranslationHelper.Translation.FileCopy, "In der Zwischenablage gespeichert");
        Assert.Equal(TranslationHelper.Translation.FileCopyPath, "Dateipfad kopieren");
        Assert.Equal(TranslationHelper.Translation.FileCopyPathMessage, "Dateipfad zur Zwischenablage hinzugefügt");
        Assert.Equal(TranslationHelper.Translation.FileCutMessage, "Datei in der Zwischenablage gespeichert");
        Assert.Equal(TranslationHelper.Translation.FileExtension, "Dateierweiterung");
        Assert.Equal(TranslationHelper.Translation.FileManagement, "Dateiverwaltung");
        Assert.Equal(TranslationHelper.Translation.FileName, "Dateiname");
        Assert.Equal(TranslationHelper.Translation.FilePaste, "Datei einfügen");
        Assert.Equal(TranslationHelper.Translation.FileProperties, "Dateieigenschaften");
        Assert.Equal(TranslationHelper.Translation.FileSize, "Dateigröße");
        Assert.Equal(TranslationHelper.Translation.Files, "Dateien");
        Assert.Equal(TranslationHelper.Translation.Fill, "Füllen");
        Assert.Equal(TranslationHelper.Translation.FillHeight, "⇔ Füllhöhe");
        Assert.Equal(TranslationHelper.Translation.FillSquare, "Quadrat Füllen");
        Assert.Equal(TranslationHelper.Translation.FineWeather, "Gutes Wetter");
        Assert.Equal(TranslationHelper.Translation.FirstImage, "Erstes Bild");
        Assert.Equal(TranslationHelper.Translation.Fit, "Anpassen");
        Assert.Equal(TranslationHelper.Translation.FitToWindow, "An Fenster/Bild anpassen");
        Assert.Equal(TranslationHelper.Translation.Flash, "Blitz");
        Assert.Equal(TranslationHelper.Translation.FlashDidNotFire, "Blitz nicht ausgelöst");
        Assert.Equal(TranslationHelper.Translation.FlashEnergy, "Blitzenergie");
        Assert.Equal(TranslationHelper.Translation.FlashFired, "Blitz ausgelöst");
        Assert.Equal(TranslationHelper.Translation.FlashMode, "Blitzmodus");
        Assert.Equal(TranslationHelper.Translation.Flip, "Horizontal spiegeln");
        Assert.Equal(TranslationHelper.Translation.Flipped, "Horizontal gespiegelt");
        Assert.Equal(TranslationHelper.Translation.Fluorescent, "Fluoreszierend");
        Assert.Equal(TranslationHelper.Translation.FocalLength, "Brennweite");
        Assert.Equal(TranslationHelper.Translation.FocalLength35mm, "Brennweite (35mm)");
        Assert.Equal(TranslationHelper.Translation.Folder, "Ordner");
        Assert.Equal(TranslationHelper.Translation.Forward, "Vorwärts");
        Assert.Equal(TranslationHelper.Translation.FrostyOutline, "Eiskalter Umriss");
        Assert.Equal(TranslationHelper.Translation.Fstop, "F-Stop");
        Assert.Equal(TranslationHelper.Translation.FullPath, "Vollständiger Pfad");
        Assert.Equal(TranslationHelper.Translation.Fullscreen, "Vollbild");
        Assert.Equal(TranslationHelper.Translation.GallerySettings, "Galerie Einstellungen");
        Assert.Equal(TranslationHelper.Translation.GalleryThumbnailStretch, "Miniaturansicht-Verhältnis");
        Assert.Equal(TranslationHelper.Translation.GeneralSettings, "Allgemeine Einstellungen");
        Assert.Equal(TranslationHelper.Translation.GenerateThumbnails, "Miniaturansichten generieren");
        Assert.Equal(TranslationHelper.Translation.GithubRepo, "Github-Repository");
        Assert.Equal(TranslationHelper.Translation.GlassTheme, "Glas");
        Assert.Equal(TranslationHelper.Translation.GlassTile, "Glaskachel");
        Assert.Equal(TranslationHelper.Translation.Gloom, "Dunkelheit");
        Assert.Equal(TranslationHelper.Translation.GoBackBy100Images, "100 Bilder zurück gehen");
        Assert.Equal(TranslationHelper.Translation.GoBackBy10Images, "10 Bilder zurück gehen");
        Assert.Equal(TranslationHelper.Translation.GoToImageAtSpecifiedIndex, "Zu Bild mit angegebenen Index gehen");
        Assert.Equal(TranslationHelper.Translation.Hard, "Hart");
        Assert.Equal(TranslationHelper.Translation.Height, "Höhe");
        Assert.Equal(TranslationHelper.Translation.HideBottomGallery, "Untere Galerie ausblenden");
        Assert.Equal(TranslationHelper.Translation.HideBottomToolbar, "Untere Symbolleiste ausblenden");
        Assert.Equal(TranslationHelper.Translation.HideUI, "Benutzeroberfläche ausblenden");
        Assert.Equal(TranslationHelper.Translation.High, "Hoch");
        Assert.Equal(TranslationHelper.Translation.HighQuality, "Hohe Qualität");
        Assert.Equal(TranslationHelper.Translation.HighlightColor, "Hervorhebungsfarbe");
        Assert.Equal(TranslationHelper.Translation.ISOSpeed, "ISO-Geschwindigkeit");
        Assert.Equal(TranslationHelper.Translation.IconsUsed, "Verwendete Symbole:");
        Assert.Equal(TranslationHelper.Translation.Image, "Bild");
        Assert.Equal(TranslationHelper.Translation.ImageAliasing, "Bild-Aliasing");
        Assert.Equal(TranslationHelper.Translation.ImageControl, "Bildsteuerung");
        Assert.Equal(TranslationHelper.Translation.ImageInfo, "Bildinformationen");
        Assert.Equal(TranslationHelper.Translation.Inches, "Zoll");
        Assert.Equal(TranslationHelper.Translation.InfoWindow, "Infofenster");
        Assert.Equal(TranslationHelper.Translation.InfoWindowTitle, "Informationen und Tastenkürzel");
        Assert.Equal(TranslationHelper.Translation.InterfaceConfiguration, "Oberflächenkonfiguration");
        Assert.Equal(TranslationHelper.Translation.Landscape, "Landschaft");
        Assert.Equal(TranslationHelper.Translation.Language, "Sprache");
        Assert.Equal(TranslationHelper.Translation.LastAccessTime, "Datei zuletzt geöffnet");
        Assert.Equal(TranslationHelper.Translation.LastImage, "Letztes Bild");
        Assert.Equal(TranslationHelper.Translation.LastWriteTime, "Letzte Änderung");
        Assert.Equal(TranslationHelper.Translation.Latitude, "Breitengrad");
        Assert.Equal(TranslationHelper.Translation.Left, "Links");
        Assert.Equal(TranslationHelper.Translation.LensMaker, "Objektivhersteller");
        Assert.Equal(TranslationHelper.Translation.LensModel, "Objektivmodell");
        Assert.Equal(TranslationHelper.Translation.LightSource, "Lichtquelle");
        Assert.Equal(TranslationHelper.Translation.LightTheme, "Hell");
        Assert.Equal(TranslationHelper.Translation.Lighting, "Beleuchtung");
        Assert.Equal(TranslationHelper.Translation.Loading, "Lädt...");
        Assert.Equal(TranslationHelper.Translation.Longitude, "Längengrad");
        Assert.Equal(TranslationHelper.Translation.Looping, "Schleife");
        Assert.Equal(TranslationHelper.Translation.LoopingDisabled, "Schleife deaktiviert");
        Assert.Equal(TranslationHelper.Translation.LoopingEnabled, "Schleife aktiviert");
        Assert.Equal(TranslationHelper.Translation.Lossless, "Verlustfrei");
        Assert.Equal(TranslationHelper.Translation.Lossy, "Verlustbehaftet");
        Assert.Equal(TranslationHelper.Translation.Low, "Niedrig");
        Assert.Equal(TranslationHelper.Translation.Manual, "Manuell");
        Assert.Equal(TranslationHelper.Translation.MaxAperture, "Maximale Blende");
        Assert.Equal(TranslationHelper.Translation.Maximize, "Maximieren");
        Assert.Equal(TranslationHelper.Translation.MegaPixels, "Megapixel");
        Assert.Equal(TranslationHelper.Translation.Meter, "Messen");
        Assert.Equal(TranslationHelper.Translation.MeteringMode, "Messmodus");
        Assert.Equal(TranslationHelper.Translation.Minimize, "Minimieren");
        Assert.Equal(TranslationHelper.Translation.MiscSettings, "Sonstige Einstellungen");
        Assert.Equal(TranslationHelper.Translation.Modified, "Geändert");
        Assert.Equal(TranslationHelper.Translation.Monochrome, "Einfarbig");
        Assert.Equal(TranslationHelper.Translation.MouseDrag, "Maus ziehen");
        Assert.Equal(TranslationHelper.Translation.MouseKeyBack, "Maustaste zurück");
        Assert.Equal(TranslationHelper.Translation.MouseKeyForward, "Maustaste vorwärts");
        Assert.Equal(TranslationHelper.Translation.MouseWheel, "Mausrad");
        Assert.Equal(TranslationHelper.Translation.MoveWindow, "Fenster verschieben");
        Assert.Equal(TranslationHelper.Translation.Navigation, "Navigation");
        Assert.Equal(TranslationHelper.Translation.NearestNeighbor, "Nächster Nachbar");
        Assert.Equal(TranslationHelper.Translation.NegativeColors, "Negative Farben");
        Assert.Equal(TranslationHelper.Translation.NewWindow, "Neues Fenster");
        Assert.Equal(TranslationHelper.Translation.NextFolder, "Zum nächsten Ordner wechseln");
        Assert.Equal(TranslationHelper.Translation.NextImage, "Nächstes Bild");
        Assert.Equal(TranslationHelper.Translation.NoChange, "Keine Änderungen");
        Assert.Equal(TranslationHelper.Translation.NoConversion, "Keine Konvertierung");
        Assert.Equal(TranslationHelper.Translation.NoImage, "Kein Bild geladen");
        Assert.Equal(TranslationHelper.Translation.NoImages, "Keine Bilder");
        Assert.Equal(TranslationHelper.Translation.NoResize, "Keine Größenänderung");
        Assert.Equal(TranslationHelper.Translation.None, "Keine");
        Assert.Equal(TranslationHelper.Translation.Normal, "Normal");
        Assert.Equal(TranslationHelper.Translation.NormalWindow, "Normales Fenster");
        Assert.Equal(TranslationHelper.Translation.NotDefined, "Nicht definiert");
        Assert.Equal(TranslationHelper.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationHelper.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationHelper.Translation.OldMovie, "Alter Film");
        Assert.Equal(TranslationHelper.Translation.Open, "Öffnen");
        Assert.Equal(TranslationHelper.Translation.OpenFileDialog, "Datei auswählen");
        Assert.Equal(TranslationHelper.Translation.OpenInSameWindow, "Dateien im selben Fenster öffnen");
        Assert.Equal(TranslationHelper.Translation.OpenLastFile, "Letzte Datei öffnen");
        Assert.Equal(TranslationHelper.Translation.OpenWith, "Öffnen mit...");
        Assert.Equal(TranslationHelper.Translation.OptimizeImage, "Bild optimieren");
        Assert.Equal(TranslationHelper.Translation.Orientation, "Orientierung");
        Assert.Equal(TranslationHelper.Translation.OutputFolder, "Zielordner");
        Assert.Equal(TranslationHelper.Translation.Pan, "Schwenken");
        Assert.Equal(TranslationHelper.Translation.PaperFold, "Papierfalte");
        Assert.Equal(TranslationHelper.Translation.PasswordArchive,
            "Passwort geschützte Archive werden nicht unterstützt");
        Assert.Equal(TranslationHelper.Translation.PasteImageFromClipholder, "Bild von Zwischenablage einfügen");
        Assert.Equal(TranslationHelper.Translation.PencilSketch, "Bleistiftskizze");
        Assert.Equal(TranslationHelper.Translation.PercentComplete, "% vollständig...");
        Assert.Equal(TranslationHelper.Translation.Percentage, "Prozentsatz");
        Assert.Equal(TranslationHelper.Translation.PermanentlyDelete, "Endgültig löschen");
        Assert.Equal(TranslationHelper.Translation.PhotometricInterpretation, "Photometrische Interpretation");
        Assert.Equal(TranslationHelper.Translation.Pivot, "Drehpunkt");
        Assert.Equal(TranslationHelper.Translation.Pixelate, "Verpixeln");
        Assert.Equal(TranslationHelper.Translation.Pixels, "Pixel");
        Assert.Equal(TranslationHelper.Translation.Portrait, "Porträt");
        Assert.Equal(TranslationHelper.Translation.PressKey, "Taste drücken...");
        Assert.Equal(TranslationHelper.Translation.PrevFolder, "Zum vorherigen Ordner wechseln");
        Assert.Equal(TranslationHelper.Translation.PrevImage, "Vorheriges Bild");
        Assert.Equal(TranslationHelper.Translation.Print, "Drucken");
        Assert.Equal(TranslationHelper.Translation.PrintSizeCm, "Druckgröße (cm)");
        Assert.Equal(TranslationHelper.Translation.PrintSizeIn, "Druckgröße (in)");
        Assert.Equal(TranslationHelper.Translation.Quality, "Qualität");
        Assert.Equal(TranslationHelper.Translation.Random, "Zufall");
        Assert.Equal(TranslationHelper.Translation.RecentFiles, "Zuletzt geöffnete Dateien");
        Assert.Equal(TranslationHelper.Translation.RedEyeReduction, "Rote-Augen-Reduktion");
        Assert.Equal(TranslationHelper.Translation.Reload, "Neu laden");
        Assert.Equal(TranslationHelper.Translation.RemoveStarRating, "Bewertung entfernen");
        Assert.Equal(TranslationHelper.Translation.RenameFile, "Datei umbenennen");
        Assert.Equal(TranslationHelper.Translation.Reset, "Zurücksetzen");
        Assert.Equal(TranslationHelper.Translation.ResetButtonText, "Auf Standard zurücksetzen");
        Assert.Equal(TranslationHelper.Translation.ResetZoom, "Zoom zurücksetzen");
        Assert.Equal(TranslationHelper.Translation.Resize, "Größe ändern");
        Assert.Equal(TranslationHelper.Translation.ResizeImage, "Bildgröße ändern");
        Assert.Equal(TranslationHelper.Translation.Resolution, "Auflösung");
        Assert.Equal(TranslationHelper.Translation.ResolutionUnit, "Auflösungseinheit");
        Assert.Equal(TranslationHelper.Translation.RestartApp, "Anwendung neu starten");
        Assert.Equal(TranslationHelper.Translation.RestoreDown, "Mini-/Maximieren");
        Assert.Equal(TranslationHelper.Translation.Reverse, "Umkehren");
        Assert.Equal(TranslationHelper.Translation.Right, "Rechts");
        Assert.Equal(TranslationHelper.Translation.Ripple, "Wellen");
        Assert.Equal(TranslationHelper.Translation.RippleAlt, "Wellen Alternative");
        Assert.Equal(TranslationHelper.Translation.RotateLeft, "Nach links drehen");
        Assert.Equal(TranslationHelper.Translation.RotateRight, "Nach rechts drehen");
        Assert.Equal(TranslationHelper.Translation.Rotated, "Gedreht");
        Assert.Equal(TranslationHelper.Translation.Saturation, "Sättigung");
        Assert.Equal(TranslationHelper.Translation.Save, "Speichern");
        Assert.Equal(TranslationHelper.Translation.SaveAs, "Speichern unter");
        Assert.Equal(TranslationHelper.Translation.SavingFileFailed, "Speichern der Datei fehlgeschlagen");
        Assert.Equal(TranslationHelper.Translation.ScrollAndRotate, "Scrollen und drehen");
        Assert.Equal(TranslationHelper.Translation.ScrollDirection, "Scrollrichtung");
        Assert.Equal(TranslationHelper.Translation.ScrollDown, "Nach unten scrollen");
        Assert.Equal(TranslationHelper.Translation.ScrollToBottom, "Zum Ende scrollen");
        Assert.Equal(TranslationHelper.Translation.ScrollToTop, "Zum Anfang scrollen");
        Assert.Equal(TranslationHelper.Translation.ScrollToZoom, "Mit Mausrad zoomen, mit Strg navigieren");
        Assert.Equal(TranslationHelper.Translation.ScrollUp, "Nach oben scrollen");
        Assert.Equal(TranslationHelper.Translation.Scrolling, "Scrollen");
        Assert.Equal(TranslationHelper.Translation.ScrollingDisabled, "Scrollen deaktiviert");
        Assert.Equal(TranslationHelper.Translation.ScrollingEnabled, "Scrollen aktiviert");
        Assert.Equal(TranslationHelper.Translation.SearchSubdirectory, "Unterverzeichnisse durchsuchen");
        Assert.Equal(TranslationHelper.Translation.SecAbbreviation, "Sek.");
        Assert.Equal(TranslationHelper.Translation.SelectAll, "Alle auswählen");
        Assert.Equal(TranslationHelper.Translation.SelectGalleryThumb, "Miniaturansicht der Galerie auswählen");
        Assert.Equal(TranslationHelper.Translation.SendCurrentImageToRecycleBin,
            "Aktives Bild in den Papierkorb verschieben");
        Assert.Equal(TranslationHelper.Translation.SentFileToRecycleBin, "Datei in den Papierkorb verschieben");
        Assert.Equal(TranslationHelper.Translation.SetAs, "Festlegen als...");
        Assert.Equal(TranslationHelper.Translation.SetAsLockScreenImage, "Als Sperrbildschirmbild festlegen");
        Assert.Equal(TranslationHelper.Translation.SetAsWallpaper, "Als Hintergrundbild festlegen");
        Assert.Equal(TranslationHelper.Translation.SetCurrentImageAsWallpaper,
            "Aktuelles Bild als Hintergrundbild festlegen:");
        Assert.Equal(TranslationHelper.Translation.SetStarRating, "Bewertung festlegen");
        Assert.Equal(TranslationHelper.Translation.Settings, "Einstellungen");
        Assert.Equal(TranslationHelper.Translation.Shade, "Schatten");
        Assert.Equal(TranslationHelper.Translation.Sharpness, "Schärfe");
        Assert.Equal(TranslationHelper.Translation.Shift, "Schicht");
        Assert.Equal(TranslationHelper.Translation.ShowAllSettingsWindow, "Alle Einstellungsfenster anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGallery, "Untere Galerie anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Untere Galerie anzeigen, wenn die Benutzeroberfläche ausgeblendet ist");
        Assert.Equal(TranslationHelper.Translation.ShowBottomToolbar, "Untere Symbolleiste anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowConfirmationOnEsc,
            "Bestätigungsdialog anzeigen, wenn 'Esc' gedrückt wird");
        Assert.Equal(TranslationHelper.Translation.ShowFadeInButtonsOnHover,
            "Fade-in-Schaltflächen bei Mauszeiger anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowFileSavingDialog, "Dateispeicherdialog anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowImageGallery, "Bildergalerie anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowImageInfo, "Bildinformationen anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowInFolder, "Im Ordner anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowInfoWindow, "Infofenster anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowResizeWindow, "Größenänderungsfenster anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShowUI, "Benutzeroberfläche anzeigen");
        Assert.Equal(TranslationHelper.Translation.ShutterPriority, "Verschlusspriorität");
        Assert.Equal(TranslationHelper.Translation.SideBySide, "Nebeneinander");
        Assert.Equal(TranslationHelper.Translation.SideBySideTooltip, "Bilder nebeneinander anzeigen");
        Assert.Equal(TranslationHelper.Translation.Size, "Größe");
        Assert.Equal(TranslationHelper.Translation.SizeMp, "Größe (mp)");
        Assert.Equal(TranslationHelper.Translation.SizeTooltip, "Gewünschte Größe in Pixel oder Prozent eingeben.");
        Assert.Equal(TranslationHelper.Translation.Sketch, "Skizzieren");
        Assert.Equal(TranslationHelper.Translation.Slideshow, "Diashow");
        Assert.Equal(TranslationHelper.Translation.SmoothMagnify, "Sanfte Vergrößerung");
        Assert.Equal(TranslationHelper.Translation.Soft, "Weich");
        Assert.Equal(TranslationHelper.Translation.Software, "Software");
        Assert.Equal(TranslationHelper.Translation.SortFilesBy, "Dateien sortieren nach");
        Assert.Equal(TranslationHelper.Translation.SourceFolder, "Quellordner");
        Assert.Equal(TranslationHelper.Translation.Space, "Platz");
        Assert.Equal(TranslationHelper.Translation.Square, "Quadrat");
        Assert.Equal(TranslationHelper.Translation.Start, "Start");
        Assert.Equal(TranslationHelper.Translation.StartSlideshow, "Diashow starten");
        Assert.Equal(TranslationHelper.Translation.StayCentered, "Fenster zentriert halten");
        Assert.Equal(TranslationHelper.Translation.StayTopMost, "Immer im Vordergrund");
        Assert.Equal(TranslationHelper.Translation.Stretch, "Strecken");
        Assert.Equal(TranslationHelper.Translation.StretchImage, "Bild strecken");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightDetected, "Blitzlicht erkannt");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightNotDetected, "Blitzlicht nicht erkannt");
        Assert.Equal(TranslationHelper.Translation.Subject, "Thema");
        Assert.Equal(TranslationHelper.Translation.Swirl, "Wirbel");
        Assert.Equal(TranslationHelper.Translation.TelescopicBlur, "Teleskopische Unschärfe");
        Assert.Equal(TranslationHelper.Translation.Theme, "Thema");
        Assert.Equal(TranslationHelper.Translation.Thumbnail, "Miniatur");
        Assert.Equal(TranslationHelper.Translation.Tile, "Kachel");
        Assert.Equal(TranslationHelper.Translation.Title, "Titel");
        Assert.Equal(TranslationHelper.Translation.ToggleBackgroundColor, "Hintergrundfarbe umschalten");
        Assert.Equal(TranslationHelper.Translation.ToggleFullscreen, "Vollbildmodus ein-/ausschalten");
        Assert.Equal(TranslationHelper.Translation.ToggleLooping, "Wiederholung ein-/ausschalten");
        Assert.Equal(TranslationHelper.Translation.ToggleScroll, "Scrollen umschalten");
        Assert.Equal(TranslationHelper.Translation.ToggleTaskbarProgress, "Fortschritt in der Taskleiste anzeigen");
        Assert.Equal(TranslationHelper.Translation.ToneMapping, "Tönungspfade");
        Assert.Equal(TranslationHelper.Translation.UnableToRender, "Bild kann nicht gerendert werden");
        Assert.Equal(TranslationHelper.Translation.Uncalibrated, "Nicht kalibriert");
        Assert.Equal(TranslationHelper.Translation.Underwater, "Unterwasser");
        Assert.Equal(TranslationHelper.Translation.UnexpectedError, "Es ist ein unbekannter Fehler aufgetreten");
        Assert.Equal(TranslationHelper.Translation.Unflip, "Umdrehen");
        Assert.Equal(TranslationHelper.Translation.Uniform, "Gleichmäßig");
        Assert.Equal(TranslationHelper.Translation.UniformToFill, "Gleichmäßig zum Füllen");
        Assert.Equal(TranslationHelper.Translation.Unknown, "Unbekannt");
        Assert.Equal(TranslationHelper.Translation.UnsupportedFile, "Nicht unterstützte Datei");
        Assert.Equal(TranslationHelper.Translation.Up, "Hoch");
        Assert.Equal(TranslationHelper.Translation.UsingMouse, "Verwende Maus");
        Assert.Equal(TranslationHelper.Translation.UsingTouchpad, "Verwende Touchpad");
        Assert.Equal(TranslationHelper.Translation.Version, "Version:");
        Assert.Equal(TranslationHelper.Translation.ViewLicenseFile, "Lizenzdatei ansehen");
        Assert.Equal(TranslationHelper.Translation.WaveWarper, "Wellenverzerrer");
        Assert.Equal(TranslationHelper.Translation.WhiteBalance, "Weißabgleich");
        Assert.Equal(TranslationHelper.Translation.WhiteFluorescent, "Weiß fluoreszierend");
        Assert.Equal(TranslationHelper.Translation.Width, "Breite");
        Assert.Equal(TranslationHelper.Translation.WidthAndHeight, "Breite und Höhe");
        Assert.Equal(TranslationHelper.Translation.WindowManagement, "Fensterverwaltung");
        Assert.Equal(TranslationHelper.Translation.WindowScaling, "Fensterskalierung");
        Assert.Equal(TranslationHelper.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationHelper.Translation.ZoomIn, "Vergrößern");
        Assert.Equal(TranslationHelper.Translation.ZoomOut, "Verkleinern");
        Assert.Equal(TranslationHelper.Translation._1Star, "1 Stern");
        Assert.Equal(TranslationHelper.Translation._2Star, "2 Sterne");
        Assert.Equal(TranslationHelper.Translation._3Star, "3 Sterne");
        Assert.Equal(TranslationHelper.Translation._4Star, "4 Sterne");
        Assert.Equal(TranslationHelper.Translation._5Star, "5 Sterne");
    }
}
