using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class ItalianUnitTest
{
#pragma warning disable xUnit2000
    public static async Task CheckItalianLanguage()
    {
        var exists = await TranslationHelper.LoadLanguage("it");
        Assert.True(exists);

        Assert.Equal(TranslationHelper.Translation.About, "Di");
        Assert.Equal(TranslationHelper.Translation.ActionProgram, "Programma d'azione");
        Assert.Equal(TranslationHelper.Translation.AddedToClipboard, "Aggiunto agli appunti");
        Assert.Equal(TranslationHelper.Translation.AdditionalFunctions, "Funzioni aggiuntive");
        Assert.Equal(TranslationHelper.Translation.AdjustNavSpeed,
            "Regola la velocità quando il tasto viene tenuto premuto");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForSlideshow, "Regola i tempi per la presentazione");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForZoom, "Regola la velocità del zoom");
        Assert.Equal(TranslationHelper.Translation.AdjustZoomLevel, "Regola il livello di zoom");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy100Images, "Avanza di 100 immagini");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy10Images, "Avanza di 10 immagini");
        Assert.Equal(TranslationHelper.Translation.AllowZoomOut,
            "Evitare lo zoom dell'immagine quando è già alla dimensione massima");
        Assert.Equal(TranslationHelper.Translation.Alt, "Alt");
        Assert.Equal(TranslationHelper.Translation.Altitude, "Altitudine");
        Assert.Equal(TranslationHelper.Translation.AperturePriority, "Priorità di apertura");
        Assert.Equal(TranslationHelper.Translation.Appearance, "Aspetto");
        Assert.Equal(TranslationHelper.Translation.ApplicationShortcuts, "Scorciatoie per le applicazioni");
        Assert.Equal(TranslationHelper.Translation.ApplicationStartup, "Avvio dell'applicazione");
        Assert.Equal(TranslationHelper.Translation.Apply, "Applicare");
        Assert.Equal(TranslationHelper.Translation.Applying, "processo in corso");
        Assert.Equal(TranslationHelper.Translation.Ascending, "Ascendente");
        Assert.Equal(TranslationHelper.Translation.AspectRatio, "Proporzioni");
        Assert.Equal(TranslationHelper.Translation.Authors, "Autori");
        Assert.Equal(TranslationHelper.Translation.Auto, "Auto");
        Assert.Equal(TranslationHelper.Translation.AutoFitWindow, "Adattamento automatico");
        Assert.Equal(TranslationHelper.Translation.BadArchive, "Impossibile elaborare l'archivio");
        Assert.Equal(TranslationHelper.Translation.BandedSwirl, "Turbinio fasciato");
        Assert.Equal(TranslationHelper.Translation.Bands, "Bande");
        Assert.Equal(TranslationHelper.Translation.Base64Image, "Immagine base64");
        Assert.Equal(TranslationHelper.Translation.BatchResize, "Batch ridimensiona");
        Assert.Equal(TranslationHelper.Translation.BitDepth, "Profondità di bit");
        Assert.Equal(TranslationHelper.Translation.BlackAndWhite, "Bianco e nero");
        Assert.Equal(TranslationHelper.Translation.Bloom, "Fioritura");
        Assert.Equal(TranslationHelper.Translation.Blur, "Blur");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryItemSize, "Elementi galleria inferiore");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryThumbnailStretch,
            "Estiramento miniature galleria inferiore");
        Assert.Equal(TranslationHelper.Translation.Brightness, "Luminosità");
        Assert.Equal(TranslationHelper.Translation.CameraMaker, "Produttore della fotocamera");
        Assert.Equal(TranslationHelper.Translation.CameraModel, "Modello della fotocamera");
        Assert.Equal(TranslationHelper.Translation.Cancel, "Annulla");
        Assert.Equal(TranslationHelper.Translation.Center, "Centrare");
        Assert.Equal(TranslationHelper.Translation.CenterWindow, "Centrare la finestra");
        Assert.Equal(TranslationHelper.Translation.Centimeters, "centimetri");
        Assert.Equal(TranslationHelper.Translation.ChangeBackground, "Cambia sfondo");
        Assert.Equal(TranslationHelper.Translation.ChangeBackgroundTooltip,
            "Cambia tra il colore di sfondo per le immagini con sfondo trasparente");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingText,
            "Clicca su una casella di testo per cambiare la combinazione di tasti. Premere Esc per annullare la combinazione di tasti.");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingTooltip,
            "Clicca per cambiare l'assegnazione del tasto");
        Assert.Equal(TranslationHelper.Translation.ChangingThemeRequiresRestart,
            "* Il cambio di tema richiede il riavvio");
        Assert.Equal(TranslationHelper.Translation.CheckForUpdates, "Controlla gli aggiornamenti");
        Assert.Equal(TranslationHelper.Translation.ClipboardImage, "Immagine negli appunti");
        Assert.Equal(TranslationHelper.Translation.Close, "Chiudere");
        Assert.Equal(TranslationHelper.Translation.CloseApp, "Chiudi l'intera applicazione");
        Assert.Equal(TranslationHelper.Translation.CloseGallery, "Chiudi la galleria");
        Assert.Equal(TranslationHelper.Translation.CloseWindowPrompt, "Vuoi chiudere la finestra?");
        Assert.Equal(TranslationHelper.Translation.CloudyWeather, "Tempo nuvoloso");
        Assert.Equal(TranslationHelper.Translation.ColorPickerTool, "Strumento di selezione del colore");
        Assert.Equal(TranslationHelper.Translation.ColorPickerToolTooltip, "Scegli il colore dall'immagine");
        Assert.Equal(TranslationHelper.Translation.ColorRepresentation, "Rappresentazione del colore");
        Assert.Equal(TranslationHelper.Translation.ColorTone, "Tonalità di colore");
        Assert.Equal(TranslationHelper.Translation.CompressedBitsPixel, "Bit per pixel compressi");
        Assert.Equal(TranslationHelper.Translation.Compression, "Compressione");
        Assert.Equal(TranslationHelper.Translation.Contrast, "Contrasto");
        Assert.Equal(TranslationHelper.Translation.ConvertTo, "Convertire in");
        Assert.Equal(TranslationHelper.Translation.ConvertedToBase64, "Convertito in base64");
        Assert.Equal(TranslationHelper.Translation.CoolWhiteFluorescent, "Fluorescente bianco freddo");
        Assert.Equal(TranslationHelper.Translation.CopiedImage, "Immagine copiata negli appunti");
        Assert.Equal(TranslationHelper.Translation.Copy, "Copia");
        Assert.Equal(TranslationHelper.Translation.CopyFile, "Copia il file");
        Assert.Equal(TranslationHelper.Translation.CopyImage, "Copia l'immagine");
        Assert.Equal(TranslationHelper.Translation.CopyImageTooltip, "Copia come immagine negli appunti di Windows");
        Assert.Equal(TranslationHelper.Translation.Copyright, "Diritti d'autore");
        Assert.Equal(TranslationHelper.Translation.Created, "Creato");
        Assert.Equal(TranslationHelper.Translation.CreationTime, "Tempo di creazione");
        Assert.Equal(TranslationHelper.Translation.CreativeProgram, "Programma creativo");
        Assert.Equal(TranslationHelper.Translation.Credits, "Attribuzioni");
        Assert.Equal(TranslationHelper.Translation.Crop, "Ritaglia");
        Assert.Equal(TranslationHelper.Translation.CropMessage, "Premi Esc per chiudere, Enter per salvare");
        Assert.Equal(TranslationHelper.Translation.CropPicture, "Ritaglia immagine");
        Assert.Equal(TranslationHelper.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationHelper.Translation.CtrlToZoom, "Ctrl per ingrandire, scorri per navigare");
        Assert.Equal(TranslationHelper.Translation.Cut, "Couper");
        Assert.Equal(TranslationHelper.Translation.DarkTheme, "Tema scuro");
        Assert.Equal(TranslationHelper.Translation.Date, "Data");
        Assert.Equal(TranslationHelper.Translation.DateTaken, "Data di scatto");
        Assert.Equal(TranslationHelper.Translation.DayWhiteFluorescent, "Fluorescente bianco diurno");
        Assert.Equal(TranslationHelper.Translation.Daylight, "Luce diurna");
        Assert.Equal(TranslationHelper.Translation.DaylightFluorescent, "Fluorescente diurna");
        Assert.Equal(TranslationHelper.Translation.Del, "Canc");
        Assert.Equal(TranslationHelper.Translation.DeleteFile, "Cancella il file");
        Assert.Equal(TranslationHelper.Translation.DeleteFilePermanently,
            "Sei sicuro di voler eliminare definitivamente?");
        Assert.Equal(TranslationHelper.Translation.DeletedFile, "File cancellato");
        Assert.Equal(TranslationHelper.Translation.Descending, "Discendente");
        Assert.Equal(TranslationHelper.Translation.DigitalZoom, "Zoom digitale");
        Assert.Equal(TranslationHelper.Translation.DirectionalBlur, "Sfocatura direzionale");
        Assert.Equal(TranslationHelper.Translation.DisableFadeInButtonsOnHover,
            "Disabilita pulsanti in dissolvenza al passaggio del mouse");
        Assert.Equal(TranslationHelper.Translation.DiskSize, "Dimensione del disco");
        Assert.Equal(TranslationHelper.Translation.DoubleClick, "Doppio clic");
        Assert.Equal(TranslationHelper.Translation.Down, "Giù");
        Assert.Equal(TranslationHelper.Translation.Dpi, "DPI");
        Assert.Equal(TranslationHelper.Translation.DragFileTo,
            "Trascina il file nel Esploratore di Windows o in un'altra applicazione/browser");
        Assert.Equal(TranslationHelper.Translation.DragImage, "Trascina l'immagine");
        Assert.Equal(TranslationHelper.Translation.DropToLoad, "Rilascia l'immagine di caricamento");
        Assert.Equal(TranslationHelper.Translation.DuplicateFile, "Duplica file");
        Assert.Equal(TranslationHelper.Translation.Effects, "Effetti Shader");
        Assert.Equal(TranslationHelper.Translation.EffectsTooltip, "Mostra finestra effetti immagine");
        Assert.Equal(TranslationHelper.Translation.Embossed, "Rilievo");
        Assert.Equal(TranslationHelper.Translation.Enter, "Enter");
        Assert.Equal(TranslationHelper.Translation.Esc, "Esc");
        Assert.Equal(TranslationHelper.Translation.EscCloseTooltip, "Chiudi la finestra/menu attualmente aperti");
        Assert.Equal(TranslationHelper.Translation.ExifVersion, "Versione Exif");
        Assert.Equal(TranslationHelper.Translation.ExpandedGalleryItemSize, "Elementi galleria espansa");
        Assert.Equal(TranslationHelper.Translation.ExposureBias, "Esposizione Bias");
        Assert.Equal(TranslationHelper.Translation.ExposureProgram, "Programma di esposizione");
        Assert.Equal(TranslationHelper.Translation.ExposureTime, "Tempo di esposizione");
        Assert.Equal(TranslationHelper.Translation.FNumber, "Numero F");
        Assert.Equal(TranslationHelper.Translation.File, "File");
        Assert.Equal(TranslationHelper.Translation.FileCopy, "File aggiunto agli appunti");
        Assert.Equal(TranslationHelper.Translation.FileCopyPath, "Copia il percorso del file");
        Assert.Equal(TranslationHelper.Translation.FileCopyPathMessage, "Percorso del file aggiunto agli appunti");
        Assert.Equal(TranslationHelper.Translation.FileCutMessage,
            "Percorso del file aggiunto per spostare gli appunti");
        Assert.Equal(TranslationHelper.Translation.FileExtension, "Estensione del file");
        Assert.Equal(TranslationHelper.Translation.FileManagement, "Gestione dei file");
        Assert.Equal(TranslationHelper.Translation.FileName, "Nome del file");
        Assert.Equal(TranslationHelper.Translation.FilePaste, "Incolla");
        Assert.Equal(TranslationHelper.Translation.FileProperties, "Proprietà del file");
        Assert.Equal(TranslationHelper.Translation.FileSize, "Dimensione del file");
        Assert.Equal(TranslationHelper.Translation.Files, "File");
        Assert.Equal(TranslationHelper.Translation.Fill, "Riempire");
        Assert.Equal(TranslationHelper.Translation.FillHeight, "Estendere in altezza");
        Assert.Equal(TranslationHelper.Translation.FillSquare, "RiempireQuadrato");
        Assert.Equal(TranslationHelper.Translation.FineWeather, "Bel tempo");
        Assert.Equal(TranslationHelper.Translation.FirstImage, "Prima immagine");
        Assert.Equal(TranslationHelper.Translation.Fit, "Adattare");
        Assert.Equal(TranslationHelper.Translation.FitToWindow, "Adatta alla finestra/immagine");
        Assert.Equal(TranslationHelper.Translation.Flash, "Flash");
        Assert.Equal(TranslationHelper.Translation.FlashDidNotFire, "Flash non scattato");
        Assert.Equal(TranslationHelper.Translation.FlashEnergy, "Energia del flash");
        Assert.Equal(TranslationHelper.Translation.FlashFired, "Flash scattato");
        Assert.Equal(TranslationHelper.Translation.FlashMode, "Modalità flash");
        Assert.Equal(TranslationHelper.Translation.Flip, "Capovolgi orizzontalmente");
        Assert.Equal(TranslationHelper.Translation.Flipped, "Capovolto");
        Assert.Equal(TranslationHelper.Translation.Fluorescent, "Fluorescente");
        Assert.Equal(TranslationHelper.Translation.FocalLength, "Lunghezza focale");
        Assert.Equal(TranslationHelper.Translation.FocalLength35mm, "Lunghezza focale 35mm");
        Assert.Equal(TranslationHelper.Translation.Folder, "Cartella");
        Assert.Equal(TranslationHelper.Translation.Forward, "Inoltrare");
        Assert.Equal(TranslationHelper.Translation.FrostyOutline, "Contorno gelido");
        Assert.Equal(TranslationHelper.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationHelper.Translation.FullPath, "Percorso completo");
        Assert.Equal(TranslationHelper.Translation.Fullscreen, "A schermo intero");
        Assert.Equal(TranslationHelper.Translation.GallerySettings, "Impostazioni della galleria");
        Assert.Equal(TranslationHelper.Translation.GalleryThumbnailStretch,
            "Estensione della miniatura della galleria");
        Assert.Equal(TranslationHelper.Translation.GeneralSettings, "Impostazioni generali");
        Assert.Equal(TranslationHelper.Translation.GenerateThumbnails, "Genera le miniature");
        Assert.Equal(TranslationHelper.Translation.GithubRepo, "Repository Github");
        Assert.Equal(TranslationHelper.Translation.GlassTheme, "Tema di vetro");
        Assert.Equal(TranslationHelper.Translation.GlassTile, "Piastrella di vetro");
        Assert.Equal(TranslationHelper.Translation.Gloom, "BuioGloom");
        Assert.Equal(TranslationHelper.Translation.GoBackBy100Images, "Torna indietro di 100 immagini");
        Assert.Equal(TranslationHelper.Translation.GoBackBy10Images, "Torna indietro di 10 immagini");
        Assert.Equal(TranslationHelper.Translation.GoToImageAtSpecifiedIndex,
            "Vai all'immagine all'indice specificato");
        Assert.Equal(TranslationHelper.Translation.Hard, "Duro");
        Assert.Equal(TranslationHelper.Translation.Height, "Altezza");
        Assert.Equal(TranslationHelper.Translation.HideBottomGallery, "Nascondi galleria inferiore");
        Assert.Equal(TranslationHelper.Translation.HideBottomToolbar, "Masquer la barre d'outils inférieure");
        Assert.Equal(TranslationHelper.Translation.HideUI, "Nascondi interfaccia");
        Assert.Equal(TranslationHelper.Translation.High, "Alto");
        Assert.Equal(TranslationHelper.Translation.HighQuality, "Alta qualità");
        Assert.Equal(TranslationHelper.Translation.HighlightColor, "Evidenzia colore");
        Assert.Equal(TranslationHelper.Translation.ISOSpeed, "Velocità ISO");
        Assert.Equal(TranslationHelper.Translation.IconsUsed, "Icone utilizzate:");
        Assert.Equal(TranslationHelper.Translation.Image, "Immagine");
        Assert.Equal(TranslationHelper.Translation.ImageAliasing, "Alias delle immagini");
        Assert.Equal(TranslationHelper.Translation.ImageControl, "Controllo dell'immagine");
        Assert.Equal(TranslationHelper.Translation.ImageInfo, "Informazioni sull'immagine");
        Assert.Equal(TranslationHelper.Translation.Inches, "pollici");
        Assert.Equal(TranslationHelper.Translation.InfoWindow, "Finestra informativa");
        Assert.Equal(TranslationHelper.Translation.InfoWindowTitle, "Informazioni e scorciatoie");
        Assert.Equal(TranslationHelper.Translation.InterfaceConfiguration, "Interfaccia di configurazione");
        Assert.Equal(TranslationHelper.Translation.Landscape, "Paesaggio");
        Assert.Equal(TranslationHelper.Translation.Language, "Linguaggio");
        Assert.Equal(TranslationHelper.Translation.LastAccessTime, "Ora dell'ultimo accesso");
        Assert.Equal(TranslationHelper.Translation.LastImage, "Ultima immagine");
        Assert.Equal(TranslationHelper.Translation.LastWriteTime, "ora dell'ultima scrittura");
        Assert.Equal(TranslationHelper.Translation.Latitude, "Latitudine");
        Assert.Equal(TranslationHelper.Translation.Left, "Sinistra");
        Assert.Equal(TranslationHelper.Translation.LensMaker, "Produttore della lente");
        Assert.Equal(TranslationHelper.Translation.LensModel, "Modello di lente");
        Assert.Equal(TranslationHelper.Translation.LightSource, "Sorgente luminosa");
        Assert.Equal(TranslationHelper.Translation.LightTheme, "Tema chiaro");
        Assert.Equal(TranslationHelper.Translation.Lighting, "Illuminazione");
        Assert.Equal(TranslationHelper.Translation.Loading, "Caricamento in corso...");
        Assert.Equal(TranslationHelper.Translation.Longitude, "Longitudine");
        Assert.Equal(TranslationHelper.Translation.Looping, "Ciclo");
        Assert.Equal(TranslationHelper.Translation.LoopingDisabled, "Ciclo disabilitato");
        Assert.Equal(TranslationHelper.Translation.LoopingEnabled, "Ciclo abilitato");
        Assert.Equal(TranslationHelper.Translation.Lossless, "Senza perdita");
        Assert.Equal(TranslationHelper.Translation.Lossy, "Con perdita");
        Assert.Equal(TranslationHelper.Translation.Low, "Basso");
        Assert.Equal(TranslationHelper.Translation.Manual, "Manuale");
        Assert.Equal(TranslationHelper.Translation.MaxAperture, "Apertura massima");
        Assert.Equal(TranslationHelper.Translation.Maximize, "Massimizzare");
        Assert.Equal(TranslationHelper.Translation.MegaPixels, "Megapixel");
        Assert.Equal(TranslationHelper.Translation.Meter, "Metro");
        Assert.Equal(TranslationHelper.Translation.MeteringMode, "Modalità di misurazione");
        Assert.Equal(TranslationHelper.Translation.Minimize, "Minimizzare");
        Assert.Equal(TranslationHelper.Translation.MiscSettings, "Impostazioni varie");
        Assert.Equal(TranslationHelper.Translation.Modified, "Modificato");
        Assert.Equal(TranslationHelper.Translation.Monochrome, "Monocroma");
        Assert.Equal(TranslationHelper.Translation.MouseDrag, "Trascinamento del mouse");
        Assert.Equal(TranslationHelper.Translation.MouseKeyBack, "Tasto mouse indietro");
        Assert.Equal(TranslationHelper.Translation.MouseKeyForward, "Tasto mouse in avanti");
        Assert.Equal(TranslationHelper.Translation.MouseWheel, "Rotellina del mouse");
        Assert.Equal(TranslationHelper.Translation.MoveWindow, "Sposta la finestra");
        Assert.Equal(TranslationHelper.Translation.Navigation, "Navigazione");
        Assert.Equal(TranslationHelper.Translation.NearestNeighbor, "Vicino più prossimo");
        Assert.Equal(TranslationHelper.Translation.NegativeColors, "Colori negativi");
        Assert.Equal(TranslationHelper.Translation.NewWindow, "Nuova finestra");
        Assert.Equal(TranslationHelper.Translation.NextFolder, "Passa alla cartella successiva");
        Assert.Equal(TranslationHelper.Translation.NextImage, "Immagine successiva");
        Assert.Equal(TranslationHelper.Translation.NoChange, "Nessuna modifica");
        Assert.Equal(TranslationHelper.Translation.NoConversion, "Nessuna conversione");
        Assert.Equal(TranslationHelper.Translation.NoImage, "Nessuna immagine caricata");
        Assert.Equal(TranslationHelper.Translation.NoImages, "Nessuna immagine");
        Assert.Equal(TranslationHelper.Translation.NoResize, "No resize");
        Assert.Equal(TranslationHelper.Translation.None, "Nessuno");
        Assert.Equal(TranslationHelper.Translation.Normal, "Normale");
        Assert.Equal(TranslationHelper.Translation.NormalWindow, "Finestra normale");
        Assert.Equal(TranslationHelper.Translation.NotDefined, "Non definito");
        Assert.Equal(TranslationHelper.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationHelper.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationHelper.Translation.OldMovie, "Vecchio film");
        Assert.Equal(TranslationHelper.Translation.Open, "Aprire");
        Assert.Equal(TranslationHelper.Translation.OpenFileDialog, "Seleziona un file");
        Assert.Equal(TranslationHelper.Translation.OpenInSameWindow, "Apri i file nella stessa finestra");
        Assert.Equal(TranslationHelper.Translation.OpenLastFile, "Apri l'ultimo file");
        Assert.Equal(TranslationHelper.Translation.OpenWith, "Aprire con...");
        Assert.Equal(TranslationHelper.Translation.OptimizeImage, "Ottimizza immagine");
        Assert.Equal(TranslationHelper.Translation.Orientation, "Orientamento");
        Assert.Equal(TranslationHelper.Translation.OutputFolder, "Cartella di uscita");
        Assert.Equal(TranslationHelper.Translation.Pan, "Fare una panoramica");
        Assert.Equal(TranslationHelper.Translation.PaperFold, "Pieghevole");
        Assert.Equal(TranslationHelper.Translation.PasswordArchive, "Archivio protetto da password non supportato");
        Assert.Equal(TranslationHelper.Translation.PasteImageFromClipholder, "Incolla l'immagine dagli appunti");
        Assert.Equal(TranslationHelper.Translation.PencilSketch, "Schizzo a matita");
        Assert.Equal(TranslationHelper.Translation.PercentComplete, "% completo...");
        Assert.Equal(TranslationHelper.Translation.Percentage, "Percentuale");
        Assert.Equal(TranslationHelper.Translation.PermanentlyDelete, "Elimina definitivamente");
        Assert.Equal(TranslationHelper.Translation.PhotometricInterpretation, "Interpretazione fotometrica");
        Assert.Equal(TranslationHelper.Translation.Pivot, "Volto");
        Assert.Equal(TranslationHelper.Translation.Pixelate, "Pixelare");
        Assert.Equal(TranslationHelper.Translation.Pixels, "Pixel");
        Assert.Equal(TranslationHelper.Translation.Portrait, "Ritratto");
        Assert.Equal(TranslationHelper.Translation.PressKey, "Premi il tasto...");
        Assert.Equal(TranslationHelper.Translation.PrevFolder, "Torna alla cartella precedente");
        Assert.Equal(TranslationHelper.Translation.PrevImage, "Immagine precedente");
        Assert.Equal(TranslationHelper.Translation.Print, "Stampa");
        Assert.Equal(TranslationHelper.Translation.PrintSizeCm, "Dimensioni di stampa (cm)");
        Assert.Equal(TranslationHelper.Translation.PrintSizeIn, "Dimensioni di stampa (in)");
        Assert.Equal(TranslationHelper.Translation.Quality, "Qualità");
        Assert.Equal(TranslationHelper.Translation.Random, "Casuale");
        Assert.Equal(TranslationHelper.Translation.RecentFiles, "File recenti");
        Assert.Equal(TranslationHelper.Translation.RedEyeReduction, "Riduzione occhi rossi");
        Assert.Equal(TranslationHelper.Translation.Reload, "Ricaricare");
        Assert.Equal(TranslationHelper.Translation.RemoveStarRating, "Rimuovi il rating");
        Assert.Equal(TranslationHelper.Translation.RenameFile, "Rinomina il file");
        Assert.Equal(TranslationHelper.Translation.Reset, "Reimposta");
        Assert.Equal(TranslationHelper.Translation.ResetButtonText, "Reimposta alle impostazioni predefinite");
        Assert.Equal(TranslationHelper.Translation.ResetZoom, "Ripristina lo zoom");
        Assert.Equal(TranslationHelper.Translation.Resize, "Ridimensionamento");
        Assert.Equal(TranslationHelper.Translation.ResizeImage, "Ridimensiona l'immagine");
        Assert.Equal(TranslationHelper.Translation.Resolution, "Risoluzione");
        Assert.Equal(TranslationHelper.Translation.ResolutionUnit, "Unità di risoluzione");
        Assert.Equal(TranslationHelper.Translation.RestartApp, "Riavvia l'applicazione");
        Assert.Equal(TranslationHelper.Translation.RestoreDown, "Ripristina giù");
        Assert.Equal(TranslationHelper.Translation.Reverse, "Inversione");
        Assert.Equal(TranslationHelper.Translation.Right, "Destra");
        Assert.Equal(TranslationHelper.Translation.Ripple, "Ondulazione");
        Assert.Equal(TranslationHelper.Translation.RippleAlt, "Ondulazione Alt");
        Assert.Equal(TranslationHelper.Translation.RotateLeft, "Ruota a sinistra");
        Assert.Equal(TranslationHelper.Translation.RotateRight, "Ruota a destra");
        Assert.Equal(TranslationHelper.Translation.Rotated, "Ruotato");
        Assert.Equal(TranslationHelper.Translation.Saturation, "Saturazione");
        Assert.Equal(TranslationHelper.Translation.Save, "Salva");
        Assert.Equal(TranslationHelper.Translation.SaveAs, "Salva come");
        Assert.Equal(TranslationHelper.Translation.SavingFileFailed, "Salvataggio del file fallito");
        Assert.Equal(TranslationHelper.Translation.ScrollAndRotate, "Scorrere e ruotare");
        Assert.Equal(TranslationHelper.Translation.ScrollDirection, "Direzione dello scorrimento");
        Assert.Equal(TranslationHelper.Translation.ScrollDown, "Scorri verso il basso");
        Assert.Equal(TranslationHelper.Translation.ScrollToBottom, "Scorri in basso");
        Assert.Equal(TranslationHelper.Translation.ScrollToTop, "Scorri in alto");
        Assert.Equal(TranslationHelper.Translation.ScrollToZoom, "Scorri per ingrandire, Ctrl per navigare");
        Assert.Equal(TranslationHelper.Translation.ScrollUp, "Scorri verso l'alto");
        Assert.Equal(TranslationHelper.Translation.Scrolling, "Scorrimento");
        Assert.Equal(TranslationHelper.Translation.ScrollingDisabled, "Scorrimento disabilitato");
        Assert.Equal(TranslationHelper.Translation.ScrollingEnabled, "Scorrimento abilitato");
        Assert.Equal(TranslationHelper.Translation.SearchSubdirectory, "Cerca sottodirectory");
        Assert.Equal(TranslationHelper.Translation.SecAbbreviation, "Sec.");
        Assert.Equal(TranslationHelper.Translation.SelectAll, "Seleziona tutto");
        Assert.Equal(TranslationHelper.Translation.SelectGalleryThumb, "Seleziona la miniatura della galleria");
        Assert.Equal(TranslationHelper.Translation.SendCurrentImageToRecycleBin,
            "Invia l'immagine corrente al cestino");
        Assert.Equal(TranslationHelper.Translation.SentFileToRecycleBin, "File inviato al cestino");
        Assert.Equal(TranslationHelper.Translation.SetAs, "Impostato come...");
        Assert.Equal(TranslationHelper.Translation.SetAsLockScreenImage,
            "Imposta come immagine della schermata di blocco");
        Assert.Equal(TranslationHelper.Translation.SetAsWallpaper, "Imposta come sfondo");
        Assert.Equal(TranslationHelper.Translation.SetCurrentImageAsWallpaper,
            "Imposta l'immagine corrente come sfondo:");
        Assert.Equal(TranslationHelper.Translation.SetStarRating, "Imposta il rating con le stelle");
        Assert.Equal(TranslationHelper.Translation.Settings, "Impostazioni");
        Assert.Equal(TranslationHelper.Translation.Shade, "Ombra");
        Assert.Equal(TranslationHelper.Translation.Sharpness, "Nitidezza");
        Assert.Equal(TranslationHelper.Translation.Shift, "Shift");
        Assert.Equal(TranslationHelper.Translation.ShowAllSettingsWindow,
            "Mostra la finestra di tutte le impostazioni");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGallery, "Mostra galleria inferiore");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Mostra galleria inferiore quando l'interfaccia utente è nascosta");
        Assert.Equal(TranslationHelper.Translation.ShowBottomToolbar, "Mostra la barra degli strumenti inferiore");
        Assert.Equal(TranslationHelper.Translation.ShowConfirmationOnEsc,
            "Mostra la finestra di conferma quando premi 'Esc'");
        Assert.Equal(TranslationHelper.Translation.ShowFadeInButtonsOnHover,
            "Mostra pulsanti in dissolvenza al passaggio del mouse");
        Assert.Equal(TranslationHelper.Translation.ShowFileSavingDialog, "Mostra finestra di salvataggio file");
        Assert.Equal(TranslationHelper.Translation.ShowImageGallery, "Mostra galleria immagini");
        Assert.Equal(TranslationHelper.Translation.ShowImageInfo, "Mostra informazioni sull'immagine");
        Assert.Equal(TranslationHelper.Translation.ShowInFolder, "Mostra nella cartella");
        Assert.Equal(TranslationHelper.Translation.ShowInfoWindow, "Mostra finestra informativa");
        Assert.Equal(TranslationHelper.Translation.ShowResizeWindow, "Mostra la finestra Ridimensiona");
        Assert.Equal(TranslationHelper.Translation.ShowUI, "Mostra interfaccia");
        Assert.Equal(TranslationHelper.Translation.ShutterPriority, "Priorità dell'otturatore");
        Assert.Equal(TranslationHelper.Translation.SideBySide, "Fianco a fianco");
        Assert.Equal(TranslationHelper.Translation.SideBySideTooltip, "Mostra le immagini affiancate");
        Assert.Equal(TranslationHelper.Translation.Size, "Dimensione");
        Assert.Equal(TranslationHelper.Translation.SizeMp, "Dimensione (mp)");
        Assert.Equal(TranslationHelper.Translation.SizeTooltip,
            "Inserisci la dimensione desiderata in pixel o in percentuale.");
        Assert.Equal(TranslationHelper.Translation.Sketch, "Schizzo");
        Assert.Equal(TranslationHelper.Translation.Slideshow, "Presentazione");
        Assert.Equal(TranslationHelper.Translation.SmoothMagnify, "Ingrandimento uniforme");
        Assert.Equal(TranslationHelper.Translation.Soft, "Morbido");
        Assert.Equal(TranslationHelper.Translation.Software, "Software");
        Assert.Equal(TranslationHelper.Translation.SortFilesBy, "Ordina file per");
        Assert.Equal(TranslationHelper.Translation.SourceFolder, "Cartella di origine");
        Assert.Equal(TranslationHelper.Translation.Space, "Space");
        Assert.Equal(TranslationHelper.Translation.Square, "Quadrato");
        Assert.Equal(TranslationHelper.Translation.Start, "Inizio");
        Assert.Equal(TranslationHelper.Translation.StartSlideshow, "Avvia presentazione");
        Assert.Equal(TranslationHelper.Translation.StayCentered, "Mantieni la finestra centrata");
        Assert.Equal(TranslationHelper.Translation.StayTopMost, "Rimani in cima alle altre finestre");
        Assert.Equal(TranslationHelper.Translation.Stretch, "Allungare");
        Assert.Equal(TranslationHelper.Translation.StretchImage, "Estendi immagine");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightDetected, "Luce di ritorno dello strobo rilevata");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightNotDetected,
            "Luce di ritorno dello strobo non rilevata");
        Assert.Equal(TranslationHelper.Translation.Subject, "Soggetto");
        Assert.Equal(TranslationHelper.Translation.Swirl, "Turbinio");
        Assert.Equal(TranslationHelper.Translation.TelescopicBlur, "Sfocatura telescopica");
        Assert.Equal(TranslationHelper.Translation.Theme, "Tema");
        Assert.Equal(TranslationHelper.Translation.Thumbnail, "Miniature");
        Assert.Equal(TranslationHelper.Translation.Tile, "Piastrellare");
        Assert.Equal(TranslationHelper.Translation.Title, "Titolo");
        Assert.Equal(TranslationHelper.Translation.ToggleBackgroundColor, "Cambia colore di sfondo");
        Assert.Equal(TranslationHelper.Translation.ToggleFullscreen, "Passare a schermo intero");
        Assert.Equal(TranslationHelper.Translation.ToggleLooping, "Alternare il ciclo");
        Assert.Equal(TranslationHelper.Translation.ToggleScroll, "Attiva/disattiva scorrimento");
        Assert.Equal(TranslationHelper.Translation.ToggleTaskbarProgress,
            "Mostra progresso sulla barra delle applicazioni");
        Assert.Equal(TranslationHelper.Translation.ToneMapping, "Mappatura dei toni");
        Assert.Equal(TranslationHelper.Translation.UnableToRender, "Impossibile renderizzare l'immagine");
        Assert.Equal(TranslationHelper.Translation.Uncalibrated, "Non calibrato");
        Assert.Equal(TranslationHelper.Translation.Underwater, "Sott'acqua");
        Assert.Equal(TranslationHelper.Translation.UnexpectedError, "Si è verificato un errore sconosciuto");
        Assert.Equal(TranslationHelper.Translation.Unflip, "Srotolare");
        Assert.Equal(TranslationHelper.Translation.Uniform, "Uniforme");
        Assert.Equal(TranslationHelper.Translation.UniformToFill, "UniformePerRiempire");
        Assert.Equal(TranslationHelper.Translation.Unknown, "Sconosciuto");
        Assert.Equal(TranslationHelper.Translation.UnsupportedFile, "File non supportato");
        Assert.Equal(TranslationHelper.Translation.Up, "Su");
        Assert.Equal(TranslationHelper.Translation.UsingMouse, "Utilizzare il mouse");
        Assert.Equal(TranslationHelper.Translation.UsingTouchpad, "Utilizzare il touchpad");
        Assert.Equal(TranslationHelper.Translation.Version, "Versione:");
        Assert.Equal(TranslationHelper.Translation.ViewLicenseFile, "Visualizza file di licenza");
        Assert.Equal(TranslationHelper.Translation.WaveWarper, "onda deformante");
        Assert.Equal(TranslationHelper.Translation.WhiteBalance, "Bilanciamento del bianco");
        Assert.Equal(TranslationHelper.Translation.WhiteFluorescent, "Fluorescente bianco");
        Assert.Equal(TranslationHelper.Translation.Width, "Larghezza");
        Assert.Equal(TranslationHelper.Translation.WidthAndHeight, "Larghezza e altezza");
        Assert.Equal(TranslationHelper.Translation.WindowManagement, "Gestione delle finestre");
        Assert.Equal(TranslationHelper.Translation.WindowScaling, "Ridimensionamento della finestra");
        Assert.Equal(TranslationHelper.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationHelper.Translation.ZoomIn, "Ingrandire");
        Assert.Equal(TranslationHelper.Translation.ZoomOut, "Rimpicciolisci");
        Assert.Equal(TranslationHelper.Translation._1Star, "Rating a 1 stella");
        Assert.Equal(TranslationHelper.Translation._2Star, "Rating a 2 stella");
        Assert.Equal(TranslationHelper.Translation._3Star, "Rating a 3 stella");
        Assert.Equal(TranslationHelper.Translation._4Star, "Rating a 4 stella");
        Assert.Equal(TranslationHelper.Translation._5Star, "Rating a 5 stella");
    }
}