using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class ItalianUnitTest
{
#pragma warning disable xUnit2000
    public static async Task CheckItalianLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("it");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "Di");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Programma d'azione");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Aggiunto agli appunti");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Funzioni aggiuntive");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed,
            "Regola la velocità quando il tasto viene tenuto premuto");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Regola i tempi per la presentazione");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Regola la velocità del zoom");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Regola il livello di zoom");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Avanza di 100 immagini");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Avanza di 10 immagini");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Evitare lo zoom dell'immagine quando è già alla dimensione massima");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Altitudine");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Priorità di apertura");
        Assert.Equal(TranslationManager.Translation.Appearance, "Aspetto");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Scorciatoie per le applicazioni");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Avvio dell'applicazione");
        Assert.Equal(TranslationManager.Translation.Apply, "Applicare");
        Assert.Equal(TranslationManager.Translation.Applying, "processo in corso");
        Assert.Equal(TranslationManager.Translation.Ascending, "Ascendente");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Proporzioni");
        Assert.Equal(TranslationManager.Translation.Authors, "Autori");
        Assert.Equal(TranslationManager.Translation.Auto, "Auto");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Adattamento automatico");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Impossibile elaborare l'archivio");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Immagine base64");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Batch ridimensiona");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Profondità di bit");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Bianco e nero");
        Assert.Equal(TranslationManager.Translation.Blur, "Blur");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Elementi galleria inferiore");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Estiramento miniature galleria inferiore");
        Assert.Equal(TranslationManager.Translation.Brightness, "Luminosità");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Produttore della fotocamera");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Modello della fotocamera");
        Assert.Equal(TranslationManager.Translation.Cancel, "Annulla");
        Assert.Equal(TranslationManager.Translation.Center, "Centrare");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Centrare la finestra");
        Assert.Equal(TranslationManager.Translation.Centimeters, "centimetri");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Cambia sfondo");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Cambia tra il colore di sfondo per le immagini con sfondo trasparente");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Clicca su una casella di testo per cambiare la combinazione di tasti. Premere Esc per annullare la combinazione di tasti.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip,
            "Clicca per cambiare l'assegnazione del tasto");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart,
            "* Il cambio di tema richiede il riavvio");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Controlla gli aggiornamenti");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Immagine negli appunti");
        Assert.Equal(TranslationManager.Translation.Close, "Chiudere");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Chiudi l'intera applicazione");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Chiudi la galleria");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Vuoi chiudere la finestra?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Tempo nuvoloso");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Strumento di selezione del colore");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Scegli il colore dall'immagine");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Rappresentazione del colore");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Tonalità di colore");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Bit per pixel compressi");
        Assert.Equal(TranslationManager.Translation.Compression, "Compressione");
        Assert.Equal(TranslationManager.Translation.Contrast, "Contrasto");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Convertire in");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Convertito in base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Fluorescente bianco freddo");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Immagine copiata negli appunti");
        Assert.Equal(TranslationManager.Translation.Copy, "Copia");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Copia il file");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Copia l'immagine");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Copia come immagine negli appunti di Windows");
        Assert.Equal(TranslationManager.Translation.Copyright, "Diritti d'autore");
        Assert.Equal(TranslationManager.Translation.Created, "Creato");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Tempo di creazione");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Programma creativo");
        Assert.Equal(TranslationManager.Translation.Credits, "Attribuzioni");
        Assert.Equal(TranslationManager.Translation.Crop, "Ritaglia");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Premi Esc per chiudere, Enter per salvare");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Ritaglia immagine");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Ctrl per ingrandire, scorri per navigare");
        Assert.Equal(TranslationManager.Translation.Cut, "Couper");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Tema scuro");
        Assert.Equal(TranslationManager.Translation.Date, "Data");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Data di scatto");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Fluorescente bianco diurno");
        Assert.Equal(TranslationManager.Translation.Daylight, "Luce diurna");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Fluorescente diurna");
        Assert.Equal(TranslationManager.Translation.Del, "Canc");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Cancella il file");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "Sei sicuro di voler eliminare definitivamente?");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "File cancellato");
        Assert.Equal(TranslationManager.Translation.Descending, "Discendente");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Zoom digitale");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Disabilita pulsanti in dissolvenza al passaggio del mouse");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Dimensione del disco");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Doppio clic");
        Assert.Equal(TranslationManager.Translation.Down, "Giù");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Trascina il file nel Esploratore di Windows o in un'altra applicazione/browser");
        Assert.Equal(TranslationManager.Translation.DragImage, "Trascina l'immagine");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Rilascia l'immagine di caricamento");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Duplica file");
        Assert.Equal(TranslationManager.Translation.Effects, "Effetti Shader");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Mostra finestra effetti immagine");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Chiudi la finestra/menu attualmente aperti");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Versione Exif");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Elementi galleria espansa");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Esposizione Bias");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Programma di esposizione");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Tempo di esposizione");
        Assert.Equal(TranslationManager.Translation.FNumber, "Numero F");
        Assert.Equal(TranslationManager.Translation.File, "File");
        Assert.Equal(TranslationManager.Translation.FileCopy, "File aggiunto agli appunti");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Copia il percorso del file");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Percorso del file aggiunto agli appunti");
        Assert.Equal(TranslationManager.Translation.FileCutMessage,
            "Percorso del file aggiunto per spostare gli appunti");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Estensione del file");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Gestione dei file");
        Assert.Equal(TranslationManager.Translation.FileName, "Nome del file");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Incolla");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Proprietà del file");
        Assert.Equal(TranslationManager.Translation.FileSize, "Dimensione del file");
        Assert.Equal(TranslationManager.Translation.Files, "File");
        Assert.Equal(TranslationManager.Translation.Fill, "Riempire");
        Assert.Equal(TranslationManager.Translation.FillHeight, "Estendere in altezza");
        Assert.Equal(TranslationManager.Translation.FillSquare, "RiempireQuadrato");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Bel tempo");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Prima immagine");
        Assert.Equal(TranslationManager.Translation.Fit, "Adattare");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Adatta alla finestra/immagine");
        Assert.Equal(TranslationManager.Translation.Flash, "Flash");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Flash non scattato");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Energia del flash");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Flash scattato");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Modalità flash");
        Assert.Equal(TranslationManager.Translation.Flip, "Capovolgi orizzontalmente");
        Assert.Equal(TranslationManager.Translation.Flipped, "Capovolto");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Fluorescente");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Lunghezza focale");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Lunghezza focale 35mm");
        Assert.Equal(TranslationManager.Translation.Folder, "Cartella");
        Assert.Equal(TranslationManager.Translation.Forward, "Inoltrare");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationManager.Translation.FullPath, "Percorso completo");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "A schermo intero");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Impostazioni della galleria");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch,
            "Estensione della miniatura della galleria");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Impostazioni generali");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Genera le miniature");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Repository Github");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Tema di vetro");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Torna indietro di 100 immagini");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Torna indietro di 10 immagini");
        Assert.Equal(TranslationManager.Translation.Hard, "Duro");
        Assert.Equal(TranslationManager.Translation.Height, "Altezza");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Nascondi galleria inferiore");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Masquer la barre d'outils inférieure");
        Assert.Equal(TranslationManager.Translation.HideUI, "Nascondi interfaccia");
        Assert.Equal(TranslationManager.Translation.High, "Alto");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Alta qualità");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Evidenzia colore");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "Velocità ISO");
        Assert.Equal(TranslationManager.Translation.Image, "Immagine");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Alias delle immagini");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Controllo dell'immagine");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Informazioni sull'immagine");
        Assert.Equal(TranslationManager.Translation.Inches, "pollici");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Finestra informativa");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Informazioni e scorciatoie");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Interfaccia di configurazione");
        Assert.Equal(TranslationManager.Translation.Landscape, "Paesaggio");
        Assert.Equal(TranslationManager.Translation.Language, "Linguaggio");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Ora dell'ultimo accesso");
        Assert.Equal(TranslationManager.Translation.LastImage, "Ultima immagine");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "ora dell'ultima scrittura");
        Assert.Equal(TranslationManager.Translation.Latitude, "Latitudine");
        Assert.Equal(TranslationManager.Translation.Left, "Sinistra");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Produttore della lente");
        Assert.Equal(TranslationManager.Translation.LensModel, "Modello di lente");
        Assert.Equal(TranslationManager.Translation.LightSource, "Sorgente luminosa");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Tema chiaro");
        Assert.Equal(TranslationManager.Translation.Lighting, "Illuminazione");
        Assert.Equal(TranslationManager.Translation.Loading, "Caricamento in corso...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Longitudine");
        Assert.Equal(TranslationManager.Translation.Looping, "Ciclo");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Ciclo disabilitato");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Ciclo abilitato");
        Assert.Equal(TranslationManager.Translation.Lossless, "Senza perdita");
        Assert.Equal(TranslationManager.Translation.Lossy, "Con perdita");
        Assert.Equal(TranslationManager.Translation.Low, "Basso");
        Assert.Equal(TranslationManager.Translation.Manual, "Manuale");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Apertura massima");
        Assert.Equal(TranslationManager.Translation.Maximize, "Massimizzare");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "Megapixel");
        Assert.Equal(TranslationManager.Translation.Meter, "Metro");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Modalità di misurazione");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimizzare");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Impostazioni varie");
        Assert.Equal(TranslationManager.Translation.Modified, "Modificato");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Trascinamento del mouse");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Tasto mouse indietro");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Tasto mouse in avanti");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Rotellina del mouse");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Sposta la finestra");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navigazione");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Vicino più prossimo");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Colori negativi");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Nuova finestra");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Passa alla cartella successiva");
        Assert.Equal(TranslationManager.Translation.NextImage, "Immagine successiva");
        Assert.Equal(TranslationManager.Translation.NoChange, "Nessuna modifica");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Nessuna conversione");
        Assert.Equal(TranslationManager.Translation.NoImage, "Nessuna immagine caricata");
        Assert.Equal(TranslationManager.Translation.NoImages, "Nessuna immagine");
        Assert.Equal(TranslationManager.Translation.NoResize, "No resize");
        Assert.Equal(TranslationManager.Translation.None, "Nessuno");
        Assert.Equal(TranslationManager.Translation.Normal, "Normale");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Finestra normale");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Non definito");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Vecchio film");
        Assert.Equal(TranslationManager.Translation.Open, "Aprire");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Seleziona un file");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Apri i file nella stessa finestra");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Apri l'ultimo file");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Aprire con...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Ottimizza immagine");
        Assert.Equal(TranslationManager.Translation.Orientation, "Orientamento");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Cartella di uscita");
        Assert.Equal(TranslationManager.Translation.Pan, "Fare una panoramica");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Archivio protetto da password non supportato");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Incolla l'immagine dagli appunti");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Schizzo a matita");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% completo...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Percentuale");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Elimina definitivamente");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Interpretazione fotometrica");
        Assert.Equal(TranslationManager.Translation.Pixels, "Pixel");
        Assert.Equal(TranslationManager.Translation.Portrait, "Ritratto");
        Assert.Equal(TranslationManager.Translation.PressKey, "Premi il tasto...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Torna alla cartella precedente");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Immagine precedente");
        Assert.Equal(TranslationManager.Translation.Print, "Stampa");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Dimensioni di stampa (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Dimensioni di stampa (in)");
        Assert.Equal(TranslationManager.Translation.Quality, "Qualità");
        Assert.Equal(TranslationManager.Translation.Random, "Casuale");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "File recenti");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Riduzione occhi rossi");
        Assert.Equal(TranslationManager.Translation.Reload, "Ricaricare");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Rimuovi il rating");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Rinomina il file");
        Assert.Equal(TranslationManager.Translation.Reset, "Reimposta");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Reimposta alle impostazioni predefinite");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Ripristina lo zoom");
        Assert.Equal(TranslationManager.Translation.Resize, "Ridimensionamento");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Ridimensiona l'immagine");
        Assert.Equal(TranslationManager.Translation.Resolution, "Risoluzione");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Unità di risoluzione");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Riavvia l'applicazione");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Ripristina giù");
        Assert.Equal(TranslationManager.Translation.Reverse, "Inversione");
        Assert.Equal(TranslationManager.Translation.Right, "Destra");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Ruota a sinistra");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Ruota a destra");
        Assert.Equal(TranslationManager.Translation.Rotated, "Ruotato");
        Assert.Equal(TranslationManager.Translation.Saturation, "Saturazione");
        Assert.Equal(TranslationManager.Translation.Save, "Salva");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Salva come");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Salvataggio del file fallito");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Scorrere e ruotare");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Direzione dello scorrimento");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Scorri verso il basso");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Scorri in basso");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Scorri in alto");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Scorri per ingrandire, Ctrl per navigare");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Scorri verso l'alto");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Scorrimento");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Scorrimento disabilitato");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Scorrimento abilitato");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Cerca sottodirectory");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sec.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Seleziona tutto");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Seleziona la miniatura della galleria");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin,
            "Invia l'immagine corrente al cestino");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "File inviato al cestino");
        Assert.Equal(TranslationManager.Translation.SetAs, "Impostato come...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage,
            "Imposta come immagine della schermata di blocco");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Imposta come sfondo");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Imposta l'immagine corrente come sfondo:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Imposta il rating con le stelle");
        Assert.Equal(TranslationManager.Translation.Settings, "Impostazioni");
        Assert.Equal(TranslationManager.Translation.Shade, "Ombra");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Nitidezza");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow,
            "Mostra la finestra di tutte le impostazioni");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Mostra galleria inferiore");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Mostra galleria inferiore quando l'interfaccia utente è nascosta");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Mostra la barra degli strumenti inferiore");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "Mostra la finestra di conferma quando premi 'Esc'");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover,
            "Mostra pulsanti in dissolvenza al passaggio del mouse");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Mostra finestra di salvataggio file");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Mostra galleria immagini");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Mostra informazioni sull'immagine");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Mostra nella cartella");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Mostra finestra informativa");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Mostra la finestra Ridimensiona");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Mostra interfaccia");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Priorità dell'otturatore");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Fianco a fianco");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Mostra le immagini affiancate");
        Assert.Equal(TranslationManager.Translation.Size, "Dimensione");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Dimensione (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip,
            "Inserisci la dimensione desiderata in pixel o in percentuale.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Presentazione");
        Assert.Equal(TranslationManager.Translation.Soft, "Morbido");
        Assert.Equal(TranslationManager.Translation.Software, "Software");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Ordina file per");
        Assert.Equal(TranslationManager.Translation.Space, "Space");
        Assert.Equal(TranslationManager.Translation.Square, "Quadrato");
        Assert.Equal(TranslationManager.Translation.Start, "Inizio");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Avvia presentazione");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Mantieni la finestra centrata");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Rimani in cima alle altre finestre");
        Assert.Equal(TranslationManager.Translation.Stretch, "Allungare");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Estendi immagine");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Luce di ritorno dello strobo rilevata");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected,
            "Luce di ritorno dello strobo non rilevata");
        Assert.Equal(TranslationManager.Translation.Subject, "Soggetto");
        Assert.Equal(TranslationManager.Translation.Theme, "Tema");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Miniature");
        Assert.Equal(TranslationManager.Translation.Tile, "Piastrellare");
        Assert.Equal(TranslationManager.Translation.Title, "Titolo");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Cambia colore di sfondo");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Passare a schermo intero");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Alternare il ciclo");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Attiva/disattiva scorrimento");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress,
            "Mostra progresso sulla barra delle applicazioni");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Impossibile renderizzare l'immagine");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Non calibrato");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Si è verificato un errore sconosciuto");
        Assert.Equal(TranslationManager.Translation.Unflip, "Srotolare");
        Assert.Equal(TranslationManager.Translation.Uniform, "Uniforme");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "UniformePerRiempire");
        Assert.Equal(TranslationManager.Translation.Unknown, "Sconosciuto");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "File non supportato");
        Assert.Equal(TranslationManager.Translation.Up, "Su");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Utilizzare il mouse");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Utilizzare il touchpad");
        Assert.Equal(TranslationManager.Translation.Version, "Versione:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Visualizza file di licenza");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Bilanciamento del bianco");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Fluorescente bianco");
        Assert.Equal(TranslationManager.Translation.Width, "Larghezza");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Larghezza e altezza");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Gestione delle finestre");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Ridimensionamento della finestra");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Ingrandire");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Rimpicciolisci");
        Assert.Equal(TranslationManager.Translation._1Star, "Rating a 1 stella");
        Assert.Equal(TranslationManager.Translation._2Star, "Rating a 2 stella");
        Assert.Equal(TranslationManager.Translation._3Star, "Rating a 3 stella");
        Assert.Equal(TranslationManager.Translation._4Star, "Rating a 4 stella");
        Assert.Equal(TranslationManager.Translation._5Star, "Rating a 5 stella");
    }
}