using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class KoreanUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckKoreanLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("ko");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "정보");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "실행 프로그램");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "클립보드에 추가됨");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "부가 기능");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed, "키를 누르고 있을 때 속도 조정");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "슬라이드쇼 시간 조정");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "확대/축소 속도 조정");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "확대/축소 수준 조정");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "이미지 100개 앞으로 이동");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "이미지 10개 앞으로 이동");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut, "이미지가 이미 최대 크기일 때는 축소하지 않음");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "고도");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "조리개 우선");
        Assert.Equal(TranslationManager.Translation.Appearance, "모양");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "응용 프로그램 단축키");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "응용 프로그램 시작");
        Assert.Equal(TranslationManager.Translation.Apply, "적용");
        Assert.Equal(TranslationManager.Translation.Applying, "적용");
        Assert.Equal(TranslationManager.Translation.Ascending, "오름차순");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "가로 세로 비율");
        Assert.Equal(TranslationManager.Translation.Authors, "저자");
        Assert.Equal(TranslationManager.Translation.Auto, "자동");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "자동 맞춤 창");
        Assert.Equal(TranslationManager.Translation.BadArchive, "압축파일을 처리할 수 없습니다");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Base64 이미지");
        Assert.Equal(TranslationManager.Translation.BatchResize, "일괄 크기 조정");
        Assert.Equal(TranslationManager.Translation.BitDepth, "비트 깊이");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "흑백");
        Assert.Equal(TranslationManager.Translation.Blur, "흐림");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "하단 갤러리의 썸네일 크기");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch, "하단 갤러리의 슬라이드쇼 크기");
        Assert.Equal(TranslationManager.Translation.Brightness, "밝기");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "카메라 제조사");
        Assert.Equal(TranslationManager.Translation.CameraModel, "카메라 모델");
        Assert.Equal(TranslationManager.Translation.Cancel, "취소");
        Assert.Equal(TranslationManager.Translation.Center, "가운데");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "창 가운데");
        Assert.Equal(TranslationManager.Translation.Centimeters, "센티미터");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "배경 변경");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip, "배경이 투명한 이미지의 배경색 변경");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "키 바인딩을 변경하려면 텍스트 상자를 클릭합니다. Esc 키를 누르면 키 바인딩이 해제됩니다.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip, "키 바인딩을 변경하려면 클릭");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart, "* 테마 변경 시 재시작 필요");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "업데이트 확인");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "클립보드 이미지");
        Assert.Equal(TranslationManager.Translation.Close, "닫기");
        Assert.Equal(TranslationManager.Translation.CloseApp, "전체 응용 프로그램 닫기");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "갤러리 닫기");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "창을 닫으시겠습니까?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "흐린 날씨");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "색 선택 도구");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "이미지에서 색 선택");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "색상 표현");
        Assert.Equal(TranslationManager.Translation.ColorTone, "색조");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "픽셀당 압축 비트");
        Assert.Equal(TranslationManager.Translation.Compression, "압축");
        Assert.Equal(TranslationManager.Translation.Contrast, "대비");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "변환");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "base64로 변환");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "차가운 흰색 형광등");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "클립보드에 이미지 복사");
        Assert.Equal(TranslationManager.Translation.Copy, "복사");
        Assert.Equal(TranslationManager.Translation.CopyFile, "파일 복사");
        Assert.Equal(TranslationManager.Translation.CopyImage, "이미지 복사");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Windows 클립보드 이미지로 복사");
        Assert.Equal(TranslationManager.Translation.Copyright, "저작권");
        Assert.Equal(TranslationManager.Translation.Created, "생성 날짜");
        Assert.Equal(TranslationManager.Translation.CreationTime, "생성 날짜");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "창작 프로그램");
        Assert.Equal(TranslationManager.Translation.Credits, "크레딧");
        Assert.Equal(TranslationManager.Translation.Crop, "자르기");
        Assert.Equal(TranslationManager.Translation.CropMessage, "닫으려면 Esc를, 저장하려면 Enter를 누르세요");
        Assert.Equal(TranslationManager.Translation.CropPicture, "사진 자르기");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "확대/축소하려면 Ctrl, 탐색하려면 스크롤");
        Assert.Equal(TranslationManager.Translation.Cut, "잘라내기");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "어두운 테마");
        Assert.Equal(TranslationManager.Translation.Date, "날짜");
        Assert.Equal(TranslationManager.Translation.DateTaken, "촬영 날짜");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "일광 백색 형광등");
        Assert.Equal(TranslationManager.Translation.Daylight, "일광");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "일광 형광등");
        Assert.Equal(TranslationManager.Translation.Del, "Del");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "파일 삭제");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently, "영구적으로 삭제하시겠습니까");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "삭제된 파일");
        Assert.Equal(TranslationManager.Translation.Descending, "내림차순");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "디지털 줌");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover, "마우스 오버 시 페이드인 버튼 비활성화");
        Assert.Equal(TranslationManager.Translation.DiskSize, "디스크 크기");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "더블 클릭");
        Assert.Equal(TranslationManager.Translation.Down, "아래로");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo, "파일을 Windows 탐색기 또는 다른 응용 프로그램/브라우저로 끌어다 놓기");
        Assert.Equal(TranslationManager.Translation.DragImage, "이미지 끌기");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "이미지를 불러오려면 끌기");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "파일 복제");
        Assert.Equal(TranslationManager.Translation.Effects, "효과");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "이미지 효과 창 표시");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "현재 열려 있는 창/메뉴 닫기");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Exif 버전");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "썸네일 크기");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "노출 보정");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "노출 프로그램");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "노출 시간");
        Assert.Equal(TranslationManager.Translation.FNumber, "F 번호");
        Assert.Equal(TranslationManager.Translation.File, "파일");
        Assert.Equal(TranslationManager.Translation.FileCopy, "클립보드에 파일 추가");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "파일 경로 복사");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "클립보드에 파일 경로 추가");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "클립보드 이동을 위해 파일 추가");
        Assert.Equal(TranslationManager.Translation.FileExtension, "파일 확장자");
        Assert.Equal(TranslationManager.Translation.FileManagement, "파일 관리");
        Assert.Equal(TranslationManager.Translation.FileName, "파일 이름");
        Assert.Equal(TranslationManager.Translation.FilePaste, "붙여넣기");
        Assert.Equal(TranslationManager.Translation.FileProperties, "파일 속성");
        Assert.Equal(TranslationManager.Translation.FileSize, "파일 크기");
        Assert.Equal(TranslationManager.Translation.Files, "파일");
        Assert.Equal(TranslationManager.Translation.Fill, "채우기");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ 높이 채우기");
        Assert.Equal(TranslationManager.Translation.FillSquare, "정사각형 채우기");
        Assert.Equal(TranslationManager.Translation.FineWeather, "맑은 날씨");
        Assert.Equal(TranslationManager.Translation.FirstImage, "첫 번째 이미지");
        Assert.Equal(TranslationManager.Translation.Fit, "맟춤");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "창/이미지에 맞춤");
        Assert.Equal(TranslationManager.Translation.Flash, "플래시");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "플래시 발광 안 함");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "플래시 에너지");
        Assert.Equal(TranslationManager.Translation.FlashFired, "플래시 발광");
        Assert.Equal(TranslationManager.Translation.FlashMode, "플래시 모드");
        Assert.Equal(TranslationManager.Translation.Flip, "수평 뒤집기");
        Assert.Equal(TranslationManager.Translation.Flipped, "수평으로 뒤집음");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "형광등");
        Assert.Equal(TranslationManager.Translation.FocalLength, "초점 거리");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "35mm 초점 거리");
        Assert.Equal(TranslationManager.Translation.Folder, "폴더");
        Assert.Equal(TranslationManager.Translation.Forward, "앞으로");
        Assert.Equal(TranslationManager.Translation.Fstop, "F 값");
        Assert.Equal(TranslationManager.Translation.FullPath, "전체 경로");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "전체 화면");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "갤러리 설정");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "썸네일 스크립트");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "일반 설정");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "썸네일 생성");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Github 저장소");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "유리 테마");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "이미지 100개 뒤로 이동");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "이미지 10개 뒤로 이동");
        Assert.Equal(TranslationManager.Translation.Hard, "단단함");
        Assert.Equal(TranslationManager.Translation.Height, "높이");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "하단 갤러리 숨기기");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "하단 도구 모음 숨기기");
        Assert.Equal(TranslationManager.Translation.HideUI, "UI 숨기기");
        Assert.Equal(TranslationManager.Translation.High, "높음");
        Assert.Equal(TranslationManager.Translation.HighQuality, "높은 품질");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "강조 색상");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "ISO 속도");
        Assert.Equal(TranslationManager.Translation.Image, "이미지");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "이미지 앨리어싱");
        Assert.Equal(TranslationManager.Translation.ImageControl, "이미지 제어");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "이미지 정보");
        Assert.Equal(TranslationManager.Translation.Inches, "인치");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "정보 창");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "정보 및 한국어 번역: 비너스걸");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "인터페이스 구성");
        Assert.Equal(TranslationManager.Translation.Landscape, "가로");
        Assert.Equal(TranslationManager.Translation.Language, "언어");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "최근 접근 날짜");
        Assert.Equal(TranslationManager.Translation.LastImage, "마지막 이미지");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "최근 쓰기 날짜");
        Assert.Equal(TranslationManager.Translation.Latitude, "위도");
        Assert.Equal(TranslationManager.Translation.Left, "왼쪽");
        Assert.Equal(TranslationManager.Translation.LensMaker, "렌즈 제조사");
        Assert.Equal(TranslationManager.Translation.LensModel, "렌즈 모델");
        Assert.Equal(TranslationManager.Translation.LightSource, "광원");
        Assert.Equal(TranslationManager.Translation.LightTheme, "밝은 테마");
        Assert.Equal(TranslationManager.Translation.Lighting, "조명");
        Assert.Equal(TranslationManager.Translation.Loading, "불러오는 중...");
        Assert.Equal(TranslationManager.Translation.Longitude, "경도");
        Assert.Equal(TranslationManager.Translation.Looping, "순환");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "순환 사용 안 함");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "순환 사용함");
        Assert.Equal(TranslationManager.Translation.Lossless, "무손실");
        Assert.Equal(TranslationManager.Translation.Lossy, "손실");
        Assert.Equal(TranslationManager.Translation.Low, "낮음");
        Assert.Equal(TranslationManager.Translation.Manual, "수동");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "최대 조리개");
        Assert.Equal(TranslationManager.Translation.Maximize, "최대화");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "메가픽셀");
        Assert.Equal(TranslationManager.Translation.Meter, "미터");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "미터링 모드");
        Assert.Equal(TranslationManager.Translation.Minimize, "최소화");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "기타 설정");
        Assert.Equal(TranslationManager.Translation.Modified, "수정 날짜");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "마우스 끌기");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "마우스 키 뒤로");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "마우스 키 앞으로");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "마우스 휠");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "창 이동");
        Assert.Equal(TranslationManager.Translation.Navigation, "탐색");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "가장 가까운 이웃");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "네거티브 컬러");
        Assert.Equal(TranslationManager.Translation.NewWindow, "새 창");
        Assert.Equal(TranslationManager.Translation.NextFolder, "다음 폴더로 이동");
        Assert.Equal(TranslationManager.Translation.NextImage, "다음 이미지");
        Assert.Equal(TranslationManager.Translation.NoChange, "변경 없음");
        Assert.Equal(TranslationManager.Translation.NoConversion, "변환 안 함");
        Assert.Equal(TranslationManager.Translation.NoImage, "불러온 이미지가 없습니다");
        Assert.Equal(TranslationManager.Translation.NoImages, "이미지 없음");
        Assert.Equal(TranslationManager.Translation.NoResize, "크기 조정 안 함");
        Assert.Equal(TranslationManager.Translation.None, "없음");
        Assert.Equal(TranslationManager.Translation.Normal, "일반");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "일반 창");
        Assert.Equal(TranslationManager.Translation.NotDefined, "정의되지 않음");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "숫자 패드 -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "숫자 패드 +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "오래된 영화");
        Assert.Equal(TranslationManager.Translation.Open, "열기");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "파일 열기 대화 상자");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "동일한 창에서 파일 열기");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "마지막 파일 열기");
        Assert.Equal(TranslationManager.Translation.OpenWith, "열기...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "이미지 최적화");
        Assert.Equal(TranslationManager.Translation.Orientation, "방향");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "출력 폴더");
        Assert.Equal(TranslationManager.Translation.Pan, "팬");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "암호로 보호된 압축파일은 지원되지 않습니다");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "클립 홀더에서 이미지 붙여넣기");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "연필 스케치");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% 완료...");
        Assert.Equal(TranslationManager.Translation.Percentage, "백분율");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "영구 삭제");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "측광 해석");
        Assert.Equal(TranslationManager.Translation.Pixels, "픽셀");
        Assert.Equal(TranslationManager.Translation.Portrait, "세로");
        Assert.Equal(TranslationManager.Translation.PressKey, "키를 누르세요...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "이전 폴더로 이동");
        Assert.Equal(TranslationManager.Translation.PrevImage, "이전 이미지");
        Assert.Equal(TranslationManager.Translation.Print, "인쇄");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "인쇄 크기 (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "인쇄 크기 (in)");
        Assert.Equal(TranslationManager.Translation.Quality, "품질");
        Assert.Equal(TranslationManager.Translation.Random, "무작위");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "최근 파일");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "적목 감소");
        Assert.Equal(TranslationManager.Translation.Reload, "다시 불러오기");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "등급 제거");
        Assert.Equal(TranslationManager.Translation.RenameFile, "파일 이름 바꾸기");
        Assert.Equal(TranslationManager.Translation.Reset, "재설정");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "기본값으로 재설정");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "확대/축소 재설정");
        Assert.Equal(TranslationManager.Translation.Resize, "크기 조정");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "이미지 크기 조정");
        Assert.Equal(TranslationManager.Translation.Resolution, "해상도");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "해상도 단위");
        Assert.Equal(TranslationManager.Translation.RestartApp, "응용 프로그램 다시 시작");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "복원 다운");
        Assert.Equal(TranslationManager.Translation.Reverse, "역방향");
        Assert.Equal(TranslationManager.Translation.Right, "오른쪽");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "왼쪽으로 회전");
        Assert.Equal(TranslationManager.Translation.RotateRight, "오른쪽으로 회전");
        Assert.Equal(TranslationManager.Translation.Rotated, "회전됨");
        Assert.Equal(TranslationManager.Translation.Saturation, "채도");
        Assert.Equal(TranslationManager.Translation.Save, "저장");
        Assert.Equal(TranslationManager.Translation.SaveAs, "다른 이름으로 저장");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "파일 저장 실패");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "스크롤 및 회전");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "스크롤 방향");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "아래로 스크롤");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "맨 아래로 스크롤");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "맨 위로 스크롤");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "마우스 휠로 확대/축소, Ctrl로 탐색");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "위로 스크롤");
        Assert.Equal(TranslationManager.Translation.Scrolling, "스크롤");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "스크롤 사용 안 함");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "스크롤 사용함");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "하위 디렉터리 검색");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "초");
        Assert.Equal(TranslationManager.Translation.SelectAll, "전체 선택");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "갤러리 썸네일 선택");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin, "현재 이미지를 휴지통으로 보내기");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "파일을 휴지통으로 보냈습니다");
        Assert.Equal(TranslationManager.Translation.SetAs, "다음으로 설정...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "잠금 화면 이미지로 설정");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "배경 화면으로 설정");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper, "현재 이미지를 배경 화면으로 설정:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "별 등급 설정");
        Assert.Equal(TranslationManager.Translation.Settings, "설정");
        Assert.Equal(TranslationManager.Translation.Shade, "그늘");
        Assert.Equal(TranslationManager.Translation.Sharpness, "선명도");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "모든 설정 창 표시");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "하단 갤러리 표시");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden, "UI를 숨겼을 때 하단 갤러리 표시");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "하단 도구 모음 표시");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc, "'Esc'를 누를 때 확인 대화 상자를 표시");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover, "마우스 오버 시 페이드인 버튼 표시");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "파일 저장 대화상자 표시");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "이미지 갤러리 표시");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "이미지 정보 표시");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "폴더에서 표시");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "정보 창 표시");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "크기 조정 창 표시");
        Assert.Equal(TranslationManager.Translation.ShowUI, "UI 표시");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "셔터 우선");
        Assert.Equal(TranslationManager.Translation.SideBySide, "나란히");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "이미지를 나란히 표시");
        Assert.Equal(TranslationManager.Translation.Size, "크기");
        Assert.Equal(TranslationManager.Translation.SizeMp, "크기 (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "원하는 크기를 픽셀 또는 백분율로 입력하세요.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "슬라이드쇼");
        Assert.Equal(TranslationManager.Translation.Soft, "부드럽게");
        Assert.Equal(TranslationManager.Translation.Software, "소프트웨어");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "파일 정렬");
        Assert.Equal(TranslationManager.Translation.Space, "공간");
        Assert.Equal(TranslationManager.Translation.Square, "정사각형");
        Assert.Equal(TranslationManager.Translation.Start, "시작");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "슬라이드쇼 시작");
        Assert.Equal(TranslationManager.Translation.StayCentered, "창 중앙 유지");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "다른 창 위에 유지");
        Assert.Equal(TranslationManager.Translation.Stretch, "늘이기");
        Assert.Equal(TranslationManager.Translation.StretchImage, "이미지 늘리기");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "스트로브 반사 빛 감지됨");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected, "스트로브 반사 빛 감지 안 됨");
        Assert.Equal(TranslationManager.Translation.Subject, "주제");
        Assert.Equal(TranslationManager.Translation.Theme, "테마");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "썸네일");
        Assert.Equal(TranslationManager.Translation.Tile, "타일");
        Assert.Equal(TranslationManager.Translation.Title, "제목");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "배경색 전환");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "전체 화면 전환");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "순환 전환");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "스크롤 전환");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "작업 표시줄 진행률 표시");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "이미지를 렌더링할 수 없습니다");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "보정되지 않음");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "알 수 없는 오류 발생");
        Assert.Equal(TranslationManager.Translation.Unflip, "뒤집기 취소");
        Assert.Equal(TranslationManager.Translation.Uniform, "균일하게");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "균일하게 채우기");
        Assert.Equal(TranslationManager.Translation.Unknown, "알 수 없음");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "지원되지 않는 파일");
        Assert.Equal(TranslationManager.Translation.Up, "위로");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "마우스 사용");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "터치패드 사용");
        Assert.Equal(TranslationManager.Translation.Version, "버전:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "라이선스 파일 보기");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "화이트 밸런스");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "백색 형광등");
        Assert.Equal(TranslationManager.Translation.Width, "너비");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "너비 및 높이");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "창 관리");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "창 비율");
        Assert.Equal(TranslationManager.Translation.Zoom, "확대/축소");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "확대");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "축소");
        Assert.Equal(TranslationManager.Translation._1Star, "별 1 등급");
        Assert.Equal(TranslationManager.Translation._2Star, "별 2 등급");
        Assert.Equal(TranslationManager.Translation._3Star, "별 3 등급");
        Assert.Equal(TranslationManager.Translation._4Star, "별 4 등급");
        Assert.Equal(TranslationManager.Translation._5Star, "별 5 등급");
    }
}