using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class PolishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckPolishLanguage()
    {
        var exists = await TranslationHelper.LoadLanguage("pl");
        Assert.True(exists);

        Assert.Equal(TranslationHelper.Translation.About, "Informacje");
        Assert.Equal(TranslationHelper.Translation.ActionProgram, "Program akcji");
        Assert.Equal(TranslationHelper.Translation.AddedToClipboard, "dodano do schowka");
        Assert.Equal(TranslationHelper.Translation.AdditionalFunctions, "Dodatkowe funkcje");
        Assert.Equal(TranslationHelper.Translation.AdjustNavSpeed,
            "Dostosuj prędkość: gdy klawisz jest trzymany wciśnięty");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForSlideshow, "Zmień czas na zdjęcie podczas pokazu");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForZoom, "Zmień prędkość przybliżania");
        Assert.Equal(TranslationHelper.Translation.AdjustZoomLevel, "Dostosuj poziom przybliżenia");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy100Images, "Przejdź o 100 obrazów do przodu");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy10Images, "Przejdź o 10 obrazów do przodu");
        Assert.Equal(TranslationHelper.Translation.AllowZoomOut,
            "Unikaj zmniejszania obrazu: gdy jest już w maksymalnym rozmiarze");
        Assert.Equal(TranslationHelper.Translation.Alt, "Alt");
        Assert.Equal(TranslationHelper.Translation.Altitude, "Wysokość");
        Assert.Equal(TranslationHelper.Translation.AperturePriority, "Priorytet przysłony");
        Assert.Equal(TranslationHelper.Translation.Appearance, "Wygląd");
        Assert.Equal(TranslationHelper.Translation.ApplicationShortcuts, "Skróty aplikacji");
        Assert.Equal(TranslationHelper.Translation.ApplicationStartup, "Uruchamianie aplikacji");
        Assert.Equal(TranslationHelper.Translation.Apply, "Zastosuj");
        Assert.Equal(TranslationHelper.Translation.Applying, "Zapisywanie");
        Assert.Equal(TranslationHelper.Translation.Ascending, "Rosnąco");
        Assert.Equal(TranslationHelper.Translation.AspectRatio, "Stosunek");
        Assert.Equal(TranslationHelper.Translation.Authors, "Autorzy");
        Assert.Equal(TranslationHelper.Translation.Auto, "Automatyczny");
        Assert.Equal(TranslationHelper.Translation.AutoFitWindow, "Automatycznie dopasuj okno");
        Assert.Equal(TranslationHelper.Translation.BadArchive, "Archiwum nie mogło być przetworzone");
        Assert.Equal(TranslationHelper.Translation.BandedSwirl, "Zakręcenie");
        Assert.Equal(TranslationHelper.Translation.Bands, "Paski");
        Assert.Equal(TranslationHelper.Translation.Base64Image, "Zdjęcie z tekstu Base64");
        Assert.Equal(TranslationHelper.Translation.BatchResize, "Resize wsadowe");
        Assert.Equal(TranslationHelper.Translation.BitDepth, "Bitów głębkości koloru");
        Assert.Equal(TranslationHelper.Translation.BlackAndWhite, "Czarny i Biały");
        Assert.Equal(TranslationHelper.Translation.Bloom, "Lekki róż");
        Assert.Equal(TranslationHelper.Translation.Blur, "Rozmycie");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryItemSize, "Liczba elementów na dole galerii");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryThumbnailStretch,
            "Prześrodkuj miniatury na dole galerii");
        Assert.Equal(TranslationHelper.Translation.Brightness, "Jasność");
        Assert.Equal(TranslationHelper.Translation.CameraMaker, "Producent aparatu");
        Assert.Equal(TranslationHelper.Translation.CameraModel, "Model aparatu");
        Assert.Equal(TranslationHelper.Translation.Cancel, "Anuluj");
        Assert.Equal(TranslationHelper.Translation.Center, "Wycentruj");
        Assert.Equal(TranslationHelper.Translation.CenterWindow, "Wyśrodkuj okno");
        Assert.Equal(TranslationHelper.Translation.Centimeters, "centymetrów");
        Assert.Equal(TranslationHelper.Translation.ChangeBackground, "Zmień tło");
        Assert.Equal(TranslationHelper.Translation.ChangeBackgroundTooltip,
            "Zmień kolor tła dla obrazów z przezroczystym tłem");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingText,
            "Kliknij na polu tekstowym: aby zmienić przypisanie klawiszy. Naciśnięcie klawisza Esc odwiązuje klawisz.");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingTooltip,
            "Kliknij: aby zmienić przypisanie klawisza");
        Assert.Equal(TranslationHelper.Translation.ChangingThemeRequiresRestart,
            "* Zmiana motywu wymaga restartu programu");
        Assert.Equal(TranslationHelper.Translation.CheckForUpdates, "Sprawdź aktualizacje");
        Assert.Equal(TranslationHelper.Translation.ClipboardImage, "Zdjęcie ze schowka");
        Assert.Equal(TranslationHelper.Translation.Close, "Zamknij");
        Assert.Equal(TranslationHelper.Translation.CloseApp, "Zamyka aplikację");
        Assert.Equal(TranslationHelper.Translation.CloseGallery, "Zamknij galerię");
        Assert.Equal(TranslationHelper.Translation.CloseWindowPrompt, "Czy chcesz zamknąć okno?");
        Assert.Equal(TranslationHelper.Translation.CloudyWeather, "Pochmurno");
        Assert.Equal(TranslationHelper.Translation.ColorPickerTool, "Narzędzie wyboru koloru");
        Assert.Equal(TranslationHelper.Translation.ColorPickerToolTooltip, "Wybierz kolor ze zdjęcia");
        Assert.Equal(TranslationHelper.Translation.ColorRepresentation, "Reprezentacja kolorów");
        Assert.Equal(TranslationHelper.Translation.ColorTone, "Odcień");
        Assert.Equal(TranslationHelper.Translation.CompressedBitsPixel, "Kompresja bitów na piksel");
        Assert.Equal(TranslationHelper.Translation.Compression, "Kompresja");
        Assert.Equal(TranslationHelper.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationHelper.Translation.ConvertTo, "Konwertuj na");
        Assert.Equal(TranslationHelper.Translation.ConvertedToBase64, "Zamieniono na Base64");
        Assert.Equal(TranslationHelper.Translation.CoolWhiteFluorescent, "Zimny biały - świetlówka");
        Assert.Equal(TranslationHelper.Translation.CopiedImage, "Obraz skopiowany do schowka");
        Assert.Equal(TranslationHelper.Translation.Copy, "Kopiuj");
        Assert.Equal(TranslationHelper.Translation.CopyFile, "Kopiuj plik");
        Assert.Equal(TranslationHelper.Translation.CopyImage, "Skopiuj obraz");
        Assert.Equal(TranslationHelper.Translation.CopyImageTooltip, "Skopiuj jako obraz Schowka Windows");
        Assert.Equal(TranslationHelper.Translation.Copyright, "Prawa autorskie");
        Assert.Equal(TranslationHelper.Translation.Created, "Utworzony");
        Assert.Equal(TranslationHelper.Translation.CreationTime, "Czasie stworzenia");
        Assert.Equal(TranslationHelper.Translation.CreativeProgram, "Program kreatywny");
        Assert.Equal(TranslationHelper.Translation.Credits, "Autorzy");
        Assert.Equal(TranslationHelper.Translation.Crop, "Przytnij");
        Assert.Equal(TranslationHelper.Translation.CropMessage, "Wciśnij Esc aby zamknąć: Enter aby zapisać");
        Assert.Equal(TranslationHelper.Translation.CropPicture, "Przytnij zdjęcie");
        Assert.Equal(TranslationHelper.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationHelper.Translation.CtrlToZoom,
            "Wciśnij Ctrl aby przybliżyć: użyj kółka myszy aby się poruszać");
        Assert.Equal(TranslationHelper.Translation.Cut, "Wytnij");
        Assert.Equal(TranslationHelper.Translation.DarkTheme, "Ciemny motyw");
        Assert.Equal(TranslationHelper.Translation.Date, "Data");
        Assert.Equal(TranslationHelper.Translation.DateTaken, "Data wykonania");
        Assert.Equal(TranslationHelper.Translation.DayWhiteFluorescent, "Dzienny biały - świetlówka");
        Assert.Equal(TranslationHelper.Translation.Daylight, "Światło dzienne");
        Assert.Equal(TranslationHelper.Translation.DaylightFluorescent, "Światło dzienne - świetlówka");
        Assert.Equal(TranslationHelper.Translation.Del, "Del");
        Assert.Equal(TranslationHelper.Translation.DeleteFile, "Usuń plik");
        Assert.Equal(TranslationHelper.Translation.DeleteFilePermanently, "Czy na pewno chcesz trwale usunąć");
        Assert.Equal(TranslationHelper.Translation.DeletedFile, "Usunięto");
        Assert.Equal(TranslationHelper.Translation.Descending, "Malejący");
        Assert.Equal(TranslationHelper.Translation.DigitalZoom, "Zoom cyfrowy");
        Assert.Equal(TranslationHelper.Translation.DirectionalBlur, "Rozmycie ruchu");
        Assert.Equal(TranslationHelper.Translation.DisableFadeInButtonsOnHover, "마우스 오버 시 페이드인 버튼 비활성화");
        Assert.Equal(TranslationHelper.Translation.DiskSize, "Rozmiar na dysku");
        Assert.Equal(TranslationHelper.Translation.DoubleClick, "Podwójne kliknięcie");
        Assert.Equal(TranslationHelper.Translation.Down, "Dół");
        Assert.Equal(TranslationHelper.Translation.Dpi, "DPI");
        Assert.Equal(TranslationHelper.Translation.DragFileTo,
            "Przeciągnij plik do Eksploratora lub innej aplikacji/przeglądarki");
        Assert.Equal(TranslationHelper.Translation.DragImage, "Przeciągnij obraz");
        Assert.Equal(TranslationHelper.Translation.DropToLoad, "Upuść obraz: aby wczytać");
        Assert.Equal(TranslationHelper.Translation.DuplicateFile, "Duplikuj plik");
        Assert.Equal(TranslationHelper.Translation.Effects, "Efekty");
        Assert.Equal(TranslationHelper.Translation.EffectsTooltip, "Pokaż okno z efektami zdjęć");
        Assert.Equal(TranslationHelper.Translation.Embossed, "Wytoczenie");
        Assert.Equal(TranslationHelper.Translation.Enter, "Enter");
        Assert.Equal(TranslationHelper.Translation.Esc, "Esc");
        Assert.Equal(TranslationHelper.Translation.EscCloseTooltip, "Zamyka obecnie otwarte okno/menu");
        Assert.Equal(TranslationHelper.Translation.ExifVersion, "Wersja Exif");
        Assert.Equal(TranslationHelper.Translation.ExpandedGalleryItemSize, "Rozszerzone elementy galerii");
        Assert.Equal(TranslationHelper.Translation.ExposureBias, "Kompensacja ekspozycji");
        Assert.Equal(TranslationHelper.Translation.ExposureProgram, "Program ekspozycji");
        Assert.Equal(TranslationHelper.Translation.ExposureTime, "Czas ekspozycji");
        Assert.Equal(TranslationHelper.Translation.File, "plik");
        Assert.Equal(TranslationHelper.Translation.FileCopy, "Dodano plik do schowka");
        Assert.Equal(TranslationHelper.Translation.FileCopyPath, "Kopiuj ścieżkę do pliku");
        Assert.Equal(TranslationHelper.Translation.FileCopyPathMessage, "Ścieżka do pliku dodana do schowka");
        Assert.Equal(TranslationHelper.Translation.FileCutMessage, "Wycięto plik");
        Assert.Equal(TranslationHelper.Translation.FileExtension, "Rozszerzeniu");
        Assert.Equal(TranslationHelper.Translation.FileManagement, "Zarządzanie plikami");
        Assert.Equal(TranslationHelper.Translation.FileName, "Nazwie");
        Assert.Equal(TranslationHelper.Translation.FilePaste, "Wklej");
        Assert.Equal(TranslationHelper.Translation.FileProperties, "Ustawienia pliku");
        Assert.Equal(TranslationHelper.Translation.FileSize, "Rozmiarze");
        Assert.Equal(TranslationHelper.Translation.Files, "pliki");
        Assert.Equal(TranslationHelper.Translation.Fill, "Wypełnij");
        Assert.Equal(TranslationHelper.Translation.FillHeight, "⇔ Rozszerz na wysokość");
        Assert.Equal(TranslationHelper.Translation.FillSquare, "WypełnijKwadrat");
        Assert.Equal(TranslationHelper.Translation.FineWeather, "Dobra pogoda");
        Assert.Equal(TranslationHelper.Translation.FirstImage, "Pierwszy obraz");
        Assert.Equal(TranslationHelper.Translation.Fit, "Dopasuj");
        Assert.Equal(TranslationHelper.Translation.FitToWindow, "Dopasuj do okna/obrazu");
        Assert.Equal(TranslationHelper.Translation.Flash, "Błysk");
        Assert.Equal(TranslationHelper.Translation.FlashDidNotFire, "Błysk nie wyzwolony");
        Assert.Equal(TranslationHelper.Translation.FlashEnergy, "Energia błysku");
        Assert.Equal(TranslationHelper.Translation.FlashFired, "Błysk wyzwolony");
        Assert.Equal(TranslationHelper.Translation.FlashMode, "Tryb błysku");
        Assert.Equal(TranslationHelper.Translation.Flip, "Przeróć poziomo");
        Assert.Equal(TranslationHelper.Translation.Flipped, "Przerócone");
        Assert.Equal(TranslationHelper.Translation.Fluorescent, "Świetlówka");
        Assert.Equal(TranslationHelper.Translation.FNumber, "Liczba F");
        Assert.Equal(TranslationHelper.Translation.FocalLength, "Długość ogniskowej");
        Assert.Equal(TranslationHelper.Translation.FocalLength35mm, "Długość ogniskowej (35mm)");
        Assert.Equal(TranslationHelper.Translation.Folder, "Folder");
        Assert.Equal(TranslationHelper.Translation.Forward, "Do przodu");
        Assert.Equal(TranslationHelper.Translation.FrostyOutline, "Zimne kontury");
        Assert.Equal(TranslationHelper.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationHelper.Translation.FullPath, "Pełna ścieżka");
        Assert.Equal(TranslationHelper.Translation.Fullscreen, "Pełny ekran");
        Assert.Equal(TranslationHelper.Translation.GallerySettings, "Ustawienia galerii");
        Assert.Equal(TranslationHelper.Translation.GalleryThumbnailStretch, "Przytnij miniatury");
        Assert.Equal(TranslationHelper.Translation.GeneralSettings, "Ustawienia ogólne");
        Assert.Equal(TranslationHelper.Translation.GenerateThumbnails, "Generuj miniatury");
        Assert.Equal(TranslationHelper.Translation.GithubRepo, "Repozytorium na Github");
        Assert.Equal(TranslationHelper.Translation.GlassTheme, "Motyw szklany");
        Assert.Equal(TranslationHelper.Translation.GlassTile, "Szklane kafelki");
        Assert.Equal(TranslationHelper.Translation.Gloom, "Przyciemniony");
        Assert.Equal(TranslationHelper.Translation.GoBackBy100Images, "Przejdź o 100 obrazów do tyłu");
        Assert.Equal(TranslationHelper.Translation.GoBackBy10Images, "Przejdź o 10 obrazów do tyłu");
        Assert.Equal(TranslationHelper.Translation.GoToImageAtSpecifiedIndex,
            "Przejdź do zdjęcia o określonym indeksie");
        Assert.Equal(TranslationHelper.Translation.Hard, "Twardy");
        Assert.Equal(TranslationHelper.Translation.Height, "Wysokość");
        Assert.Equal(TranslationHelper.Translation.HideBottomGallery, "Ukryj dolną galerię");
        Assert.Equal(TranslationHelper.Translation.HideBottomToolbar, "Ukryj dolny pasek narzędzi");
        Assert.Equal(TranslationHelper.Translation.HideUI, "Ukryj interfejs");
        Assert.Equal(TranslationHelper.Translation.High, "Wysoki");
        Assert.Equal(TranslationHelper.Translation.HighQuality, "Wysoka jakość");
        Assert.Equal(TranslationHelper.Translation.HighlightColor, "Kolor zaznaczenia");
        Assert.Equal(TranslationHelper.Translation.ISOSpeed, "Czułość ISO");
        Assert.Equal(TranslationHelper.Translation.IconsUsed, "Wykorzystane ikony:");
        Assert.Equal(TranslationHelper.Translation.Image, "Obraz");
        Assert.Equal(TranslationHelper.Translation.ImageAliasing, "Aliasing obrazu");
        Assert.Equal(TranslationHelper.Translation.ImageControl, "Kontrola obrazu");
        Assert.Equal(TranslationHelper.Translation.ImageInfo, "Szczegóły obrazu");
        Assert.Equal(TranslationHelper.Translation.Inches, "cali");
        Assert.Equal(TranslationHelper.Translation.InfoWindow, "Okno z informacją");
        Assert.Equal(TranslationHelper.Translation.InfoWindowTitle, "Informacje i skróty");
        Assert.Equal(TranslationHelper.Translation.InterfaceConfiguration, "Konfiguracja interfejsu");
        Assert.Equal(TranslationHelper.Translation.Landscape, "Krajobrazowy");
        Assert.Equal(TranslationHelper.Translation.Language, "Język");
        Assert.Equal(TranslationHelper.Translation.LastAccessTime, "Czasie ostatniego dostępu");
        Assert.Equal(TranslationHelper.Translation.LastImage, "Ostatni obraz");
        Assert.Equal(TranslationHelper.Translation.LastWriteTime, "Czasie ostatniego zapisu");
        Assert.Equal(TranslationHelper.Translation.Latitude, "Szerokość geograficzna");
        Assert.Equal(TranslationHelper.Translation.Left, "Lewo");
        Assert.Equal(TranslationHelper.Translation.LensMaker, "Producent obiektywu");
        Assert.Equal(TranslationHelper.Translation.LensModel, "Model obiektywu");
        Assert.Equal(TranslationHelper.Translation.LightSource, "Źródło światła");
        Assert.Equal(TranslationHelper.Translation.LightTheme, "Jasny motyw");
        Assert.Equal(TranslationHelper.Translation.Lighting, "Oświetlenie");
        Assert.Equal(TranslationHelper.Translation.Loading, "Ładowanie...");
        Assert.Equal(TranslationHelper.Translation.Longitude, "Długość geograficzna");
        Assert.Equal(TranslationHelper.Translation.Looping, "Zapętlanie");
        Assert.Equal(TranslationHelper.Translation.LoopingDisabled, "Zapętlenie wyłączone");
        Assert.Equal(TranslationHelper.Translation.LoopingEnabled, "Zapętlenie włączone");
        Assert.Equal(TranslationHelper.Translation.Lossless, "Bezstratna");
        Assert.Equal(TranslationHelper.Translation.Lossy, "Stratna");
        Assert.Equal(TranslationHelper.Translation.Low, "Niski");
        Assert.Equal(TranslationHelper.Translation.Manual, "Ręczny");
        Assert.Equal(TranslationHelper.Translation.MaxAperture, "Maksymalna przysłona");
        Assert.Equal(TranslationHelper.Translation.Maximize, "Maksymalizuj");
        Assert.Equal(TranslationHelper.Translation.MegaPixels, "megapikseli");
        Assert.Equal(TranslationHelper.Translation.Meter, "Metr");
        Assert.Equal(TranslationHelper.Translation.MeteringMode, "Tryb pomiaru");
        Assert.Equal(TranslationHelper.Translation.Minimize, "Minimalizuj");
        Assert.Equal(TranslationHelper.Translation.MiscSettings, "Pozostałe ustawienia");
        Assert.Equal(TranslationHelper.Translation.Modified, "Zmodyfikowany");
        Assert.Equal(TranslationHelper.Translation.Monochrome, "Monochromatyczny");
        Assert.Equal(TranslationHelper.Translation.MouseDrag, "Przenieś");
        Assert.Equal(TranslationHelper.Translation.MouseKeyBack, "Przycisk myszy wstecz");
        Assert.Equal(TranslationHelper.Translation.MouseKeyForward, "Przycisk myszy wprzód");
        Assert.Equal(TranslationHelper.Translation.MouseWheel, "Kółko myszy");
        Assert.Equal(TranslationHelper.Translation.MoveWindow, "Przenieś okno");
        Assert.Equal(TranslationHelper.Translation.Navigation, "Nawigacja");
        Assert.Equal(TranslationHelper.Translation.NearestNeighbor, "Najbliższy sąsiad");
        Assert.Equal(TranslationHelper.Translation.NegativeColors, "Przeciwne kolory");
        Assert.Equal(TranslationHelper.Translation.NewWindow, "Nowe okno");
        Assert.Equal(TranslationHelper.Translation.NextFolder, "Przejdź do następnego folderu");
        Assert.Equal(TranslationHelper.Translation.NextImage, "Kolejny obraz");
        Assert.Equal(TranslationHelper.Translation.NoChange, "Brak zmian");
        Assert.Equal(TranslationHelper.Translation.NoConversion, "Bez konwersji");
        Assert.Equal(TranslationHelper.Translation.NoImage, "Brak obrazu");
        Assert.Equal(TranslationHelper.Translation.NoImages, "Brak obrazów");
        Assert.Equal(TranslationHelper.Translation.NoResize, "Brak zmiany");
        Assert.Equal(TranslationHelper.Translation.None, "Nic");
        Assert.Equal(TranslationHelper.Translation.Normal, "Normalny");
        Assert.Equal(TranslationHelper.Translation.NormalWindow, "Normalne okno");
        Assert.Equal(TranslationHelper.Translation.NotDefined, "Nie zdefiniowano");
        Assert.Equal(TranslationHelper.Translation.NumpadMinus, "Klawisz \"-\" klawiatury numerycznej");
        Assert.Equal(TranslationHelper.Translation.NumpadPlus, "Klawisz \"+\" klawiatury numerycznej");
        Assert.Equal(TranslationHelper.Translation.OldMovie, "Stary film");
        Assert.Equal(TranslationHelper.Translation.Open, "Otwórz");
        Assert.Equal(TranslationHelper.Translation.OpenFileDialog, "Wybierz plik");
        Assert.Equal(TranslationHelper.Translation.OpenInSameWindow, "Otwórz pliki w tym samym oknie");
        Assert.Equal(TranslationHelper.Translation.OpenLastFile, "Otwórz ostatni plik");
        Assert.Equal(TranslationHelper.Translation.OpenWith, "Otwórz przy pomocy...");
        Assert.Equal(TranslationHelper.Translation.OptimizeImage, "Optymalizuj zdjęcie");
        Assert.Equal(TranslationHelper.Translation.Orientation, "Orientacja");
        Assert.Equal(TranslationHelper.Translation.OutputFolder, "Folder wyjściowy");
        Assert.Equal(TranslationHelper.Translation.Pan, "Pochyl");
        Assert.Equal(TranslationHelper.Translation.PaperFold, "Złożenie");
        Assert.Equal(TranslationHelper.Translation.PasswordArchive, "Archiwa chronione hasłem nie są wspierane");
        Assert.Equal(TranslationHelper.Translation.PasteImageFromClipholder, "Wklej zdjęcie ze schowka");
        Assert.Equal(TranslationHelper.Translation.PencilSketch, "Szkic ołówkiem");
        Assert.Equal(TranslationHelper.Translation.PercentComplete, "% ukończono...");
        Assert.Equal(TranslationHelper.Translation.Percentage, "Procent");
        Assert.Equal(TranslationHelper.Translation.PermanentlyDelete, "Usuń trwale");
        Assert.Equal(TranslationHelper.Translation.PhotometricInterpretation, "Interpretacja fotometryczna");
        Assert.Equal(TranslationHelper.Translation.Pivot, "Pivot");
        Assert.Equal(TranslationHelper.Translation.Pixelate, "Pikselizacja");
        Assert.Equal(TranslationHelper.Translation.Pixels, "pikseli");
        Assert.Equal(TranslationHelper.Translation.Portrait, "Portretowy");
        Assert.Equal(TranslationHelper.Translation.PressKey, "Naciśnij klawisz...");
        Assert.Equal(TranslationHelper.Translation.PrevFolder, "Przejdź do poprzedniego folderu");
        Assert.Equal(TranslationHelper.Translation.PrevImage, "Poprzedni obraz");
        Assert.Equal(TranslationHelper.Translation.Print, "Drukuj");
        Assert.Equal(TranslationHelper.Translation.PrintSizeCm, "Rozmiar wydruku (cm)");
        Assert.Equal(TranslationHelper.Translation.PrintSizeIn, "Rozmiar wydruku (cale)");
        Assert.Equal(TranslationHelper.Translation.Quality, "Jakość");
        Assert.Equal(TranslationHelper.Translation.Random, "Losowo");
        Assert.Equal(TranslationHelper.Translation.RecentFiles, "Ostatnie pliki");
        Assert.Equal(TranslationHelper.Translation.RedEyeReduction, "Redukcja efektu czerwonych oczu");
        Assert.Equal(TranslationHelper.Translation.Reload, "Przeładuj");
        Assert.Equal(TranslationHelper.Translation.RemoveStarRating, "Usuń ocenę");
        Assert.Equal(TranslationHelper.Translation.RenameFile, "Zmień nazwę");
        Assert.Equal(TranslationHelper.Translation.Reset, "Zresetuj");
        Assert.Equal(TranslationHelper.Translation.ResetButtonText, "Przywróć domyślne");
        Assert.Equal(TranslationHelper.Translation.ResetZoom, "Resetuj zoom");
        Assert.Equal(TranslationHelper.Translation.Resize, "Zmień rozmiar");
        Assert.Equal(TranslationHelper.Translation.ResizeImage, "Zmień rozmiar obrazu");
        Assert.Equal(TranslationHelper.Translation.Resolution, "Rozdzielczość");
        Assert.Equal(TranslationHelper.Translation.ResolutionUnit, "Jednostka rozdzielczości");
        Assert.Equal(TranslationHelper.Translation.RestartApp, "Zrestartuj aplikację");
        Assert.Equal(TranslationHelper.Translation.RestoreDown, "Przywróć");
        Assert.Equal(TranslationHelper.Translation.Reverse, "Odwrócić");
        Assert.Equal(TranslationHelper.Translation.Right, "Prawo");
        Assert.Equal(TranslationHelper.Translation.Ripple, "Zmarszczki");
        Assert.Equal(TranslationHelper.Translation.RippleAlt, "Zmarszczki 2");
        Assert.Equal(TranslationHelper.Translation.RotateLeft, "Obróć w lewo");
        Assert.Equal(TranslationHelper.Translation.RotateRight, "Obróć w prawo");
        Assert.Equal(TranslationHelper.Translation.Rotated, "Obrócone");
        Assert.Equal(TranslationHelper.Translation.Saturation, "Nasycenie");
        Assert.Equal(TranslationHelper.Translation.Save, "Zapisz");
        Assert.Equal(TranslationHelper.Translation.SaveAs, "Zapisz jako");
        Assert.Equal(TranslationHelper.Translation.SavingFileFailed, "Zapis pliku nie powiódł się");
        Assert.Equal(TranslationHelper.Translation.ScrollAndRotate, "Przewijaj i obracaj");
        Assert.Equal(TranslationHelper.Translation.ScrollDirection, "Kierunek przewijania");
        Assert.Equal(TranslationHelper.Translation.ScrollDown, "Przewiń w dół");
        Assert.Equal(TranslationHelper.Translation.ScrollToBottom, "Przewiń na dół");
        Assert.Equal(TranslationHelper.Translation.ScrollToTop, "Przewiń do góry");
        Assert.Equal(TranslationHelper.Translation.ScrollToZoom,
            "Użyj kółka myszy: aby przybliżyć: wciśnij Ctrl: aby się poruszać");
        Assert.Equal(TranslationHelper.Translation.ScrollUp, "Przewiń w górę");
        Assert.Equal(TranslationHelper.Translation.Scrolling, "Przewijanie");
        Assert.Equal(TranslationHelper.Translation.ScrollingDisabled, "Przewijanie wyłączone");
        Assert.Equal(TranslationHelper.Translation.ScrollingEnabled, "Przewijanie włączone");
        Assert.Equal(TranslationHelper.Translation.SearchSubdirectory, "Przeszukaj podkatalogi");
        Assert.Equal(TranslationHelper.Translation.SecAbbreviation, "Sek.");
        Assert.Equal(TranslationHelper.Translation.SelectAll, "Zaznacz wszystko");
        Assert.Equal(TranslationHelper.Translation.SelectGalleryThumb, "Wybierz miniaturę galerii");
        Assert.Equal(TranslationHelper.Translation.SendCurrentImageToRecycleBin, "Przenieś obecne zdjęcie do kosza");
        Assert.Equal(TranslationHelper.Translation.SentFileToRecycleBin, "Przenieś plik do kosza");
        Assert.Equal(TranslationHelper.Translation.SetAs, "Ustaw jako...");
        Assert.Equal(TranslationHelper.Translation.SetAsLockScreenImage, "Ustaw jako ekran blokady");
        Assert.Equal(TranslationHelper.Translation.SetAsWallpaper, "Ustaw jako tapetę");
        Assert.Equal(TranslationHelper.Translation.SetCurrentImageAsWallpaper, "Ustaw zdjęcie jako tapetę:");
        Assert.Equal(TranslationHelper.Translation.SetStarRating, "Ustawianie oceny gwiazdkowej");
        Assert.Equal(TranslationHelper.Translation.Settings, "Ustawienia");
        Assert.Equal(TranslationHelper.Translation.Shade, "Cień");
        Assert.Equal(TranslationHelper.Translation.Sharpness, "Ostrość");
        Assert.Equal(TranslationHelper.Translation.Shift, "Shift");
        Assert.Equal(TranslationHelper.Translation.ShowAllSettingsWindow, "Pokaż okno ze wszystkimi ustawieniami");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGallery, "Pokaż dolną galerię");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Pokaż dolną galerię: gdy UI jest ukryte");
        Assert.Equal(TranslationHelper.Translation.ShowBottomToolbar, "Pokaż dolny pasek narzędzi");
        Assert.Equal(TranslationHelper.Translation.ShowConfirmationOnEsc,
            "Pokaż okno potwierdzenia po naciśnięciu 'Esc'");
        Assert.Equal(TranslationHelper.Translation.ShowFadeInButtonsOnHover, "마우스 오버 시 페이드인 버튼 표시");
        Assert.Equal(TranslationHelper.Translation.ShowFileSavingDialog, "Pokaż okno zapisywania pliku");
        Assert.Equal(TranslationHelper.Translation.ShowImageGallery, "Pokaż galerię zdjęć");
        Assert.Equal(TranslationHelper.Translation.ShowImageInfo, "Pokaż szczegóły zdjęcia");
        Assert.Equal(TranslationHelper.Translation.ShowInFolder, "Pokaż w folderze");
        Assert.Equal(TranslationHelper.Translation.ShowInfoWindow, "Pokaż okno z informacją");
        Assert.Equal(TranslationHelper.Translation.ShowResizeWindow, "Pokaż okno Zmiana rozmiaru");
        Assert.Equal(TranslationHelper.Translation.ShowUI, "Pokaż interfejs");
        Assert.Equal(TranslationHelper.Translation.ShutterPriority, "Priorytet migawki");
        Assert.Equal(TranslationHelper.Translation.SideBySide, "Obok siebie");
        Assert.Equal(TranslationHelper.Translation.SideBySideTooltip, "Pokaż obrazy obok siebie");
        Assert.Equal(TranslationHelper.Translation.Size, "Szerokość");
        Assert.Equal(TranslationHelper.Translation.SizeMp, "Rozmiar (mp)");
        Assert.Equal(TranslationHelper.Translation.SizeTooltip, "Wprowadź rozmiar w pikselach lub procentach.");
        Assert.Equal(TranslationHelper.Translation.Sketch, "Szkic");
        Assert.Equal(TranslationHelper.Translation.Slideshow, "Pokaz");
        Assert.Equal(TranslationHelper.Translation.SmoothMagnify, "Gładkie wyostrzenie");
        Assert.Equal(TranslationHelper.Translation.Soft, "Miękki");
        Assert.Equal(TranslationHelper.Translation.Software, "Oprogramowanie");
        Assert.Equal(TranslationHelper.Translation.SortFilesBy, "Posortuj pliki po");
        Assert.Equal(TranslationHelper.Translation.SourceFolder, "Folder źródłowy");
        Assert.Equal(TranslationHelper.Translation.Space, "Spacja");
        Assert.Equal(TranslationHelper.Translation.Square, "Kwadrat");
        Assert.Equal(TranslationHelper.Translation.Start, "Rozpocznij");
        Assert.Equal(TranslationHelper.Translation.StartSlideshow, "Rozpocznij pokaz");
        Assert.Equal(TranslationHelper.Translation.StayCentered, "Pozostaw okno wyśrodkowane");
        Assert.Equal(TranslationHelper.Translation.StayTopMost, "Pozostań ponad innymi oknami");
        Assert.Equal(TranslationHelper.Translation.Stretch, "Rozciągnij");
        Assert.Equal(TranslationHelper.Translation.StretchImage, "Rozciągnij obraz");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightDetected, "Wykryto światło powrotne");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightNotDetected, "Nie wykryto światła powrotnego");
        Assert.Equal(TranslationHelper.Translation.Subject, "Temat");
        Assert.Equal(TranslationHelper.Translation.Swirl, "Wir");
        Assert.Equal(TranslationHelper.Translation.TelescopicBlur, "Rozmycie teleskopowe");
        Assert.Equal(TranslationHelper.Translation.Theme, "Motyw");
        Assert.Equal(TranslationHelper.Translation.Thumbnail, "Miniatura");
        Assert.Equal(TranslationHelper.Translation.Tile, "Kafelek");
        Assert.Equal(TranslationHelper.Translation.Title, "Tytuł");
        Assert.Equal(TranslationHelper.Translation.ToggleBackgroundColor, "Włącz kolor tła");
        Assert.Equal(TranslationHelper.Translation.ToggleFullscreen, "Włącz tryb pełnoekranowy");
        Assert.Equal(TranslationHelper.Translation.ToggleLooping, "Włącz zapętlenie");
        Assert.Equal(TranslationHelper.Translation.ToggleScroll, "Włącz scroll");
        Assert.Equal(TranslationHelper.Translation.ToggleTaskbarProgress, "Wyświetl postęp na pasku zadań");
        Assert.Equal(TranslationHelper.Translation.ToneMapping, "Odwzorowanie tonalne");
        Assert.Equal(TranslationHelper.Translation.UnableToRender, "Nie można wyświetlić obrazu");
        Assert.Equal(TranslationHelper.Translation.Uncalibrated, "Niekalibrowany");
        Assert.Equal(TranslationHelper.Translation.Underwater, "Pod wodą");
        Assert.Equal(TranslationHelper.Translation.UnexpectedError, "Wystąpił nieznany błąd");
        Assert.Equal(TranslationHelper.Translation.Unflip, "Cofnij przewracanie");
        Assert.Equal(TranslationHelper.Translation.Uniform, "Jednolity");
        Assert.Equal(TranslationHelper.Translation.UniformToFill, "JednolityDoWypełnienia");
        Assert.Equal(TranslationHelper.Translation.Unknown, "Nieznane");
        Assert.Equal(TranslationHelper.Translation.UnsupportedFile, "Nieobsługiwany plik");
        Assert.Equal(TranslationHelper.Translation.Up, "Góra");
        Assert.Equal(TranslationHelper.Translation.UsingMouse, "Używanie myszy");
        Assert.Equal(TranslationHelper.Translation.UsingTouchpad, "Używanie touchpada");
        Assert.Equal(TranslationHelper.Translation.Version, "Wersja:");
        Assert.Equal(TranslationHelper.Translation.ViewLicenseFile, "Pokaż licencję");
        Assert.Equal(TranslationHelper.Translation.WaveWarper, "Fale");
        Assert.Equal(TranslationHelper.Translation.WhiteBalance, "Balans bieli");
        Assert.Equal(TranslationHelper.Translation.WhiteFluorescent, "Biały - świetlówka");
        Assert.Equal(TranslationHelper.Translation.Width, "Szerokość");
        Assert.Equal(TranslationHelper.Translation.WidthAndHeight, "Szerokość i wysokość");
        Assert.Equal(TranslationHelper.Translation.WindowManagement, "Zarządzanie oknem");
        Assert.Equal(TranslationHelper.Translation.WindowScaling, "Skalowanie okna");
        Assert.Equal(TranslationHelper.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationHelper.Translation.ZoomIn, "Przybliż");
        Assert.Equal(TranslationHelper.Translation.ZoomOut, "Oddal");
        Assert.Equal(TranslationHelper.Translation._1Star, "Ocena 1 gwiazdki");
        Assert.Equal(TranslationHelper.Translation._2Star, "Ocena 2 gwiazdek");
        Assert.Equal(TranslationHelper.Translation._3Star, "Ocena 3 gwiazdek");
        Assert.Equal(TranslationHelper.Translation._4Star, "Ocena 4 gwiazdek");
        Assert.Equal(TranslationHelper.Translation._5Star, "Ocena 5 gwiazdek");
    }
}