using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class PolishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckPolishLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("pl");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "Informacje");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Program akcji");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "dodano do schowka");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Dodatkowe funkcje");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed,
            "Dostosuj prędkość: gdy klawisz jest trzymany wciśnięty");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Zmień czas na zdjęcie podczas pokazu");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Zmień prędkość przybliżania");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Dostosuj poziom przybliżenia");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Przejdź o 100 obrazów do przodu");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Przejdź o 10 obrazów do przodu");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Unikaj zmniejszania obrazu: gdy jest już w maksymalnym rozmiarze");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Wysokość");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Priorytet przysłony");
        Assert.Equal(TranslationManager.Translation.Appearance, "Wygląd");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Skróty aplikacji");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Uruchamianie aplikacji");
        Assert.Equal(TranslationManager.Translation.Apply, "Zastosuj");
        Assert.Equal(TranslationManager.Translation.Applying, "Zapisywanie");
        Assert.Equal(TranslationManager.Translation.Ascending, "Rosnąco");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Stosunek");
        Assert.Equal(TranslationManager.Translation.Authors, "Autorzy");
        Assert.Equal(TranslationManager.Translation.Auto, "Automatyczny");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Automatycznie dopasuj okno");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Archiwum nie mogło być przetworzone");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Zdjęcie z tekstu Base64");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Resize wsadowe");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Bitów głębkości koloru");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Czarny i Biały");
        Assert.Equal(TranslationManager.Translation.Blur, "Rozmycie");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Liczba elementów na dole galerii");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Prześrodkuj miniatury na dole galerii");
        Assert.Equal(TranslationManager.Translation.Brightness, "Jasność");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Producent aparatu");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Model aparatu");
        Assert.Equal(TranslationManager.Translation.Cancel, "Anuluj");
        Assert.Equal(TranslationManager.Translation.Center, "Wycentruj");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Wyśrodkuj okno");
        Assert.Equal(TranslationManager.Translation.Centimeters, "centymetrów");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Zmień tło");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Zmień kolor tła dla obrazów z przezroczystym tłem");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Kliknij na polu tekstowym: aby zmienić przypisanie klawiszy. Naciśnięcie klawisza Esc odwiązuje klawisz.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip,
            "Kliknij: aby zmienić przypisanie klawisza");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart,
            "* Zmiana motywu wymaga restartu programu");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Sprawdź aktualizacje");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Zdjęcie ze schowka");
        Assert.Equal(TranslationManager.Translation.Close, "Zamknij");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Zamyka aplikację");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Zamknij galerię");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Czy chcesz zamknąć okno?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Pochmurno");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Narzędzie wyboru koloru");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Wybierz kolor ze zdjęcia");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Reprezentacja kolorów");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Odcień");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Kompresja bitów na piksel");
        Assert.Equal(TranslationManager.Translation.Compression, "Kompresja");
        Assert.Equal(TranslationManager.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Konwertuj na");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Zamieniono na Base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Zimny biały - świetlówka");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Obraz skopiowany do schowka");
        Assert.Equal(TranslationManager.Translation.Copy, "Kopiuj");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Kopiuj plik");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Skopiuj obraz");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Skopiuj jako obraz Schowka Windows");
        Assert.Equal(TranslationManager.Translation.Copyright, "Prawa autorskie");
        Assert.Equal(TranslationManager.Translation.Created, "Utworzony");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Czasie stworzenia");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Program kreatywny");
        Assert.Equal(TranslationManager.Translation.Credits, "Autorzy");
        Assert.Equal(TranslationManager.Translation.Crop, "Przytnij");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Wciśnij Esc aby zamknąć: Enter aby zapisać");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Przytnij zdjęcie");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom,
            "Wciśnij Ctrl aby przybliżyć: użyj kółka myszy aby się poruszać");
        Assert.Equal(TranslationManager.Translation.Cut, "Wytnij");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Ciemny motyw");
        Assert.Equal(TranslationManager.Translation.Date, "Data");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Data wykonania");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Dzienny biały - świetlówka");
        Assert.Equal(TranslationManager.Translation.Daylight, "Światło dzienne");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Światło dzienne - świetlówka");
        Assert.Equal(TranslationManager.Translation.Del, "Del");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Usuń plik");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently, "Czy na pewno chcesz trwale usunąć");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Usunięto");
        Assert.Equal(TranslationManager.Translation.Descending, "Malejący");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Zoom cyfrowy");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover, "Wyłącz przyciski fade-in po najechaniu myszką");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Rozmiar na dysku");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Podwójne kliknięcie");
        Assert.Equal(TranslationManager.Translation.Down, "Dół");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Przeciągnij plik do Eksploratora lub innej aplikacji/przeglądarki");
        Assert.Equal(TranslationManager.Translation.DragImage, "Przeciągnij obraz");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Upuść obraz: aby wczytać");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Duplikuj plik");
        Assert.Equal(TranslationManager.Translation.Effects, "Efekty");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Pokaż okno z efektami zdjęć");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Zamyka obecnie otwarte okno/menu");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Wersja Exif");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Rozszerzone elementy galerii");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Kompensacja ekspozycji");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Program ekspozycji");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Czas ekspozycji");
        Assert.Equal(TranslationManager.Translation.File, "plik");
        Assert.Equal(TranslationManager.Translation.FileCopy, "Dodano plik do schowka");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Kopiuj ścieżkę do pliku");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Ścieżka do pliku dodana do schowka");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "Wycięto plik");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Rozszerzeniu");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Zarządzanie plikami");
        Assert.Equal(TranslationManager.Translation.FileName, "Nazwie");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Wklej");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Ustawienia pliku");
        Assert.Equal(TranslationManager.Translation.FileSize, "Rozmiarze");
        Assert.Equal(TranslationManager.Translation.Files, "pliki");
        Assert.Equal(TranslationManager.Translation.Fill, "Wypełnij");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Rozszerz na wysokość");
        Assert.Equal(TranslationManager.Translation.FillSquare, "WypełnijKwadrat");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Dobra pogoda");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Pierwszy obraz");
        Assert.Equal(TranslationManager.Translation.Fit, "Dopasuj");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Dopasuj do okna/obrazu");
        Assert.Equal(TranslationManager.Translation.Flash, "Błysk");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Błysk nie wyzwolony");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Energia błysku");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Błysk wyzwolony");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Tryb błysku");
        Assert.Equal(TranslationManager.Translation.Flip, "Przeróć poziomo");
        Assert.Equal(TranslationManager.Translation.Flipped, "Przerócone");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Świetlówka");
        Assert.Equal(TranslationManager.Translation.FNumber, "Liczba F");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Długość ogniskowej");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Długość ogniskowej (35mm)");
        Assert.Equal(TranslationManager.Translation.Folder, "Folder");
        Assert.Equal(TranslationManager.Translation.Forward, "Do przodu");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationManager.Translation.FullPath, "Pełna ścieżka");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Pełny ekran");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Ustawienia galerii");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "Przytnij miniatury");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Ustawienia ogólne");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Generuj miniatury");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Repozytorium na Github");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Motyw szklany");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Przejdź o 100 obrazów do tyłu");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Przejdź o 10 obrazów do tyłu");
        Assert.Equal(TranslationManager.Translation.Hard, "Twardy");
        Assert.Equal(TranslationManager.Translation.Height, "Wysokość");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Ukryj dolną galerię");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Ukryj dolny pasek narzędzi");
        Assert.Equal(TranslationManager.Translation.HideUI, "Ukryj interfejs");
        Assert.Equal(TranslationManager.Translation.High, "Wysoki");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Wysoka jakość");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Kolor zaznaczenia");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "Czułość ISO");
        Assert.Equal(TranslationManager.Translation.Image, "Obraz");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Aliasing obrazu");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Kontrola obrazu");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Szczegóły obrazu");
        Assert.Equal(TranslationManager.Translation.Inches, "cali");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Okno z informacją");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Informacje i skróty");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Konfiguracja interfejsu");
        Assert.Equal(TranslationManager.Translation.Landscape, "Krajobrazowy");
        Assert.Equal(TranslationManager.Translation.Language, "Język");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Czasie ostatniego dostępu");
        Assert.Equal(TranslationManager.Translation.LastImage, "Ostatni obraz");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Czasie ostatniego zapisu");
        Assert.Equal(TranslationManager.Translation.Latitude, "Szerokość geograficzna");
        Assert.Equal(TranslationManager.Translation.Left, "Lewo");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Producent obiektywu");
        Assert.Equal(TranslationManager.Translation.LensModel, "Model obiektywu");
        Assert.Equal(TranslationManager.Translation.LightSource, "Źródło światła");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Jasny motyw");
        Assert.Equal(TranslationManager.Translation.Lighting, "Oświetlenie");
        Assert.Equal(TranslationManager.Translation.Loading, "Ładowanie...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Długość geograficzna");
        Assert.Equal(TranslationManager.Translation.Looping, "Zapętlanie");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Zapętlenie wyłączone");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Zapętlenie włączone");
        Assert.Equal(TranslationManager.Translation.Lossless, "Bezstratna");
        Assert.Equal(TranslationManager.Translation.Lossy, "Stratna");
        Assert.Equal(TranslationManager.Translation.Low, "Niski");
        Assert.Equal(TranslationManager.Translation.Manual, "Ręczny");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Maksymalna przysłona");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maksymalizuj");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "megapikseli");
        Assert.Equal(TranslationManager.Translation.Meter, "Metr");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Tryb pomiaru");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimalizuj");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Pozostałe ustawienia");
        Assert.Equal(TranslationManager.Translation.Modified, "Zmodyfikowany");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Przenieś");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Przycisk myszy wstecz");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Przycisk myszy wprzód");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Kółko myszy");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Przenieś okno");
        Assert.Equal(TranslationManager.Translation.Navigation, "Nawigacja");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Najbliższy sąsiad");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Przeciwne kolory");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Nowe okno");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Przejdź do następnego folderu");
        Assert.Equal(TranslationManager.Translation.NextImage, "Kolejny obraz");
        Assert.Equal(TranslationManager.Translation.NoChange, "Brak zmian");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Bez konwersji");
        Assert.Equal(TranslationManager.Translation.NoImage, "Brak obrazu");
        Assert.Equal(TranslationManager.Translation.NoImages, "Brak obrazów");
        Assert.Equal(TranslationManager.Translation.NoResize, "Brak zmiany");
        Assert.Equal(TranslationManager.Translation.None, "Nic");
        Assert.Equal(TranslationManager.Translation.Normal, "Normalny");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Normalne okno");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Nie zdefiniowano");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Klawisz \"-\" klawiatury numerycznej");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Klawisz \"+\" klawiatury numerycznej");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Stary film");
        Assert.Equal(TranslationManager.Translation.Open, "Otwórz");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Wybierz plik");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Otwórz pliki w tym samym oknie");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Otwórz ostatni plik");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Otwórz przy pomocy...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Optymalizuj zdjęcie");
        Assert.Equal(TranslationManager.Translation.Orientation, "Orientacja");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Folder wyjściowy");
        Assert.Equal(TranslationManager.Translation.Pan, "Pochyl");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Archiwa chronione hasłem nie są wspierane");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Wklej zdjęcie ze schowka");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Szkic ołówkiem");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% ukończono...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Procent");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Usuń trwale");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Interpretacja fotometryczna");
        Assert.Equal(TranslationManager.Translation.Pixels, "pikseli");
        Assert.Equal(TranslationManager.Translation.Portrait, "Portretowy");
        Assert.Equal(TranslationManager.Translation.PressKey, "Naciśnij klawisz...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Przejdź do poprzedniego folderu");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Poprzedni obraz");
        Assert.Equal(TranslationManager.Translation.Print, "Drukuj");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Rozmiar wydruku (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Rozmiar wydruku (cale)");
        Assert.Equal(TranslationManager.Translation.Quality, "Jakość");
        Assert.Equal(TranslationManager.Translation.Random, "Losowo");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Ostatnie pliki");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Redukcja efektu czerwonych oczu");
        Assert.Equal(TranslationManager.Translation.Reload, "Przeładuj");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Usuń ocenę");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Zmień nazwę");
        Assert.Equal(TranslationManager.Translation.Reset, "Zresetuj");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Przywróć domyślne");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Resetuj zoom");
        Assert.Equal(TranslationManager.Translation.Resize, "Zmień rozmiar");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Zmień rozmiar obrazu");
        Assert.Equal(TranslationManager.Translation.Resolution, "Rozdzielczość");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Jednostka rozdzielczości");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Zrestartuj aplikację");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Przywróć");
        Assert.Equal(TranslationManager.Translation.Reverse, "Odwrócić");
        Assert.Equal(TranslationManager.Translation.Right, "Prawo");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Obróć w lewo");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Obróć w prawo");
        Assert.Equal(TranslationManager.Translation.Rotated, "Obrócone");
        Assert.Equal(TranslationManager.Translation.Saturation, "Nasycenie");
        Assert.Equal(TranslationManager.Translation.Save, "Zapisz");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Zapisz jako");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Zapis pliku nie powiódł się");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Przewijaj i obracaj");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Kierunek przewijania");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Przewiń w dół");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Przewiń na dół");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Przewiń do góry");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom,
            "Użyj kółka myszy: aby przybliżyć: wciśnij Ctrl: aby się poruszać");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Przewiń w górę");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Przewijanie");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Przewijanie wyłączone");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Przewijanie włączone");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Przeszukaj podkatalogi");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sek.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Zaznacz wszystko");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Wybierz miniaturę galerii");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin, "Przenieś obecne zdjęcie do kosza");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Przenieś plik do kosza");
        Assert.Equal(TranslationManager.Translation.SetAs, "Ustaw jako...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Ustaw jako ekran blokady");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Ustaw jako tapetę");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper, "Ustaw zdjęcie jako tapetę:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Ustawianie oceny gwiazdkowej");
        Assert.Equal(TranslationManager.Translation.Settings, "Ustawienia");
        Assert.Equal(TranslationManager.Translation.Shade, "Cień");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Ostrość");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Pokaż okno ze wszystkimi ustawieniami");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Pokaż dolną galerię");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Pokaż dolną galerię: gdy UI jest ukryte");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Pokaż dolny pasek narzędzi");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "Pokaż okno potwierdzenia po naciśnięciu 'Esc'");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover, "Pokaż przyciski fade-in po najechaniu myszką");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Pokaż okno zapisywania pliku");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Pokaż galerię zdjęć");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Pokaż szczegóły zdjęcia");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Pokaż w folderze");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Pokaż okno z informacją");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Pokaż okno Zmiana rozmiaru");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Pokaż interfejs");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Priorytet migawki");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Obok siebie");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Pokaż obrazy obok siebie");
        Assert.Equal(TranslationManager.Translation.Size, "Szerokość");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Rozmiar (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "Wprowadź rozmiar w pikselach lub procentach.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Pokaz");
        Assert.Equal(TranslationManager.Translation.Soft, "Miękki");
        Assert.Equal(TranslationManager.Translation.Software, "Oprogramowanie");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Posortuj pliki po");
        Assert.Equal(TranslationManager.Translation.Space, "Spacja");
        Assert.Equal(TranslationManager.Translation.Square, "Kwadrat");
        Assert.Equal(TranslationManager.Translation.Start, "Rozpocznij");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Rozpocznij pokaz");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Pozostaw okno wyśrodkowane");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Pozostań ponad innymi oknami");
        Assert.Equal(TranslationManager.Translation.Stretch, "Rozciągnij");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Rozciągnij obraz");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Wykryto światło powrotne");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected, "Nie wykryto światła powrotnego");
        Assert.Equal(TranslationManager.Translation.Subject, "Temat");
        Assert.Equal(TranslationManager.Translation.Theme, "Motyw");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Miniatura");
        Assert.Equal(TranslationManager.Translation.Tile, "Kafelek");
        Assert.Equal(TranslationManager.Translation.Title, "Tytuł");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Włącz kolor tła");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Włącz tryb pełnoekranowy");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Włącz zapętlenie");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Włącz scroll");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Wyświetl postęp na pasku zadań");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Nie można wyświetlić obrazu");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Niekalibrowany");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Wystąpił nieznany błąd");
        Assert.Equal(TranslationManager.Translation.Unflip, "Cofnij przewracanie");
        Assert.Equal(TranslationManager.Translation.Uniform, "Jednolity");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "JednolityDoWypełnienia");
        Assert.Equal(TranslationManager.Translation.Unknown, "Nieznane");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Nieobsługiwany plik");
        Assert.Equal(TranslationManager.Translation.Up, "Góra");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Używanie myszy");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Używanie touchpada");
        Assert.Equal(TranslationManager.Translation.Version, "Wersja:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Pokaż licencję");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Balans bieli");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Biały - świetlówka");
        Assert.Equal(TranslationManager.Translation.Width, "Szerokość");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Szerokość i wysokość");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Zarządzanie oknem");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Skalowanie okna");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Przybliż");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Oddal");
        Assert.Equal(TranslationManager.Translation._1Star, "Ocena 1 gwiazdki");
        Assert.Equal(TranslationManager.Translation._2Star, "Ocena 2 gwiazdek");
        Assert.Equal(TranslationManager.Translation._3Star, "Ocena 3 gwiazdek");
        Assert.Equal(TranslationManager.Translation._4Star, "Ocena 4 gwiazdek");
        Assert.Equal(TranslationManager.Translation._5Star, "Ocena 5 gwiazdek");
    }
}