using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class RussianUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckRussianLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("ru");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "О программе");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Программа действия");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Добавлен в буфер обмена");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Дополнительные функции");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed, "Настроить скорость при удержании клавиши");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Отрегулировать время для слайд-шоу");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Отрегулировать скорость масштабирования");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Отрегулировать уровень масштабирования");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Продвинуться на 100 изображений вперед");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Продвинуться на 10 изображений вперед");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Избегайте уменьшения изображения, когда оно уже находится в максимальном размере");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Высота");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Приоритет диафрагмы");
        Assert.Equal(TranslationManager.Translation.Appearance, "Внешний вид");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Сочетания клавиш приложения");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Запуск приложения");
        Assert.Equal(TranslationManager.Translation.Apply, "Применить");
        Assert.Equal(TranslationManager.Translation.Applying, "Применение");
        Assert.Equal(TranslationManager.Translation.Ascending, "Возрастанию");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Соотношение сторон");
        Assert.Equal(TranslationManager.Translation.Authors, "Авторы");
        Assert.Equal(TranslationManager.Translation.Auto, "Авто");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Окно автозаполнения");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Архив не может быть обработан");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Изображение Base64");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Групповое изменение размера");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Битовая глубина");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Черно-белый");
        Assert.Equal(TranslationManager.Translation.Blur, "Размытие");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Количество элементов нижней галереи");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Растягивание миниатюр в нижней галерее");
        Assert.Equal(TranslationManager.Translation.Brightness, "Яркость");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Производитель камеры");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Модель камеры");
        Assert.Equal(TranslationManager.Translation.Cancel, "Отмена");
        Assert.Equal(TranslationManager.Translation.Center, "Центрировать");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Центрировать окно");
        Assert.Equal(TranslationManager.Translation.Centimeters, "сантиметров");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Сменить фон");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Изменение цвета фона для изображений с прозрачным фоном");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Нажмите на текстовом поле, чтобы изменить сочетание клавиш. Нажатие Esc снимает привязку клавиши.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip,
            "Щелкните, чтобы изменить назначение клавиши");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart,
            "* Для изменения темы требуется перезапуск");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Проверить наличие обновлений");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Изображение из буфера обмена");
        Assert.Equal(TranslationManager.Translation.Close, "Закрыть");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Закрыть приложение");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Закрыть галерею");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Вы хотите закрыть окно?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Облачная погода");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Инструмент выбора цвета");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Выберите цвет из изображения");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Цветовое представление");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Цветовой тон");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Сжатые биты на пиксель");
        Assert.Equal(TranslationManager.Translation.Compression, "Сжатие");
        Assert.Equal(TranslationManager.Translation.Contrast, "Контраст");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Преобразовать в");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Преобразовано в base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Холодный белый флуоресцентный");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Изображение скопировано в буфер обмена");
        Assert.Equal(TranslationManager.Translation.Copy, "Копировать");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Копировать файл");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Копировать изображение");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip,
            "Копировать как изображение из буфера обмена Windows");
        Assert.Equal(TranslationManager.Translation.Copyright, "Авторское право");
        Assert.Equal(TranslationManager.Translation.Created, "Созданно");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Времени создания");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Творческая программа");
        Assert.Equal(TranslationManager.Translation.Credits, "Титры");
        Assert.Equal(TranslationManager.Translation.Crop, "Обрезать");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Нажмите Esc, чтобы закрыть, Enter, чтобы сохранить");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Кадрирование снимка");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Ctrl для увеличения, прокрутка для навигации");
        Assert.Equal(TranslationManager.Translation.Cut, "Вырезать");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Темная тема");
        Assert.Equal(TranslationManager.Translation.Date, "Дата");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Дата съемки");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Дневной белый флуоресцентный");
        Assert.Equal(TranslationManager.Translation.Daylight, "Дневной свет");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Дневной флуоресцентный");
        Assert.Equal(TranslationManager.Translation.Del, "Del");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Удалить файл");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently, "Вы уверены, что хотите удалить навсегда");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Удаленный файл");
        Assert.Equal(TranslationManager.Translation.Descending, "Убыванию");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Цифровое увеличение");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Отключить кнопки с эффектом плавного появления при наведении мыши");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Размер диска");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Двойной клик");
        Assert.Equal(TranslationManager.Translation.Down, "Вниз");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Перетащите файл в проводник Windows или другое приложение/браузер");
        Assert.Equal(TranslationManager.Translation.DragImage, "Перетащите изображение");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Перетащите, чтобы загрузить изображение");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Создать копию файла");
        Assert.Equal(TranslationManager.Translation.Effects, "Эффекты");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Показать окно эффектов изображения");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Закрывает открытое в данный момент окно/меню");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Версия Exif");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Расширенные элементы галереи");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Компенсация экспозиции");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Программа экспозиции");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Время экспозиции");
        Assert.Equal(TranslationManager.Translation.FNumber, "Число F");
        Assert.Equal(TranslationManager.Translation.File, "Файл");
        Assert.Equal(TranslationManager.Translation.FileCopy, "Файл добавлен в буфер обмена");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Копировать путь к файлу");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Путь к файлу добавлен в буфер обмена");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "Файл добавлен в буфер обмена");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Расширению файла");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Управление файлами");
        Assert.Equal(TranslationManager.Translation.FileName, "Имени файла");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Вставить");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Свойства файла");
        Assert.Equal(TranslationManager.Translation.FileSize, "Размеру файла");
        Assert.Equal(TranslationManager.Translation.Files, "Файлы");
        Assert.Equal(TranslationManager.Translation.Fill, "Наполнить");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Высота заполнения");
        Assert.Equal(TranslationManager.Translation.FillSquare, "ЗаполнитьКвадрат");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Хорошая погода");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Первое изображение");
        Assert.Equal(TranslationManager.Translation.Fit, "Соотнести");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Соотнести к изображению/окну");
        Assert.Equal(TranslationManager.Translation.Flash, "Вспышка");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Вспышка не сработала");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Энергия вспышки");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Вспышка сработала");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Режим вспышки");
        Assert.Equal(TranslationManager.Translation.Flip, "Отразить по горизонталиy");
        Assert.Equal(TranslationManager.Translation.Flipped, "Отражено");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Флуоресцентный");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Фокусное расстояние");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Фокусное расстояние (35 мм)");
        Assert.Equal(TranslationManager.Translation.Folder, "Папка");
        Assert.Equal(TranslationManager.Translation.Forward, "Вперед");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-стоп");
        Assert.Equal(TranslationManager.Translation.FullPath, "Полный путь");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Весь экран");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Настройки галерей");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "Растягивание миниатюр");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Общие настройки");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Генерировать миниатюры");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Репозиторий Github");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Стеклянная тема");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Вернуться на 100 изображений назад");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Вернуться на 10 изображений назад");
        Assert.Equal(TranslationManager.Translation.Hard, "Жесткий");
        Assert.Equal(TranslationManager.Translation.Height, "Высота");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Скрыть нижнюю галерею");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Скрыть нижнюю панель инструментов");
        Assert.Equal(TranslationManager.Translation.HideUI, "Скрыть интерфейс");
        Assert.Equal(TranslationManager.Translation.High, "Высокий");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Высокое качество");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Цвет выделения");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "Чувствительность ISO");
        Assert.Equal(TranslationManager.Translation.Image, "Изображение");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Сглаживание изображения");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Управление изображением");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Информация об изображении");
        Assert.Equal(TranslationManager.Translation.Inches, "дюймов");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Информационное окно");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Информация и сочетания клавиш");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Конфигурация интерфейса");
        Assert.Equal(TranslationManager.Translation.Landscape, "Пейзаж");
        Assert.Equal(TranslationManager.Translation.Language, "Язык");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Времени последнего доступа");
        Assert.Equal(TranslationManager.Translation.LastImage, "Последнее изображение");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Времени последней записи");
        Assert.Equal(TranslationManager.Translation.Latitude, "Широта");
        Assert.Equal(TranslationManager.Translation.Left, "Влево");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Производитель объектива");
        Assert.Equal(TranslationManager.Translation.LensModel, "Модель объектива");
        Assert.Equal(TranslationManager.Translation.LightSource, "Источник света");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Светлая тема");
        Assert.Equal(TranslationManager.Translation.Lighting, "Освещение");
        Assert.Equal(TranslationManager.Translation.Loading, "Загрузка...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Долгота");
        Assert.Equal(TranslationManager.Translation.Looping, "Зацикливание");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Цикл отключен");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Цикл включен");
        Assert.Equal(TranslationManager.Translation.Lossless, "Без потерь");
        Assert.Equal(TranslationManager.Translation.Lossy, "Потеря");
        Assert.Equal(TranslationManager.Translation.Low, "Низкий");
        Assert.Equal(TranslationManager.Translation.Manual, "Ручной");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Максимальная диафрагма");
        Assert.Equal(TranslationManager.Translation.Maximize, "Развернуть");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "мегапикселей");
        Assert.Equal(TranslationManager.Translation.Meter, "Метр");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Режим измерения");
        Assert.Equal(TranslationManager.Translation.Minimize, "Свернуть");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Прочие настройки");
        Assert.Equal(TranslationManager.Translation.Modified, "Изменено");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Перетаскивание мышью");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Клавиша мыши назад");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Клавиша мыши вперед");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Колесико мыши");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Переместить окно");
        Assert.Equal(TranslationManager.Translation.Navigation, "Навигация");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Ближайший сосед");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Обратные цвета");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Новое окно");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Перейти к следующей папке");
        Assert.Equal(TranslationManager.Translation.NextImage, "Следующее изображение");
        Assert.Equal(TranslationManager.Translation.NoChange, "Без изменений");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Нет преобразования");
        Assert.Equal(TranslationManager.Translation.NoImage, "Изображение не загружено");
        Assert.Equal(TranslationManager.Translation.NoImages, "Нет изображений");
        Assert.Equal(TranslationManager.Translation.NoResize, "Нет изменений");
        Assert.Equal(TranslationManager.Translation.None, "Никто");
        Assert.Equal(TranslationManager.Translation.Normal, "Нормальный");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Обычное окно");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Не определено");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Старый фильм");
        Assert.Equal(TranslationManager.Translation.Open, "Открыть");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Выберать файл");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Открывать файлы в том же окне");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Открыть последний файл");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Открыть вместе с...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Оптимизировать изображение");
        Assert.Equal(TranslationManager.Translation.Orientation, "Ориентация");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Папки вывода");
        Assert.Equal(TranslationManager.Translation.Pan, "Панорамировать");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Архив, защищенный паролем, не поддерживается");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Вставить изображение из буфера обмена");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Карандашный набросок");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% завершено...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Процент");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Удалить навсегда");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Фотометрическая интерпретация");
        Assert.Equal(TranslationManager.Translation.Pixels, "пиксели");
        Assert.Equal(TranslationManager.Translation.Portrait, "Портрет");
        Assert.Equal(TranslationManager.Translation.PressKey, "Нажмите клавишу...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Перейти к предыдущей папке");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Предыдущее изображение");
        Assert.Equal(TranslationManager.Translation.Print, "Распечатать");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Размер печати (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Размер печати (in)");
        Assert.Equal(TranslationManager.Translation.Quality, "Качественный");
        Assert.Equal(TranslationManager.Translation.Random, "Случайно");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Недавние файлы");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Уменьшение эффекта красных глаз");
        Assert.Equal(TranslationManager.Translation.Reload, "Перезагрузить");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Убрать рейтинг");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Переименовать файл");
        Assert.Equal(TranslationManager.Translation.Reset, "Сбросить");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Сбросить настройки по умолчанию");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Сбросить масштаб");
        Assert.Equal(TranslationManager.Translation.Resize, "Изменить размер");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Изменить размер изображения");
        Assert.Equal(TranslationManager.Translation.Resolution, "Разрешение");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Единица разрешения");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Перезапустить приложение");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Восстановить");
        Assert.Equal(TranslationManager.Translation.Reverse, "Назад");
        Assert.Equal(TranslationManager.Translation.Right, "Вправо");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Повернуть налево");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Повернуть вправо");
        Assert.Equal(TranslationManager.Translation.Rotated, "Повернуто");
        Assert.Equal(TranslationManager.Translation.Saturation, "Насыщенность");
        Assert.Equal(TranslationManager.Translation.Save, "Сохранить");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Сохранить как");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Ошибка сохранения файла");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Прокрутка и вращение");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Направление прокрутки");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Прокрутить вниз");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Прокрутить вниз");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Прокрутить вверх");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom,
            "Масштабирование с помощью колесика мыши, перемещение с помощью Ctrl");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Прокрутить вверх");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Прокрутка");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Прокрутка отключена");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Прокрутка включена");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Искать в подкаталогах");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sec.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Выбрать все");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Выбрать миниатюру галереи");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin,
            "Отправить текущее изображение в корзину");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Файл отправлен в корзину");
        Assert.Equal(TranslationManager.Translation.SetAs, "Установить как...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Установить на экран блокировки");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Сделать фоновым рисунком");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Установить текущее изображение в качестве обоев:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Установить рейтинг звезд");
        Assert.Equal(TranslationManager.Translation.Settings, "Настройки");
        Assert.Equal(TranslationManager.Translation.Shade, "Тень");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Резкость");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Показать окно всех настроек");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Показать нижнюю галерею");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Показывать нижнюю галерею при скрытом интерфейсе");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Показать нижнюю панель инструментов");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "Показывать диалог подтверждения при нажатии 'Esc'");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover,
            "Показать кнопки с эффектом плавного появления при наведении мыши");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Показать диалоговое окно сохранения файла");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Показать галерею изображений");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Показать информацию об изображении");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Показать в папке");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Показать информационное окно");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Показать окно изменения размера");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Afișează interfața");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Приоритет затвора");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Бок о бок");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Показывать изображения рядом");
        Assert.Equal(TranslationManager.Translation.Size, "Размер");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Размер (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "Введите желаемый размер в пикселях или процентах.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Слайдшоу");
        Assert.Equal(TranslationManager.Translation.Soft, "Мягкий");
        Assert.Equal(TranslationManager.Translation.Software, "Программное обеспечение");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Сортировать файлы по");
        Assert.Equal(TranslationManager.Translation.Space, "Space");
        Assert.Equal(TranslationManager.Translation.Square, "Квадрат");
        Assert.Equal(TranslationManager.Translation.Start, "Начинать");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Начать слайдшоу");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Зафиксировать окно по центру");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Оставаться поверх других окон");
        Assert.Equal(TranslationManager.Translation.Stretch, "Растянуть");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Растянуть изображение");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Вспышка обнаружила возвратный свет");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected,
            "Вспышка не обнаружила возвратного света");
        Assert.Equal(TranslationManager.Translation.Subject, "Тема");
        Assert.Equal(TranslationManager.Translation.Theme, "Тема");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Thumb");
        Assert.Equal(TranslationManager.Translation.Tile, "Плитка");
        Assert.Equal(TranslationManager.Translation.Title, "Заголовок");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Переключить цвет фона");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Включить полноэкранный режим");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Переключить цикл");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Переключить прокрутку");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Отображение прогресса на панели задач");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Невозможно отобразить изображение");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Некалиброванный");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Произошла неизвестная ошибка");
        Assert.Equal(TranslationManager.Translation.Unflip, "Развернуть");
        Assert.Equal(TranslationManager.Translation.Uniform, "Равномерный");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "РавномерныйДляЗаполнения");
        Assert.Equal(TranslationManager.Translation.Unknown, "Неизвестно");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Неподдерживаемый файл");
        Assert.Equal(TranslationManager.Translation.Up, "Вверх");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Использование мыши");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Использование тачпада");
        Assert.Equal(TranslationManager.Translation.Version, "Версия:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Просмотреть файл лицензии");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Баланс белого");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Белый флуоресцентный");
        Assert.Equal(TranslationManager.Translation.Width, "Ширина");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Ширина и высота");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Управление окнами");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Масштабирование окна");
        Assert.Equal(TranslationManager.Translation.Zoom, "Зуммирование");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Увеличить");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Уменьшить");
        Assert.Equal(TranslationManager.Translation._1Star, "1 звезда");
        Assert.Equal(TranslationManager.Translation._2Star, "2звезды");
        Assert.Equal(TranslationManager.Translation._3Star, "3звезды");
        Assert.Equal(TranslationManager.Translation._4Star, "4звезды");
        Assert.Equal(TranslationManager.Translation._5Star, "5звезды");
    }
}