using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class RussianUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckRussianLanguage()
    {
        var exists = await TranslationHelper.LoadLanguage("pt-br");
        Assert.True(exists);

        Assert.Equal(TranslationHelper.Translation.About, "О программе");
        Assert.Equal(TranslationHelper.Translation.ActionProgram, "Программа действия");
        Assert.Equal(TranslationHelper.Translation.AddedToClipboard, "Добавлен в буфер обмена");
        Assert.Equal(TranslationHelper.Translation.AdditionalFunctions, "Дополнительные функции");
        Assert.Equal(TranslationHelper.Translation.AdjustNavSpeed, "Настроить скорость при удержании клавиши");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForSlideshow, "Отрегулировать время для слайд-шоу");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForZoom, "Отрегулировать скорость масштабирования");
        Assert.Equal(TranslationHelper.Translation.AdjustZoomLevel, "Отрегулировать уровень масштабирования");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy100Images, "Продвинуться на 100 изображений вперед");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy10Images, "Продвинуться на 10 изображений вперед");
        Assert.Equal(TranslationHelper.Translation.AllowZoomOut,
            "Избегайте уменьшения изображения, когда оно уже находится в максимальном размере");
        Assert.Equal(TranslationHelper.Translation.Alt, "Alt");
        Assert.Equal(TranslationHelper.Translation.Altitude, "Высота");
        Assert.Equal(TranslationHelper.Translation.AperturePriority, "Приоритет диафрагмы");
        Assert.Equal(TranslationHelper.Translation.Appearance, "Внешний вид");
        Assert.Equal(TranslationHelper.Translation.ApplicationShortcuts, "Сочетания клавиш приложения");
        Assert.Equal(TranslationHelper.Translation.ApplicationStartup, "Запуск приложения");
        Assert.Equal(TranslationHelper.Translation.Apply, "Применить");
        Assert.Equal(TranslationHelper.Translation.Applying, "Применение");
        Assert.Equal(TranslationHelper.Translation.Ascending, "Возрастанию");
        Assert.Equal(TranslationHelper.Translation.AspectRatio, "Соотношение сторон");
        Assert.Equal(TranslationHelper.Translation.Authors, "Авторы");
        Assert.Equal(TranslationHelper.Translation.Auto, "Авто");
        Assert.Equal(TranslationHelper.Translation.AutoFitWindow, "Окно автозаполнения");
        Assert.Equal(TranslationHelper.Translation.BadArchive, "Архив не может быть обработан");
        Assert.Equal(TranslationHelper.Translation.BandedSwirl, "Водоворот");
        Assert.Equal(TranslationHelper.Translation.Bands, "Группы");
        Assert.Equal(TranslationHelper.Translation.Base64Image, "Изображение Base64");
        Assert.Equal(TranslationHelper.Translation.BatchResize, "Групповое изменение размера");
        Assert.Equal(TranslationHelper.Translation.BitDepth, "Битовая глубина");
        Assert.Equal(TranslationHelper.Translation.BlackAndWhite, "Черно-белый");
        Assert.Equal(TranslationHelper.Translation.Bloom, "Цветение");
        Assert.Equal(TranslationHelper.Translation.Blur, "Размытие");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryItemSize, "Количество элементов нижней галереи");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryThumbnailStretch,
            "Растягивание миниатюр в нижней галерее");
        Assert.Equal(TranslationHelper.Translation.Brightness, "Яркость");
        Assert.Equal(TranslationHelper.Translation.CameraMaker, "Производитель камеры");
        Assert.Equal(TranslationHelper.Translation.CameraModel, "Модель камеры");
        Assert.Equal(TranslationHelper.Translation.Cancel, "Отмена");
        Assert.Equal(TranslationHelper.Translation.Center, "Центрировать");
        Assert.Equal(TranslationHelper.Translation.CenterWindow, "Центрировать окно");
        Assert.Equal(TranslationHelper.Translation.Centimeters, "сантиметров");
        Assert.Equal(TranslationHelper.Translation.ChangeBackground, "Сменить фон");
        Assert.Equal(TranslationHelper.Translation.ChangeBackgroundTooltip,
            "Изменение цвета фона для изображений с прозрачным фоном");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingText,
            "Нажмите на текстовом поле, чтобы изменить сочетание клавиш. Нажатие Esc снимает привязку клавиши.");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingTooltip,
            "Щелкните, чтобы изменить назначение клавиши");
        Assert.Equal(TranslationHelper.Translation.ChangingThemeRequiresRestart,
            "* Для изменения темы требуется перезапуск");
        Assert.Equal(TranslationHelper.Translation.CheckForUpdates, "Проверить наличие обновлений");
        Assert.Equal(TranslationHelper.Translation.ClipboardImage, "Изображение из буфера обмена");
        Assert.Equal(TranslationHelper.Translation.Close, "Закрыть");
        Assert.Equal(TranslationHelper.Translation.CloseApp, "Закрыть приложение");
        Assert.Equal(TranslationHelper.Translation.CloseGallery, "Закрыть галерею");
        Assert.Equal(TranslationHelper.Translation.CloseWindowPrompt, "Вы хотите закрыть окно?");
        Assert.Equal(TranslationHelper.Translation.CloudyWeather, "Облачная погода");
        Assert.Equal(TranslationHelper.Translation.ColorPickerTool, "Инструмент выбора цвета");
        Assert.Equal(TranslationHelper.Translation.ColorPickerToolTooltip, "Выберите цвет из изображения");
        Assert.Equal(TranslationHelper.Translation.ColorRepresentation, "Цветовое представление");
        Assert.Equal(TranslationHelper.Translation.ColorTone, "Цветовой тон");
        Assert.Equal(TranslationHelper.Translation.CompressedBitsPixel, "Сжатые биты на пиксель");
        Assert.Equal(TranslationHelper.Translation.Compression, "Сжатие");
        Assert.Equal(TranslationHelper.Translation.Contrast, "Контраст");
        Assert.Equal(TranslationHelper.Translation.ConvertTo, "Преобразовать в");
        Assert.Equal(TranslationHelper.Translation.ConvertedToBase64, "Преобразовано в base64");
        Assert.Equal(TranslationHelper.Translation.CoolWhiteFluorescent, "Холодный белый флуоресцентный");
        Assert.Equal(TranslationHelper.Translation.CopiedImage, "Изображение скопировано в буфер обмена");
        Assert.Equal(TranslationHelper.Translation.Copy, "Копировать");
        Assert.Equal(TranslationHelper.Translation.CopyFile, "Копировать файл");
        Assert.Equal(TranslationHelper.Translation.CopyImage, "Копировать изображение");
        Assert.Equal(TranslationHelper.Translation.CopyImageTooltip,
            "Копировать как изображение из буфера обмена Windows");
        Assert.Equal(TranslationHelper.Translation.Copyright, "Авторское право");
        Assert.Equal(TranslationHelper.Translation.Created, "Созданно");
        Assert.Equal(TranslationHelper.Translation.CreationTime, "Времени создания");
        Assert.Equal(TranslationHelper.Translation.CreativeProgram, "Творческая программа");
        Assert.Equal(TranslationHelper.Translation.Credits, "Титры");
        Assert.Equal(TranslationHelper.Translation.Crop, "Обрезать");
        Assert.Equal(TranslationHelper.Translation.CropMessage, "Нажмите Esc, чтобы закрыть, Enter, чтобы сохранить");
        Assert.Equal(TranslationHelper.Translation.CropPicture, "Кадрирование снимка");
        Assert.Equal(TranslationHelper.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationHelper.Translation.CtrlToZoom, "Ctrl для увеличения, прокрутка для навигации");
        Assert.Equal(TranslationHelper.Translation.Cut, "Вырезать");
        Assert.Equal(TranslationHelper.Translation.DarkTheme, "Темная тема");
        Assert.Equal(TranslationHelper.Translation.Date, "Дата");
        Assert.Equal(TranslationHelper.Translation.DateTaken, "Дата съемки");
        Assert.Equal(TranslationHelper.Translation.DayWhiteFluorescent, "Дневной белый флуоресцентный");
        Assert.Equal(TranslationHelper.Translation.Daylight, "Дневной свет");
        Assert.Equal(TranslationHelper.Translation.DaylightFluorescent, "Дневной флуоресцентный");
        Assert.Equal(TranslationHelper.Translation.Del, "Del");
        Assert.Equal(TranslationHelper.Translation.DeleteFile, "Удалить файл");
        Assert.Equal(TranslationHelper.Translation.DeleteFilePermanently, "Вы уверены, что хотите удалить навсегда");
        Assert.Equal(TranslationHelper.Translation.DeletedFile, "Удаленный файл");
        Assert.Equal(TranslationHelper.Translation.Descending, "Убыванию");
        Assert.Equal(TranslationHelper.Translation.DigitalZoom, "Цифровое увеличение");
        Assert.Equal(TranslationHelper.Translation.DirectionalBlur, "Направленное размытие");
        Assert.Equal(TranslationHelper.Translation.DisableFadeInButtonsOnHover,
            "Отключить кнопки с эффектом плавного появления при наведении мыши");
        Assert.Equal(TranslationHelper.Translation.DiskSize, "Размер диска");
        Assert.Equal(TranslationHelper.Translation.DoubleClick, "Двойной клик");
        Assert.Equal(TranslationHelper.Translation.Down, "Вниз");
        Assert.Equal(TranslationHelper.Translation.Dpi, "DPI");
        Assert.Equal(TranslationHelper.Translation.DragFileTo,
            "Перетащите файл в проводник Windows или другое приложение/браузер");
        Assert.Equal(TranslationHelper.Translation.DragImage, "Перетащите изображение");
        Assert.Equal(TranslationHelper.Translation.DropToLoad, "Перетащите, чтобы загрузить изображение");
        Assert.Equal(TranslationHelper.Translation.DuplicateFile, "Создать копию файла");
        Assert.Equal(TranslationHelper.Translation.Effects, "Эффекты");
        Assert.Equal(TranslationHelper.Translation.EffectsTooltip, "Показать окно эффектов изображения");
        Assert.Equal(TranslationHelper.Translation.Embossed, "Тисненый");
        Assert.Equal(TranslationHelper.Translation.Enter, "Enter");
        Assert.Equal(TranslationHelper.Translation.Esc, "Esc");
        Assert.Equal(TranslationHelper.Translation.EscCloseTooltip, "Закрывает открытое в данный момент окно/меню");
        Assert.Equal(TranslationHelper.Translation.ExifVersion, "Версия Exif");
        Assert.Equal(TranslationHelper.Translation.ExpandedGalleryItemSize, "Расширенные элементы галереи");
        Assert.Equal(TranslationHelper.Translation.ExposureBias, "Компенсация экспозиции");
        Assert.Equal(TranslationHelper.Translation.ExposureProgram, "Программа экспозиции");
        Assert.Equal(TranslationHelper.Translation.ExposureTime, "Время экспозиции");
        Assert.Equal(TranslationHelper.Translation.FNumber, "Число F");
        Assert.Equal(TranslationHelper.Translation.File, "Файл");
        Assert.Equal(TranslationHelper.Translation.FileCopy, "Файл добавлен в буфер обмена");
        Assert.Equal(TranslationHelper.Translation.FileCopyPath, "Копировать путь к файлу");
        Assert.Equal(TranslationHelper.Translation.FileCopyPathMessage, "Путь к файлу добавлен в буфер обмена");
        Assert.Equal(TranslationHelper.Translation.FileCutMessage, "Файл добавлен в буфер обмена");
        Assert.Equal(TranslationHelper.Translation.FileExtension, "Расширению файла");
        Assert.Equal(TranslationHelper.Translation.FileManagement, "Управление файлами");
        Assert.Equal(TranslationHelper.Translation.FileName, "Имени файла");
        Assert.Equal(TranslationHelper.Translation.FilePaste, "Вставить");
        Assert.Equal(TranslationHelper.Translation.FileProperties, "Свойства файла");
        Assert.Equal(TranslationHelper.Translation.FileSize, "Размеру файла");
        Assert.Equal(TranslationHelper.Translation.Files, "Файлы");
        Assert.Equal(TranslationHelper.Translation.Fill, "Наполнить");
        Assert.Equal(TranslationHelper.Translation.FillHeight, "⇔ Высота заполнения");
        Assert.Equal(TranslationHelper.Translation.FillSquare, "ЗаполнитьКвадрат");
        Assert.Equal(TranslationHelper.Translation.FineWeather, "Хорошая погода");
        Assert.Equal(TranslationHelper.Translation.FirstImage, "Первое изображение");
        Assert.Equal(TranslationHelper.Translation.Fit, "Соотнести");
        Assert.Equal(TranslationHelper.Translation.FitToWindow, "Соотнести к изображению/окну");
        Assert.Equal(TranslationHelper.Translation.Flash, "Вспышка");
        Assert.Equal(TranslationHelper.Translation.FlashDidNotFire, "Вспышка не сработала");
        Assert.Equal(TranslationHelper.Translation.FlashEnergy, "Энергия вспышки");
        Assert.Equal(TranslationHelper.Translation.FlashFired, "Вспышка сработала");
        Assert.Equal(TranslationHelper.Translation.FlashMode, "Режим вспышки");
        Assert.Equal(TranslationHelper.Translation.Flip, "Отразить по горизонталиy");
        Assert.Equal(TranslationHelper.Translation.Flipped, "Отражено");
        Assert.Equal(TranslationHelper.Translation.Fluorescent, "Флуоресцентный");
        Assert.Equal(TranslationHelper.Translation.FocalLength, "Фокусное расстояние");
        Assert.Equal(TranslationHelper.Translation.FocalLength35mm, "Фокусное расстояние (35 мм)");
        Assert.Equal(TranslationHelper.Translation.Folder, "Папка");
        Assert.Equal(TranslationHelper.Translation.Forward, "Вперед");
        Assert.Equal(TranslationHelper.Translation.FrostyOutline, "Морозный контур");
        Assert.Equal(TranslationHelper.Translation.Fstop, "F-стоп");
        Assert.Equal(TranslationHelper.Translation.FullPath, "Полный путь");
        Assert.Equal(TranslationHelper.Translation.Fullscreen, "Весь экран");
        Assert.Equal(TranslationHelper.Translation.GallerySettings, "Настройки галерей");
        Assert.Equal(TranslationHelper.Translation.GalleryThumbnailStretch, "Растягивание миниатюр");
        Assert.Equal(TranslationHelper.Translation.GeneralSettings, "Общие настройки");
        Assert.Equal(TranslationHelper.Translation.GenerateThumbnails, "Генерировать миниатюры");
        Assert.Equal(TranslationHelper.Translation.GithubRepo, "Репозиторий Github");
        Assert.Equal(TranslationHelper.Translation.GlassTheme, "Стеклянная тема");
        Assert.Equal(TranslationHelper.Translation.GlassTile, "Стеклянная плитка");
        Assert.Equal(TranslationHelper.Translation.Gloom, "Мрак");
        Assert.Equal(TranslationHelper.Translation.GoBackBy100Images, "Вернуться на 100 изображений назад");
        Assert.Equal(TranslationHelper.Translation.GoBackBy10Images, "Вернуться на 10 изображений назад");
        Assert.Equal(TranslationHelper.Translation.GoToImageAtSpecifiedIndex,
            "Перейти к изображению по указанному индексу");
        Assert.Equal(TranslationHelper.Translation.Hard, "Жесткий");
        Assert.Equal(TranslationHelper.Translation.Height, "Высота");
        Assert.Equal(TranslationHelper.Translation.HideBottomGallery, "Скрыть нижнюю галерею");
        Assert.Equal(TranslationHelper.Translation.HideBottomToolbar, "Скрыть нижнюю панель инструментов");
        Assert.Equal(TranslationHelper.Translation.HideUI, "Скрыть интерфейс");
        Assert.Equal(TranslationHelper.Translation.High, "Высокий");
        Assert.Equal(TranslationHelper.Translation.HighQuality, "Высокое качество");
        Assert.Equal(TranslationHelper.Translation.HighlightColor, "Цвет выделения");
        Assert.Equal(TranslationHelper.Translation.ISOSpeed, "Чувствительность ISO");
        Assert.Equal(TranslationHelper.Translation.IconsUsed, "Используемые значки");
        Assert.Equal(TranslationHelper.Translation.Image, "Изображение");
        Assert.Equal(TranslationHelper.Translation.ImageAliasing, "Сглаживание изображения");
        Assert.Equal(TranslationHelper.Translation.ImageControl, "Управление изображением");
        Assert.Equal(TranslationHelper.Translation.ImageInfo, "Информация об изображении");
        Assert.Equal(TranslationHelper.Translation.Inches, "дюймов");
        Assert.Equal(TranslationHelper.Translation.InfoWindow, "Информационное окно");
        Assert.Equal(TranslationHelper.Translation.InfoWindowTitle, "Информация и сочетания клавиш");
        Assert.Equal(TranslationHelper.Translation.InterfaceConfiguration, "Конфигурация интерфейса");
        Assert.Equal(TranslationHelper.Translation.Landscape, "Пейзаж");
        Assert.Equal(TranslationHelper.Translation.Language, "Язык");
        Assert.Equal(TranslationHelper.Translation.LastAccessTime, "Времени последнего доступа");
        Assert.Equal(TranslationHelper.Translation.LastImage, "Последнее изображение");
        Assert.Equal(TranslationHelper.Translation.LastWriteTime, "Времени последней записи");
        Assert.Equal(TranslationHelper.Translation.Latitude, "Широта");
        Assert.Equal(TranslationHelper.Translation.Left, "Влево");
        Assert.Equal(TranslationHelper.Translation.LensMaker, "Производитель объектива");
        Assert.Equal(TranslationHelper.Translation.LensModel, "Модель объектива");
        Assert.Equal(TranslationHelper.Translation.LightSource, "Источник света");
        Assert.Equal(TranslationHelper.Translation.LightTheme, "Светлая тема");
        Assert.Equal(TranslationHelper.Translation.Lighting, "Освещение");
        Assert.Equal(TranslationHelper.Translation.Loading, "Загрузка...");
        Assert.Equal(TranslationHelper.Translation.Longitude, "Долгота");
        Assert.Equal(TranslationHelper.Translation.Looping, "Зацикливание");
        Assert.Equal(TranslationHelper.Translation.LoopingDisabled, "Цикл отключен");
        Assert.Equal(TranslationHelper.Translation.LoopingEnabled, "Цикл включен");
        Assert.Equal(TranslationHelper.Translation.Lossless, "Без потерь");
        Assert.Equal(TranslationHelper.Translation.Lossy, "Потеря");
        Assert.Equal(TranslationHelper.Translation.Low, "Низкий");
        Assert.Equal(TranslationHelper.Translation.Manual, "Ручной");
        Assert.Equal(TranslationHelper.Translation.MaxAperture, "Максимальная диафрагма");
        Assert.Equal(TranslationHelper.Translation.Maximize, "Развернуть");
        Assert.Equal(TranslationHelper.Translation.MegaPixels, "мегапикселей");
        Assert.Equal(TranslationHelper.Translation.Meter, "Метр");
        Assert.Equal(TranslationHelper.Translation.MeteringMode, "Режим измерения");
        Assert.Equal(TranslationHelper.Translation.Minimize, "Свернуть");
        Assert.Equal(TranslationHelper.Translation.MiscSettings, "Прочие настройки");
        Assert.Equal(TranslationHelper.Translation.Modified, "Изменено");
        Assert.Equal(TranslationHelper.Translation.Monochrome, "Монохром");
        Assert.Equal(TranslationHelper.Translation.MouseDrag, "Перетаскивание мышью");
        Assert.Equal(TranslationHelper.Translation.MouseKeyBack, "Клавиша мыши назад");
        Assert.Equal(TranslationHelper.Translation.MouseKeyForward, "Клавиша мыши вперед");
        Assert.Equal(TranslationHelper.Translation.MouseWheel, "Колесико мыши");
        Assert.Equal(TranslationHelper.Translation.MoveWindow, "Переместить окно");
        Assert.Equal(TranslationHelper.Translation.Navigation, "Навигация");
        Assert.Equal(TranslationHelper.Translation.NearestNeighbor, "Ближайший сосед");
        Assert.Equal(TranslationHelper.Translation.NegativeColors, "Обратные цвета");
        Assert.Equal(TranslationHelper.Translation.NewWindow, "Новое окно");
        Assert.Equal(TranslationHelper.Translation.NextFolder, "Перейти к следующей папке");
        Assert.Equal(TranslationHelper.Translation.NextImage, "Следующее изображение");
        Assert.Equal(TranslationHelper.Translation.NoChange, "Без изменений");
        Assert.Equal(TranslationHelper.Translation.NoConversion, "Нет преобразования");
        Assert.Equal(TranslationHelper.Translation.NoImage, "Изображение не загружено");
        Assert.Equal(TranslationHelper.Translation.NoImages, "Нет изображений");
        Assert.Equal(TranslationHelper.Translation.NoResize, "Нет изменений");
        Assert.Equal(TranslationHelper.Translation.None, "Никто");
        Assert.Equal(TranslationHelper.Translation.Normal, "Нормальный");
        Assert.Equal(TranslationHelper.Translation.NormalWindow, "Обычное окно");
        Assert.Equal(TranslationHelper.Translation.NotDefined, "Не определено");
        Assert.Equal(TranslationHelper.Translation.NumpadMinus, "Numpad -");
        Assert.Equal(TranslationHelper.Translation.NumpadPlus, "Numpad +");
        Assert.Equal(TranslationHelper.Translation.OldMovie, "Старый фильм");
        Assert.Equal(TranslationHelper.Translation.Open, "Открыть");
        Assert.Equal(TranslationHelper.Translation.OpenFileDialog, "Выберать файл");
        Assert.Equal(TranslationHelper.Translation.OpenInSameWindow, "Открывать файлы в том же окне");
        Assert.Equal(TranslationHelper.Translation.OpenLastFile, "Открыть последний файл");
        Assert.Equal(TranslationHelper.Translation.OpenWith, "Открыть вместе с...");
        Assert.Equal(TranslationHelper.Translation.OptimizeImage, "Оптимизировать изображение");
        Assert.Equal(TranslationHelper.Translation.Orientation, "Ориентация");
        Assert.Equal(TranslationHelper.Translation.OutputFolder, "Папки вывода");
        Assert.Equal(TranslationHelper.Translation.Pan, "Панорамировать");
        Assert.Equal(TranslationHelper.Translation.PaperFold, "Бумага");
        Assert.Equal(TranslationHelper.Translation.PasswordArchive, "Архив, защищенный паролем, не поддерживается");
        Assert.Equal(TranslationHelper.Translation.PasteImageFromClipholder, "Вставить изображение из буфера обмена");
        Assert.Equal(TranslationHelper.Translation.PencilSketch, "Карандашный набросок");
        Assert.Equal(TranslationHelper.Translation.PercentComplete, "% завершено...");
        Assert.Equal(TranslationHelper.Translation.Percentage, "Процент");
        Assert.Equal(TranslationHelper.Translation.PermanentlyDelete, "Удалить навсегда");
        Assert.Equal(TranslationHelper.Translation.PhotometricInterpretation, "Фотометрическая интерпретация");
        Assert.Equal(TranslationHelper.Translation.Pivot, "Вращение");
        Assert.Equal(TranslationHelper.Translation.Pixelate, "Пикселизация");
        Assert.Equal(TranslationHelper.Translation.Pixels, "пиксели");
        Assert.Equal(TranslationHelper.Translation.Portrait, "Портрет");
        Assert.Equal(TranslationHelper.Translation.PressKey, "Нажмите клавишу...");
        Assert.Equal(TranslationHelper.Translation.PrevFolder, "Перейти к предыдущей папке");
        Assert.Equal(TranslationHelper.Translation.PrevImage, "Предыдущее изображение");
        Assert.Equal(TranslationHelper.Translation.Print, "Распечатать");
        Assert.Equal(TranslationHelper.Translation.PrintSizeCm, "Размер печати (cm)");
        Assert.Equal(TranslationHelper.Translation.PrintSizeIn, "Размер печати (in)");
        Assert.Equal(TranslationHelper.Translation.Quality, "Качественный");
        Assert.Equal(TranslationHelper.Translation.Random, "Случайно");
        Assert.Equal(TranslationHelper.Translation.RecentFiles, "Недавние файлы");
        Assert.Equal(TranslationHelper.Translation.RedEyeReduction, "Уменьшение эффекта красных глаз");
        Assert.Equal(TranslationHelper.Translation.Reload, "Перезагрузить");
        Assert.Equal(TranslationHelper.Translation.RemoveStarRating, "Убрать рейтинг");
        Assert.Equal(TranslationHelper.Translation.RenameFile, "Переименовать файл");
        Assert.Equal(TranslationHelper.Translation.Reset, "Сбросить");
        Assert.Equal(TranslationHelper.Translation.ResetButtonText, "Сбросить настройки по умолчанию");
        Assert.Equal(TranslationHelper.Translation.ResetZoom, "Сбросить масштаб");
        Assert.Equal(TranslationHelper.Translation.Resize, "Изменить размер");
        Assert.Equal(TranslationHelper.Translation.ResizeImage, "Изменить размер изображения");
        Assert.Equal(TranslationHelper.Translation.Resolution, "Разрешение");
        Assert.Equal(TranslationHelper.Translation.ResolutionUnit, "Единица разрешения");
        Assert.Equal(TranslationHelper.Translation.RestartApp, "Перезапустить приложение");
        Assert.Equal(TranslationHelper.Translation.RestoreDown, "Восстановить");
        Assert.Equal(TranslationHelper.Translation.Reverse, "Назад");
        Assert.Equal(TranslationHelper.Translation.Right, "Вправо");
        Assert.Equal(TranslationHelper.Translation.Ripple, "Пульсация");
        Assert.Equal(TranslationHelper.Translation.RippleAlt, "Aльтернативная пульсация");
        Assert.Equal(TranslationHelper.Translation.RotateLeft, "Повернуть налево");
        Assert.Equal(TranslationHelper.Translation.RotateRight, "Повернуть вправо");
        Assert.Equal(TranslationHelper.Translation.Rotated, "Повернуто");
        Assert.Equal(TranslationHelper.Translation.Saturation, "Насыщенность");
        Assert.Equal(TranslationHelper.Translation.Save, "Сохранить");
        Assert.Equal(TranslationHelper.Translation.SaveAs, "Сохранить как");
        Assert.Equal(TranslationHelper.Translation.SavingFileFailed, "Ошибка сохранения файла");
        Assert.Equal(TranslationHelper.Translation.ScrollAndRotate, "Прокрутка и вращение");
        Assert.Equal(TranslationHelper.Translation.ScrollDirection, "Направление прокрутки");
        Assert.Equal(TranslationHelper.Translation.ScrollDown, "Прокрутить вниз");
        Assert.Equal(TranslationHelper.Translation.ScrollToBottom, "Прокрутить вниз");
        Assert.Equal(TranslationHelper.Translation.ScrollToTop, "Прокрутить вверх");
        Assert.Equal(TranslationHelper.Translation.ScrollToZoom,
            "Масштабирование с помощью колесика мыши, перемещение с помощью Ctrl");
        Assert.Equal(TranslationHelper.Translation.ScrollUp, "Прокрутить вверх");
        Assert.Equal(TranslationHelper.Translation.Scrolling, "Прокрутка");
        Assert.Equal(TranslationHelper.Translation.ScrollingDisabled, "Прокрутка отключена");
        Assert.Equal(TranslationHelper.Translation.ScrollingEnabled, "Прокрутка включена");
        Assert.Equal(TranslationHelper.Translation.SearchSubdirectory, "Искать в подкаталогах");
        Assert.Equal(TranslationHelper.Translation.SecAbbreviation, "Sec.");
        Assert.Equal(TranslationHelper.Translation.SelectAll, "Выбрать все");
        Assert.Equal(TranslationHelper.Translation.SelectGalleryThumb, "Выбрать миниатюру галереи");
        Assert.Equal(TranslationHelper.Translation.SendCurrentImageToRecycleBin,
            "Отправить текущее изображение в корзину");
        Assert.Equal(TranslationHelper.Translation.SentFileToRecycleBin, "Файл отправлен в корзину");
        Assert.Equal(TranslationHelper.Translation.SetAs, "Установить как...");
        Assert.Equal(TranslationHelper.Translation.SetAsLockScreenImage, "Установить на экран блокировки");
        Assert.Equal(TranslationHelper.Translation.SetAsWallpaper, "Сделать фоновым рисунком");
        Assert.Equal(TranslationHelper.Translation.SetCurrentImageAsWallpaper,
            "Установить текущее изображение в качестве обоев:");
        Assert.Equal(TranslationHelper.Translation.SetStarRating, "Установить рейтинг звезд");
        Assert.Equal(TranslationHelper.Translation.Settings, "Настройки");
        Assert.Equal(TranslationHelper.Translation.Shade, "Тень");
        Assert.Equal(TranslationHelper.Translation.Sharpness, "Резкость");
        Assert.Equal(TranslationHelper.Translation.Shift, "Shift");
        Assert.Equal(TranslationHelper.Translation.ShowAllSettingsWindow, "Показать окно всех настроек");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGallery, "Показать нижнюю галерею");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Показывать нижнюю галерею при скрытом интерфейсе");
        Assert.Equal(TranslationHelper.Translation.ShowBottomToolbar, "Показать нижнюю панель инструментов");
        Assert.Equal(TranslationHelper.Translation.ShowConfirmationOnEsc,
            "Показывать диалог подтверждения при нажатии 'Esc'");
        Assert.Equal(TranslationHelper.Translation.ShowFadeInButtonsOnHover,
            "Показать кнопки с эффектом плавного появления при наведении мыши");
        Assert.Equal(TranslationHelper.Translation.ShowFileSavingDialog, "Показать диалоговое окно сохранения файла");
        Assert.Equal(TranslationHelper.Translation.ShowImageGallery, "Показать галерею изображений");
        Assert.Equal(TranslationHelper.Translation.ShowImageInfo, "Показать информацию об изображении");
        Assert.Equal(TranslationHelper.Translation.ShowInFolder, "Показать в папке");
        Assert.Equal(TranslationHelper.Translation.ShowInfoWindow, "Показать информационное окно");
        Assert.Equal(TranslationHelper.Translation.ShowResizeWindow, "Показать окно изменения размера");
        Assert.Equal(TranslationHelper.Translation.ShowUI, "Afișează interfața");
        Assert.Equal(TranslationHelper.Translation.ShutterPriority, "Приоритет затвора");
        Assert.Equal(TranslationHelper.Translation.SideBySide, "Бок о бок");
        Assert.Equal(TranslationHelper.Translation.SideBySideTooltip, "Показывать изображения рядом");
        Assert.Equal(TranslationHelper.Translation.Size, "Размер");
        Assert.Equal(TranslationHelper.Translation.SizeMp, "Размер (mp)");
        Assert.Equal(TranslationHelper.Translation.SizeTooltip, "Введите желаемый размер в пикселях или процентах.");
        Assert.Equal(TranslationHelper.Translation.Sketch, "Эскиз");
        Assert.Equal(TranslationHelper.Translation.Slideshow, "Слайдшоу");
        Assert.Equal(TranslationHelper.Translation.SmoothMagnify, "Гладкое увеличение");
        Assert.Equal(TranslationHelper.Translation.Soft, "Мягкий");
        Assert.Equal(TranslationHelper.Translation.Software, "Программное обеспечение");
        Assert.Equal(TranslationHelper.Translation.SortFilesBy, "Сортировать файлы по");
        Assert.Equal(TranslationHelper.Translation.SourceFolder, "Источник папки");
        Assert.Equal(TranslationHelper.Translation.Space, "Space");
        Assert.Equal(TranslationHelper.Translation.Square, "Квадрат");
        Assert.Equal(TranslationHelper.Translation.Start, "Начинать");
        Assert.Equal(TranslationHelper.Translation.StartSlideshow, "Начать слайдшоу");
        Assert.Equal(TranslationHelper.Translation.StayCentered, "Зафиксировать окно по центру");
        Assert.Equal(TranslationHelper.Translation.StayTopMost, "Оставаться поверх других окон");
        Assert.Equal(TranslationHelper.Translation.Stretch, "Растянуть");
        Assert.Equal(TranslationHelper.Translation.StretchImage, "Растянуть изображение");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightDetected, "Вспышка обнаружила возвратный свет");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightNotDetected,
            "Вспышка не обнаружила возвратного света");
        Assert.Equal(TranslationHelper.Translation.Subject, "Тема");
        Assert.Equal(TranslationHelper.Translation.Swirl, "Вихрь");
        Assert.Equal(TranslationHelper.Translation.TelescopicBlur, "Телескопическое размытие");
        Assert.Equal(TranslationHelper.Translation.Theme, "Тема");
        Assert.Equal(TranslationHelper.Translation.Thumbnail, "Thumb");
        Assert.Equal(TranslationHelper.Translation.Tile, "Плитка");
        Assert.Equal(TranslationHelper.Translation.Title, "Заголовок");
        Assert.Equal(TranslationHelper.Translation.ToggleBackgroundColor, "Переключить цвет фона");
        Assert.Equal(TranslationHelper.Translation.ToggleFullscreen, "Включить полноэкранный режим");
        Assert.Equal(TranslationHelper.Translation.ToggleLooping, "Переключить цикл");
        Assert.Equal(TranslationHelper.Translation.ToggleScroll, "Переключить прокрутку");
        Assert.Equal(TranslationHelper.Translation.ToggleTaskbarProgress, "Отображение прогресса на панели задач");
        Assert.Equal(TranslationHelper.Translation.ToneMapping, "Тональное отображение");
        Assert.Equal(TranslationHelper.Translation.UnableToRender, "Невозможно отобразить изображение");
        Assert.Equal(TranslationHelper.Translation.Uncalibrated, "Некалиброванный");
        Assert.Equal(TranslationHelper.Translation.Underwater, "Подводный");
        Assert.Equal(TranslationHelper.Translation.UnexpectedError, "Произошла неизвестная ошибка");
        Assert.Equal(TranslationHelper.Translation.Unflip, "Развернуть");
        Assert.Equal(TranslationHelper.Translation.Uniform, "Равномерный");
        Assert.Equal(TranslationHelper.Translation.UniformToFill, "РавномерныйДляЗаполнения");
        Assert.Equal(TranslationHelper.Translation.Unknown, "Неизвестно");
        Assert.Equal(TranslationHelper.Translation.UnsupportedFile, "Неподдерживаемый файл");
        Assert.Equal(TranslationHelper.Translation.Up, "Вверх");
        Assert.Equal(TranslationHelper.Translation.UsingMouse, "Использование мыши");
        Assert.Equal(TranslationHelper.Translation.UsingTouchpad, "Использование тачпада");
        Assert.Equal(TranslationHelper.Translation.Version, "Версия:");
        Assert.Equal(TranslationHelper.Translation.ViewLicenseFile, "Просмотреть файл лицензии");
        Assert.Equal(TranslationHelper.Translation.WaveWarper, "Искаженные волны");
        Assert.Equal(TranslationHelper.Translation.WhiteBalance, "Баланс белого");
        Assert.Equal(TranslationHelper.Translation.WhiteFluorescent, "Белый флуоресцентный");
        Assert.Equal(TranslationHelper.Translation.Width, "Ширина");
        Assert.Equal(TranslationHelper.Translation.WidthAndHeight, "Ширина и высота");
        Assert.Equal(TranslationHelper.Translation.WindowManagement, "Управление окнами");
        Assert.Equal(TranslationHelper.Translation.WindowScaling, "Масштабирование окна");
        Assert.Equal(TranslationHelper.Translation.Zoom, "Зуммирование");
        Assert.Equal(TranslationHelper.Translation.ZoomIn, "Увеличить");
        Assert.Equal(TranslationHelper.Translation.ZoomOut, "Уменьшить");
        Assert.Equal(TranslationHelper.Translation._1Star, "1 звезда");
        Assert.Equal(TranslationHelper.Translation._2Star, "2звезды");
        Assert.Equal(TranslationHelper.Translation._3Star, "3звезды");
        Assert.Equal(TranslationHelper.Translation._4Star, "4звезды");
        Assert.Equal(TranslationHelper.Translation._5Star, "5звезды");
    }
}