using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public class SpanishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckSpanishLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("es");
        Assert.True(exists);
        Assert.Equal(TranslationManager.Translation.About, "Acerca de");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Programa de acción");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "agregada al portapapeles");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Funciones adicionales");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed,
            "Ajustar velocidad cuando la tecla se mantiene presionada");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Ajustar velocidad de presentación");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Ajustar velocidad de acercado/alejado");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Ajustar nivel de zoom");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Avanzar 100 imágenes");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Avanzar 10 imágenes");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Evite hacer zoom out en la imagen cuando ya esté en tamaño máximo");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Altitud");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Prioridad de apertura");
        Assert.Equal(TranslationManager.Translation.Appearance, "Opciones de interfaz");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Atajos de la aplicación");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Inicio de la aplicación");
        Assert.Equal(TranslationManager.Translation.Apply, "Aplicar");
        Assert.Equal(TranslationManager.Translation.Applying, "Aplicando");
        Assert.Equal(TranslationManager.Translation.Ascending, "Ascendante");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Dimensiones");
        Assert.Equal(TranslationManager.Translation.Authors, "Autores");
        Assert.Equal(TranslationManager.Translation.Auto, "Automático");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Auto ajustar ventana");
        Assert.Equal(TranslationManager.Translation.BadArchive, "No se ha podido procesar el archivo");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Imagen en Base64");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Cambio de tamaño por lotes");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Profundidad de bits");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Blanco y Negro");
        Assert.Equal(TranslationManager.Translation.Blur, "Desenfoque");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Elementos de la galería inferior");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Estiramiento de miniatura de la galería inferior");
        Assert.Equal(TranslationManager.Translation.Brightness, "Brillo");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Fabricante de la cámara");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Modelo de la cámara");
        Assert.Equal(TranslationManager.Translation.Cancel, "Cancelar");
        Assert.Equal(TranslationManager.Translation.Center, "Centro");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Centrar ventana");
        Assert.Equal(TranslationManager.Translation.Centimeters, "centímetros");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Cambiar fondo");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Cambiar entre color de fondo para imágenes de fondo transparente");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Haz clic en un cuadro de texto para cambiar la asignación de teclas. Presiona Esc para desvincular la tecla.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip,
            "Haz clic para cambiar la asignación de teclas");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart,
            "* Cambiar el tema requiere reabrir el programa");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Compruebe las actualizaciones");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Imagen de Portapapeles");
        Assert.Equal(TranslationManager.Translation.Close, "Cerrar");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Cierra la aplicación por completo");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Cerrar galería");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "¿Desea cerrar la ventana?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Tiempo nublado");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Cuentagotas");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Elegir color desde imagen");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Representación de color");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Tono de Color");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Bits por píxel comprimidos");
        Assert.Equal(TranslationManager.Translation.Compression, "Compresión");
        Assert.Equal(TranslationManager.Translation.Contrast, "Contraste");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Convertir a");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Convertido a base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Fluorescente blanco frío");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Copiar imagen al portapapeles");
        Assert.Equal(TranslationManager.Translation.Copy, "Copiar");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Copiar archivo");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Copiar imagen");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Copiar como imagen del portapapeles de Windows");
        Assert.Equal(TranslationManager.Translation.Copyright, "Derechos de autor");
        Assert.Equal(TranslationManager.Translation.Created, "Creado");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Fecha de creación");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Programa creativo");
        Assert.Equal(TranslationManager.Translation.Credits, "Créditos");
        Assert.Equal(TranslationManager.Translation.Crop, "Recortar");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Presiona Esc para cerrar, Enter para guardar");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Recortar Imagen");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Ctrl para zoom, rueda para navegar");
        Assert.Equal(TranslationManager.Translation.Cut, "Cortar");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Tema oscuro");
        Assert.Equal(TranslationManager.Translation.Date, "Fecha");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Fecha de toma");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Fluorescente blanco de luz del día");
        Assert.Equal(TranslationManager.Translation.Daylight, "Luz del día");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Fluorescente de luz del día");
        Assert.Equal(TranslationManager.Translation.Del, "Supr");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Eliminar archivo");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "¿Estás seguro de que deseas eliminar permanentemente");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Archivo eliminado");
        Assert.Equal(TranslationManager.Translation.Descending, "Descendante");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Zoom digital");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Desactivar botones de desvanecimiento al pasar el ratón");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Tamaño en disco");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Doble Click");
        Assert.Equal(TranslationManager.Translation.Down, "Abajo");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Arrastra el archivo al Explorador de Windows o a otra aplicación/navegador");
        Assert.Equal(TranslationManager.Translation.DragImage, "Arrastrar imagen");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Arrastra para cargar una imagen");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Duplicar archivo");
        Assert.Equal(TranslationManager.Translation.Effects, "Efectos de Sombra");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Mostrar ventana de efectos");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Cierra el menú/ventana actualmente abierto");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Versión Exif");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Elementos de la galería expandida");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Compensación de exposición");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Programa de exposición");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Tiempo de exposición");
        Assert.Equal(TranslationManager.Translation.FNumber, "Número F");
        Assert.Equal(TranslationManager.Translation.File, "archivo");
        Assert.Equal(TranslationManager.Translation.FileCopy, "Archivo agregado al portapapeles");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Copiar carpeta del archivo");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Carpeta del archivo agregada al portapapeles");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "Archivo agregada para mover al portapapeles");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Extensión de archivo");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Gestión de archivos");
        Assert.Equal(TranslationManager.Translation.FileName, "Nombre de archivo");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Pegar");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Propiedades del archivo");
        Assert.Equal(TranslationManager.Translation.FileSize, "Tamaño de archivo");
        Assert.Equal(TranslationManager.Translation.Files, "archivos");
        Assert.Equal(TranslationManager.Translation.Fill, "Rellenar");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Rellenar altura");
        Assert.Equal(TranslationManager.Translation.FillSquare, "LlenarCuadrado");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Buen tiempo");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Primera imagen");
        Assert.Equal(TranslationManager.Translation.Fit, "Ajustar");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Ajustar a ventana/imagen");
        Assert.Equal(TranslationManager.Translation.Flash, "Flash");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Flash no disparado");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Energía de flash");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Flash disparado");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Modo de flash");
        Assert.Equal(TranslationManager.Translation.Flip, "Voltear horizontalmente");
        Assert.Equal(TranslationManager.Translation.Flipped, "Volteado");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Fluorescente");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Longitud focal");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Longitud focal 35mm");
        Assert.Equal(TranslationManager.Translation.Folder, "Carpeta");
        Assert.Equal(TranslationManager.Translation.Forward, "Hacia adelante");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationManager.Translation.FullPath, "Nombre completo de la carpeta");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Pantalla Completa");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Configuración de la Galería");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch,
            "Estiramiento de la miniatura de la galería");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Opciones Generales");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Generar miniaturas");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Repositorio de Github");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Tema de vidrio");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Retroceder 100 imágenes");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Retroceder 10 imágenes");
        Assert.Equal(TranslationManager.Translation.Hard, "Duro");
        Assert.Equal(TranslationManager.Translation.Height, "Alto");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Ocultar galería inferior");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Ocultar barra de herramientas inferior");
        Assert.Equal(TranslationManager.Translation.HideUI, "Ocultar interfaz");
        Assert.Equal(TranslationManager.Translation.High, "Alto");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Alta calidad");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Color de resaltado");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "Velocidad ISO");
        Assert.Equal(TranslationManager.Translation.Image, "Imagen");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Alias de imagen");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Control de Imagen");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Información de Imagen");
        Assert.Equal(TranslationManager.Translation.Inches, "pulgadas");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Ventana de información");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Información y atajos");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Configuración de interfaz");
        Assert.Equal(TranslationManager.Translation.Landscape, "Horizontal");
        Assert.Equal(TranslationManager.Translation.Language, "Lenguaje");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Fecha de último acceso");
        Assert.Equal(TranslationManager.Translation.LastImage, "Última imagen");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Fecha de última modificación");
        Assert.Equal(TranslationManager.Translation.Latitude, "Latitud");
        Assert.Equal(TranslationManager.Translation.Left, "Izquierda");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Fabricante de lente");
        Assert.Equal(TranslationManager.Translation.LensModel, "Modelo de lente");
        Assert.Equal(TranslationManager.Translation.LightSource, "Fuente de luz");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Tema claro");
        Assert.Equal(TranslationManager.Translation.Lighting, "Iluminación");
        Assert.Equal(TranslationManager.Translation.Loading, "Cargando...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Longitud");
        Assert.Equal(TranslationManager.Translation.Looping, "Bucle");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Bucle desactivado");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Bucle activado");
        Assert.Equal(TranslationManager.Translation.Lossless, "Lossless");
        Assert.Equal(TranslationManager.Translation.Lossy, "Lossy");
        Assert.Equal(TranslationManager.Translation.Low, "Bajo");
        Assert.Equal(TranslationManager.Translation.Manual, "Manual");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Apertura máxima");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maximizar");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "megapixeles");
        Assert.Equal(TranslationManager.Translation.Meter, "Medidor");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Modo de medición");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimizar");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Otras opciones");
        Assert.Equal(TranslationManager.Translation.Modified, "Modificado");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Arrastrar con el ratón");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Tecla de retroceder del ratón");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Rueda del ratón hacia atrás");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Rueda del ratón");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Mover ventana");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navegación");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Vecino más cercano");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Negativo");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Nueva Ventana");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Navegar a la siguiente carpeta");
        Assert.Equal(TranslationManager.Translation.NextImage, "Imagen siguiente");
        Assert.Equal(TranslationManager.Translation.NoChange, "Sin cambios");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Sin conversión");
        Assert.Equal(TranslationManager.Translation.NoImage, "No se ha cargado imagen");
        Assert.Equal(TranslationManager.Translation.NoImages, "No hay imágenes");
        Assert.Equal(TranslationManager.Translation.NoResize, "No resize");
        Assert.Equal(TranslationManager.Translation.None, "Ninguna");
        Assert.Equal(TranslationManager.Translation.Normal, "Normal");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Ventana normal");
        Assert.Equal(TranslationManager.Translation.NotDefined, "No definido");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Teclado numérico -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Teclado numérico +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Filme Antiguo");
        Assert.Equal(TranslationManager.Translation.Open, "Abrir");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Abrir selector de archivo");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Abrir archivos en la misma ventana");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Abrir ultimo archivo");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Abrir con...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Optimizar la imagen");
        Assert.Equal(TranslationManager.Translation.Orientation, "Orientación");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Carpeta de salida");
        Assert.Equal(TranslationManager.Translation.Pan, "Ajustar Tamaño");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Archivo protegido por contraseña no soportado");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Pegar imagen desde portapapeles");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Dibujo a lápiz");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% completado...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Porcentaje");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Eliminar permanentemente");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Interpretación fotométrica");
        Assert.Equal(TranslationManager.Translation.Pixels, "pixeles");
        Assert.Equal(TranslationManager.Translation.Portrait, "Vertical");
        Assert.Equal(TranslationManager.Translation.PressKey, "Presiona tecla...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Navegar a la carpeta anterior");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Imagen anterior");
        Assert.Equal(TranslationManager.Translation.Print, "Imprimir");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Tamaño de impresión (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Tamaño de impresión (in)");
        Assert.Equal(TranslationManager.Translation.Quality, "Calidad");
        Assert.Equal(TranslationManager.Translation.Random, "Aleatorio");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Archivos recientes");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Reducción de ojos rojos");
        Assert.Equal(TranslationManager.Translation.Reload, "Recargar");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Eliminar clasificación");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Renombrar archivo");
        Assert.Equal(TranslationManager.Translation.Reset, "Restablecer");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Restablecer a predeterminado");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Reset zoom");
        Assert.Equal(TranslationManager.Translation.Resize, "Cambiar de tamaño");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Cambiar el tamaño de la imagen");
        Assert.Equal(TranslationManager.Translation.Resolution, "Resolución");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Unidad de resolución");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Reiniciar la aplicación");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Restaurar Abajo");
        Assert.Equal(TranslationManager.Translation.Reverse, "Marcha atrás");
        Assert.Equal(TranslationManager.Translation.Right, "Derecha");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Rotar a la izquierda");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Rotar a la derecha");
        Assert.Equal(TranslationManager.Translation.Rotated, "Rotado");
        Assert.Equal(TranslationManager.Translation.Saturation, "Saturación");
        Assert.Equal(TranslationManager.Translation.Save, "Guardar");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Guardar como");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Guardando archivo fallido");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Desplazar y rotar");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Dirección de desplazamiento");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Desplazar hacia abajo");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Desplazar hacia abajo al fondo");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Desplazar hacia arriba al tope");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Rueda para zoom, Ctrl para navegar");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Desplazar hacia arriba");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Desplazar");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Rueda del mouse desactivada");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Rueda del mouse activada");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Buscar subdirectorios");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Seg.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Seleccionar todo");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Seleccionar miniatura de la galería");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin,
            "Enviar imagen actual a papelera de reciclaje");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Enviar archivo a papelera de reciclaje");
        Assert.Equal(TranslationManager.Translation.SetAs, "Establecer como...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Establecer como imagen de bloqueo");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Establecer como fondo de pantalla");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Establecer imagen actual como fondo de pantalla:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Establecer clasificación con estrellas");
        Assert.Equal(TranslationManager.Translation.Settings, "Opciones");
        Assert.Equal(TranslationManager.Translation.Shade, "Sombra");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Nitidez");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Ventana de mostrar todas las opciones");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Mostrar galería inferior");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Mostrar galería inferior cuando la interfaz de usuario está oculta");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Mostrar barra de herramientas inferior");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "Mostrar cuadro de confirmación al presionar 'Esc'");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover,
            "Mostrar botones de desvanecimiento al pasar el ratón");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog,
            "Mostrar el cuadro de diálogo de guardar archivo");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Mostrar galería de imáagenes");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Mostrar Información de Imagen");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Mostrar en carpeta");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Mostrar ventana de información");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Mostrar la ventana de cambio de tamaño");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Mostrar interfaz");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Prioridad de obturador");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Vista lateral");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Mostrar las imagenes uno al lado del otro");
        Assert.Equal(TranslationManager.Translation.Size, "Tamaño");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Tamaño (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "Ingrese el tamaño deseado en píxeles o porcentaje.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Presentación");
        Assert.Equal(TranslationManager.Translation.Soft, "Suave");
        Assert.Equal(TranslationManager.Translation.Software, "Software");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Ordenar archivos por");
        Assert.Equal(TranslationManager.Translation.Space, "Espacio");
        Assert.Equal(TranslationManager.Translation.Square, "Cuadrado");
        Assert.Equal(TranslationManager.Translation.Start, "Comienzo");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Iniciar presentación");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Mantener ventana centrada");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Mostrar sobre otras ventanas");
        Assert.Equal(TranslationManager.Translation.Stretch, "Estirar");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Estirar imagen");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Luz de retorno de flash detectada");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected,
            "Luz de retorno de flash no detectada");
        Assert.Equal(TranslationManager.Translation.Subject, "Asunto");
        Assert.Equal(TranslationManager.Translation.Theme, "Tema");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Miniatura");
        Assert.Equal(TranslationManager.Translation.Tile, "Mosaico");
        Assert.Equal(TranslationManager.Translation.Title, "Título");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Alternar color de fondo");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Alternar pantalla completa");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Alternar bucles");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Alternar desplazamiento");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Mostrar el progreso en la barra de tareas");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "No se puede renderizar la imagen");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Sin calibrar");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Ha ocurrido un error desconocido");
        Assert.Equal(TranslationManager.Translation.Unflip, "Deshacer volteado");
        Assert.Equal(TranslationManager.Translation.Uniform, "Uniforme");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "UniformeParaRellenar");
        Assert.Equal(TranslationManager.Translation.Unknown, "Desconocido");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Archivo no compatible");
        Assert.Equal(TranslationManager.Translation.Up, "Arriba");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Usar ratón");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Usar panel táctil");
        Assert.Equal(TranslationManager.Translation.Version, "Versión:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Ver archivo de licencia");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Balance de blancos");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Fluorescente blanco");
        Assert.Equal(TranslationManager.Translation.Width, "Ancho");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Ancho y alto");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Gestión de ventana");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Escalado de ventana");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zoom");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Acercar");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Alejar");
        Assert.Equal(TranslationManager.Translation._1Star, "Clasificación de 1 estrella");
        Assert.Equal(TranslationManager.Translation._2Star, "Clasificación de 2 estrella");
        Assert.Equal(TranslationManager.Translation._3Star, "Clasificación de 3 estrella");
        Assert.Equal(TranslationManager.Translation._4Star, "Clasificación de 4 estrella");
        Assert.Equal(TranslationManager.Translation._5Star, "Clasificación de 5 estrella");
    }
}
