using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class SwedishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckSwedishLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("sv");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "Om");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Programaktivitet");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Tillagt i urklipp");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Ytterligare funktioner");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed, "Justera hastighet när tangenten hålls ner");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Justera tid för bildvisning");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Justera zoomhastighet");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Justera zoomnivå");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "Framåt 10 bilder");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "Framåt 100 bilder");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Undvik att zooma ut bilden när den redan är maximerad");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "Höjd");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Bländarautomatik");
        Assert.Equal(TranslationManager.Translation.Appearance, "Utseende");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Genvägar till programmet");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Uppstart av programmet");
        Assert.Equal(TranslationManager.Translation.Apply, "Utför");
        Assert.Equal(TranslationManager.Translation.Applying, "Utför");
        Assert.Equal(TranslationManager.Translation.Ascending, "Stigande");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "Bildförhållande");
        Assert.Equal(TranslationManager.Translation.Authors, "Författare");
        Assert.Equal(TranslationManager.Translation.Auto, "Auto");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Auto-anpassa fönster");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Arkivet kan inte bearbetas");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Base64-bild");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Batch ändra storlek");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Bitdjup");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Svart/vit");
        Assert.Equal(TranslationManager.Translation.Blur, "Oskärpa");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Storlek på tumnaglar i nedre galleriet");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch,
            "Sträck tumnagnaglar i nedre galleriet");
        Assert.Equal(TranslationManager.Translation.Brightness, "Ljusstyrka");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Kameratillverkare");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Kameramodell");
        Assert.Equal(TranslationManager.Translation.Cancel, "Avbryt");
        Assert.Equal(TranslationManager.Translation.Center, "Centrera");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Mittfönster");
        Assert.Equal(TranslationManager.Translation.Centimeters, "centimeter");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Ändra bakgrund");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Ändra mellan bakgrundsfärger för bilder med genomskinlig bakgrund");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Klicka i textrutan för att associera tangent. Esc tar bort ändringen.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip, "Klicka för att associera tangent");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart,
            "* Ändring av tema kräver omstart av programmet");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Sök efter uppdateringar");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Urklippsbild");
        Assert.Equal(TranslationManager.Translation.Close, "Stäng");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Stäng programmet");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Stäng galleriet");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Vill du stänga fönstret?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Molnigt");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Färgprov");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Ta färgprov i bilden");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Färgrepresentation");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Färgton");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Komprimerade bitar per pixel");
        Assert.Equal(TranslationManager.Translation.Compression, "Kompression");
        Assert.Equal(TranslationManager.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Konvertera till");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Konverterad till base64");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Lysrör kallvitt");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Kopierade bilden till urklipp");
        Assert.Equal(TranslationManager.Translation.Copy, "Kopiera");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Kopiera fil");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Kopiera bild");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Kopiera som urklippsbild");
        Assert.Equal(TranslationManager.Translation.Copyright, "Upphovsrätt");
        Assert.Equal(TranslationManager.Translation.Created, "Skapad");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Skapat tidpunkt");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Kreativt program");
        Assert.Equal(TranslationManager.Translation.Credits, "Tack till medverkande");
        Assert.Equal(TranslationManager.Translation.Crop, "Beskär");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Tryck Esc för att spara, Enter för att spara");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Beskär bild");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Ctrl för att zooma, rulla för att flytta");
        Assert.Equal(TranslationManager.Translation.Cut, "Klipp");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Mörkt tema");
        Assert.Equal(TranslationManager.Translation.Date, "Datum");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Ursprungsdatum");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Lysrör dagsvitt");
        Assert.Equal(TranslationManager.Translation.Daylight, "Dagsljus");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Lysrör dagsljus");
        Assert.Equal(TranslationManager.Translation.Del, "Del");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Radera fil");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "Är du säker på att du vill ta bort filen permanent");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Fil raderad");
        Assert.Equal(TranslationManager.Translation.Descending, "Sjunkande");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Digital zoom");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Göm dolda knappar när musen är i kanterna av programmet");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Skivstorlek");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Dubbelklick");
        Assert.Equal(TranslationManager.Translation.Down, "Ner");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo, "Dra filen till Utforskaren eller annat program");
        Assert.Equal(TranslationManager.Translation.DragImage, "Dra bild");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Släpp för att ladda bild");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Duplicera fil");
        Assert.Equal(TranslationManager.Translation.Effects, "Effekter");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Visa bildeffekts-fönstret");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Stänger nuvarande fönster/meny");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Exif-version");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Storlek på tumnaglar");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Exponeringsbias");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Exponeringsprogram");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Exponeringstid");
        Assert.Equal(TranslationManager.Translation.FNumber, "Bländare");
        Assert.Equal(TranslationManager.Translation.File, "fil");
        Assert.Equal(TranslationManager.Translation.FileCopy, "Filen tillagd till urklipp");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Kopiera sökväg");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Sökvägen tillagd till urklipp");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "Filen tillagd till urklipp");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Filtillägg");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Filhantering");
        Assert.Equal(TranslationManager.Translation.FileName, "Filnamn");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Klistra in");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Filegenskaper");
        Assert.Equal(TranslationManager.Translation.FileSize, "Filstorlek");
        Assert.Equal(TranslationManager.Translation.Files, "filer");
        Assert.Equal(TranslationManager.Translation.Fill, "Fyll");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Fyll höjd");
        Assert.Equal(TranslationManager.Translation.FillSquare, "Fyll kvadrat");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Vackert väder");
        Assert.Equal(TranslationManager.Translation.FirstImage, "Första bilden");
        Assert.Equal(TranslationManager.Translation.Fit, "Passa");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Passa till fönster/bild");
        Assert.Equal(TranslationManager.Translation.Flash, "Blixt");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Blixt avfyrades inte");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Blixtenergy");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Blixt avfyrades");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Blixtläge");
        Assert.Equal(TranslationManager.Translation.Flip, "Spegelvänd horisontellt");
        Assert.Equal(TranslationManager.Translation.Flipped, "Spegelvänd horisontellt");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Lysrör");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Brännvidd");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "Brännvidd 35mm");
        Assert.Equal(TranslationManager.Translation.Folder, "Mapp");
        Assert.Equal(TranslationManager.Translation.Forward, "Framåt");
        Assert.Equal(TranslationManager.Translation.Fstop, "Bländarsteg");
        Assert.Equal(TranslationManager.Translation.FullPath, "Full sökkväg");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Fullskärm");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Inställningar galleri");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "Sträck tumnaglar i galleriet");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Generella inställningar");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Generera tumnaglar");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Github-repository");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Glastema");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "Bakåt 100 bilder");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "Bakåt 10 bilder");
        Assert.Equal(TranslationManager.Translation.Hard, "Hård");
        Assert.Equal(TranslationManager.Translation.Height, "Höjd");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Dölj nedre galleriet");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Dölj nedre verktygsfält");
        Assert.Equal(TranslationManager.Translation.HideUI, "Dölj användargränssnitt");
        Assert.Equal(TranslationManager.Translation.High, "Hög");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Hög kvalitet");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Markera färg");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "ISO-tal");
        Assert.Equal(TranslationManager.Translation.Image, "Bild");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Kantutjämning");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Bildkontroll");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Bildinformation");
        Assert.Equal(TranslationManager.Translation.Inches, "tum");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Informationsfönster");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Information och genvägar");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Gränssnittskonfiguration");
        Assert.Equal(TranslationManager.Translation.Landscape, "Liggande");
        Assert.Equal(TranslationManager.Translation.Language, "Språk");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Senast använd");
        Assert.Equal(TranslationManager.Translation.LastImage, "Sista bilden");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Senast ändrad");
        Assert.Equal(TranslationManager.Translation.Latitude, "Latitud");
        Assert.Equal(TranslationManager.Translation.Left, "Vänster");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Linstillverkare");
        Assert.Equal(TranslationManager.Translation.LensModel, "Linsmodell");
        Assert.Equal(TranslationManager.Translation.LightSource, "Ljuskälla");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Ljust tema");
        Assert.Equal(TranslationManager.Translation.Lighting, "Belysning");
        Assert.Equal(TranslationManager.Translation.Loading, "Laddar...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Longitud");
        Assert.Equal(TranslationManager.Translation.Looping, "Slinga");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Slinga av");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Slinga på");
        Assert.Equal(TranslationManager.Translation.Lossless, "Förlustfri");
        Assert.Equal(TranslationManager.Translation.Lossy, "Förstörande");
        Assert.Equal(TranslationManager.Translation.Low, "Låg");
        Assert.Equal(TranslationManager.Translation.Manual, "Manuell");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "Största bländare");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maximera");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "megapixel");
        Assert.Equal(TranslationManager.Translation.Meter, "Meter");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Mätmetod");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimera");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Övriga inställningar");
        Assert.Equal(TranslationManager.Translation.Modified, "Ändrad");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Dra musen");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Musknapp bakåt");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Musknapp framåt");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Mushjul");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Flytta fönster");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navigering");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "Närmaste granne");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Negativa färger");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Nytt fönster");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Nästa mapp");
        Assert.Equal(TranslationManager.Translation.NextImage, "Nästa bild");
        Assert.Equal(TranslationManager.Translation.NoChange, "Inga ändringar");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Ingen konvertering");
        Assert.Equal(TranslationManager.Translation.NoImage, "Bild saknas");
        Assert.Equal(TranslationManager.Translation.NoImages, "Inga bilder");
        Assert.Equal(TranslationManager.Translation.NoResize, "Ingen storleksändring");
        Assert.Equal(TranslationManager.Translation.None, "Ingen");
        Assert.Equal(TranslationManager.Translation.Normal, "Normal");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Normalt fönster");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Inte definierad");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Num -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Num +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Gammal film");
        Assert.Equal(TranslationManager.Translation.Open, "Öppna");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Välj fil");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Öppna filer i samma fönster");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Öppna senaste filen");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Öppna med...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Optimera bild");
        Assert.Equal(TranslationManager.Translation.Orientation, "Orientering");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Destinationsmapp");
        Assert.Equal(TranslationManager.Translation.Pan, "Panorera");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Lösenordsskyddade arkiv stöds inte");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Klista in bild");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Blyertsskiss");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% färdig...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Procent");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Ta bort permanent");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Fotometrisk tolkning");
        Assert.Equal(TranslationManager.Translation.Pixels, "pixlar");
        Assert.Equal(TranslationManager.Translation.Portrait, "Stående");
        Assert.Equal(TranslationManager.Translation.PressKey, "Tryck en tangent...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Föregående mapp");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Föregående bild");
        Assert.Equal(TranslationManager.Translation.Print, "Skriv ut");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Utskriftsstorlek (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Utskriftsstorlek (tum)");
        Assert.Equal(TranslationManager.Translation.Quality, "Kvalitet");
        Assert.Equal(TranslationManager.Translation.Random, "Slumpad");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Senaste filer");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Ta bort röda ögon");
        Assert.Equal(TranslationManager.Translation.Reload, "Hämta igen");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Ta bort omdöme");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Ändra filnamn");
        Assert.Equal(TranslationManager.Translation.Reset, "Återställ");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Återställ till standard");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Återställ zoom");
        Assert.Equal(TranslationManager.Translation.Resize, "Ändra storlek");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Ändra bildstorlek");
        Assert.Equal(TranslationManager.Translation.Resolution, "Upplösning");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Upplösningsenhet");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Starta om programmet");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Återställ ner");
        Assert.Equal(TranslationManager.Translation.Reverse, "Bakåt");
        Assert.Equal(TranslationManager.Translation.Right, "Höger");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Rotera vänster");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Rotera höger");
        Assert.Equal(TranslationManager.Translation.Rotated, "Roterad");
        Assert.Equal(TranslationManager.Translation.Saturation, "Mättnad");
        Assert.Equal(TranslationManager.Translation.Save, "Spara");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Spara som");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Spara bild misslyckades");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Rulla och rotera");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Rullningsriktning");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Rulla ner");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "Rulla till botten");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "Rulla till toppen");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Zooma med mushjulet, flytta med Ctrl");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Rulla upp");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Rullar");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Rullning av");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Rullning på");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Sök i undermappar");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sek.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Välj alla");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Välj tumnagel för galleriet");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin, "Lägg bilden i papperskorgen");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Bilden lagd i papperskorgen");
        Assert.Equal(TranslationManager.Translation.SetAs, "Sätt som...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Använd som låsskärmsbild");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Använd som bakgrundsbild");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Använd nuvarande bild som bakgrundsbild:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Ge omdöme");
        Assert.Equal(TranslationManager.Translation.Settings, "Inställningar");
        Assert.Equal(TranslationManager.Translation.Shade, "Skugga");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Skärpa");
        Assert.Equal(TranslationManager.Translation.Shift, "Skift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Visa inställningsfönstret");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Visa nedre galleriet");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Visa nedre galleriet när användargränssnittet är dolt");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Visa nedre verktygsfält");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc, "Visa bekräftelsedialog när 'Esc' trycks");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover,
            "Visa dolda knappar när musen är i kanterna av programmet");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Visa spara fil-dialog");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Visa bildgalleri");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Visa bildinformation");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Visa i mapp");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Visa informationsfönster");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Visa ändra storlek-fönstret");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Visa användargränssnitt");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Tidsautomatik");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Sida vid sida");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Visa bilder sida vid sida");
        Assert.Equal(TranslationManager.Translation.Size, "Storlek");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Storlek (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "Ange önskad storlek i pixlar eller procent.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Bildvisning");
        Assert.Equal(TranslationManager.Translation.Soft, "Mjuk");
        Assert.Equal(TranslationManager.Translation.Software, "Program");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Sortera filer efter");
        Assert.Equal(TranslationManager.Translation.Space, "Mellanslag");
        Assert.Equal(TranslationManager.Translation.Square, "Kvadrat");
        Assert.Equal(TranslationManager.Translation.Start, "Start");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Starta bildvisning");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Centrera fönstret");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Lägg fönstret överst");
        Assert.Equal(TranslationManager.Translation.Stretch, "Sträck");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Sträck bilden");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Strob-returljus detekterat");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected, "Strob-returljus inte detekterat");
        Assert.Equal(TranslationManager.Translation.Subject, "Ämne");
        Assert.Equal(TranslationManager.Translation.Theme, "Tema");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Tumnagel");
        Assert.Equal(TranslationManager.Translation.Tile, "Flisa");
        Assert.Equal(TranslationManager.Translation.Title, "Titel");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Bakgrundsfärg av/på");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Fullskärm av/på");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Slinga av/på");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Rullning av/på");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Visa framstegsstapel");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Kan inte skapa bilden");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Okalilbrerad");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Ett oväntat fel inträffade");
        Assert.Equal(TranslationManager.Translation.Unflip, "Återställ spegelvänd horisontellt");
        Assert.Equal(TranslationManager.Translation.Uniform, "Enhetlig");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "Enhetlig att fylla");
        Assert.Equal(TranslationManager.Translation.Unknown, "Okänd");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Filformatet stöds inte");
        Assert.Equal(TranslationManager.Translation.Up, "Upp");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Använder mus");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Använder pekplatta");
        Assert.Equal(TranslationManager.Translation.Version, "Version:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Se licensfilen");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Vitbalans");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Lysrör vitt");
        Assert.Equal(TranslationManager.Translation.Width, "Bredd");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Bredd och höjd");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Fönsterhantering");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Fönsterskalning");
        Assert.Equal(TranslationManager.Translation.Zoom, "Zooma");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Zooma in");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Zooma ut");
        Assert.Equal(TranslationManager.Translation._1Star, "1 stjärna");
        Assert.Equal(TranslationManager.Translation._2Star, "2 stjärnor");
        Assert.Equal(TranslationManager.Translation._3Star, "3 stjärnor");
        Assert.Equal(TranslationManager.Translation._4Star, "4 stjärnor");
        Assert.Equal(TranslationManager.Translation._5Star, "5 stjärnor");
    }
}