using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class TurkishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckTurkishLanguage()
    {
        var exists = await TranslationHelper.LoadLanguage("tr");
        Assert.True(exists);

        Assert.Equal(TranslationHelper.Translation.About, "Hakkında");
        Assert.Equal(TranslationHelper.Translation.ActionProgram, "Eylem programı");
        Assert.Equal(TranslationHelper.Translation.AddedToClipboard, "Panoya eklendi");
        Assert.Equal(TranslationHelper.Translation.AdditionalFunctions, "Ek fonksiyonlar");
        Assert.Equal(TranslationHelper.Translation.AdjustNavSpeed, "Tuşa basılı tutulduğunda hızı ayarla");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForSlideshow, "Slayt gösterisi zamanlamasını ayarla");
        Assert.Equal(TranslationHelper.Translation.AdjustTimingForZoom, "Yakınlaştırma hızını ayarla");
        Assert.Equal(TranslationHelper.Translation.AdjustZoomLevel, "Yakınlaştırma seviyesini ayarla");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy100Images, "100 Resim ileri");
        Assert.Equal(TranslationHelper.Translation.AdvanceBy10Images, "10 Resim ileri");
        Assert.Equal(TranslationHelper.Translation.AllowZoomOut,
            "Görüntü zaten maksimum boyuttayken görüntüyü uzaklaştırmaktan kaçın");
        Assert.Equal(TranslationHelper.Translation.Alt, "Alt");
        Assert.Equal(TranslationHelper.Translation.Altitude, "İrtifa");
        Assert.Equal(TranslationHelper.Translation.AperturePriority, "Diyafram önceliği");
        Assert.Equal(TranslationHelper.Translation.Appearance, "Görünüm");
        Assert.Equal(TranslationHelper.Translation.ApplicationShortcuts, "Uygulama kısayolları");
        Assert.Equal(TranslationHelper.Translation.ApplicationStartup, "Uygulama başlangıcı");
        Assert.Equal(TranslationHelper.Translation.Apply, "Uygula");
        Assert.Equal(TranslationHelper.Translation.Applying, "Uygulanıyor");
        Assert.Equal(TranslationHelper.Translation.Ascending, "Artan");
        Assert.Equal(TranslationHelper.Translation.AspectRatio, "En-boy oranı");
        Assert.Equal(TranslationHelper.Translation.Authors, "Yazarlar");
        Assert.Equal(TranslationHelper.Translation.Auto, "Otomatik");
        Assert.Equal(TranslationHelper.Translation.AutoFitWindow, "Pencereye otomatik sığdır");
        Assert.Equal(TranslationHelper.Translation.BadArchive, "Arşiv işlenemedi");
        Assert.Equal(TranslationHelper.Translation.BandedSwirl, "Şeritli Girdap");
        Assert.Equal(TranslationHelper.Translation.Bands, "Şeritler");
        Assert.Equal(TranslationHelper.Translation.Base64Image, "Base64 resim");
        Assert.Equal(TranslationHelper.Translation.BatchResize, "Toplu Yeniden Boyutlandırma");
        Assert.Equal(TranslationHelper.Translation.BitDepth, "Bit derinliği");
        Assert.Equal(TranslationHelper.Translation.BlackAndWhite, "Siyah Beyaz");
        Assert.Equal(TranslationHelper.Translation.Bloom, "Çiçeklenme");
        Assert.Equal(TranslationHelper.Translation.Blur, "Bulanıklaştırma");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryItemSize, "Alt galerideki küçük resimlerin boyutu");
        Assert.Equal(TranslationHelper.Translation.BottomGalleryThumbnailStretch, "Alt galeride küçük resim esnetme");
        Assert.Equal(TranslationHelper.Translation.Brightness, "Parlaklık");
        Assert.Equal(TranslationHelper.Translation.CameraMaker, "Kamera üreticisi");
        Assert.Equal(TranslationHelper.Translation.CameraModel, "Kamera modeli");
        Assert.Equal(TranslationHelper.Translation.Cancel, "İptal");
        Assert.Equal(TranslationHelper.Translation.Center, "Merkez");
        Assert.Equal(TranslationHelper.Translation.CenterWindow, "Pencereyi ortala");
        Assert.Equal(TranslationHelper.Translation.Centimeters, "Santimetre");
        Assert.Equal(TranslationHelper.Translation.ChangeBackground, "Arka planı değiştir");
        Assert.Equal(TranslationHelper.Translation.ChangeBackgroundTooltip,
            "Şeffaf arka plana sahip resimler için arka plan rengini değiştir");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingText,
            "Kısayolu değiştirmek için bir metin kutusuna tıkla. Esc tuşuna basmak kısayolu kaldırır.");
        Assert.Equal(TranslationHelper.Translation.ChangeKeybindingTooltip, "Kısayolu değiştirmek için tıkla");
        Assert.Equal(TranslationHelper.Translation.ChangingThemeRequiresRestart,
            "* Tema değişikliği yeniden başlatmayı gerektirir");
        Assert.Equal(TranslationHelper.Translation.CheckForUpdates, "Güncellemeleri kontrol et");
        Assert.Equal(TranslationHelper.Translation.ClipboardImage, "Pano resmi");
        Assert.Equal(TranslationHelper.Translation.Close, "Kapat");
        Assert.Equal(TranslationHelper.Translation.CloseApp, "Tüm uygulamayı kapat");
        Assert.Equal(TranslationHelper.Translation.CloseGallery, "Galeriyi kapat");
        Assert.Equal(TranslationHelper.Translation.CloseWindowPrompt, "Pencereyi kapatmak istiyor musunuz?");
        Assert.Equal(TranslationHelper.Translation.CloudyWeather, "Bulutlu hava");
        Assert.Equal(TranslationHelper.Translation.ColorPickerTool, "Renk Seçme Aracı");
        Assert.Equal(TranslationHelper.Translation.ColorPickerToolTooltip, "Resimden renk seç");
        Assert.Equal(TranslationHelper.Translation.ColorRepresentation, "Renk temsili");
        Assert.Equal(TranslationHelper.Translation.ColorTone, "Renk Tonu");
        Assert.Equal(TranslationHelper.Translation.CompressedBitsPixel, "Piksel başına sıkıştırılmış bit");
        Assert.Equal(TranslationHelper.Translation.Compression, "Sıkıştırma");
        Assert.Equal(TranslationHelper.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationHelper.Translation.ConvertTo, "Dönüştür");
        Assert.Equal(TranslationHelper.Translation.ConvertedToBase64, "Base64'e dönüştürüldü");
        Assert.Equal(TranslationHelper.Translation.CoolWhiteFluorescent, "Soğuk beyaz floresan");
        Assert.Equal(TranslationHelper.Translation.CopiedImage, "Resim panoya kopyalandı");
        Assert.Equal(TranslationHelper.Translation.Copy, "Kopyala");
        Assert.Equal(TranslationHelper.Translation.CopyFile, "Dosyayı kopyala");
        Assert.Equal(TranslationHelper.Translation.CopyImage, "Resmi kopyala");
        Assert.Equal(TranslationHelper.Translation.CopyImageTooltip, "Windows panosuna resim olarak kopyala");
        Assert.Equal(TranslationHelper.Translation.Copyright, "Telif Hakkı");
        Assert.Equal(TranslationHelper.Translation.Created, "Oluşturuldu");
        Assert.Equal(TranslationHelper.Translation.CreationTime, "Oluşturma zamanı");
        Assert.Equal(TranslationHelper.Translation.CreativeProgram, "Yaratıcı program");
        Assert.Equal(TranslationHelper.Translation.Credits, "Krediler");
        Assert.Equal(TranslationHelper.Translation.Crop, "Kırp");
        Assert.Equal(TranslationHelper.Translation.CropMessage, "Kapatmak için Esc, kaydetmek için Enter'a bas");
        Assert.Equal(TranslationHelper.Translation.CropPicture, "Resmi Kırp");
        Assert.Equal(TranslationHelper.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationHelper.Translation.CtrlToZoom, "Yakınlaştırmak için Ctrl, gezinmek için kaydır");
        Assert.Equal(TranslationHelper.Translation.Cut, "Kes");
        Assert.Equal(TranslationHelper.Translation.DarkTheme, "Karanlık tema");
        Assert.Equal(TranslationHelper.Translation.Date, "Tarih");
        Assert.Equal(TranslationHelper.Translation.DateTaken, "Çekilme tarihi");
        Assert.Equal(TranslationHelper.Translation.DayWhiteFluorescent, "Gündüz beyaz floresan");
        Assert.Equal(TranslationHelper.Translation.Daylight, "Gün ışığı");
        Assert.Equal(TranslationHelper.Translation.DaylightFluorescent, "Gün ışığı floresan");
        Assert.Equal(TranslationHelper.Translation.Del, "Sil");
        Assert.Equal(TranslationHelper.Translation.DeleteFile, "Dosyayı sil");
        Assert.Equal(TranslationHelper.Translation.DeleteFilePermanently,
            "Dosyayı kalıcı olarak silmek istediğinizden emin misin");
        Assert.Equal(TranslationHelper.Translation.DeletedFile, "Silinen dosya");
        Assert.Equal(TranslationHelper.Translation.Descending, "Azalan");
        Assert.Equal(TranslationHelper.Translation.DigitalZoom, "Dijital yakınlaştırma");
        Assert.Equal(TranslationHelper.Translation.DirectionalBlur, "Yönlü bulanıklık");
        Assert.Equal(TranslationHelper.Translation.DisableFadeInButtonsOnHover,
            "Fareyle üzerine gelindiğinde soluklaşan butonları devre dışı bırak");
        Assert.Equal(TranslationHelper.Translation.DiskSize, "Disk boyutu");
        Assert.Equal(TranslationHelper.Translation.DoubleClick, "Çift tıklama");
        Assert.Equal(TranslationHelper.Translation.Down, "Aşağı");
        Assert.Equal(TranslationHelper.Translation.Dpi, "DPI");
        Assert.Equal(TranslationHelper.Translation.DragFileTo,
            "Dosyayı Windows Gezgini'ne veya başka bir uygulama/tarayıcıya sürükle");
        Assert.Equal(TranslationHelper.Translation.DragImage, "Resmi sürükle");
        Assert.Equal(TranslationHelper.Translation.DropToLoad, "Resmi yüklemek için bırak");
        Assert.Equal(TranslationHelper.Translation.DuplicateFile, "Yinelenen dosya");
        Assert.Equal(TranslationHelper.Translation.Effects, "Efektler");
        Assert.Equal(TranslationHelper.Translation.EffectsTooltip, "Resim efektleri penceresini göster");
        Assert.Equal(TranslationHelper.Translation.Embossed, "Kabartma");
        Assert.Equal(TranslationHelper.Translation.Enter, "Enter");
        Assert.Equal(TranslationHelper.Translation.Esc, "Esc");
        Assert.Equal(TranslationHelper.Translation.EscCloseTooltip, "Açık olan pencere/menüyü kapatır");
        Assert.Equal(TranslationHelper.Translation.ExifVersion, "Exif sürümü");
        Assert.Equal(TranslationHelper.Translation.ExpandedGalleryItemSize, "Küçük resim boyutu");
        Assert.Equal(TranslationHelper.Translation.ExposureBias, "Pozlama yanlılığı");
        Assert.Equal(TranslationHelper.Translation.ExposureProgram, "Pozlama programı");
        Assert.Equal(TranslationHelper.Translation.ExposureTime, "Pozlama süresi");
        Assert.Equal(TranslationHelper.Translation.FNumber, "F numarası");
        Assert.Equal(TranslationHelper.Translation.File, "Dosya");
        Assert.Equal(TranslationHelper.Translation.FileCopy, "Dosya panoya eklendi");
        Assert.Equal(TranslationHelper.Translation.FileCopyPath, "Dosya yolunu kopyala");
        Assert.Equal(TranslationHelper.Translation.FileCopyPathMessage, "Dosya yolu panoya eklendi");
        Assert.Equal(TranslationHelper.Translation.FileCutMessage, "Dosya taşınmak üzere panoya eklendi");
        Assert.Equal(TranslationHelper.Translation.FileExtension, "Dosya uzantısı");
        Assert.Equal(TranslationHelper.Translation.FileManagement, "Dosya yönetimi");
        Assert.Equal(TranslationHelper.Translation.FileName, "Dosya adı");
        Assert.Equal(TranslationHelper.Translation.FilePaste, "Yapıştır");
        Assert.Equal(TranslationHelper.Translation.FileProperties, "Dosya özellikleri");
        Assert.Equal(TranslationHelper.Translation.FileSize, "Dosya boyutu");
        Assert.Equal(TranslationHelper.Translation.Files, "Dosyalar");
        Assert.Equal(TranslationHelper.Translation.Fill, "Doldur");
        Assert.Equal(TranslationHelper.Translation.FillHeight, "⇔ Yüksekliği doldur");
        Assert.Equal(TranslationHelper.Translation.FillSquare, "Kareyi doldur");
        Assert.Equal(TranslationHelper.Translation.FineWeather, "Güzel hava");
        Assert.Equal(TranslationHelper.Translation.FirstImage, "İlk resim");
        Assert.Equal(TranslationHelper.Translation.Fit, "Sığdır");
        Assert.Equal(TranslationHelper.Translation.FitToWindow, "Pencereye/resme sığdır");
        Assert.Equal(TranslationHelper.Translation.Flash, "Flaş");
        Assert.Equal(TranslationHelper.Translation.FlashDidNotFire, "Flaş ateşlenmedi");
        Assert.Equal(TranslationHelper.Translation.FlashEnergy, "Flaş enerjisi");
        Assert.Equal(TranslationHelper.Translation.FlashFired, "Flaş ateşlendi");
        Assert.Equal(TranslationHelper.Translation.FlashMode, "Flaş modu");
        Assert.Equal(TranslationHelper.Translation.Flip, "Yatay olarak çevir");
        Assert.Equal(TranslationHelper.Translation.Flipped, "Yatay olarak çevrildi");
        Assert.Equal(TranslationHelper.Translation.Fluorescent, "Floresan");
        Assert.Equal(TranslationHelper.Translation.FocalLength, "Odak uzaklığı");
        Assert.Equal(TranslationHelper.Translation.FocalLength35mm, "35mm odak uzaklığı");
        Assert.Equal(TranslationHelper.Translation.Folder, "Klasör");
        Assert.Equal(TranslationHelper.Translation.Forward, "İleri");
        Assert.Equal(TranslationHelper.Translation.FrostyOutline, "Buzlu Kontur");
        Assert.Equal(TranslationHelper.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationHelper.Translation.FullPath, "Tam dosya yolu");
        Assert.Equal(TranslationHelper.Translation.Fullscreen, "Tam ekran");
        Assert.Equal(TranslationHelper.Translation.GallerySettings, "Galeri ayarları");
        Assert.Equal(TranslationHelper.Translation.GalleryThumbnailStretch, "Galeri küçük resmi esnetme");
        Assert.Equal(TranslationHelper.Translation.GeneralSettings, "Genel ayarlar");
        Assert.Equal(TranslationHelper.Translation.GenerateThumbnails, "Küçük resimler oluştur");
        Assert.Equal(TranslationHelper.Translation.GithubRepo, "Github deposu");
        Assert.Equal(TranslationHelper.Translation.GlassTheme, "Cam Teması");
        Assert.Equal(TranslationHelper.Translation.GlassTile, "Cam Karosu");
        Assert.Equal(TranslationHelper.Translation.Gloom, "Kasvet");
        Assert.Equal(TranslationHelper.Translation.GoBackBy100Images, "100 Resim geri git");
        Assert.Equal(TranslationHelper.Translation.GoBackBy10Images, "10 Resim geri git");
        Assert.Equal(TranslationHelper.Translation.GoToImageAtSpecifiedIndex, "Belirtilen dizindeki görüntüye git");
        Assert.Equal(TranslationHelper.Translation.Hard, "Zor");
        Assert.Equal(TranslationHelper.Translation.Height, "Yükseklik");
        Assert.Equal(TranslationHelper.Translation.HideBottomGallery, "Alt galeriyi gizle");
        Assert.Equal(TranslationHelper.Translation.HideBottomToolbar, "Alt araç çubuğunu gizle");
        Assert.Equal(TranslationHelper.Translation.HideUI, "Arayüzü gizle");
        Assert.Equal(TranslationHelper.Translation.High, "Yüksek");
        Assert.Equal(TranslationHelper.Translation.HighQuality, "Yüksek kalite");
        Assert.Equal(TranslationHelper.Translation.HighlightColor, "Vurgulama rengi");
        Assert.Equal(TranslationHelper.Translation.ISOSpeed, "ISO hızı");
        Assert.Equal(TranslationHelper.Translation.IconsUsed, "Kullanılan ikonlar:");
        Assert.Equal(TranslationHelper.Translation.Image, "Resim");
        Assert.Equal(TranslationHelper.Translation.ImageAliasing, "Resim taklidi");
        Assert.Equal(TranslationHelper.Translation.ImageControl, "Resim kontrolü");
        Assert.Equal(TranslationHelper.Translation.ImageInfo, "Resim Bilgisi");
        Assert.Equal(TranslationHelper.Translation.Inches, "inç");
        Assert.Equal(TranslationHelper.Translation.InfoWindow, "Bilgi penceresi");
        Assert.Equal(TranslationHelper.Translation.InfoWindowTitle, "Bilgi ve kısayollar");
        Assert.Equal(TranslationHelper.Translation.InterfaceConfiguration, "Arayüz yapılandırması");
        Assert.Equal(TranslationHelper.Translation.Landscape, "Yatay");
        Assert.Equal(TranslationHelper.Translation.Language, "Dil");
        Assert.Equal(TranslationHelper.Translation.LastAccessTime, "Son erişim zamanı");
        Assert.Equal(TranslationHelper.Translation.LastImage, "Son resim");
        Assert.Equal(TranslationHelper.Translation.LastWriteTime, "Son yazma zamanı");
        Assert.Equal(TranslationHelper.Translation.Latitude, "Enlem");
        Assert.Equal(TranslationHelper.Translation.Left, "Sol");
        Assert.Equal(TranslationHelper.Translation.LensMaker, "Lens üreticisi");
        Assert.Equal(TranslationHelper.Translation.LensModel, "Lens modeli");
        Assert.Equal(TranslationHelper.Translation.LightSource, "Işık kaynağı");
        Assert.Equal(TranslationHelper.Translation.LightTheme, "Aydınlık tema");
        Assert.Equal(TranslationHelper.Translation.Lighting, "Aydınlatma");
        Assert.Equal(TranslationHelper.Translation.Loading, "Yükleniyor...");
        Assert.Equal(TranslationHelper.Translation.Longitude, "Boylam");
        Assert.Equal(TranslationHelper.Translation.Looping, "Döngü");
        Assert.Equal(TranslationHelper.Translation.LoopingDisabled, "Döngü devre dışı bırakıldı");
        Assert.Equal(TranslationHelper.Translation.LoopingEnabled, "Döngü etkinleştirildi");
        Assert.Equal(TranslationHelper.Translation.Lossless, "Kayıpsız");
        Assert.Equal(TranslationHelper.Translation.Lossy, "Kayıplı");
        Assert.Equal(TranslationHelper.Translation.Low, "Düşük");
        Assert.Equal(TranslationHelper.Translation.Manual, "Manuel");
        Assert.Equal(TranslationHelper.Translation.MaxAperture, "En büyük diyafram açıklığı");
        Assert.Equal(TranslationHelper.Translation.Maximize, "Maksimize et");
        Assert.Equal(TranslationHelper.Translation.MegaPixels, "megapikseller");
        Assert.Equal(TranslationHelper.Translation.Meter, "Metre");
        Assert.Equal(TranslationHelper.Translation.MeteringMode, "Ölçüm modu");
        Assert.Equal(TranslationHelper.Translation.Minimize, "Minimize et");
        Assert.Equal(TranslationHelper.Translation.MiscSettings, "Çeşitli ayarlar");
        Assert.Equal(TranslationHelper.Translation.Modified, "Değiştirilmiş");
        Assert.Equal(TranslationHelper.Translation.Monochrome, "Monokrom");
        Assert.Equal(TranslationHelper.Translation.MouseDrag, "Fare sürükleme");
        Assert.Equal(TranslationHelper.Translation.MouseKeyBack, "Fare tuşu geri");
        Assert.Equal(TranslationHelper.Translation.MouseKeyForward, "Fare tuşu ileri");
        Assert.Equal(TranslationHelper.Translation.MouseWheel, "Fare tekerleği");
        Assert.Equal(TranslationHelper.Translation.MoveWindow, "Pencereyi taşı");
        Assert.Equal(TranslationHelper.Translation.Navigation, "Navigasyon");
        Assert.Equal(TranslationHelper.Translation.NearestNeighbor, "En yakın komşu");
        Assert.Equal(TranslationHelper.Translation.NegativeColors, "Negatif renkler");
        Assert.Equal(TranslationHelper.Translation.NewWindow, "Yeni pencere");
        Assert.Equal(TranslationHelper.Translation.NextFolder, "Sonraki klasöre git");
        Assert.Equal(TranslationHelper.Translation.NextImage, "Sonraki resim");
        Assert.Equal(TranslationHelper.Translation.NoChange, "Değişiklik yok");
        Assert.Equal(TranslationHelper.Translation.NoConversion, "Dönüşüm yok");
        Assert.Equal(TranslationHelper.Translation.NoImage, "Yüklenen resim yok");
        Assert.Equal(TranslationHelper.Translation.NoImages, "Resim yok");
        Assert.Equal(TranslationHelper.Translation.NoResize, "Yeniden boyutlandırma yok");
        Assert.Equal(TranslationHelper.Translation.None, "Yok");
        Assert.Equal(TranslationHelper.Translation.Normal, "Normal");
        Assert.Equal(TranslationHelper.Translation.NormalWindow, "Normal pencere");
        Assert.Equal(TranslationHelper.Translation.NotDefined, "Tanımlanmadı");
        Assert.Equal(TranslationHelper.Translation.NumpadMinus, "Sayısal tuş takımı -");
        Assert.Equal(TranslationHelper.Translation.NumpadPlus, "Sayısal tuş takımı +");
        Assert.Equal(TranslationHelper.Translation.OldMovie, "Eski Film");
        Assert.Equal(TranslationHelper.Translation.Open, "Aç");
        Assert.Equal(TranslationHelper.Translation.OpenFileDialog, "Bir dosya seçin");
        Assert.Equal(TranslationHelper.Translation.OpenInSameWindow, "Dosyaları aynı pencerede aç");
        Assert.Equal(TranslationHelper.Translation.OpenLastFile, "Son dosyayı aç");
        Assert.Equal(TranslationHelper.Translation.OpenWith, "Şununla aç...");
        Assert.Equal(TranslationHelper.Translation.OptimizeImage, "Resmi Optimize Et");
        Assert.Equal(TranslationHelper.Translation.Orientation, "Yönlendirme");
        Assert.Equal(TranslationHelper.Translation.OutputFolder, "Çıktı klasörü");
        Assert.Equal(TranslationHelper.Translation.Pan, "Panorama");
        Assert.Equal(TranslationHelper.Translation.PaperFold, "Kağıt Katlama");
        Assert.Equal(TranslationHelper.Translation.PasswordArchive, "Şifreli arşiv desteklenmiyor");
        Assert.Equal(TranslationHelper.Translation.PasteImageFromClipholder, "Panodan resmi yapıştır");
        Assert.Equal(TranslationHelper.Translation.PencilSketch, "Kurşun Kalem Çizimi");
        Assert.Equal(TranslationHelper.Translation.PercentComplete, "% tamamlandı...");
        Assert.Equal(TranslationHelper.Translation.Percentage, "Yüzde");
        Assert.Equal(TranslationHelper.Translation.PermanentlyDelete, "Kalıcı olarak sil");
        Assert.Equal(TranslationHelper.Translation.PhotometricInterpretation, "Fotometrik yorumlama");
        Assert.Equal(TranslationHelper.Translation.Pivot, "Eksen");
        Assert.Equal(TranslationHelper.Translation.Pixelate, "Pikselleştir");
        Assert.Equal(TranslationHelper.Translation.Pixels, "pikseller");
        Assert.Equal(TranslationHelper.Translation.Portrait, "Portre");
        Assert.Equal(TranslationHelper.Translation.PressKey, "Tuşa basın...");
        Assert.Equal(TranslationHelper.Translation.PrevFolder, "Önceki klasöre git");
        Assert.Equal(TranslationHelper.Translation.PrevImage, "Önceki resim");
        Assert.Equal(TranslationHelper.Translation.Print, "Yazdır");
        Assert.Equal(TranslationHelper.Translation.PrintSizeCm, "Yazdırma boyutu (cm)");
        Assert.Equal(TranslationHelper.Translation.PrintSizeIn, "Yazdırma boyutu (inç)");
        Assert.Equal(TranslationHelper.Translation.Quality, "Kalite");
        Assert.Equal(TranslationHelper.Translation.Random, "Rastgele");
        Assert.Equal(TranslationHelper.Translation.RecentFiles, "Son dosyalar");
        Assert.Equal(TranslationHelper.Translation.RedEyeReduction, "Kırmızı göz azaltma");
        Assert.Equal(TranslationHelper.Translation.Reload, "Yeniden yükle");
        Assert.Equal(TranslationHelper.Translation.RemoveStarRating, "Derecelendirmeyi kaldır");
        Assert.Equal(TranslationHelper.Translation.RenameFile, "Dosyayı yeniden adlandır");
        Assert.Equal(TranslationHelper.Translation.Reset, "Sıfırla");
        Assert.Equal(TranslationHelper.Translation.ResetButtonText, "Varsayılana sıfırla");
        Assert.Equal(TranslationHelper.Translation.ResetZoom, "Yakınlaştırmayı sıfırla");
        Assert.Equal(TranslationHelper.Translation.Resize, "Yeniden boyutlandır");
        Assert.Equal(TranslationHelper.Translation.ResizeImage, "Resmi yeniden boyutlandır");
        Assert.Equal(TranslationHelper.Translation.Resolution, "Çözünürlük");
        Assert.Equal(TranslationHelper.Translation.ResolutionUnit, "Çözünürlük birimi");
        Assert.Equal(TranslationHelper.Translation.RestartApp, "Uygulamayı yeniden başlat");
        Assert.Equal(TranslationHelper.Translation.RestoreDown, "Küçült");
        Assert.Equal(TranslationHelper.Translation.Reverse, "Tersine çevir");
        Assert.Equal(TranslationHelper.Translation.Right, "Sağ");
        Assert.Equal(TranslationHelper.Translation.Ripple, "Dalgalanma");
        Assert.Equal(TranslationHelper.Translation.RippleAlt, "Dalgalanma yüksekliği");
        Assert.Equal(TranslationHelper.Translation.RotateLeft, "Sola döndür");
        Assert.Equal(TranslationHelper.Translation.RotateRight, "Sağa döndür");
        Assert.Equal(TranslationHelper.Translation.Rotated, "Döndürülmüş");
        Assert.Equal(TranslationHelper.Translation.Saturation, "Doygunluk");
        Assert.Equal(TranslationHelper.Translation.Save, "Kaydet");
        Assert.Equal(TranslationHelper.Translation.SaveAs, "Farklı kaydet");
        Assert.Equal(TranslationHelper.Translation.SaveImage, "Resmi kaydet");
        Assert.Equal(TranslationHelper.Translation.SavingFileFailed, "Dosya kaydedilemedi");
        Assert.Equal(TranslationHelper.Translation.ScrollAndRotate, "Kaydır ve döndür");
        Assert.Equal(TranslationHelper.Translation.ScrollDirection, "Kaydırma yönü");
        Assert.Equal(TranslationHelper.Translation.ScrollDown, "Aşağı kaydır");
        Assert.Equal(TranslationHelper.Translation.ScrollToBottom, "En alta kaydır");
        Assert.Equal(TranslationHelper.Translation.ScrollToTop, "En üste kaydır");
        Assert.Equal(TranslationHelper.Translation.ScrollToZoom, "Fare tekerleği ile yakınlaştır, Ctrl ile gezin");
        Assert.Equal(TranslationHelper.Translation.ScrollUp, "Yukarı kaydır");
        Assert.Equal(TranslationHelper.Translation.Scrolling, "Kaydırma");
        Assert.Equal(TranslationHelper.Translation.ScrollingDisabled, "Kaydırma devre dışı");
        Assert.Equal(TranslationHelper.Translation.ScrollingEnabled, "Kaydırma etkin");
        Assert.Equal(TranslationHelper.Translation.SearchSubdirectory, "Alt dizinlerde ara");
        Assert.Equal(TranslationHelper.Translation.SecAbbreviation, "Sny.");
        Assert.Equal(TranslationHelper.Translation.SelectAll, "Hepsini seç");
        Assert.Equal(TranslationHelper.Translation.SelectGalleryThumb, "Galeri küçük resmini seç");
        Assert.Equal(TranslationHelper.Translation.SendCurrentImageToRecycleBin, "Mevcut resmi çöp kutusuna gönder");
        Assert.Equal(TranslationHelper.Translation.SentFileToRecycleBin, "Dosya çöp kutusuna gönderildi");
        Assert.Equal(TranslationHelper.Translation.SetAs, "Olarak ayarla...");
        Assert.Equal(TranslationHelper.Translation.SetAsLockScreenImage, "Kilit ekranı resmi olarak ayarla");
        Assert.Equal(TranslationHelper.Translation.SetAsWallpaper, "Duvar kağıdı olarak ayarla");
        Assert.Equal(TranslationHelper.Translation.SetCurrentImageAsWallpaper,
            "Mevcut resmi duvar kağıdı olarak ayarla:");
        Assert.Equal(TranslationHelper.Translation.SetStarRating, "Yıldız derecelendirmesi ayarla");
        Assert.Equal(TranslationHelper.Translation.Settings, "Ayarlar");
        Assert.Equal(TranslationHelper.Translation.Shade, "Gölge");
        Assert.Equal(TranslationHelper.Translation.Sharpness, "Keskinlik");
        Assert.Equal(TranslationHelper.Translation.Shift, "Shift");
        Assert.Equal(TranslationHelper.Translation.ShowAllSettingsWindow, "Tüm ayarlar penceresini göster");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGallery, "Alt galeriyi göster");
        Assert.Equal(TranslationHelper.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Arayüz gizlendiğinde alt galeriyi göster");
        Assert.Equal(TranslationHelper.Translation.ShowBottomToolbar, "Alt araç çubuğunu göster");
        Assert.Equal(TranslationHelper.Translation.ShowConfirmationOnEsc,
            "ESC'yi basarak pencereyi kapatmak istiyor musunuz?");
        Assert.Equal(TranslationHelper.Translation.ShowFadeInButtonsOnHover,
            "Farenin üzerine gelindiğinde soluklaşan düğmeleri göster");
        Assert.Equal(TranslationHelper.Translation.ShowFileSavingDialog, "Dosya kaydetme penceresini göster");
        Assert.Equal(TranslationHelper.Translation.ShowImageGallery, "Resim galerisini göster");
        Assert.Equal(TranslationHelper.Translation.ShowImageInfo, "Resim bilgisini göster");
        Assert.Equal(TranslationHelper.Translation.ShowInFolder, "Klasörde göster");
        Assert.Equal(TranslationHelper.Translation.ShowInfoWindow, "Bilgi penceresini göster");
        Assert.Equal(TranslationHelper.Translation.ShowResizeWindow, "Boyutlandırma penceresini göster");
        Assert.Equal(TranslationHelper.Translation.ShowUI, "Arayüzü göster");
        Assert.Equal(TranslationHelper.Translation.ShutterPriority, "Enstantane önceliği");
        Assert.Equal(TranslationHelper.Translation.SideBySide, "Yan yana");
        Assert.Equal(TranslationHelper.Translation.SideBySideTooltip, "Resimleri yan yana göster");
        Assert.Equal(TranslationHelper.Translation.Size, "Boyut");
        Assert.Equal(TranslationHelper.Translation.SizeMp, "Boyut (mp)");
        Assert.Equal(TranslationHelper.Translation.SizeTooltip, "İstediğiniz boyutu piksel veya yüzde cinsinden gir.");
        Assert.Equal(TranslationHelper.Translation.Sketch, "Çizim");
        Assert.Equal(TranslationHelper.Translation.Slideshow, "Slayt gösterisi");
        Assert.Equal(TranslationHelper.Translation.SmoothMagnify, "Pürüzsüz Büyütme");
        Assert.Equal(TranslationHelper.Translation.Soft, "Yumuşak");
        Assert.Equal(TranslationHelper.Translation.Software, "Yazılım");
        Assert.Equal(TranslationHelper.Translation.SortFilesBy, "Dosyaları şuna göre sırala");
        Assert.Equal(TranslationHelper.Translation.SourceFolder, "Kaynak klasör");
        Assert.Equal(TranslationHelper.Translation.Space, "Boşluk");
        Assert.Equal(TranslationHelper.Translation.Square, "Kare");
        Assert.Equal(TranslationHelper.Translation.Start, "Başla");
        Assert.Equal(TranslationHelper.Translation.StartSlideshow, "Slayt gösterisini başlat");
        Assert.Equal(TranslationHelper.Translation.StayCentered, "Pencereyi ortada tut");
        Assert.Equal(TranslationHelper.Translation.StayTopMost, "Diğer pencerelerin üstünde kal");
        Assert.Equal(TranslationHelper.Translation.Stretch, "Esneme");
        Assert.Equal(TranslationHelper.Translation.StretchImage, "Resmi esnet");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightDetected, "Strob ışık geri dönüşü algılandı");
        Assert.Equal(TranslationHelper.Translation.StrobeReturnLightNotDetected, "Strob ışık geri dönüşü algılanmadı");
        Assert.Equal(TranslationHelper.Translation.Subject, "Konu");
        Assert.Equal(TranslationHelper.Translation.Swirl, "Girdap");
        Assert.Equal(TranslationHelper.Translation.TelescopicBlur, "Teleskopik Bulanıklık");
        Assert.Equal(TranslationHelper.Translation.Theme, "Tema");
        Assert.Equal(TranslationHelper.Translation.Thumbnail, "Küçük resim");
        Assert.Equal(TranslationHelper.Translation.Tile, "Fayans");
        Assert.Equal(TranslationHelper.Translation.Title, "Başlık");
        Assert.Equal(TranslationHelper.Translation.ToggleBackgroundColor, "Arka plan rengini aç / kapat");
        Assert.Equal(TranslationHelper.Translation.ToggleFullscreen, "Tam ekranı aç / kapat");
        Assert.Equal(TranslationHelper.Translation.ToggleLooping, "Döngüyü aç / kapat");
        Assert.Equal(TranslationHelper.Translation.ToggleScroll, "Kaydırmayı aç / kapat");
        Assert.Equal(TranslationHelper.Translation.ToggleTaskbarProgress, "Görev çubuğu ilerlemesini görüntüle");
        Assert.Equal(TranslationHelper.Translation.ToneMapping, "Ton Haritalama");
        Assert.Equal(TranslationHelper.Translation.UnableToRender, "Görüntü işlenemiyor");
        Assert.Equal(TranslationHelper.Translation.Uncalibrated, "Uncalibrated");
        Assert.Equal(TranslationHelper.Translation.Underwater, "Kalibre edilmemiş");
        Assert.Equal(TranslationHelper.Translation.UnexpectedError, "Bilinmeyen bir hata oluştu");
        Assert.Equal(TranslationHelper.Translation.Unflip, "Ters çevir");
        Assert.Equal(TranslationHelper.Translation.Uniform, "üniforma");
        Assert.Equal(TranslationHelper.Translation.UniformToFill, "Doldurulacak üniforma");
        Assert.Equal(TranslationHelper.Translation.Unknown, "Bilinmiyor");
        Assert.Equal(TranslationHelper.Translation.UnsupportedFile, "Desteklenmeyen dosya");
        Assert.Equal(TranslationHelper.Translation.Up, "Yukarı");
        Assert.Equal(TranslationHelper.Translation.UsingMouse, "Fare kullanılıyor");
        Assert.Equal(TranslationHelper.Translation.UsingTouchpad, "Dokunmatik yüzey kullanılıyor");
        Assert.Equal(TranslationHelper.Translation.Version, "Sürüm:");
        Assert.Equal(TranslationHelper.Translation.ViewLicenseFile, "Lisans dosyasını görüntüle");
        Assert.Equal(TranslationHelper.Translation.WaveWarper, "Dalga Savar");
        Assert.Equal(TranslationHelper.Translation.WhiteBalance, "Beyaz dengesi");
        Assert.Equal(TranslationHelper.Translation.WhiteFluorescent, "Beyaz floresan");
        Assert.Equal(TranslationHelper.Translation.Width, "Genişlik");
        Assert.Equal(TranslationHelper.Translation.WidthAndHeight, "Genişlik ve yükseklik");
        Assert.Equal(TranslationHelper.Translation.WindowManagement, "Pencere yönetimi");
        Assert.Equal(TranslationHelper.Translation.WindowScaling, "Pencere ölçeklendirme");
        Assert.Equal(TranslationHelper.Translation.Zoom, "Yakınlaştırma");
        Assert.Equal(TranslationHelper.Translation.ZoomIn, "Yakınlaştır");
        Assert.Equal(TranslationHelper.Translation.ZoomOut, "Uzaklaştır");
        Assert.Equal(TranslationHelper.Translation._1Star, "1 yıldız derecesi");
        Assert.Equal(TranslationHelper.Translation._2Star, "2 yıldız derecesi");
        Assert.Equal(TranslationHelper.Translation._3Star, "3 yıldız derecesi");
        Assert.Equal(TranslationHelper.Translation._4Star, "4 yıldız derecesi");
        Assert.Equal(TranslationHelper.Translation._5Star, "5 yıldız derecesi");
    }
}