using PicView.Core.Localization;

namespace PicView.Tests.LanguageTests;

public static class TurkishUnitTest
{
#pragma warning disable xUnit2000
    [Fact]
    public static async Task CheckTurkishLanguage()
    {
        var exists = await TranslationManager.LoadLanguage("tr");
        Assert.True(exists);

        Assert.Equal(TranslationManager.Translation.About, "Hakkında");
        Assert.Equal(TranslationManager.Translation.ActionProgram, "Eylem programı");
        Assert.Equal(TranslationManager.Translation.AddedToClipboard, "Panoya eklendi");
        Assert.Equal(TranslationManager.Translation.AdditionalFunctions, "Ek fonksiyonlar");
        Assert.Equal(TranslationManager.Translation.AdjustNavSpeed, "Tuşa basılı tutulduğunda hızı ayarla");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForSlideshow, "Slayt gösterisi zamanlamasını ayarla");
        Assert.Equal(TranslationManager.Translation.AdjustTimingForZoom, "Yakınlaştırma hızını ayarla");
        Assert.Equal(TranslationManager.Translation.AdjustZoomLevel, "Yakınlaştırma seviyesini ayarla");
        Assert.Equal(TranslationManager.Translation.AdvanceBy100Images, "100 Resim ileri");
        Assert.Equal(TranslationManager.Translation.AdvanceBy10Images, "10 Resim ileri");
        Assert.Equal(TranslationManager.Translation.AllowZoomOut,
            "Görüntü zaten maksimum boyuttayken görüntüyü uzaklaştırmaktan kaçın");
        Assert.Equal(TranslationManager.Translation.Alt, "Alt");
        Assert.Equal(TranslationManager.Translation.Altitude, "İrtifa");
        Assert.Equal(TranslationManager.Translation.AperturePriority, "Diyafram önceliği");
        Assert.Equal(TranslationManager.Translation.Appearance, "Görünüm");
        Assert.Equal(TranslationManager.Translation.ApplicationShortcuts, "Uygulama kısayolları");
        Assert.Equal(TranslationManager.Translation.ApplicationStartup, "Uygulama başlangıcı");
        Assert.Equal(TranslationManager.Translation.Apply, "Uygula");
        Assert.Equal(TranslationManager.Translation.Applying, "Uygulanıyor");
        Assert.Equal(TranslationManager.Translation.Ascending, "Artan");
        Assert.Equal(TranslationManager.Translation.AspectRatio, "En-boy oranı");
        Assert.Equal(TranslationManager.Translation.Authors, "Yazarlar");
        Assert.Equal(TranslationManager.Translation.Auto, "Otomatik");
        Assert.Equal(TranslationManager.Translation.AutoFitWindow, "Pencereye otomatik sığdır");
        Assert.Equal(TranslationManager.Translation.BadArchive, "Arşiv işlenemedi");
        Assert.Equal(TranslationManager.Translation.Base64Image, "Base64 resim");
        Assert.Equal(TranslationManager.Translation.BatchResize, "Toplu Yeniden Boyutlandırma");
        Assert.Equal(TranslationManager.Translation.BitDepth, "Bit derinliği");
        Assert.Equal(TranslationManager.Translation.BlackAndWhite, "Siyah Beyaz");
        Assert.Equal(TranslationManager.Translation.Blur, "Bulanıklaştırma");
        Assert.Equal(TranslationManager.Translation.BottomGalleryItemSize, "Alt galerideki küçük resimlerin boyutu");
        Assert.Equal(TranslationManager.Translation.BottomGalleryThumbnailStretch, "Alt galeride küçük resim esnetme");
        Assert.Equal(TranslationManager.Translation.Brightness, "Parlaklık");
        Assert.Equal(TranslationManager.Translation.CameraMaker, "Kamera üreticisi");
        Assert.Equal(TranslationManager.Translation.CameraModel, "Kamera modeli");
        Assert.Equal(TranslationManager.Translation.Cancel, "İptal");
        Assert.Equal(TranslationManager.Translation.Center, "Merkez");
        Assert.Equal(TranslationManager.Translation.CenterWindow, "Pencereyi ortala");
        Assert.Equal(TranslationManager.Translation.Centimeters, "Santimetre");
        Assert.Equal(TranslationManager.Translation.ChangeBackground, "Arka planı değiştir");
        Assert.Equal(TranslationManager.Translation.ChangeBackgroundTooltip,
            "Şeffaf arka plana sahip resimler için arka plan rengini değiştir");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingText,
            "Kısayolu değiştirmek için bir metin kutusuna tıkla. Esc tuşuna basmak kısayolu kaldırır.");
        Assert.Equal(TranslationManager.Translation.ChangeKeybindingTooltip, "Kısayolu değiştirmek için tıkla");
        Assert.Equal(TranslationManager.Translation.ChangingThemeRequiresRestart,
            "* Tema değişikliği yeniden başlatmayı gerektirir");
        Assert.Equal(TranslationManager.Translation.CheckForUpdates, "Güncellemeleri kontrol et");
        Assert.Equal(TranslationManager.Translation.ClipboardImage, "Pano resmi");
        Assert.Equal(TranslationManager.Translation.Close, "Kapat");
        Assert.Equal(TranslationManager.Translation.CloseApp, "Tüm uygulamayı kapat");
        Assert.Equal(TranslationManager.Translation.CloseGallery, "Galeriyi kapat");
        Assert.Equal(TranslationManager.Translation.CloseWindowPrompt, "Pencereyi kapatmak istiyor musunuz?");
        Assert.Equal(TranslationManager.Translation.CloudyWeather, "Bulutlu hava");
        Assert.Equal(TranslationManager.Translation.ColorPickerTool, "Renk Seçme Aracı");
        Assert.Equal(TranslationManager.Translation.ColorPickerToolTooltip, "Resimden renk seç");
        Assert.Equal(TranslationManager.Translation.ColorRepresentation, "Renk temsili");
        Assert.Equal(TranslationManager.Translation.ColorTone, "Renk Tonu");
        Assert.Equal(TranslationManager.Translation.CompressedBitsPixel, "Piksel başına sıkıştırılmış bit");
        Assert.Equal(TranslationManager.Translation.Compression, "Sıkıştırma");
        Assert.Equal(TranslationManager.Translation.Contrast, "Kontrast");
        Assert.Equal(TranslationManager.Translation.ConvertTo, "Dönüştür");
        Assert.Equal(TranslationManager.Translation.ConvertedToBase64, "Base64'e dönüştürüldü");
        Assert.Equal(TranslationManager.Translation.CoolWhiteFluorescent, "Soğuk beyaz floresan");
        Assert.Equal(TranslationManager.Translation.CopiedImage, "Resim panoya kopyalandı");
        Assert.Equal(TranslationManager.Translation.Copy, "Kopyala");
        Assert.Equal(TranslationManager.Translation.CopyFile, "Dosyayı kopyala");
        Assert.Equal(TranslationManager.Translation.CopyImage, "Resmi kopyala");
        Assert.Equal(TranslationManager.Translation.CopyImageTooltip, "Windows panosuna resim olarak kopyala");
        Assert.Equal(TranslationManager.Translation.Copyright, "Telif Hakkı");
        Assert.Equal(TranslationManager.Translation.Created, "Oluşturuldu");
        Assert.Equal(TranslationManager.Translation.CreationTime, "Oluşturma zamanı");
        Assert.Equal(TranslationManager.Translation.CreativeProgram, "Yaratıcı program");
        Assert.Equal(TranslationManager.Translation.Credits, "Krediler");
        Assert.Equal(TranslationManager.Translation.Crop, "Kırp");
        Assert.Equal(TranslationManager.Translation.CropMessage, "Kapatmak için Esc, kaydetmek için Enter'a bas");
        Assert.Equal(TranslationManager.Translation.CropPicture, "Resmi Kırp");
        Assert.Equal(TranslationManager.Translation.Ctrl, "Ctrl");
        Assert.Equal(TranslationManager.Translation.CtrlToZoom, "Yakınlaştırmak için Ctrl, gezinmek için kaydır");
        Assert.Equal(TranslationManager.Translation.Cut, "Kes");
        Assert.Equal(TranslationManager.Translation.DarkTheme, "Karanlık tema");
        Assert.Equal(TranslationManager.Translation.Date, "Tarih");
        Assert.Equal(TranslationManager.Translation.DateTaken, "Çekilme tarihi");
        Assert.Equal(TranslationManager.Translation.DayWhiteFluorescent, "Gündüz beyaz floresan");
        Assert.Equal(TranslationManager.Translation.Daylight, "Gün ışığı");
        Assert.Equal(TranslationManager.Translation.DaylightFluorescent, "Gün ışığı floresan");
        Assert.Equal(TranslationManager.Translation.Del, "Sil");
        Assert.Equal(TranslationManager.Translation.DeleteFile, "Dosyayı sil");
        Assert.Equal(TranslationManager.Translation.DeleteFilePermanently,
            "Dosyayı kalıcı olarak silmek istediğinizden emin misin");
        Assert.Equal(TranslationManager.Translation.DeletedFile, "Silinen dosya");
        Assert.Equal(TranslationManager.Translation.Descending, "Azalan");
        Assert.Equal(TranslationManager.Translation.DigitalZoom, "Dijital yakınlaştırma");
        Assert.Equal(TranslationManager.Translation.DisableFadeInButtonsOnHover,
            "Fareyle üzerine gelindiğinde soluklaşan butonları devre dışı bırak");
        Assert.Equal(TranslationManager.Translation.DiskSize, "Disk boyutu");
        Assert.Equal(TranslationManager.Translation.DoubleClick, "Çift tıklama");
        Assert.Equal(TranslationManager.Translation.Down, "Aşağı");
        Assert.Equal(TranslationManager.Translation.Dpi, "DPI");
        Assert.Equal(TranslationManager.Translation.DragFileTo,
            "Dosyayı Windows Gezgini'ne veya başka bir uygulama/tarayıcıya sürükle");
        Assert.Equal(TranslationManager.Translation.DragImage, "Resmi sürükle");
        Assert.Equal(TranslationManager.Translation.DropToLoad, "Resmi yüklemek için bırak");
        Assert.Equal(TranslationManager.Translation.DuplicateFile, "Yinelenen dosya");
        Assert.Equal(TranslationManager.Translation.Effects, "Efektler");
        Assert.Equal(TranslationManager.Translation.EffectsTooltip, "Resim efektleri penceresini göster");
        Assert.Equal(TranslationManager.Translation.Enter, "Enter");
        Assert.Equal(TranslationManager.Translation.Esc, "Esc");
        Assert.Equal(TranslationManager.Translation.EscCloseTooltip, "Açık olan pencere/menüyü kapatır");
        Assert.Equal(TranslationManager.Translation.ExifVersion, "Exif sürümü");
        Assert.Equal(TranslationManager.Translation.ExpandedGalleryItemSize, "Küçük resim boyutu");
        Assert.Equal(TranslationManager.Translation.ExposureBias, "Pozlama yanlılığı");
        Assert.Equal(TranslationManager.Translation.ExposureProgram, "Pozlama programı");
        Assert.Equal(TranslationManager.Translation.ExposureTime, "Pozlama süresi");
        Assert.Equal(TranslationManager.Translation.FNumber, "F numarası");
        Assert.Equal(TranslationManager.Translation.File, "Dosya");
        Assert.Equal(TranslationManager.Translation.FileCopy, "Dosya panoya eklendi");
        Assert.Equal(TranslationManager.Translation.FileCopyPath, "Dosya yolunu kopyala");
        Assert.Equal(TranslationManager.Translation.FileCopyPathMessage, "Dosya yolu panoya eklendi");
        Assert.Equal(TranslationManager.Translation.FileCutMessage, "Dosya taşınmak üzere panoya eklendi");
        Assert.Equal(TranslationManager.Translation.FileExtension, "Dosya uzantısı");
        Assert.Equal(TranslationManager.Translation.FileManagement, "Dosya yönetimi");
        Assert.Equal(TranslationManager.Translation.FileName, "Dosya adı");
        Assert.Equal(TranslationManager.Translation.FilePaste, "Yapıştır");
        Assert.Equal(TranslationManager.Translation.FileProperties, "Dosya özellikleri");
        Assert.Equal(TranslationManager.Translation.FileSize, "Dosya boyutu");
        Assert.Equal(TranslationManager.Translation.Files, "Dosyalar");
        Assert.Equal(TranslationManager.Translation.Fill, "Doldur");
        Assert.Equal(TranslationManager.Translation.FillHeight, "⇔ Yüksekliği doldur");
        Assert.Equal(TranslationManager.Translation.FillSquare, "Kareyi doldur");
        Assert.Equal(TranslationManager.Translation.FineWeather, "Güzel hava");
        Assert.Equal(TranslationManager.Translation.FirstImage, "İlk resim");
        Assert.Equal(TranslationManager.Translation.Fit, "Sığdır");
        Assert.Equal(TranslationManager.Translation.FitToWindow, "Pencereye/resme sığdır");
        Assert.Equal(TranslationManager.Translation.Flash, "Flaş");
        Assert.Equal(TranslationManager.Translation.FlashDidNotFire, "Flaş ateşlenmedi");
        Assert.Equal(TranslationManager.Translation.FlashEnergy, "Flaş enerjisi");
        Assert.Equal(TranslationManager.Translation.FlashFired, "Flaş ateşlendi");
        Assert.Equal(TranslationManager.Translation.FlashMode, "Flaş modu");
        Assert.Equal(TranslationManager.Translation.Flip, "Yatay olarak çevir");
        Assert.Equal(TranslationManager.Translation.Flipped, "Yatay olarak çevrildi");
        Assert.Equal(TranslationManager.Translation.Fluorescent, "Floresan");
        Assert.Equal(TranslationManager.Translation.FocalLength, "Odak uzaklığı");
        Assert.Equal(TranslationManager.Translation.FocalLength35mm, "35mm odak uzaklığı");
        Assert.Equal(TranslationManager.Translation.Folder, "Klasör");
        Assert.Equal(TranslationManager.Translation.Forward, "İleri");
        Assert.Equal(TranslationManager.Translation.Fstop, "F-stop");
        Assert.Equal(TranslationManager.Translation.FullPath, "Tam dosya yolu");
        Assert.Equal(TranslationManager.Translation.Fullscreen, "Tam ekran");
        Assert.Equal(TranslationManager.Translation.GallerySettings, "Galeri ayarları");
        Assert.Equal(TranslationManager.Translation.GalleryThumbnailStretch, "Galeri küçük resmi esnetme");
        Assert.Equal(TranslationManager.Translation.GeneralSettings, "Genel ayarlar");
        Assert.Equal(TranslationManager.Translation.GenerateThumbnails, "Küçük resimler oluştur");
        Assert.Equal(TranslationManager.Translation.GithubRepo, "Github deposu");
        Assert.Equal(TranslationManager.Translation.GlassTheme, "Cam Teması");
        Assert.Equal(TranslationManager.Translation.GoBackBy100Images, "100 Resim geri git");
        Assert.Equal(TranslationManager.Translation.GoBackBy10Images, "10 Resim geri git");
        Assert.Equal(TranslationManager.Translation.Hard, "Zor");
        Assert.Equal(TranslationManager.Translation.Height, "Yükseklik");
        Assert.Equal(TranslationManager.Translation.HideBottomGallery, "Alt galeriyi gizle");
        Assert.Equal(TranslationManager.Translation.HideBottomToolbar, "Alt araç çubuğunu gizle");
        Assert.Equal(TranslationManager.Translation.HideUI, "Arayüzü gizle");
        Assert.Equal(TranslationManager.Translation.High, "Yüksek");
        Assert.Equal(TranslationManager.Translation.HighQuality, "Yüksek kalite");
        Assert.Equal(TranslationManager.Translation.HighlightColor, "Vurgulama rengi");
        Assert.Equal(TranslationManager.Translation.ISOSpeed, "ISO hızı");
        Assert.Equal(TranslationManager.Translation.Image, "Resim");
        Assert.Equal(TranslationManager.Translation.ImageAliasing, "Resim taklidi");
        Assert.Equal(TranslationManager.Translation.ImageControl, "Resim kontrolü");
        Assert.Equal(TranslationManager.Translation.ImageInfo, "Resim Bilgisi");
        Assert.Equal(TranslationManager.Translation.Inches, "inç");
        Assert.Equal(TranslationManager.Translation.InfoWindow, "Bilgi penceresi");
        Assert.Equal(TranslationManager.Translation.InfoWindowTitle, "Bilgi ve kısayollar");
        Assert.Equal(TranslationManager.Translation.InterfaceConfiguration, "Arayüz yapılandırması");
        Assert.Equal(TranslationManager.Translation.Landscape, "Yatay");
        Assert.Equal(TranslationManager.Translation.Language, "Dil");
        Assert.Equal(TranslationManager.Translation.LastAccessTime, "Son erişim zamanı");
        Assert.Equal(TranslationManager.Translation.LastImage, "Son resim");
        Assert.Equal(TranslationManager.Translation.LastWriteTime, "Son yazma zamanı");
        Assert.Equal(TranslationManager.Translation.Latitude, "Enlem");
        Assert.Equal(TranslationManager.Translation.Left, "Sol");
        Assert.Equal(TranslationManager.Translation.LensMaker, "Lens üreticisi");
        Assert.Equal(TranslationManager.Translation.LensModel, "Lens modeli");
        Assert.Equal(TranslationManager.Translation.LightSource, "Işık kaynağı");
        Assert.Equal(TranslationManager.Translation.LightTheme, "Aydınlık tema");
        Assert.Equal(TranslationManager.Translation.Lighting, "Aydınlatma");
        Assert.Equal(TranslationManager.Translation.Loading, "Yükleniyor...");
        Assert.Equal(TranslationManager.Translation.Longitude, "Boylam");
        Assert.Equal(TranslationManager.Translation.Looping, "Döngü");
        Assert.Equal(TranslationManager.Translation.LoopingDisabled, "Döngü devre dışı bırakıldı");
        Assert.Equal(TranslationManager.Translation.LoopingEnabled, "Döngü etkinleştirildi");
        Assert.Equal(TranslationManager.Translation.Lossless, "Kayıpsız");
        Assert.Equal(TranslationManager.Translation.Lossy, "Kayıplı");
        Assert.Equal(TranslationManager.Translation.Low, "Düşük");
        Assert.Equal(TranslationManager.Translation.Manual, "Manuel");
        Assert.Equal(TranslationManager.Translation.MaxAperture, "En büyük diyafram açıklığı");
        Assert.Equal(TranslationManager.Translation.Maximize, "Maksimize et");
        Assert.Equal(TranslationManager.Translation.MegaPixels, "megapikseller");
        Assert.Equal(TranslationManager.Translation.Meter, "Metre");
        Assert.Equal(TranslationManager.Translation.MeteringMode, "Ölçüm modu");
        Assert.Equal(TranslationManager.Translation.Minimize, "Minimize et");
        Assert.Equal(TranslationManager.Translation.MiscSettings, "Çeşitli ayarlar");
        Assert.Equal(TranslationManager.Translation.Modified, "Değiştirilmiş");
        Assert.Equal(TranslationManager.Translation.MouseDrag, "Fare sürükleme");
        Assert.Equal(TranslationManager.Translation.MouseKeyBack, "Fare tuşu geri");
        Assert.Equal(TranslationManager.Translation.MouseKeyForward, "Fare tuşu ileri");
        Assert.Equal(TranslationManager.Translation.MouseWheel, "Fare tekerleği");
        Assert.Equal(TranslationManager.Translation.MoveWindow, "Pencereyi taşı");
        Assert.Equal(TranslationManager.Translation.Navigation, "Navigasyon");
        Assert.Equal(TranslationManager.Translation.NearestNeighbor, "En yakın komşu");
        Assert.Equal(TranslationManager.Translation.NegativeColors, "Negatif renkler");
        Assert.Equal(TranslationManager.Translation.NewWindow, "Yeni pencere");
        Assert.Equal(TranslationManager.Translation.NextFolder, "Sonraki klasöre git");
        Assert.Equal(TranslationManager.Translation.NextImage, "Sonraki resim");
        Assert.Equal(TranslationManager.Translation.NoChange, "Değişiklik yok");
        Assert.Equal(TranslationManager.Translation.NoConversion, "Dönüşüm yok");
        Assert.Equal(TranslationManager.Translation.NoImage, "Yüklenen resim yok");
        Assert.Equal(TranslationManager.Translation.NoImages, "Resim yok");
        Assert.Equal(TranslationManager.Translation.NoResize, "Yeniden boyutlandırma yok");
        Assert.Equal(TranslationManager.Translation.None, "Yok");
        Assert.Equal(TranslationManager.Translation.Normal, "Normal");
        Assert.Equal(TranslationManager.Translation.NormalWindow, "Normal pencere");
        Assert.Equal(TranslationManager.Translation.NotDefined, "Tanımlanmadı");
        Assert.Equal(TranslationManager.Translation.NumpadMinus, "Sayısal tuş takımı -");
        Assert.Equal(TranslationManager.Translation.NumpadPlus, "Sayısal tuş takımı +");
        Assert.Equal(TranslationManager.Translation.OldMovie, "Eski Film");
        Assert.Equal(TranslationManager.Translation.Open, "Aç");
        Assert.Equal(TranslationManager.Translation.OpenFileDialog, "Bir dosya seçin");
        Assert.Equal(TranslationManager.Translation.OpenInSameWindow, "Dosyaları aynı pencerede aç");
        Assert.Equal(TranslationManager.Translation.OpenLastFile, "Son dosyayı aç");
        Assert.Equal(TranslationManager.Translation.OpenWith, "Şununla aç...");
        Assert.Equal(TranslationManager.Translation.OptimizeImage, "Resmi Optimize Et");
        Assert.Equal(TranslationManager.Translation.Orientation, "Yönlendirme");
        Assert.Equal(TranslationManager.Translation.OutputFolder, "Çıktı klasörü");
        Assert.Equal(TranslationManager.Translation.Pan, "Panorama");
        Assert.Equal(TranslationManager.Translation.PasswordArchive, "Şifreli arşiv desteklenmiyor");
        Assert.Equal(TranslationManager.Translation.PasteImageFromClipholder, "Panodan resmi yapıştır");
        Assert.Equal(TranslationManager.Translation.PencilSketch, "Kurşun Kalem Çizimi");
        Assert.Equal(TranslationManager.Translation.PercentComplete, "% tamamlandı...");
        Assert.Equal(TranslationManager.Translation.Percentage, "Yüzde");
        Assert.Equal(TranslationManager.Translation.PermanentlyDelete, "Kalıcı olarak sil");
        Assert.Equal(TranslationManager.Translation.PhotometricInterpretation, "Fotometrik yorumlama");
        Assert.Equal(TranslationManager.Translation.Pixels, "pikseller");
        Assert.Equal(TranslationManager.Translation.Portrait, "Portre");
        Assert.Equal(TranslationManager.Translation.PressKey, "Tuşa basın...");
        Assert.Equal(TranslationManager.Translation.PrevFolder, "Önceki klasöre git");
        Assert.Equal(TranslationManager.Translation.PrevImage, "Önceki resim");
        Assert.Equal(TranslationManager.Translation.Print, "Yazdır");
        Assert.Equal(TranslationManager.Translation.PrintSizeCm, "Yazdırma boyutu (cm)");
        Assert.Equal(TranslationManager.Translation.PrintSizeIn, "Yazdırma boyutu (inç)");
        Assert.Equal(TranslationManager.Translation.Quality, "Kalite");
        Assert.Equal(TranslationManager.Translation.Random, "Rastgele");
        Assert.Equal(TranslationManager.Translation.RecentFiles, "Son dosyalar");
        Assert.Equal(TranslationManager.Translation.RedEyeReduction, "Kırmızı göz azaltma");
        Assert.Equal(TranslationManager.Translation.Reload, "Yeniden yükle");
        Assert.Equal(TranslationManager.Translation.RemoveStarRating, "Derecelendirmeyi kaldır");
        Assert.Equal(TranslationManager.Translation.RenameFile, "Dosyayı yeniden adlandır");
        Assert.Equal(TranslationManager.Translation.Reset, "Sıfırla");
        Assert.Equal(TranslationManager.Translation.ResetButtonText, "Varsayılana sıfırla");
        Assert.Equal(TranslationManager.Translation.ResetZoom, "Yakınlaştırmayı sıfırla");
        Assert.Equal(TranslationManager.Translation.Resize, "Yeniden boyutlandır");
        Assert.Equal(TranslationManager.Translation.ResizeImage, "Resmi yeniden boyutlandır");
        Assert.Equal(TranslationManager.Translation.Resolution, "Çözünürlük");
        Assert.Equal(TranslationManager.Translation.ResolutionUnit, "Çözünürlük birimi");
        Assert.Equal(TranslationManager.Translation.RestartApp, "Uygulamayı yeniden başlat");
        Assert.Equal(TranslationManager.Translation.RestoreDown, "Küçült");
        Assert.Equal(TranslationManager.Translation.Reverse, "Tersine çevir");
        Assert.Equal(TranslationManager.Translation.Right, "Sağ");
        Assert.Equal(TranslationManager.Translation.RotateLeft, "Sola döndür");
        Assert.Equal(TranslationManager.Translation.RotateRight, "Sağa döndür");
        Assert.Equal(TranslationManager.Translation.Rotated, "Döndürülmüş");
        Assert.Equal(TranslationManager.Translation.Saturation, "Doygunluk");
        Assert.Equal(TranslationManager.Translation.Save, "Kaydet");
        Assert.Equal(TranslationManager.Translation.SaveAs, "Farklı kaydet");
        Assert.Equal(TranslationManager.Translation.SavingFileFailed, "Dosya kaydedilemedi");
        Assert.Equal(TranslationManager.Translation.ScrollAndRotate, "Kaydır ve döndür");
        Assert.Equal(TranslationManager.Translation.ScrollDirection, "Kaydırma yönü");
        Assert.Equal(TranslationManager.Translation.ScrollDown, "Aşağı kaydır");
        Assert.Equal(TranslationManager.Translation.ScrollToBottom, "En alta kaydır");
        Assert.Equal(TranslationManager.Translation.ScrollToTop, "En üste kaydır");
        Assert.Equal(TranslationManager.Translation.ScrollToZoom, "Fare tekerleği ile yakınlaştır, Ctrl ile gezin");
        Assert.Equal(TranslationManager.Translation.ScrollUp, "Yukarı kaydır");
        Assert.Equal(TranslationManager.Translation.Scrolling, "Kaydırma");
        Assert.Equal(TranslationManager.Translation.ScrollingDisabled, "Kaydırma devre dışı");
        Assert.Equal(TranslationManager.Translation.ScrollingEnabled, "Kaydırma etkin");
        Assert.Equal(TranslationManager.Translation.SearchSubdirectory, "Alt dizinlerde ara");
        Assert.Equal(TranslationManager.Translation.SecAbbreviation, "Sny.");
        Assert.Equal(TranslationManager.Translation.SelectAll, "Hepsini seç");
        Assert.Equal(TranslationManager.Translation.SelectGalleryThumb, "Galeri küçük resmini seç");
        Assert.Equal(TranslationManager.Translation.SendCurrentImageToRecycleBin, "Mevcut resmi çöp kutusuna gönder");
        Assert.Equal(TranslationManager.Translation.SentFileToRecycleBin, "Dosya çöp kutusuna gönderildi");
        Assert.Equal(TranslationManager.Translation.SetAs, "Olarak ayarla...");
        Assert.Equal(TranslationManager.Translation.SetAsLockScreenImage, "Kilit ekranı resmi olarak ayarla");
        Assert.Equal(TranslationManager.Translation.SetAsWallpaper, "Duvar kağıdı olarak ayarla");
        Assert.Equal(TranslationManager.Translation.SetCurrentImageAsWallpaper,
            "Mevcut resmi duvar kağıdı olarak ayarla:");
        Assert.Equal(TranslationManager.Translation.SetStarRating, "Yıldız derecelendirmesi ayarla");
        Assert.Equal(TranslationManager.Translation.Settings, "Ayarlar");
        Assert.Equal(TranslationManager.Translation.Shade, "Gölge");
        Assert.Equal(TranslationManager.Translation.Sharpness, "Keskinlik");
        Assert.Equal(TranslationManager.Translation.Shift, "Shift");
        Assert.Equal(TranslationManager.Translation.ShowAllSettingsWindow, "Tüm ayarlar penceresini göster");
        Assert.Equal(TranslationManager.Translation.ShowBottomGallery, "Alt galeriyi göster");
        Assert.Equal(TranslationManager.Translation.ShowBottomGalleryWhenUiIsHidden,
            "Arayüz gizlendiğinde alt galeriyi göster");
        Assert.Equal(TranslationManager.Translation.ShowBottomToolbar, "Alt araç çubuğunu göster");
        Assert.Equal(TranslationManager.Translation.ShowConfirmationOnEsc,
            "ESC'yi basarak pencereyi kapatmak istiyor musunuz?");
        Assert.Equal(TranslationManager.Translation.ShowFadeInButtonsOnHover,
            "Farenin üzerine gelindiğinde soluklaşan düğmeleri göster");
        Assert.Equal(TranslationManager.Translation.ShowFileSavingDialog, "Dosya kaydetme penceresini göster");
        Assert.Equal(TranslationManager.Translation.ShowImageGallery, "Resim galerisini göster");
        Assert.Equal(TranslationManager.Translation.ShowImageInfo, "Resim bilgisini göster");
        Assert.Equal(TranslationManager.Translation.ShowInFolder, "Klasörde göster");
        Assert.Equal(TranslationManager.Translation.ShowInfoWindow, "Bilgi penceresini göster");
        Assert.Equal(TranslationManager.Translation.ShowResizeWindow, "Boyutlandırma penceresini göster");
        Assert.Equal(TranslationManager.Translation.ShowUI, "Arayüzü göster");
        Assert.Equal(TranslationManager.Translation.ShutterPriority, "Enstantane önceliği");
        Assert.Equal(TranslationManager.Translation.SideBySide, "Yan yana");
        Assert.Equal(TranslationManager.Translation.SideBySideTooltip, "Resimleri yan yana göster");
        Assert.Equal(TranslationManager.Translation.Size, "Boyut");
        Assert.Equal(TranslationManager.Translation.SizeMp, "Boyut (mp)");
        Assert.Equal(TranslationManager.Translation.SizeTooltip, "İstediğiniz boyutu piksel veya yüzde cinsinden gir.");
        Assert.Equal(TranslationManager.Translation.Slideshow, "Slayt gösterisi");
        Assert.Equal(TranslationManager.Translation.Soft, "Yumuşak");
        Assert.Equal(TranslationManager.Translation.Software, "Yazılım");
        Assert.Equal(TranslationManager.Translation.SortFilesBy, "Dosyaları şuna göre sırala");
        Assert.Equal(TranslationManager.Translation.Space, "Boşluk");
        Assert.Equal(TranslationManager.Translation.Square, "Kare");
        Assert.Equal(TranslationManager.Translation.Start, "Başla");
        Assert.Equal(TranslationManager.Translation.StartSlideshow, "Slayt gösterisini başlat");
        Assert.Equal(TranslationManager.Translation.StayCentered, "Pencereyi ortada tut");
        Assert.Equal(TranslationManager.Translation.StayTopMost, "Diğer pencerelerin üstünde kal");
        Assert.Equal(TranslationManager.Translation.Stretch, "Esneme");
        Assert.Equal(TranslationManager.Translation.StretchImage, "Resmi esnet");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightDetected, "Strob ışık geri dönüşü algılandı");
        Assert.Equal(TranslationManager.Translation.StrobeReturnLightNotDetected, "Strob ışık geri dönüşü algılanmadı");
        Assert.Equal(TranslationManager.Translation.Subject, "Konu");
        Assert.Equal(TranslationManager.Translation.Theme, "Tema");
        Assert.Equal(TranslationManager.Translation.Thumbnail, "Küçük resim");
        Assert.Equal(TranslationManager.Translation.Tile, "Fayans");
        Assert.Equal(TranslationManager.Translation.Title, "Başlık");
        Assert.Equal(TranslationManager.Translation.ToggleBackgroundColor, "Arka plan rengini aç / kapat");
        Assert.Equal(TranslationManager.Translation.ToggleFullscreen, "Tam ekranı aç / kapat");
        Assert.Equal(TranslationManager.Translation.ToggleLooping, "Döngüyü aç / kapat");
        Assert.Equal(TranslationManager.Translation.ToggleScroll, "Kaydırmayı aç / kapat");
        Assert.Equal(TranslationManager.Translation.ToggleTaskbarProgress, "Görev çubuğu ilerlemesini görüntüle");
        Assert.Equal(TranslationManager.Translation.UnableToRender, "Görüntü işlenemiyor");
        Assert.Equal(TranslationManager.Translation.Uncalibrated, "Uncalibrated");
        Assert.Equal(TranslationManager.Translation.UnexpectedError, "Bilinmeyen bir hata oluştu");
        Assert.Equal(TranslationManager.Translation.Unflip, "Ters çevir");
        Assert.Equal(TranslationManager.Translation.Uniform, "üniforma");
        Assert.Equal(TranslationManager.Translation.UniformToFill, "Doldurulacak üniforma");
        Assert.Equal(TranslationManager.Translation.Unknown, "Bilinmiyor");
        Assert.Equal(TranslationManager.Translation.UnsupportedFile, "Desteklenmeyen dosya");
        Assert.Equal(TranslationManager.Translation.Up, "Yukarı");
        Assert.Equal(TranslationManager.Translation.UsingMouse, "Fare kullanılıyor");
        Assert.Equal(TranslationManager.Translation.UsingTouchpad, "Dokunmatik yüzey kullanılıyor");
        Assert.Equal(TranslationManager.Translation.Version, "Sürüm:");
        Assert.Equal(TranslationManager.Translation.ViewLicenseFile, "Lisans dosyasını görüntüle");
        Assert.Equal(TranslationManager.Translation.WhiteBalance, "Beyaz dengesi");
        Assert.Equal(TranslationManager.Translation.WhiteFluorescent, "Beyaz floresan");
        Assert.Equal(TranslationManager.Translation.Width, "Genişlik");
        Assert.Equal(TranslationManager.Translation.WidthAndHeight, "Genişlik ve yükseklik");
        Assert.Equal(TranslationManager.Translation.WindowManagement, "Pencere yönetimi");
        Assert.Equal(TranslationManager.Translation.WindowScaling, "Pencere ölçeklendirme");
        Assert.Equal(TranslationManager.Translation.Zoom, "Yakınlaştırma");
        Assert.Equal(TranslationManager.Translation.ZoomIn, "Yakınlaştır");
        Assert.Equal(TranslationManager.Translation.ZoomOut, "Uzaklaştır");
        Assert.Equal(TranslationManager.Translation._1Star, "1 yıldız derecesi");
        Assert.Equal(TranslationManager.Translation._2Star, "2 yıldız derecesi");
        Assert.Equal(TranslationManager.Translation._3Star, "3 yıldız derecesi");
        Assert.Equal(TranslationManager.Translation._4Star, "4 yıldız derecesi");
        Assert.Equal(TranslationManager.Translation._5Star, "5 yıldız derecesi");
    }
}