<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <ImplicitUsings>enable</ImplicitUsings>
        <Company>Ruben Hyldgaard Negendahl</Company>
        <Product>PicView</Product>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <Platforms>x64;arm64</Platforms>

        <!-- AOT -->
        <PublishAot>true</PublishAot>
        <Trimming>full</Trimming>
        <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
        <OptimizationPreference>Speed</OptimizationPreference>
        <HttpActivityPropagationSupport>false</HttpActivityPropagationSupport>
        <IsAotCompatible>True</IsAotCompatible>
        <IsTrimmable>True</IsTrimmable>
        <EventSourceSupport>false</EventSourceSupport>
        <StackTraceSupport>true</StackTraceSupport>
        <EventSourceSupport>false</EventSourceSupport>
        <IlcTrimMetadata>true</IlcTrimMetadata>

        <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
    </PropertyGroup>
    <PropertyGroup Label="Avalonia">
        <AvaloniaXamlIlDebuggerLaunch>False</AvaloniaXamlIlDebuggerLaunch>
    </PropertyGroup>


    <PropertyGroup Condition="'$(Platform)' == 'x64'">
        <PlatformTarget>x64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Platform)' == 'arm64'">
        <PlatformTarget>ARM64</PlatformTarget>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|arm64' ">
        <DebugType>full</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|x64' ">
        <DebugType>full</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|arm64' ">
        <DebugType>none</DebugType>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|x64' ">
        <DebugType>none</DebugType>
    </PropertyGroup>

    <PropertyGroup>
        <EnablePreviewFeatures>true</EnablePreviewFeatures>
    </PropertyGroup>


    <ItemGroup>
        <AvaloniaResource Include="Assets\**" />
    </ItemGroup>


    <ItemGroup>
        <Compile Update="Views\UC\DragDrogView.axaml.cs">
            <DependentUpon>DragDrogView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\Buttons\AltRestore.axaml.cs">
            <DependentUpon>AltRestore.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\Buttons\AltMinimize.axaml.cs">
            <DependentUpon>AltMinimize.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SettingsView.axaml.cs">
            <DependentUpon>SettingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\GallerySettingsView.axaml.cs">
            <DependentUpon>GalleryViewView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ImageSettingsView.axaml.cs">
            <DependentUpon>ImageSettingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\MouseView.axaml.cs">
            <DependentUpon>MouseWheelView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SlideshowSettingsView.axaml.cs">
            <DependentUpon>SlideshowSettingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\ZoomSettingsView.axaml.cs">
            <DependentUpon>ZoomSettingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\SingleImageResizeView.axaml.cs">
            <DependentUpon>SingleImageResizeView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\PopUps\DeleteDialog.axaml.cs">
            <DependentUpon>DeleteDialog.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\EffectsView.axaml.cs">
            <DependentUpon>EffectsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\WindowSettingsView.axaml.cs">
            <DependentUpon>WindowSettingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\PopUps\NavigationDialog.axaml.cs">
            <DependentUpon>NavigationDialog.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="CustomControls\DateTimePickerButtons.axaml.cs">
            <DependentUpon>DateTimePickerButtons.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\PrintPreviewView.axaml.cs">
            <DependentUpon>PrintPreviewView.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\UC\PopUps\FileSearchDialog.axaml.cs">
            <DependentUpon>FileSearchDialog.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\InterfaceConfigurationView.axaml.cs">
            <DependentUpon>InterfaceConfigurationView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\BottomBar2.axaml.cs">
            <DependentUpon>BottomBar2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\ImageViewer2.axaml.cs">
            <DependentUpon>ImageViewer2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\ZoomPreviewer2.axaml.cs">
            <DependentUpon>ZoomPreviewer2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\Menus\DropDownMenu.axaml.cs">
            <DependentUpon>DropDownMenu.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Main\MainView3.axaml.cs">
            <DependentUpon>MainView3.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\HoverBar2.axaml.cs">
            <DependentUpon>HoverBar2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\SettingsView2.axaml.cs">
            <DependentUpon>SettingsView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\GeneralSettingsView2.axaml.cs">
            <DependentUpon>GeneralSettingsView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\AppearanceView2.axaml.cs">
            <DependentUpon>AppearanceView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\InterfaceConfigurationView2.axaml.cs">
            <DependentUpon>InterfaceConfigurationView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\ImageSettingsView2.axaml.cs">
            <DependentUpon>ImageSettingsView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\WindowSettingsView2.axaml.cs">
            <DependentUpon>WindowSettingsView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\GallerySettingsView2.axaml.cs">
            <DependentUpon>GallerySettingsView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\SlideshowSettingsView2.axaml.cs">
            <DependentUpon>SlideshowSettingsView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\NavigationView2.axaml.cs">
            <DependentUpon>NavigationView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\ZoomSettingsView2.axaml.cs">
            <DependentUpon>ZoomSettingsView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\MouseView2.axaml.cs">
            <DependentUpon>MouseView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\LanguageView2.axaml.cs">
            <DependentUpon>LanguageView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\PrintPreviewView2.axaml.cs">
            <DependentUpon>PrintPreviewView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Main\AboutView2.axaml.cs">
            <DependentUpon>AboutView2.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\DragDropView.axaml.cs">
            <DependentUpon>DragDropView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Config\KeybindingsView.axaml.cs">
            <DependentUpon>KeybindingsView.axaml</DependentUpon>
            <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\UC\PopUps\RenameDialog.axaml.cs">
          <DependentUpon>RenameDialog.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Menu\DropDownMenu.axaml.cs">
          <DependentUpon>DropDownMenu.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Menu\FileMenu.axaml.cs">
          <DependentUpon>FileMenu.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
        <Compile Update="Views\Menu\SettingsMenu.axaml.cs">
          <DependentUpon>SettingsMenu.axaml</DependentUpon>
          <SubType>Code</SubType>
        </Compile>
    </ItemGroup>


    <ItemGroup>
        <None Remove="DarkTheme\Resources\noisy-texture-200x200-o4-d31-c-161616-t0.png" />
        <None Update="Views\UC\RotationContextMenu.axaml.cs~">
            <DependentUpon>RotationContextMenu.axaml</DependentUpon>
        </None>
    </ItemGroup>


    <ItemGroup>
        <AvaloniaResource Include="PicViewTheme\Resources\noisy-texture-200x200-o4-d31-c-161616-t0.png" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia" Version="12.1.1" />
        <PackageReference Include="Avalonia.Desktop" Version="12.1.1" />
        <PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" Version="2.2.3" />
        <PackageReference Include="Magick.NET.AvaloniaMediaImaging" Version="1.1.14" />
        <PackageReference Include="R3Extensions.Avalonia" Version="1.3.1" />
        <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.15" />
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Views\Main\ImageInfoView.axaml.cs">
            <DependentUpon>ExifView.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Main\AppearanceView.axaml.cs">
            <DependentUpon>AppearanceView.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Main\AboutView.axaml.cs">
            <DependentUpon>AboutView.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Main\KeybindingsView.axaml.cs">
            <DependentUpon>ShortcutsView.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Config\GeneralSettingsView.axaml.cs">
            <DependentUpon>GeneralSettingsView.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\UC\Buttons\StarOutlineButtons.axaml.cs">
            <DependentUpon>StarOutlineButtons.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\UC\ImageViewer.axaml.cs">
            <DependentUpon>ImageViewer.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\UC\Menus\ToolsMenu.axaml.cs">
            <DependentUpon>ToolsMenu.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\UC\Menus\SettingsMenu.axaml.cs">
            <DependentUpon>SettingsMenu.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\UC\Menus\ImageMenu.axaml.cs">
            <DependentUpon>ImageMenu.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\UC\SpinWaiter.axaml.cs">
            <DependentUpon>SpinWaiter.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\UC\TitleTextbox.axaml.cs">
            <DependentUpon>TitleTextBox.axaml</DependentUpon>
        </Compile>
        <Compile Update="Views\Config\AppearanceView.axaml.cs">
            <DependentUpon>AppearanceView.axaml</DependentUpon>
        </Compile>
    </ItemGroup>

    <ItemGroup>
        <Folder Include="Assets\" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PicView.Core\PicView.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="PicView.Tests" />
    </ItemGroup>
</Project>
