//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PicView.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public short ColorTheme {
            get {
                return ((short)(this["ColorTheme"]));
            }
            set {
                this["ColorTheme"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0461B1")]
        public global::System.Windows.Media.Color Blue {
            get {
                return ((global::System.Windows.Media.Color)(this["Blue"]));
            }
            set {
                this["Blue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFE68BEE")]
        public global::System.Windows.Media.Color Pink {
            get {
                return ((global::System.Windows.Media.Color)(this["Pink"]));
            }
            set {
                this["Pink"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFDB5B3D")]
        public global::System.Windows.Media.Color Orange {
            get {
                return ((global::System.Windows.Media.Color)(this["Orange"]));
            }
            set {
                this["Orange"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF0EB24C")]
        public global::System.Windows.Media.Color Green {
            get {
                return ((global::System.Windows.Media.Color)(this["Green"]));
            }
            set {
                this["Green"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF91110")]
        public global::System.Windows.Media.Color Red {
            get {
                return ((global::System.Windows.Media.Color)(this["Red"]));
            }
            set {
                this["Red"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F20D8039")]
        public global::System.Windows.Media.Color GreenMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["GreenMouse"]));
            }
            set {
                this["GreenMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F2F19DFA")]
        public global::System.Windows.Media.Color PinkMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["PinkMouse"]));
            }
            set {
                this["PinkMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFF35353")]
        public global::System.Windows.Media.Color RedMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["RedMouse"]));
            }
            set {
                this["RedMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F200ADEE")]
        public global::System.Windows.Media.Color BlueMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["BlueMouse"]));
            }
            set {
                this["BlueMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E2FF6441")]
        public global::System.Windows.Media.Color OrangeMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["OrangeMouse"]));
            }
            set {
                this["OrangeMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F2008080")]
        public global::System.Windows.Media.Color TealMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["TealMouse"]));
            }
            set {
                this["TealMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF36E6CC")]
        public global::System.Windows.Media.Color Aqua {
            get {
                return ((global::System.Windows.Media.Color)(this["Aqua"]));
            }
            set {
                this["Aqua"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F209A68E")]
        public global::System.Windows.Media.Color AquaMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["AquaMouse"]));
            }
            set {
                this["AquaMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFE2C290")]
        public global::System.Windows.Media.Color Beige {
            get {
                return ((global::System.Windows.Media.Color)(this["Beige"]));
            }
            set {
                this["Beige"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F2E2C290")]
        public global::System.Windows.Media.Color BeigeMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["BeigeMouse"]));
            }
            set {
                this["BeigeMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF931AF7")]
        public global::System.Windows.Media.Color Teal {
            get {
                return ((global::System.Windows.Media.Color)(this["Teal"]));
            }
            set {
                this["Teal"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFD40FD4")]
        public global::System.Windows.Media.Color Purple {
            get {
                return ((global::System.Windows.Media.Color)(this["Purple"]));
            }
            set {
                this["Purple"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E29E46E9")]
        public global::System.Windows.Media.Color PurpleMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["PurpleMouse"]));
            }
            set {
                this["PurpleMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF1BA1E2")]
        public global::System.Windows.Media.Color Cyan {
            get {
                return ((global::System.Windows.Media.Color)(this["Cyan"]));
            }
            set {
                this["Cyan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F236BBFF")]
        public global::System.Windows.Media.Color CyanMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["CyanMouse"]));
            }
            set {
                this["CyanMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FF5F5449")]
        public global::System.Windows.Media.Color Grey {
            get {
                return ((global::System.Windows.Media.Color)(this["Grey"]));
            }
            set {
                this["Grey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#F25F5449")]
        public global::System.Windows.Media.Color GreyMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["GreyMouse"]));
            }
            set {
                this["GreyMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#FFFF35C5")]
        public global::System.Windows.Media.Color Magenta {
            get {
                return ((global::System.Windows.Media.Color)(this["Magenta"]));
            }
            set {
                this["Magenta"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("#E2FF55C8")]
        public global::System.Windows.Media.Color MagentaMouse {
            get {
                return ((global::System.Windows.Media.Color)(this["MagentaMouse"]));
            }
            set {
                this["MagentaMouse"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ScrollEnabled {
            get {
                return ((bool)(this["ScrollEnabled"]));
            }
            set {
                this["ScrollEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowInterface {
            get {
                return ((bool)(this["ShowInterface"]));
            }
            set {
                this["ShowInterface"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public short SortPreference {
            get {
                return ((short)(this["SortPreference"]));
            }
            set {
                this["SortPreference"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte PicGallery {
            get {
                return ((byte)(this["PicGallery"]));
            }
            set {
                this["PicGallery"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public double Slidetimeren {
            get {
                return ((double)(this["Slidetimeren"]));
            }
            set {
                this["Slidetimeren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Looping {
            get {
                return ((bool)(this["Looping"]));
            }
            set {
                this["Looping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool WindowBorderColorEnabled {
            get {
                return ((bool)(this["WindowBorderColorEnabled"]));
            }
            set {
                this["WindowBorderColorEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool BgColorWhite {
            get {
                return ((bool)(this["BgColorWhite"]));
            }
            set {
                this["BgColorWhite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FitToWindow {
            get {
                return ((bool)(this["FitToWindow"]));
            }
            set {
                this["FitToWindow"] = value;
            }
        }
    }
}
