//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.Configuration;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Windows.Media;

namespace PicView.Properties {
    
    
    [CompilerGenerated()]
    [GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    public sealed partial class Settings : ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#1a8cf0")]
        public Color Blue {
            get {
                return ((Color)(this["Blue"]));
            }
            set {
                this["Blue"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFE68BEE")]
        public Color Pink {
            get {
                return ((Color)(this["Pink"]));
            }
            set {
                this["Pink"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFDB5B3D")]
        public Color Orange {
            get {
                return ((Color)(this["Orange"]));
            }
            set {
                this["Orange"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#20E76B")]
        public Color Green {
            get {
                return ((Color)(this["Green"]));
            }
            set {
                this["Green"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFF91110")]
        public Color Red {
            get {
                return ((Color)(this["Red"]));
            }
            set {
                this["Red"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF36E6CC")]
        public Color Aqua {
            get {
                return ((Color)(this["Aqua"]));
            }
            set {
                this["Aqua"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFEA955")]
        public Color Golden {
            get {
                return ((Color)(this["Golden"]));
            }
            set {
                this["Golden"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF44A1A0")]
        public Color Teal {
            get {
                return ((Color)(this["Teal"]));
            }
            set {
                this["Teal"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF9738EB")]
        public Color Purple {
            get {
                return ((Color)(this["Purple"]));
            }
            set {
                this["Purple"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF1BA1E2")]
        public Color Cyan {
            get {
                return ((Color)(this["Cyan"]));
            }
            set {
                this["Cyan"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FF22CB97")]
        public Color Lime {
            get {
                return ((Color)(this["Lime"]));
            }
            set {
                this["Lime"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool CallUpgrade {
            get {
                return ((bool)(this["CallUpgrade"]));
            }
            set {
                this["CallUpgrade"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("#FFFF35C5")]
        public Color Magenta {
            get {
                return ((Color)(this["Magenta"]));
            }
            set {
                this["Magenta"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool ScrollEnabled {
            get {
                return ((bool)(this["ScrollEnabled"]));
            }
            set {
                this["ScrollEnabled"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowInterface {
            get {
                return ((bool)(this["ShowInterface"]));
            }
            set {
                this["ShowInterface"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int SortPreference {
            get {
                return ((int)(this["SortPreference"]));
            }
            set {
                this["SortPreference"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool FullscreenGalleryHorizontal {
            get {
                return ((bool)(this["FullscreenGalleryHorizontal"]));
            }
            set {
                this["FullscreenGalleryHorizontal"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("5000")]
        public double SlideTimer {
            get {
                return ((double)(this["SlideTimer"]));
            }
            set {
                this["SlideTimer"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Looping {
            get {
                return ((bool)(this["Looping"]));
            }
            set {
                this["Looping"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public int BgColorChoice {
            get {
                return ((int)(this["BgColorChoice"]));
            }
            set {
                this["BgColorChoice"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool AutoFitWindow {
            get {
                return ((bool)(this["AutoFitWindow"]));
            }
            set {
                this["AutoFitWindow"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool FillImage {
            get {
                return ((bool)(this["FillImage"]));
            }
            set {
                this["FillImage"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double Top {
            get {
                return ((double)(this["Top"]));
            }
            set {
                this["Top"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double Left {
            get {
                return ((double)(this["Left"]));
            }
            set {
                this["Left"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double Height {
            get {
                return ((double)(this["Height"]));
            }
            set {
                this["Height"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0")]
        public double Width {
            get {
                return ((double)(this["Width"]));
            }
            set {
                this["Width"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Fullscreen {
            get {
                return ((bool)(this["Fullscreen"]));
            }
            set {
                this["Fullscreen"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool IncludeSubDirectories {
            get {
                return ((bool)(this["IncludeSubDirectories"]));
            }
            set {
                this["IncludeSubDirectories"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool DarkTheme {
            get {
                return ((bool)(this["DarkTheme"]));
            }
            set {
                this["DarkTheme"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("en")]
        public string UserLanguage {
            get {
                return ((string)(this["UserLanguage"]));
            }
            set {
                this["UserLanguage"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool ShowAltInterfaceButtons {
            get {
                return ((bool)(this["ShowAltInterfaceButtons"]));
            }
            set {
                this["ShowAltInterfaceButtons"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("3")]
        public int ColorTheme {
            get {
                return ((int)(this["ColorTheme"]));
            }
            set {
                this["ColorTheme"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("0.2")]
        public double ZoomSpeed {
            get {
                return ((double)(this["ZoomSpeed"]));
            }
            set {
                this["ZoomSpeed"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool TopMost {
            get {
                return ((bool)(this["TopMost"]));
            }
            set {
                this["TopMost"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool KeepCentered {
            get {
                return ((bool)(this["KeepCentered"]));
            }
            set {
                this["KeepCentered"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool CtrlZoom {
            get {
                return ((bool)(this["CtrlZoom"]));
            }
            set {
                this["CtrlZoom"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool Maximized {
            get {
                return ((bool)(this["Maximized"]));
            }
            set {
                this["Maximized"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool Ascending {
            get {
                return ((bool)(this["Ascending"]));
            }
            set {
                this["Ascending"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("True")]
        public bool HorizontalReverseScroll {
            get {
                return ((bool)(this["HorizontalReverseScroll"]));
            }
            set {
                this["HorizontalReverseScroll"] = value;
            }
        }
        
        [UserScopedSetting()]
        [DebuggerNonUserCode()]
        [DefaultSettingValue("False")]
        public bool AvoidZoomingOut {
            get {
                return ((bool)(this["AvoidZoomingOut"]));
            }
            set {
                this["AvoidZoomingOut"] = value;
            }
        }
    }
}
