namespace PicView.Core.MacOS;

public static class MacOsKeybindings
{
    public const string DefaultKeybindings = """
                                              {
                                                "D": "Next",
                                                "Right": "Next",
                                                "Cmd+Right": "Last",
                                                "Cmd+D": "Last",
                                                "Cmd+Left": "First",
                                                "Cmd+A": "First",
                                                "Shift+D": "NextFolder",
                                                "Shift+Right": "NextFolder",
                                                "Shift+A": "PrevFolder",
                                                "Shift+Left": "PrevFolder",
                                                "A": "Prev",
                                                "Left": "Prev",
                                                "W": "Up",
                                                "Up": "Up",
                                                "S": "Down",
                                                "Down": "Down",
                                                "PageUp": "ScrollUp",
                                                "PageDown": "ScrollDown",
                                                "Add": "ZoomIn",
                                                "OemPlus": "ZoomIn",
                                                "OemMinus": "ZoomOut",
                                                "Subtract": "ZoomOut",
                                                "Alt+X": "ToggleScroll",
                                                "Home": "ScrollToTop",
                                                "End": "ScrollToBottom",
                                                "G": "ToggleGallery",
                                                "F": "Flip",
                                                "L": "ToggleLooping",
                                                "C": "Crop",
                                                "E": "GalleryClick",
                                                "Return": "GalleryClick",
                                                "I": "ImageInfoWindow",
                                                "F6": "EffectsWindow",
                                                "F1": "AboutWindow",
                                                "F3": "OpenInExplorer",
                                                "Alt+S": "SettingsWindow",
                                                "F5": "Slideshow",
                                                "Ctrl+Cmd+F": "Fullscreen",
                                                "F12": "Fullscreen",
                                                "B": "ChangeBackground",
                                                "Space": "Center",
                                                "K": "KeybindingsWindow",
                                                "Cmd+O": "Open",
                                                "Cmd+E": "OpenWith",
                                                "Cmd+R": "Reload",
                                                "Cmd+S": "Save",
                                                "Shift+Cmd+S": "SaveAs",
                                                "F2": "Rename",
                                                "Cmd+C": "CopyFile",
                                                "Alt+Cmd+V": "CopyFilePath",
                                                "Shift+Cmd+C": "CopyImage",
                                                "Cmd+X": "CutFile",
                                                "Cmd+V": "Paste",
                                                "Cmd+P": "Print",
                                                "Alt+Z": "ToggleInterface",
                                                "Delete": "DeleteFile",
                                                "Shift+Delete": "DeleteFilePermanently",
                                                "Back": "DeleteFile",
                                                "Shift+Back": "DeleteFilePermanently",
                                                "Cmd+N": "NewWindow",
                                                "J": "ResizeWindow",
                                                "Alt+Cmd+I": "ResizeWindow",
                                                "Cmd+F": "Search",
                                              }
                                              """;
}
