<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net11.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>

        <EnablePreviewFeatures>true</EnablePreviewFeatures>

        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <Platforms>arm64;x64</Platforms>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Headless.XUnit" Version="12.1.999-cibuild0065238-alpha" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.9.0" />
        <PackageReference Include="xunit.v3" Version="4.0.0" />
        <PackageReference Include="xunit.runner.visualstudio" Version="4.0.0">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="coverlet.collector" Version="10.0.1">
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
            <PrivateAssets>all</PrivateAssets>
        </PackageReference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\PicView.Avalonia.MacOS\PicView.Avalonia.MacOS.csproj" />
        <ProjectReference Include="..\PicView.Avalonia\PicView.Avalonia.csproj" />
        <ProjectReference Include="..\PicView.Core\PicView.Core.csproj" />
    </ItemGroup>

</Project>
