<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <LangVersion>preview</LangVersion>
  </PropertyGroup>
    
  <PropertyGroup>
      <EnablePreviewFeatures>true</EnablePreviewFeatures>
      <Features>$(Features);runtime-async=on</Features>
  </PropertyGroup>

  <ItemGroup>
      <PackageReference Include="BenchmarkDotNet" Version="0.16.0-preview.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PicView.Avalonia\PicView.Avalonia.csproj" />
    <ProjectReference Include="..\PicView.Core\PicView.Core.csproj" />
  </ItemGroup>

</Project>
